// (job, gender, motion) -> frameCount

#define _gender_M true  //   male
#define _gender_F false // female

{{JOB_WARRIOR, _gender_F, 0}, 11},
{{JOB_WARRIOR, _gender_F, 1}, 11},
{{JOB_WARRIOR, _gender_F, 2}, 11},
{{JOB_WARRIOR, _gender_F, 3}, 12},
{{JOB_WARRIOR, _gender_F, 4}, 16},
{{JOB_WARRIOR, _gender_M, 0}, 11},
{{JOB_WARRIOR, _gender_M, 1}, 20},
{{JOB_WARRIOR, _gender_M, 2}, 12},
{{JOB_WARRIOR, _gender_M, 3},  8},
{{JOB_WARRIOR, _gender_M, 4}, 18},
{{JOB_TAOIST , _gender_F, 0}, 11},
{{JOB_TAOIST , _gender_F, 1}, 17},
{{JOB_TAOIST , _gender_F, 2}, 11},
{{JOB_TAOIST , _gender_F, 3}, 10},
{{JOB_TAOIST , _gender_F, 4}, 15},
{{JOB_TAOIST , _gender_M, 0}, 11},
{{JOB_TAOIST , _gender_M, 1}, 17},
{{JOB_TAOIST , _gender_M, 2}, 20},
{{JOB_TAOIST , _gender_M, 3}, 12},
{{JOB_TAOIST , _gender_M, 4}, 17},
{{JOB_WIZARD , _gender_F, 0}, 11},
{{JOB_WIZARD , _gender_F, 1}, 18},
{{JOB_WIZARD , _gender_F, 2}, 11},
{{JOB_WIZARD , _gender_F, 3},  9},
{{JOB_WIZARD , _gender_F, 4}, 17},
{{JOB_WIZARD , _gender_M, 0}, 11},
{{JOB_WIZARD , _gender_M, 1}, 12},
{{JOB_WIZARD , _gender_M, 2}, 11},
{{JOB_WIZARD , _gender_M, 3}, 11},
{{JOB_WIZARD , _gender_M, 4}, 15},

#undef _gender_M
#undef _gender_F
