// generated by Fast Light User Interface Designer (fluid) version 1.0302

#ifndef addmonsterwindow_hpp
#define addmonsterwindow_hpp
#include <FL/Fl.H>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Choice.H>
#include <FL/Fl_Button.H>
#include "sceneserver.hpp"

class AddMonsterWindow {
public:
  AddMonsterWindow();
  Fl_Double_Window *m_Window;
  Fl_Choice *m_ValidList;
  Fl_Choice *m_CurrentList;
private:
  inline void cb_Add_i(Fl_Button*, void*);
  static void cb_Add(Fl_Button*, void*);
  inline void cb_OK_i(Fl_Button*, void*);
  static void cb_OK(Fl_Button*, void*);
  inline void cb_Refresh_i(Fl_Button*, void*);
  static void cb_Refresh(Fl_Button*, void*);
public:
  Fl_Choice *m_CurrentList;
  void ShowAll();
  void AddValid(const char *szSID, const char *szName);
  void AddCurrent(const char *szSID, const char *szName);
  void Refresh();
};
#endif
