// generated by Fast Light User Interface Designer (fluid) version 1.0400

#ifndef qdinputtextbutton_h
#define qdinputtextbutton_h
#include <FL/Fl.H>
#include <math.h>
#include <FL/Fl_Group.H>
#include <FL/Fl_Text_Editor.H>
#include <FL/Fl_Button.H>

class QD_InputTextButton : public Fl_Group {
public:
  QD_InputTextButton(int X, int Y, int W, int H, const char *L = 0);
protected:
  std::string m_defaultLabel;
  Fl_Align m_inputAlign = FL_ALIGN_CENTER;
public:
  Fl_Text_Editor *m_editor;
  Fl_Button *m_button;
  void edit(bool enable);
  void handle(int event);
  void label_align(Fl_Align align);
};
#endif
