// generated by Fast Light User Interface Designer (fluid) version 1.0303

#ifndef aboutwindow_hpp
#define aboutwindow_hpp
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Output.H>

class AboutWindow {
public:
  AboutWindow();
private:
  Fl_Double_Window *m_Window;
  Fl_Output *m_Output;
public:
  void ShowAll();
};
#endif
