// generated by Fast Light User Interface Designer (fluid) version 1.0303

#pragma once
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Shared_Image.H>
#include <cstdint>
#include <cstdint>

class PreviewWindow: public Fl_Double_Window
{
    public:
        PreviewWindow(int, int, int, int);

    private:
        int handle(int);
};

class AnimationPreviewWindow
{
    private:
        PreviewWindow    *m_Window;
        Fl_Shared_Image  *m_PNG[2][100];
    private:
        int     m_CurrentFrameIndex;
        int     m_FrameCount;
        int     m_LastFrameIndex;
        int     m_MaxW;
        int     m_MaxH;
        int     m_ImageMaxW;
        int     m_ImageMaxH;
        int     m_FileIndex;
        int     m_AnimationIndex;
        int     m_AnimationState;
        int     m_DSX[100];
        int     m_DSY[100];
        int     m_PX[100];
        int     m_PY[100];
    public:
        AnimationPreviewWindow(uint32_t, uint32_t);
        ~AnimationPreviewWindow();
    public:
        void ShowAll();
        void HideAll();
        void RedrawAll();
        void UpdateFrame();
public:
	int FileIndex();
	int AnimationIndex();

    public:
        static void EventCallback(void *);
        static void TimeoutCallback(void *);
};
