// generated by Fast Light User Interface Designer (fluid) version 1.0303

#ifndef animationinfowindow_hpp
#define animationinfowindow_hpp
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Text_Display.H>
#include <FL/Fl_Button.H>
#include "mainwindow.hpp"
#include "animationset.hpp"
#include "animationpreviewwindow.hpp"

class AnimationInfoWindow {
  Fl_Text_Buffer *m_Buffer; 
public:
  AnimationInfoWindow();
  Fl_Double_Window *m_Window;
  Fl_Text_Display *m_Display;
private:
  inline void cb_Import_i(Fl_Button*, void*);
  static void cb_Import(Fl_Button*, void*);
  inline void cb_Drop_i(Fl_Button*, void*);
  static void cb_Drop(Fl_Button*, void*);
public:
  ~AnimationInfoWindow();
  void Set(int nCount);
  void ShowAll();
  void RedrawAll();
  static void TimeoutCallback();
};
#endif
