// generated by Fast Light User Interface Designer (fluid) version 1.0303

#include "dynamicshadowgroup.hpp"
#include "mainwindow.hpp"

void DynamicShadowGroup::cb_8_i(Fl_Button*, void*) {
  {
    extern MainWindow *g_MainWindow;
    if(!g_MainWindow->EnableEdit()){
        return;
    }
    extern AnimationSet g_AnimationSet;
    g_AnimationSet.DSetDynamicShadowOffset(false, 0, 0 - m_VSResolution->value());
    extern MainWindow *g_MainWindow;
    g_MainWindow->RedrawAll();
};
}
void DynamicShadowGroup::cb_8(Fl_Button* o, void* v) {
  ((DynamicShadowGroup*)(o->parent()))->cb_8_i(o,v);
}

void DynamicShadowGroup::cb_2_i(Fl_Button*, void*) {
  {
    extern MainWindow *g_MainWindow;
    if(!g_MainWindow->EnableEdit()){
        return;
    }
    extern AnimationSet g_AnimationSet;
    g_AnimationSet.DSetDynamicShadowOffset(false, 0, m_VSResolution->value());
        extern MainWindow *g_MainWindow;
    g_MainWindow->RedrawAll();

};
}
void DynamicShadowGroup::cb_2(Fl_Button* o, void* v) {
  ((DynamicShadowGroup*)(o->parent()))->cb_2_i(o,v);
}

void DynamicShadowGroup::cb_4_i(Fl_Button*, void*) {
  {
    extern MainWindow *g_MainWindow;
    if(!g_MainWindow->EnableEdit()){
        return;
    }
    extern AnimationSet g_AnimationSet;
    g_AnimationSet.DSetDynamicShadowOffset(false, 0 - m_VSResolution->value(), 0);
        extern MainWindow *g_MainWindow;
    g_MainWindow->RedrawAll();

};
}
void DynamicShadowGroup::cb_4(Fl_Button* o, void* v) {
  ((DynamicShadowGroup*)(o->parent()))->cb_4_i(o,v);
}

void DynamicShadowGroup::cb__i(Fl_Button*, void*) {
  {
    extern MainWindow *g_MainWindow;
    if(!g_MainWindow->EnableEdit()){
        return;
    }
    extern AnimationSet g_AnimationSet;
    g_AnimationSet.DSetDynamicShadowOffset(false, m_VSResolution->value(), 0);
        extern MainWindow *g_MainWindow;
    g_MainWindow->RedrawAll();
};
}
void DynamicShadowGroup::cb_(Fl_Button* o, void* v) {
  ((DynamicShadowGroup*)(o->parent()))->cb__i(o,v);
}

void DynamicShadowGroup::cb_1_i(Fl_Button*, void*) {
  extern AnimationSet g_AnimationSet;
g_AnimationSet.FirstFrame();
    extern MainWindow *g_MainWindow;
    g_MainWindow->RedrawAll();
}
void DynamicShadowGroup::cb_1(Fl_Button* o, void* v) {
  ((DynamicShadowGroup*)(o->parent()))->cb_1_i(o,v);
}

void DynamicShadowGroup::cb_3_i(Fl_Button*, void*) {
  extern AnimationSet g_AnimationSet;
g_AnimationSet.PreviousFrame();
    extern MainWindow *g_MainWindow;
    g_MainWindow->RedrawAll();
}
void DynamicShadowGroup::cb_3(Fl_Button* o, void* v) {
  ((DynamicShadowGroup*)(o->parent()))->cb_3_i(o,v);
}

void DynamicShadowGroup::cb_5_i(Fl_Button*, void*) {
  extern AnimationSet g_AnimationSet;
g_AnimationSet.NextFrame();
    extern MainWindow *g_MainWindow;
    g_MainWindow->RedrawAll();
}
void DynamicShadowGroup::cb_5(Fl_Button* o, void* v) {
  ((DynamicShadowGroup*)(o->parent()))->cb_5_i(o,v);
}

void DynamicShadowGroup::cb_6_i(Fl_Button*, void*) {
  extern AnimationSet g_AnimationSet;
g_AnimationSet.LastFrame();
    extern MainWindow *g_MainWindow;
    g_MainWindow->RedrawAll();
}
void DynamicShadowGroup::cb_6(Fl_Button* o, void* v) {
  ((DynamicShadowGroup*)(o->parent()))->cb_6_i(o,v);
}

void DynamicShadowGroup::cb_Isometric_i(Fl_Menu_*, void*) {
  {
    m_PointGroup->hide();
    extern AnimationSet g_AnimationSet;
    g_AnimationSet.DSetDynamicShadowOffset(true, 0, 0);
    extern MainWindow *g_MainWindow;
    g_MainWindow->RedrawAll();
};
}
void DynamicShadowGroup::cb_Isometric(Fl_Menu_* o, void* v) {
  ((DynamicShadowGroup*)(o->parent()))->cb_Isometric_i(o,v);
}

void DynamicShadowGroup::cb_Orthogonal_i(Fl_Menu_*, void*) {
  {
    m_PointGroup->hide();
    extern AnimationSet g_AnimationSet;
    g_AnimationSet.DSetDynamicShadowOffset(true, 0, 0);
    extern MainWindow *g_MainWindow;
    g_MainWindow->RedrawAll();
};
}
void DynamicShadowGroup::cb_Orthogonal(Fl_Menu_* o, void* v) {
  ((DynamicShadowGroup*)(o->parent()))->cb_Orthogonal_i(o,v);
}

void DynamicShadowGroup::cb_Advanced_i(Fl_Menu_*, void*) {
  {
    m_PointGroup->show();
    extern AnimationSet g_AnimationSet;
    g_AnimationSet.DSetDynamicShadowOffset(true, 0, 0);
    extern MainWindow *g_MainWindow;
    g_MainWindow->RedrawAll();
};
}
void DynamicShadowGroup::cb_Advanced(Fl_Menu_* o, void* v) {
  ((DynamicShadowGroup*)(o->parent()))->cb_Advanced_i(o,v);
}

Fl_Menu_Item DynamicShadowGroup::menu_m_Method[] = {
 {"Isometric", 0,  (Fl_Callback*)DynamicShadowGroup::cb_Isometric, 0, 0, FL_NORMAL_LABEL, 4, 14, 0},
 {"Orthogonal", 0,  (Fl_Callback*)DynamicShadowGroup::cb_Orthogonal, 0, 0, FL_NORMAL_LABEL, 4, 14, 0},
 {"Advanced", 0,  (Fl_Callback*)DynamicShadowGroup::cb_Advanced, 0, 0, FL_NORMAL_LABEL, 4, 14, 0},
 {0,0,0,0,0,0,0,0,0}
};
DynamicShadowGroup::DynamicShadowGroup(int X, int Y, int W, int H, const char *L)
  : Fl_Group(0, 0, W, H, L) {
{ Fl_Button* o = new Fl_Button(106, 22, 50, 50, "@8->");
  o->callback((Fl_Callback*)cb_8);
} // Fl_Button* o
{ Fl_Button* o = new Fl_Button(106, 120, 50, 50, "@2->");
  o->callback((Fl_Callback*)cb_2);
} // Fl_Button* o
{ Fl_Button* o = new Fl_Button(57, 71, 50, 50, "@4->");
  o->callback((Fl_Callback*)cb_4);
} // Fl_Button* o
{ Fl_Button* o = new Fl_Button(155, 71, 50, 50, "@->");
  o->callback((Fl_Callback*)cb_);
} // Fl_Button* o
{ m_VSResolution = new Fl_Value_Slider(28, 315, 205, 20, "Resolution");
  m_VSResolution->type(1);
  m_VSResolution->labelfont(4);
  m_VSResolution->minimum(1);
  m_VSResolution->maximum(100);
  m_VSResolution->step(1);
  m_VSResolution->value(1);
  m_VSResolution->textfont(4);
  m_VSResolution->textsize(14);
} // Fl_Value_Slider* m_VSResolution
{ Fl_Button* o = new Fl_Button(33, 177, 50, 45, "@|<");
  o->callback((Fl_Callback*)cb_1);
} // Fl_Button* o
{ Fl_Button* o = new Fl_Button(83, 177, 50, 45, "@<-");
  o->callback((Fl_Callback*)cb_3);
} // Fl_Button* o
{ Fl_Button* o = new Fl_Button(133, 177, 50, 45, "@->");
  o->callback((Fl_Callback*)cb_5);
} // Fl_Button* o
{ Fl_Button* o = new Fl_Button(183, 177, 50, 45, "@>|");
  o->callback((Fl_Callback*)cb_6);
} // Fl_Button* o
{ m_PointGroup = new Fl_Group(50, 265, 170, 46);
  { m_DS1 = new Fl_Round_Button(88, 268, 73, 15, "Point 1");
    m_DS1->type(102);
    m_DS1->down_box(FL_ROUND_DOWN_BOX);
    m_DS1->value(1);
    m_DS1->labelfont(4);
  } // Fl_Round_Button* m_DS1
  { m_DS2 = new Fl_Round_Button(89, 291, 81, 15, "Point 2");
    m_DS2->type(102);
    m_DS2->down_box(FL_ROUND_DOWN_BOX);
    m_DS2->labelfont(4);
  } // Fl_Round_Button* m_DS2
  m_PointGroup->end();
} // Fl_Group* m_PointGroup
{ m_Method = new Fl_Choice(53, 233, 160, 25);
  m_Method->down_box(FL_BORDER_BOX);
  m_Method->labeltype(FL_NO_LABEL);
  m_Method->labelfont(4);
  m_Method->textfont(4);
  m_Method->menu(menu_m_Method);
} // Fl_Choice* m_Method
position(X, Y);
end();
}

int DynamicShadowGroup::Point() {
  {
      if(m_DS1->value()){ return 0; }
      if(m_DS2->value()){ return 1; }
  }
}

int DynamicShadowGroup::Method() {
  {
      return m_Method->value();
  }
}

void DynamicShadowGroup::Reset() {
  {
      m_Method->value(0);
      m_PointGroup->hide();
  }
}
