// generated by Fast Light User Interface Designer (fluid) version 1.0303

#include "framealigngroup.hpp"
#include "mainwindow.hpp"

void FrameAlignGroup::cb_8_i(Fl_Button*, void*) {
  {
    extern MainWindow *g_MainWindow;
    if(!g_MainWindow->EnableEdit()){
        return;
    }
    extern AnimationSet g_AnimationSet;
    g_AnimationSet.DSetFrameAlign(0, 0 - m_VSResolution->value());
    extern MainWindow *g_MainWindow;
    g_MainWindow->RedrawAll();
};
}
void FrameAlignGroup::cb_8(Fl_Button* o, void* v) {
  ((FrameAlignGroup*)(o->parent()))->cb_8_i(o,v);
}

void FrameAlignGroup::cb_2_i(Fl_Button*, void*) {
  {
    extern MainWindow *g_MainWindow;
    if(!g_MainWindow->EnableEdit()){
        return;
    }
    extern AnimationSet g_AnimationSet;
    g_AnimationSet.DSetFrameAlign(0, m_VSResolution->value());
    extern MainWindow *g_MainWindow;
    g_MainWindow->RedrawAll();

};
}
void FrameAlignGroup::cb_2(Fl_Button* o, void* v) {
  ((FrameAlignGroup*)(o->parent()))->cb_2_i(o,v);
}

void FrameAlignGroup::cb_4_i(Fl_Button*, void*) {
  {
    extern MainWindow *g_MainWindow;
    if(!g_MainWindow->EnableEdit()){
        return;
    }
    extern AnimationSet g_AnimationSet;
    g_AnimationSet.DSetFrameAlign(0 - m_VSResolution->value(), 0);
    extern MainWindow *g_MainWindow;
    g_MainWindow->RedrawAll();

};
}
void FrameAlignGroup::cb_4(Fl_Button* o, void* v) {
  ((FrameAlignGroup*)(o->parent()))->cb_4_i(o,v);
}

void FrameAlignGroup::cb__i(Fl_Button*, void*) {
  {
    extern MainWindow *g_MainWindow;
    if(!g_MainWindow->EnableEdit()){
        return;
    }
    extern AnimationSet g_AnimationSet;
    g_AnimationSet.DSetFrameAlign(m_VSResolution->value(), 0);
    extern MainWindow *g_MainWindow;
    g_MainWindow->RedrawAll();
};
}
void FrameAlignGroup::cb_(Fl_Button* o, void* v) {
  ((FrameAlignGroup*)(o->parent()))->cb__i(o,v);
}

void FrameAlignGroup::cb_1_i(Fl_Button*, void*) {
  extern AnimationSet g_AnimationSet;
g_AnimationSet.FirstFrame();
    extern MainWindow *g_MainWindow;
    g_MainWindow->RedrawAll();
}
void FrameAlignGroup::cb_1(Fl_Button* o, void* v) {
  ((FrameAlignGroup*)(o->parent()))->cb_1_i(o,v);
}

void FrameAlignGroup::cb_3_i(Fl_Button*, void*) {
  extern AnimationSet g_AnimationSet;
    extern MainWindow *g_MainWindow;
    g_MainWindow->RedrawAll();
}
void FrameAlignGroup::cb_3(Fl_Button* o, void* v) {
  ((FrameAlignGroup*)(o->parent()))->cb_3_i(o,v);
}

void FrameAlignGroup::cb_5_i(Fl_Button*, void*) {
  extern AnimationSet g_AnimationSet;
g_AnimationSet.NextFrame();
    extern MainWindow *g_MainWindow;
    g_MainWindow->RedrawAll();
}
void FrameAlignGroup::cb_5(Fl_Button* o, void* v) {
  ((FrameAlignGroup*)(o->parent()))->cb_5_i(o,v);
}

void FrameAlignGroup::cb_6_i(Fl_Button*, void*) {
  extern AnimationSet g_AnimationSet;
g_AnimationSet.LastFrame();
    extern MainWindow *g_MainWindow;
    g_MainWindow->RedrawAll();
}
void FrameAlignGroup::cb_6(Fl_Button* o, void* v) {
  ((FrameAlignGroup*)(o->parent()))->cb_6_i(o,v);
}
FrameAlignGroup::FrameAlignGroup(int X, int Y, int W, int H, const char *L)
  : Fl_Group(0, 0, W, H, L) {
{ Fl_Button* o = new Fl_Button(106, 22, 50, 50, "@8->");
  o->callback((Fl_Callback*)cb_8);
} // Fl_Button* o
{ Fl_Button* o = new Fl_Button(106, 120, 50, 50, "@2->");
  o->callback((Fl_Callback*)cb_2);
} // Fl_Button* o
{ Fl_Button* o = new Fl_Button(57, 71, 50, 50, "@4->");
  o->callback((Fl_Callback*)cb_4);
} // Fl_Button* o
{ Fl_Button* o = new Fl_Button(155, 71, 50, 50, "@->");
  o->callback((Fl_Callback*)cb_);
} // Fl_Button* o
{ m_VSResolution = new Fl_Value_Slider(28, 315, 205, 20, "Resolution");
  m_VSResolution->type(1);
  m_VSResolution->labelfont(4);
  m_VSResolution->minimum(1);
  m_VSResolution->maximum(100);
  m_VSResolution->step(1);
  m_VSResolution->value(1);
  m_VSResolution->textfont(4);
  m_VSResolution->textsize(14);
} // Fl_Value_Slider* m_VSResolution
{ Fl_Button* o = new Fl_Button(33, 217, 50, 45, "@|<");
  o->callback((Fl_Callback*)cb_1);
} // Fl_Button* o
{ Fl_Button* o = new Fl_Button(83, 217, 50, 45, "@<-");
  o->callback((Fl_Callback*)cb_3);
} // Fl_Button* o
{ Fl_Button* o = new Fl_Button(133, 217, 50, 45, "@->");
  o->callback((Fl_Callback*)cb_5);
} // Fl_Button* o
{ Fl_Button* o = new Fl_Button(183, 217, 50, 45, "@>|");
  o->callback((Fl_Callback*)cb_6);
} // Fl_Button* o
position(X, Y);
end();
}
