// generated by Fast Light User Interface Designer (fluid) version 1.0303

#ifndef mainwindow_hpp
#define mainwindow_hpp
#include <FL/Fl.H>
#include "operationarea.hpp"
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Menu_Bar.H>
#include <FL/Fl_Native_File_Chooser.H>
#include <FL/fl_ask.H>
#include "validwilfilewindow.hpp"
#include "animationset.hpp"
#include "actionsettestgroup.hpp"
#include "dynamicshadowgroup.hpp"
#include "aboutwindow.hpp"
#include "operationarea.hpp"
#include "rectcovereditgroup.hpp"
#include "shadoweditgroup.hpp"
#include "framealigngroup.hpp"
#include "actionsetaligngroup.hpp"
#include <FL/Fl_Group.H>
#include <FL/Fl_Choice.H>

class MainWindow {
public:
  MainWindow();
private:
  Fl_Double_Window *m_Window;
  inline void cb_m_Window_i(Fl_Double_Window*, void*);
  static void cb_m_Window(Fl_Double_Window*, void*);
  Fl_Menu_Bar *m_MenuBar;
  static Fl_Menu_Item menu_m_MenuBar[];
  inline void cb_Load_i(Fl_Menu_*, void*);
  static void cb_Load(Fl_Menu_*, void*);
  inline void cb_Export_i(Fl_Menu_*, void*);
  static void cb_Export(Fl_Menu_*, void*);
  inline void cb_Quit_i(Fl_Menu_*, void*);
  static void cb_Quit(Fl_Menu_*, void*);
  static Fl_Menu_Item *m_MenuItemShowBodyLayer;
  static Fl_Menu_Item *m_MenuItemShowShadowLayer;
  static Fl_Menu_Item *m_MenuItemRectCover;
  static Fl_Menu_Item *m_MenuItemBodyFrame;
  static Fl_Menu_Item *m_MenuItemShadowFrame;
  static Fl_Menu_Item *m_MenuItemEnableEdit;
  inline void cb_m_MenuItemEnableEdit_i(Fl_Menu_*, void*);
  static void cb_m_MenuItemEnableEdit(Fl_Menu_*, void*);
  static Fl_Menu_Item *m_MenuItemEnableAnimation;
  static Fl_Menu_Item *m_MenuItemEditCover;
  inline void cb_m_MenuItemEditCover_i(Fl_Menu_*, void*);
  static void cb_m_MenuItemEditCover(Fl_Menu_*, void*);
  static Fl_Menu_Item *m_MenuItemEditShadow;
  inline void cb_m_MenuItemEditShadow_i(Fl_Menu_*, void*);
  static void cb_m_MenuItemEditShadow(Fl_Menu_*, void*);
  static Fl_Menu_Item *m_MenuItemEditFrameAlign;
  inline void cb_m_MenuItemEditFrameAlign_i(Fl_Menu_*, void*);
  static void cb_m_MenuItemEditFrameAlign(Fl_Menu_*, void*);
  static Fl_Menu_Item *m_MenuItemEditActionSetAlign;
  inline void cb_m_MenuItemEditActionSetAlign_i(Fl_Menu_*, void*);
  static void cb_m_MenuItemEditActionSetAlign(Fl_Menu_*, void*);
  static Fl_Menu_Item *m_MenuItemDynamicShadow;
  inline void cb_m_MenuItemDynamicShadow_i(Fl_Menu_*, void*);
  static void cb_m_MenuItemDynamicShadow(Fl_Menu_*, void*);
  static Fl_Menu_Item *m_MenuItemTest;
  inline void cb_m_MenuItemTest_i(Fl_Menu_*, void*);
  static void cb_m_MenuItemTest(Fl_Menu_*, void*);
  inline void cb_About_i(Fl_Menu_*, void*);
  static void cb_About(Fl_Menu_*, void*);
  OperationArea *m_OperationArea;
  RectCoverEditGroup *m_RectCoverEditGroup;
public:
  ShadowEditGroup *m_ShadowEditGroup;
  FrameAlignGroup *m_FrameAlignGroup;
  ActionSetAlignGroup *m_ActionSetAlignGroup;
  Fl_Group *m_StatusDirectionGroup;
  Fl_Choice *m_ChoiceStatus;
  Fl_Choice *m_ChoiceDirection;
  DynamicShadowGroup *m_DynamicShadowGroup;
  ActionSetTestGroup *m_TestGroup;
  void ShowAll();
  void RedrawAll();
  void LoadAnimationSet();
  void MakeCurrent();
  bool ShowRectCover();
  bool ShowBodyLayer();
  bool ShowBodyFrame();
  bool ShowShadowLayer();
  bool ShowShadowFrame();
  bool EnableEdit();
  void EnableAnimation(bool bEnable);
  bool EditCover();
  bool EditDynamicShadow();
  bool EditFrameAlign();
  bool EditActionSetAlign();
  bool EditShadow();
  bool NeedUpdateFrame();
  int RectCoverCopyMethod();
  bool TestMode();
  bool TestAnimation();
  void TestAnimationUpdate();
  void AddStatusItem();
  void AddDirectionItem(int nStatus);
  static void StatusItemCallback(Fl_Widget *, void *pData);
  static void DirectionItemCallback(Fl_Widget *, void *pData);
  void MakeWorkingFolder();
  void OperationRect(int &nX, int &nY, int &nW, int &nH);
  int DynamicShadowPoint();
  int DynamicShadowMethod();
  void DynamicShadowMethodReset();
};
#endif
