// generated by Fast Light User Interface Designer (fluid) version 1.0303

#ifndef rectcovereditgroup_hpp
#define rectcovereditgroup_hpp
#include <FL/Fl.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Button.H>
#include "animationset.hpp"
#include <FL/Fl_Value_Slider.H>
#include <FL/Fl_Round_Button.H>

class RectCoverEditGroup : public Fl_Group {
public:
  RectCoverEditGroup(int X, int Y, int W, int H, const char *L = 0);
private:
  inline void cb_8_i(Fl_Button*, void*);
  static void cb_8(Fl_Button*, void*);
  inline void cb_2_i(Fl_Button*, void*);
  static void cb_2(Fl_Button*, void*);
  inline void cb_4_i(Fl_Button*, void*);
  static void cb_4(Fl_Button*, void*);
  inline void cb__i(Fl_Button*, void*);
  static void cb_(Fl_Button*, void*);
  inline void cb_1_i(Fl_Button*, void*);
  static void cb_1(Fl_Button*, void*);
  inline void cb_11_i(Fl_Button*, void*);
  static void cb_11(Fl_Button*, void*);
  inline void cb_12_i(Fl_Button*, void*);
  static void cb_12(Fl_Button*, void*);
  inline void cb_13_i(Fl_Button*, void*);
  static void cb_13(Fl_Button*, void*);
public:
  Fl_Value_Slider *m_VSResolution;
  Fl_Round_Button *m_RadioBtnNoneCopy;
  Fl_Round_Button *m_RadioBtnSameCopy;
  Fl_Round_Button *m_RadioBtnDualCopy;
private:
  inline void cb_W_i(Fl_Button*, void*);
  static void cb_W(Fl_Button*, void*);
  inline void cb_W1_i(Fl_Button*, void*);
  static void cb_W1(Fl_Button*, void*);
  inline void cb_H_i(Fl_Button*, void*);
  static void cb_H(Fl_Button*, void*);
  inline void cb_H1_i(Fl_Button*, void*);
  static void cb_H1(Fl_Button*, void*);
public:
  int RectCoverCopyMethod();
};
#endif
