// generated by Fast Light User Interface Designer (fluid) version 1.0303

#ifndef sidwindow_hpp
#define sidwindow_hpp
#include <FL/Fl.H>
#include <cmath>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Value_Input.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Choice.H>

class SIDWindow {
public:
  SIDWindow();
  Fl_Double_Window *m_Window;
  Fl_Value_Input *m_Input;
private:
  inline void cb_OK_i(Fl_Button*, void*);
  static void cb_OK(Fl_Button*, void*);
public:
  Fl_Choice *m_Gender;
  static Fl_Menu_Item menu_m_Gender[];
  void ShowAll();
  int BaseLID();
  int Gender();
};
#endif
