// generated by Fast Light User Interface Designer (fluid) version 1.0303

#ifndef validwilfilewindow_hpp
#define validwilfilewindow_hpp
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Browser.H>
#include "wilimagepackage.hpp"
#include "progressbarwindow.hpp"
#include "validanimationwindow.hpp"

class ValidWilFileWindow {
public:
  ValidWilFileWindow();
private:
  Fl_Double_Window *m_Window;
  inline void cb_m_Window_i(Fl_Double_Window*, void*);
  static void cb_m_Window(Fl_Double_Window*, void*);
  Fl_Browser *m_ValidWilFileBrowser;
  inline void cb_m_ValidWilFileBrowser_i(Fl_Browser*, void*);
  static void cb_m_ValidWilFileBrowser(Fl_Browser*, void*);
public:
  void ShowAll();
  void CheckValidWilFile(const char *szWilFolderName);
};
#endif
