/*
 * =====================================================================================
 *
 *       Filename: dropitemconfig.inc
 *        Created: 07/28/2017 12:25:39
 *  Last Modified: 07/30/2017 00:10:21
 *
 *    Description: 
 *
 *        Version: 1.0
 *       Revision: none
 *       Compiler: gcc
 *
 *         Author: ANHONG
 *          Email: anhonghe@gmail.com
 *   Organization: USTC
 *
 * =====================================================================================
 */

// +-MonsterName--------+-ItemName-----------+-Group-------+-ProbRecip--------+-Repeat-----------+-Value--------+
{  u8"鹿"               , u8"金币"           , 0           , 1                , 1                , 100          },
{  u8"鹿"               , u8"金币"           , 0           , 1                , 1                , 100          },
{  u8"鹿"               , u8"金币"           , 0           , 1                , 1                , 100          },
