// generated by Fast Light User Interface Designer (fluid) version 1.0303

#include "sidwindow.hpp"

void SIDWindow::cb_OK_i(Fl_Button*, void*) {
  {
    m_Window->hide();
};
}
void SIDWindow::cb_OK(Fl_Button* o, void* v) {
  ((SIDWindow*)(o->parent()->user_data()))->cb_OK_i(o,v);
}

SIDWindow::SIDWindow() {
  { m_Window = new Fl_Double_Window(294, 125, "Please Set Monster SID");
    m_Window->user_data((void*)(this));
    { m_Input = new Fl_Value_Input(99, 27, 115, 24, "SID:");
      m_Input->labelfont(4);
      m_Input->value(1024);
      m_Input->textfont(4);
    } // Fl_Value_Input* m_Input
    { Fl_Button* o = new Fl_Button(190, 70, 64, 25, "OK");
      o->labelfont(4);
      o->callback((Fl_Callback*)cb_OK);
    } // Fl_Button* o
    m_Window->end();
  } // Fl_Double_Window* m_Window
}

void SIDWindow::ShowAll() {
  {
      m_Window->show();
  }
}

int SIDWindow::SID() {
  {
      return (int)std::lround(m_Input->value());
  }
}
