// generated by Fast Light User Interface Designer (fluid) version 1.0303

#ifndef configurewindow_hpp
#define configurewindow_hpp
#include <FL/Fl.H>
#include <cmath>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Value_Input.H>
#include <FL/Fl_Input.H>

class ConfigureWindow {
public:
  ConfigureWindow();
  Fl_Double_Window *m_Window;
  Fl_Value_Input *m_VIPort1;
  Fl_Value_Input *m_VIPort2;
  Fl_Input *m_DatabaseIP;
  Fl_Value_Input *m_DatabasePort;
  Fl_Input *m_UserName;
  Fl_Input *m_Password;
  Fl_Input *m_DatabaseName;
  void ShowAll();
  int ClientPort();
  int SceneServerPort();
  int DatabasePort();
  const char * DatabaseIP();
  const char * DatabaseName();
  const char * UserName();
  const char * Password();
};
#endif
