// generated by Fast Light User Interface Designer (fluid) version 1.0303

#ifndef serverconfigurewindow_hpp
#define serverconfigurewindow_hpp
#include <FL/Fl.H>
#include <cmath>
#include <algorithm>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Value_Input.H>
#include <FL/Fl_Input.H>
#include <FL/Fl_Button.H>
#include <string>
#include <FL/Fl_Native_File_Chooser.H>
#include <FL/fl_ask.H>

class ServerConfigureWindow {
public:
  ServerConfigureWindow();
  Fl_Double_Window *m_Window;
  Fl_Value_Input *m_MaxPlayerCount;
  Fl_Input *m_MapFullName;
  Fl_Value_Input *m_EquipRate;
  Fl_Value_Input *m_ExpRate;
  Fl_Value_Input *m_GoldRate;
private:
  inline void cb_fileopen_i(Fl_Button*, void*);
  static void cb_fileopen(Fl_Button*, void*);
public:
  Fl_Value_Input *m_MaxMonsterCount;
  void ShowAll();
  const char * MapFullName();
  int MaxPlayerCount();
  double ExpRate();
  double EquipRate();
  double GoldRate();
  int MaxMonsterCount();
};
#endif
