// generated by Fast Light User Interface Designer (fluid) version 1.0303

#ifndef cropconfigurewindow_hpp
#define cropconfigurewindow_hpp
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Value_Input.H>
#include <FL/Fl_Button.H>
#include <algorithm>
#include "mir2map.hpp"
#include "mainwindow.hpp"

class CropConfigureWindow {
public:
  CropConfigureWindow();
  Fl_Double_Window *m_Window;
  Fl_Value_Input *m_Top;
  Fl_Value_Input *m_Bottom;
  Fl_Value_Input *m_Left;
  Fl_Value_Input *m_Right;
private:
  inline void cb_OK_i(Fl_Button*, void*);
  static void cb_OK(Fl_Button*, void*);
public:
  void ShowAll();
};
#endif
