// generated by Fast Light User Interface Designer (fluid) version 1.0303

#ifndef groundinfowindow_hpp
#define groundinfowindow_hpp
#include <FL/Fl.H>
#include <cstdint>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Check_Button.H>
#include <FL/Fl_Button.H>
#include "mainwindow.hpp"
#include <FL/Fl_Menu_Bar.H>

class GroundInfoWindow {
public:
  GroundInfoWindow();
  Fl_Double_Window *m_Window;
private:
  inline void cb__i(Fl_Group*, void*);
  static void cb_(Fl_Group*, void*);
public:
  Fl_Check_Button *m_Bit0;
private:
  inline void cb_m_Bit0_i(Fl_Check_Button*, void*);
  static void cb_m_Bit0(Fl_Check_Button*, void*);
public:
  Fl_Check_Button *m_Bit1;
private:
  inline void cb_m_Bit1_i(Fl_Check_Button*, void*);
  static void cb_m_Bit1(Fl_Check_Button*, void*);
public:
  Fl_Check_Button *m_Bit2;
private:
  inline void cb_m_Bit2_i(Fl_Check_Button*, void*);
  static void cb_m_Bit2(Fl_Check_Button*, void*);
public:
  Fl_Check_Button *m_Bit3;
private:
  inline void cb_m_Bit3_i(Fl_Check_Button*, void*);
  static void cb_m_Bit3(Fl_Check_Button*, void*);
public:
  Fl_Check_Button *m_Bit4;
private:
  inline void cb_m_Bit4_i(Fl_Check_Button*, void*);
  static void cb_m_Bit4(Fl_Check_Button*, void*);
public:
  Fl_Check_Button *m_Bit5;
private:
  inline void cb_m_Bit5_i(Fl_Check_Button*, void*);
  static void cb_m_Bit5(Fl_Check_Button*, void*);
public:
  Fl_Check_Button *m_Bit6;
private:
  inline void cb_m_Bit6_i(Fl_Check_Button*, void*);
  static void cb_m_Bit6(Fl_Check_Button*, void*);
public:
  Fl_Check_Button *m_Bit7;
private:
  inline void cb_m_Bit7_i(Fl_Check_Button*, void*);
  static void cb_m_Bit7(Fl_Check_Button*, void*);
public:
  Fl_Check_Button *m_Bit8;
private:
  inline void cb_m_Bit8_i(Fl_Check_Button*, void*);
  static void cb_m_Bit8(Fl_Check_Button*, void*);
public:
  Fl_Check_Button *m_Bit9;
private:
  inline void cb_m_Bit9_i(Fl_Check_Button*, void*);
  static void cb_m_Bit9(Fl_Check_Button*, void*);
public:
  Fl_Check_Button *m_Bit10;
private:
  inline void cb_m_Bit10_i(Fl_Check_Button*, void*);
  static void cb_m_Bit10(Fl_Check_Button*, void*);
public:
  Fl_Check_Button *m_Bit11;
private:
  inline void cb_m_Bit11_i(Fl_Check_Button*, void*);
  static void cb_m_Bit11(Fl_Check_Button*, void*);
public:
  Fl_Check_Button *m_Bit12;
private:
  inline void cb_m_Bit12_i(Fl_Check_Button*, void*);
  static void cb_m_Bit12(Fl_Check_Button*, void*);
public:
  Fl_Check_Button *m_Bit13;
private:
  inline void cb_m_Bit13_i(Fl_Check_Button*, void*);
  static void cb_m_Bit13(Fl_Check_Button*, void*);
public:
  Fl_Check_Button *m_Bit14;
private:
  inline void cb_m_Bit14_i(Fl_Check_Button*, void*);
  static void cb_m_Bit14(Fl_Check_Button*, void*);
public:
  Fl_Check_Button *m_Bit15;
private:
  inline void cb_m_Bit15_i(Fl_Check_Button*, void*);
  static void cb_m_Bit15(Fl_Check_Button*, void*);
public:
  Fl_Check_Button *m_Bit16;
private:
  inline void cb_m_Bit16_i(Fl_Check_Button*, void*);
  static void cb_m_Bit16(Fl_Check_Button*, void*);
public:
  Fl_Check_Button *m_Bit17;
private:
  inline void cb_m_Bit17_i(Fl_Check_Button*, void*);
  static void cb_m_Bit17(Fl_Check_Button*, void*);
public:
  Fl_Check_Button *m_Bit18;
private:
  inline void cb_m_Bit18_i(Fl_Check_Button*, void*);
  static void cb_m_Bit18(Fl_Check_Button*, void*);
public:
  Fl_Check_Button *m_Bit19;
private:
  inline void cb_m_Bit19_i(Fl_Check_Button*, void*);
  static void cb_m_Bit19(Fl_Check_Button*, void*);
public:
  Fl_Check_Button *m_Bit20;
private:
  inline void cb_m_Bit20_i(Fl_Check_Button*, void*);
  static void cb_m_Bit20(Fl_Check_Button*, void*);
public:
  Fl_Check_Button *m_Bit21;
private:
  inline void cb_m_Bit21_i(Fl_Check_Button*, void*);
  static void cb_m_Bit21(Fl_Check_Button*, void*);
public:
  Fl_Check_Button *m_Bit22;
private:
  inline void cb_m_Bit22_i(Fl_Check_Button*, void*);
  static void cb_m_Bit22(Fl_Check_Button*, void*);
public:
  Fl_Check_Button *m_Bit23;
private:
  inline void cb_m_Bit23_i(Fl_Check_Button*, void*);
  static void cb_m_Bit23(Fl_Check_Button*, void*);
public:
  Fl_Check_Button *m_Bit24;
private:
  inline void cb_m_Bit24_i(Fl_Check_Button*, void*);
  static void cb_m_Bit24(Fl_Check_Button*, void*);
public:
  Fl_Check_Button *m_Bit25;
private:
  inline void cb_m_Bit25_i(Fl_Check_Button*, void*);
  static void cb_m_Bit25(Fl_Check_Button*, void*);
public:
  Fl_Check_Button *m_Bit26;
private:
  inline void cb_m_Bit26_i(Fl_Check_Button*, void*);
  static void cb_m_Bit26(Fl_Check_Button*, void*);
public:
  Fl_Check_Button *m_Bit27;
private:
  inline void cb_m_Bit27_i(Fl_Check_Button*, void*);
  static void cb_m_Bit27(Fl_Check_Button*, void*);
public:
  Fl_Check_Button *m_Bit28;
private:
  inline void cb_m_Bit28_i(Fl_Check_Button*, void*);
  static void cb_m_Bit28(Fl_Check_Button*, void*);
public:
  Fl_Check_Button *m_Bit29;
private:
  inline void cb_m_Bit29_i(Fl_Check_Button*, void*);
  static void cb_m_Bit29(Fl_Check_Button*, void*);
public:
  Fl_Check_Button *m_Bit30;
private:
  inline void cb_m_Bit30_i(Fl_Check_Button*, void*);
  static void cb_m_Bit30(Fl_Check_Button*, void*);
public:
  Fl_Check_Button *m_Bit31;
private:
  inline void cb_m_Bit31_i(Fl_Check_Button*, void*);
  static void cb_m_Bit31(Fl_Check_Button*, void*);
  inline void cb_Reset_i(Fl_Button*, void*);
  static void cb_Reset(Fl_Button*, void*);
  inline void cb_Forbidden_i(Fl_Button*, void*);
  static void cb_Forbidden(Fl_Button*, void*);
  static Fl_Menu_Item menu_[];
public:
  static Fl_Menu_Item *m_Eq;
  static Fl_Menu_Item *m_Neq;
  static Fl_Menu_Item *m_Overlap;
  static Fl_Menu_Item *m_Exclude;
  static Fl_Menu_Item *m_Subset;
  static Fl_Menu_Item *m_Superset;
  static Fl_Menu_Item *m_Complement;
private:
  inline void cb_Flop_i(Fl_Button*, void*);
  static void cb_Flop(Fl_Button*, void*);
public:
  void ShowAll();
  uint32_t Mask();
  bool Test(uint32_t nInput);
};
#endif
