// generated by Fast Light User Interface Designer (fluid) version 1.0303

#include "groundinfowindow.hpp"

void GroundInfoWindow::cb__i(Fl_Group*, void*) {
  {
    extern MainWindow *g_MainWindow;
    g_MainWindow->RedrawAll();
};
}
void GroundInfoWindow::cb_(Fl_Group* o, void* v) {
  ((GroundInfoWindow*)(o->parent()->user_data()))->cb__i(o,v);
}

void GroundInfoWindow::cb_m_Bit0_i(Fl_Check_Button*, void*) {
  {
    extern MainWindow *g_MainWindow;
    g_MainWindow->RedrawAll();
};
}
void GroundInfoWindow::cb_m_Bit0(Fl_Check_Button* o, void* v) {
  ((GroundInfoWindow*)(o->parent()->parent()->user_data()))->cb_m_Bit0_i(o,v);
}

void GroundInfoWindow::cb_m_Bit1_i(Fl_Check_Button*, void*) {
  {
    extern MainWindow *g_MainWindow;
    g_MainWindow->RedrawAll();
};
}
void GroundInfoWindow::cb_m_Bit1(Fl_Check_Button* o, void* v) {
  ((GroundInfoWindow*)(o->parent()->parent()->user_data()))->cb_m_Bit1_i(o,v);
}

void GroundInfoWindow::cb_m_Bit2_i(Fl_Check_Button*, void*) {
  {
    extern MainWindow *g_MainWindow;
    g_MainWindow->RedrawAll();
};
}
void GroundInfoWindow::cb_m_Bit2(Fl_Check_Button* o, void* v) {
  ((GroundInfoWindow*)(o->parent()->parent()->user_data()))->cb_m_Bit2_i(o,v);
}

void GroundInfoWindow::cb_m_Bit3_i(Fl_Check_Button*, void*) {
  {
    extern MainWindow *g_MainWindow;
    g_MainWindow->RedrawAll();
};
}
void GroundInfoWindow::cb_m_Bit3(Fl_Check_Button* o, void* v) {
  ((GroundInfoWindow*)(o->parent()->parent()->user_data()))->cb_m_Bit3_i(o,v);
}

void GroundInfoWindow::cb_m_Bit4_i(Fl_Check_Button*, void*) {
  {
    extern MainWindow *g_MainWindow;
    g_MainWindow->RedrawAll();
};
}
void GroundInfoWindow::cb_m_Bit4(Fl_Check_Button* o, void* v) {
  ((GroundInfoWindow*)(o->parent()->parent()->user_data()))->cb_m_Bit4_i(o,v);
}

void GroundInfoWindow::cb_m_Bit5_i(Fl_Check_Button*, void*) {
  {
    extern MainWindow *g_MainWindow;
    g_MainWindow->RedrawAll();
};
}
void GroundInfoWindow::cb_m_Bit5(Fl_Check_Button* o, void* v) {
  ((GroundInfoWindow*)(o->parent()->parent()->user_data()))->cb_m_Bit5_i(o,v);
}

void GroundInfoWindow::cb_m_Bit6_i(Fl_Check_Button*, void*) {
  {
    extern MainWindow *g_MainWindow;
    g_MainWindow->RedrawAll();
};
}
void GroundInfoWindow::cb_m_Bit6(Fl_Check_Button* o, void* v) {
  ((GroundInfoWindow*)(o->parent()->parent()->user_data()))->cb_m_Bit6_i(o,v);
}

void GroundInfoWindow::cb_m_Bit7_i(Fl_Check_Button*, void*) {
  {
    extern MainWindow *g_MainWindow;
    g_MainWindow->RedrawAll();
};
}
void GroundInfoWindow::cb_m_Bit7(Fl_Check_Button* o, void* v) {
  ((GroundInfoWindow*)(o->parent()->parent()->user_data()))->cb_m_Bit7_i(o,v);
}

void GroundInfoWindow::cb_m_Bit8_i(Fl_Check_Button*, void*) {
  {
    extern MainWindow *g_MainWindow;
    g_MainWindow->RedrawAll();
};
}
void GroundInfoWindow::cb_m_Bit8(Fl_Check_Button* o, void* v) {
  ((GroundInfoWindow*)(o->parent()->parent()->user_data()))->cb_m_Bit8_i(o,v);
}

void GroundInfoWindow::cb_m_Bit9_i(Fl_Check_Button*, void*) {
  {
    extern MainWindow *g_MainWindow;
    g_MainWindow->RedrawAll();
};
}
void GroundInfoWindow::cb_m_Bit9(Fl_Check_Button* o, void* v) {
  ((GroundInfoWindow*)(o->parent()->parent()->user_data()))->cb_m_Bit9_i(o,v);
}

void GroundInfoWindow::cb_m_Bit10_i(Fl_Check_Button*, void*) {
  {
    extern MainWindow *g_MainWindow;
    g_MainWindow->RedrawAll();
};
}
void GroundInfoWindow::cb_m_Bit10(Fl_Check_Button* o, void* v) {
  ((GroundInfoWindow*)(o->parent()->parent()->user_data()))->cb_m_Bit10_i(o,v);
}

void GroundInfoWindow::cb_m_Bit11_i(Fl_Check_Button*, void*) {
  {
    extern MainWindow *g_MainWindow;
    g_MainWindow->RedrawAll();
};
}
void GroundInfoWindow::cb_m_Bit11(Fl_Check_Button* o, void* v) {
  ((GroundInfoWindow*)(o->parent()->parent()->user_data()))->cb_m_Bit11_i(o,v);
}

void GroundInfoWindow::cb_m_Bit12_i(Fl_Check_Button*, void*) {
  {
    extern MainWindow *g_MainWindow;
    g_MainWindow->RedrawAll();
};
}
void GroundInfoWindow::cb_m_Bit12(Fl_Check_Button* o, void* v) {
  ((GroundInfoWindow*)(o->parent()->parent()->user_data()))->cb_m_Bit12_i(o,v);
}

void GroundInfoWindow::cb_m_Bit13_i(Fl_Check_Button*, void*) {
  {
    extern MainWindow *g_MainWindow;
    g_MainWindow->RedrawAll();
};
}
void GroundInfoWindow::cb_m_Bit13(Fl_Check_Button* o, void* v) {
  ((GroundInfoWindow*)(o->parent()->parent()->user_data()))->cb_m_Bit13_i(o,v);
}

void GroundInfoWindow::cb_m_Bit14_i(Fl_Check_Button*, void*) {
  {
    extern MainWindow *g_MainWindow;
    g_MainWindow->RedrawAll();
};
}
void GroundInfoWindow::cb_m_Bit14(Fl_Check_Button* o, void* v) {
  ((GroundInfoWindow*)(o->parent()->parent()->user_data()))->cb_m_Bit14_i(o,v);
}

void GroundInfoWindow::cb_m_Bit15_i(Fl_Check_Button*, void*) {
  {
    extern MainWindow *g_MainWindow;
    g_MainWindow->RedrawAll();
};
}
void GroundInfoWindow::cb_m_Bit15(Fl_Check_Button* o, void* v) {
  ((GroundInfoWindow*)(o->parent()->parent()->user_data()))->cb_m_Bit15_i(o,v);
}

void GroundInfoWindow::cb_m_Bit16_i(Fl_Check_Button*, void*) {
  {
    extern MainWindow *g_MainWindow;
    g_MainWindow->RedrawAll();
};
}
void GroundInfoWindow::cb_m_Bit16(Fl_Check_Button* o, void* v) {
  ((GroundInfoWindow*)(o->parent()->parent()->user_data()))->cb_m_Bit16_i(o,v);
}

void GroundInfoWindow::cb_m_Bit17_i(Fl_Check_Button*, void*) {
  {
    extern MainWindow *g_MainWindow;
    g_MainWindow->RedrawAll();
};
}
void GroundInfoWindow::cb_m_Bit17(Fl_Check_Button* o, void* v) {
  ((GroundInfoWindow*)(o->parent()->parent()->user_data()))->cb_m_Bit17_i(o,v);
}

void GroundInfoWindow::cb_m_Bit18_i(Fl_Check_Button*, void*) {
  {
    extern MainWindow *g_MainWindow;
    g_MainWindow->RedrawAll();
};
}
void GroundInfoWindow::cb_m_Bit18(Fl_Check_Button* o, void* v) {
  ((GroundInfoWindow*)(o->parent()->parent()->user_data()))->cb_m_Bit18_i(o,v);
}

void GroundInfoWindow::cb_m_Bit19_i(Fl_Check_Button*, void*) {
  {
    extern MainWindow *g_MainWindow;
    g_MainWindow->RedrawAll();
};
}
void GroundInfoWindow::cb_m_Bit19(Fl_Check_Button* o, void* v) {
  ((GroundInfoWindow*)(o->parent()->parent()->user_data()))->cb_m_Bit19_i(o,v);
}

void GroundInfoWindow::cb_m_Bit20_i(Fl_Check_Button*, void*) {
  {
    extern MainWindow *g_MainWindow;
    g_MainWindow->RedrawAll();
};
}
void GroundInfoWindow::cb_m_Bit20(Fl_Check_Button* o, void* v) {
  ((GroundInfoWindow*)(o->parent()->parent()->user_data()))->cb_m_Bit20_i(o,v);
}

void GroundInfoWindow::cb_m_Bit21_i(Fl_Check_Button*, void*) {
  {
    extern MainWindow *g_MainWindow;
    g_MainWindow->RedrawAll();
};
}
void GroundInfoWindow::cb_m_Bit21(Fl_Check_Button* o, void* v) {
  ((GroundInfoWindow*)(o->parent()->parent()->user_data()))->cb_m_Bit21_i(o,v);
}

void GroundInfoWindow::cb_m_Bit22_i(Fl_Check_Button*, void*) {
  {
    extern MainWindow *g_MainWindow;
    g_MainWindow->RedrawAll();
};
}
void GroundInfoWindow::cb_m_Bit22(Fl_Check_Button* o, void* v) {
  ((GroundInfoWindow*)(o->parent()->parent()->user_data()))->cb_m_Bit22_i(o,v);
}

void GroundInfoWindow::cb_m_Bit23_i(Fl_Check_Button*, void*) {
  {
    extern MainWindow *g_MainWindow;
    g_MainWindow->RedrawAll();
};
}
void GroundInfoWindow::cb_m_Bit23(Fl_Check_Button* o, void* v) {
  ((GroundInfoWindow*)(o->parent()->parent()->user_data()))->cb_m_Bit23_i(o,v);
}

void GroundInfoWindow::cb_m_Bit24_i(Fl_Check_Button*, void*) {
  {
    extern MainWindow *g_MainWindow;
    g_MainWindow->RedrawAll();
};
}
void GroundInfoWindow::cb_m_Bit24(Fl_Check_Button* o, void* v) {
  ((GroundInfoWindow*)(o->parent()->parent()->user_data()))->cb_m_Bit24_i(o,v);
}

void GroundInfoWindow::cb_m_Bit25_i(Fl_Check_Button*, void*) {
  {
    extern MainWindow *g_MainWindow;
    g_MainWindow->RedrawAll();
};
}
void GroundInfoWindow::cb_m_Bit25(Fl_Check_Button* o, void* v) {
  ((GroundInfoWindow*)(o->parent()->parent()->user_data()))->cb_m_Bit25_i(o,v);
}

void GroundInfoWindow::cb_m_Bit26_i(Fl_Check_Button*, void*) {
  {
    extern MainWindow *g_MainWindow;
    g_MainWindow->RedrawAll();
};
}
void GroundInfoWindow::cb_m_Bit26(Fl_Check_Button* o, void* v) {
  ((GroundInfoWindow*)(o->parent()->parent()->user_data()))->cb_m_Bit26_i(o,v);
}

void GroundInfoWindow::cb_m_Bit27_i(Fl_Check_Button*, void*) {
  {
    extern MainWindow *g_MainWindow;
    g_MainWindow->RedrawAll();
};
}
void GroundInfoWindow::cb_m_Bit27(Fl_Check_Button* o, void* v) {
  ((GroundInfoWindow*)(o->parent()->parent()->user_data()))->cb_m_Bit27_i(o,v);
}

void GroundInfoWindow::cb_m_Bit28_i(Fl_Check_Button*, void*) {
  {
    extern MainWindow *g_MainWindow;
    g_MainWindow->RedrawAll();
};
}
void GroundInfoWindow::cb_m_Bit28(Fl_Check_Button* o, void* v) {
  ((GroundInfoWindow*)(o->parent()->parent()->user_data()))->cb_m_Bit28_i(o,v);
}

void GroundInfoWindow::cb_m_Bit29_i(Fl_Check_Button*, void*) {
  {
    extern MainWindow *g_MainWindow;
    g_MainWindow->RedrawAll();
};
}
void GroundInfoWindow::cb_m_Bit29(Fl_Check_Button* o, void* v) {
  ((GroundInfoWindow*)(o->parent()->parent()->user_data()))->cb_m_Bit29_i(o,v);
}

void GroundInfoWindow::cb_m_Bit30_i(Fl_Check_Button*, void*) {
  {
    extern MainWindow *g_MainWindow;
    g_MainWindow->RedrawAll();
};
}
void GroundInfoWindow::cb_m_Bit30(Fl_Check_Button* o, void* v) {
  ((GroundInfoWindow*)(o->parent()->parent()->user_data()))->cb_m_Bit30_i(o,v);
}

void GroundInfoWindow::cb_m_Bit31_i(Fl_Check_Button*, void*) {
  {
    extern MainWindow *g_MainWindow;
    g_MainWindow->RedrawAll();
};
}
void GroundInfoWindow::cb_m_Bit31(Fl_Check_Button* o, void* v) {
  ((GroundInfoWindow*)(o->parent()->parent()->user_data()))->cb_m_Bit31_i(o,v);
}

void GroundInfoWindow::cb_Reset_i(Fl_Button*, void*) {
  {
    m_Bit0 ->value(0);
    m_Bit1 ->value(0);
    m_Bit2 ->value(0);
    m_Bit3 ->value(0);
    m_Bit4 ->value(0);
    m_Bit5 ->value(0);
    m_Bit6 ->value(0);
    m_Bit7 ->value(0);
    m_Bit8 ->value(0);
    m_Bit9 ->value(0);
    m_Bit10->value(0);
    m_Bit11->value(0);
    m_Bit12->value(0);
    m_Bit13->value(0);
    m_Bit14->value(0);
    m_Bit15->value(0);
    m_Bit16->value(0);
    m_Bit17->value(0);
    m_Bit18->value(0);
    m_Bit19->value(0);
    m_Bit20->value(0);
    m_Bit21->value(0);
    m_Bit22->value(0);
    m_Bit23->value(0);
    m_Bit24->value(0);
    m_Bit25->value(0);
    m_Bit26->value(0);
    m_Bit27->value(0);
    m_Bit28->value(0);
    m_Bit29->value(0);
    m_Bit30->value(0);
    m_Bit31->value(0);
    extern MainWindow *g_MainWindow;
    g_MainWindow->RedrawAll();
};
}
void GroundInfoWindow::cb_Reset(Fl_Button* o, void* v) {
  ((GroundInfoWindow*)(o->parent()->user_data()))->cb_Reset_i(o,v);
}

void GroundInfoWindow::cb_Forbidden_i(Fl_Button*, void*) {
  {
    m_Bit0 ->value(1);
    m_Bit1 ->value(1);
    m_Bit2 ->value(1);
    m_Bit3 ->value(1);
    m_Bit4 ->value(1);
    m_Bit5 ->value(1);
    m_Bit6 ->value(1);
    m_Bit7 ->value(1);
    m_Bit8 ->value(1);
    m_Bit9 ->value(1);
    m_Bit10->value(1);
    m_Bit11->value(1);
    m_Bit12->value(1);
    m_Bit13->value(1);
    m_Bit14->value(1);
    m_Bit15->value(1);
    m_Bit16->value(1);
    m_Bit17->value(1);
    m_Bit18->value(1);
    m_Bit19->value(1);
    m_Bit20->value(1);
    m_Bit21->value(1);
    m_Bit22->value(1);
    m_Bit23->value(1);
    m_Bit24->value(1);
    m_Bit25->value(1);
    m_Bit26->value(1);
    m_Bit27->value(1);
    m_Bit28->value(1);
    m_Bit29->value(1);
    m_Bit30->value(1);
    m_Bit31->value(1);
    
    extern MainWindow *g_MainWindow;
    g_MainWindow->RedrawAll();
};
}
void GroundInfoWindow::cb_Forbidden(Fl_Button* o, void* v) {
  ((GroundInfoWindow*)(o->parent()->user_data()))->cb_Forbidden_i(o,v);
}

Fl_Menu_Item GroundInfoWindow::menu_[] = {
 {"Operation", 0,  0, 0, 64, FL_NORMAL_LABEL, 4, 14, 0},
 {"Equal", 0,  0, 0, 12, FL_NORMAL_LABEL, 4, 14, 0},
 {"Neq", 0,  0, 0, 8, FL_NORMAL_LABEL, 4, 14, 0},
 {"Overlap   ", 0,  0, 0, 8, FL_NORMAL_LABEL, 4, 14, 0},
 {"Exclude", 0,  0, 0, 8, FL_NORMAL_LABEL, 4, 14, 0},
 {"Subset", 0,  0, 0, 8, FL_NORMAL_LABEL, 4, 14, 0},
 {"Superset", 0,  0, 0, 8, FL_NORMAL_LABEL, 4, 14, 0},
 {"Complement  ", 0,  0, 0, 8, FL_NORMAL_LABEL, 4, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {0,0,0,0,0,0,0,0,0}
};
Fl_Menu_Item* GroundInfoWindow::m_Eq = GroundInfoWindow::menu_ + 1;
Fl_Menu_Item* GroundInfoWindow::m_Neq = GroundInfoWindow::menu_ + 2;
Fl_Menu_Item* GroundInfoWindow::m_Overlap = GroundInfoWindow::menu_ + 3;
Fl_Menu_Item* GroundInfoWindow::m_Exclude = GroundInfoWindow::menu_ + 4;
Fl_Menu_Item* GroundInfoWindow::m_Subset = GroundInfoWindow::menu_ + 5;
Fl_Menu_Item* GroundInfoWindow::m_Superset = GroundInfoWindow::menu_ + 6;
Fl_Menu_Item* GroundInfoWindow::m_Complement = GroundInfoWindow::menu_ + 7;

void GroundInfoWindow::cb_Flop_i(Fl_Button*, void*) {
  {
    {m_Bit0 ->value(!(m_Bit0 ->value()));}
    {m_Bit1 ->value(!(m_Bit1 ->value()));}
    {m_Bit2 ->value(!(m_Bit2 ->value()));}
    {m_Bit3 ->value(!(m_Bit3 ->value()));}
    {m_Bit4 ->value(!(m_Bit4 ->value()));}
    {m_Bit5 ->value(!(m_Bit5 ->value()));}
    {m_Bit6 ->value(!(m_Bit6 ->value()));}
    {m_Bit7 ->value(!(m_Bit7 ->value()));}
    {m_Bit8 ->value(!(m_Bit8 ->value()));}
    {m_Bit9 ->value(!(m_Bit9 ->value()));}
    {m_Bit10->value(!(m_Bit10->value()));}
    {m_Bit11->value(!(m_Bit11->value()));}
    {m_Bit12->value(!(m_Bit12->value()));}
    {m_Bit13->value(!(m_Bit13->value()));}
    {m_Bit14->value(!(m_Bit14->value()));}
    {m_Bit15->value(!(m_Bit15->value()));}
    {m_Bit16->value(!(m_Bit16->value()));}
    {m_Bit17->value(!(m_Bit17->value()));}
    {m_Bit18->value(!(m_Bit18->value()));}
    {m_Bit19->value(!(m_Bit19->value()));}
    {m_Bit20->value(!(m_Bit20->value()));}
    {m_Bit21->value(!(m_Bit21->value()));}
    {m_Bit22->value(!(m_Bit22->value()));}
    {m_Bit23->value(!(m_Bit23->value()));}
    {m_Bit24->value(!(m_Bit24->value()));}
    {m_Bit25->value(!(m_Bit25->value()));}
    {m_Bit26->value(!(m_Bit26->value()));}
    {m_Bit27->value(!(m_Bit27->value()));}
    {m_Bit28->value(!(m_Bit28->value()));}
    {m_Bit29->value(!(m_Bit29->value()));}
    {m_Bit30->value(!(m_Bit30->value()));}
    {m_Bit31->value(!(m_Bit31->value()));}
    
    extern MainWindow *g_MainWindow;
    g_MainWindow->RedrawAll();
};
}
void GroundInfoWindow::cb_Flop(Fl_Button* o, void* v) {
  ((GroundInfoWindow*)(o->parent()->user_data()))->cb_Flop_i(o,v);
}

GroundInfoWindow::GroundInfoWindow() {
  { m_Window = new Fl_Double_Window(733, 381);
    m_Window->user_data((void*)(this));
    { Fl_Group* o = new Fl_Group(0, 24, 740, 285);
      o->callback((Fl_Callback*)cb_);
      { m_Bit0 = new Fl_Check_Button(18, 33, 177, 33, "(00):");
        m_Bit0->down_box(FL_DOWN_BOX);
        m_Bit0->labelfont(4);
        m_Bit0->callback((Fl_Callback*)cb_m_Bit0);
      } // Fl_Check_Button* m_Bit0
      { m_Bit1 = new Fl_Check_Button(18, 65, 177, 33, "(01):");
        m_Bit1->down_box(FL_DOWN_BOX);
        m_Bit1->labelfont(4);
        m_Bit1->callback((Fl_Callback*)cb_m_Bit1);
      } // Fl_Check_Button* m_Bit1
      { m_Bit2 = new Fl_Check_Button(18, 97, 177, 33, "(02):");
        m_Bit2->down_box(FL_DOWN_BOX);
        m_Bit2->labelfont(4);
        m_Bit2->callback((Fl_Callback*)cb_m_Bit2);
      } // Fl_Check_Button* m_Bit2
      { m_Bit3 = new Fl_Check_Button(18, 129, 177, 33, "(03):");
        m_Bit3->down_box(FL_DOWN_BOX);
        m_Bit3->labelfont(4);
        m_Bit3->callback((Fl_Callback*)cb_m_Bit3);
      } // Fl_Check_Button* m_Bit3
      { m_Bit4 = new Fl_Check_Button(18, 161, 177, 33, "(04):");
        m_Bit4->down_box(FL_DOWN_BOX);
        m_Bit4->labelfont(4);
        m_Bit4->callback((Fl_Callback*)cb_m_Bit4);
      } // Fl_Check_Button* m_Bit4
      { m_Bit5 = new Fl_Check_Button(18, 193, 177, 33, "(05):");
        m_Bit5->down_box(FL_DOWN_BOX);
        m_Bit5->labelfont(4);
        m_Bit5->callback((Fl_Callback*)cb_m_Bit5);
      } // Fl_Check_Button* m_Bit5
      { m_Bit6 = new Fl_Check_Button(18, 225, 177, 33, "(06):");
        m_Bit6->down_box(FL_DOWN_BOX);
        m_Bit6->labelfont(4);
        m_Bit6->callback((Fl_Callback*)cb_m_Bit6);
      } // Fl_Check_Button* m_Bit6
      { m_Bit7 = new Fl_Check_Button(18, 257, 177, 33, "(07):");
        m_Bit7->down_box(FL_DOWN_BOX);
        m_Bit7->labelfont(4);
        m_Bit7->callback((Fl_Callback*)cb_m_Bit7);
      } // Fl_Check_Button* m_Bit7
      { m_Bit8 = new Fl_Check_Button(194, 33, 177, 33, "(08): Sand");
        m_Bit8->down_box(FL_DOWN_BOX);
        m_Bit8->labelfont(4);
        m_Bit8->callback((Fl_Callback*)cb_m_Bit8);
      } // Fl_Check_Button* m_Bit8
      { m_Bit9 = new Fl_Check_Button(194, 65, 177, 33, "(09): Earth");
        m_Bit9->down_box(FL_DOWN_BOX);
        m_Bit9->labelfont(4);
        m_Bit9->callback((Fl_Callback*)cb_m_Bit9);
      } // Fl_Check_Button* m_Bit9
      { m_Bit10 = new Fl_Check_Button(194, 97, 177, 33, "(10): Stone");
        m_Bit10->down_box(FL_DOWN_BOX);
        m_Bit10->labelfont(4);
        m_Bit10->callback((Fl_Callback*)cb_m_Bit10);
      } // Fl_Check_Button* m_Bit10
      { m_Bit11 = new Fl_Check_Button(194, 129, 177, 33, "(11): Water");
        m_Bit11->down_box(FL_DOWN_BOX);
        m_Bit11->labelfont(4);
        m_Bit11->callback((Fl_Callback*)cb_m_Bit11);
      } // Fl_Check_Button* m_Bit11
      { m_Bit12 = new Fl_Check_Button(194, 161, 177, 33, "(12):");
        m_Bit12->down_box(FL_DOWN_BOX);
        m_Bit12->labelfont(4);
        m_Bit12->callback((Fl_Callback*)cb_m_Bit12);
      } // Fl_Check_Button* m_Bit12
      { m_Bit13 = new Fl_Check_Button(194, 193, 177, 33, "(13):");
        m_Bit13->down_box(FL_DOWN_BOX);
        m_Bit13->labelfont(4);
        m_Bit13->callback((Fl_Callback*)cb_m_Bit13);
      } // Fl_Check_Button* m_Bit13
      { m_Bit14 = new Fl_Check_Button(194, 225, 177, 33, "(14):");
        m_Bit14->down_box(FL_DOWN_BOX);
        m_Bit14->labelfont(4);
        m_Bit14->callback((Fl_Callback*)cb_m_Bit14);
      } // Fl_Check_Button* m_Bit14
      { m_Bit15 = new Fl_Check_Button(194, 257, 177, 33, "(15):");
        m_Bit15->down_box(FL_DOWN_BOX);
        m_Bit15->labelfont(4);
        m_Bit15->callback((Fl_Callback*)cb_m_Bit15);
      } // Fl_Check_Button* m_Bit15
      { m_Bit16 = new Fl_Check_Button(370, 33, 177, 33, "(16): Peace");
        m_Bit16->down_box(FL_DOWN_BOX);
        m_Bit16->labelfont(4);
        m_Bit16->callback((Fl_Callback*)cb_m_Bit16);
      } // Fl_Check_Button* m_Bit16
      { m_Bit17 = new Fl_Check_Button(370, 65, 177, 33, "(17): Attack All");
        m_Bit17->down_box(FL_DOWN_BOX);
        m_Bit17->labelfont(4);
        m_Bit17->callback((Fl_Callback*)cb_m_Bit17);
      } // Fl_Check_Button* m_Bit17
      { m_Bit18 = new Fl_Check_Button(370, 97, 177, 33, "(18): Guild");
        m_Bit18->down_box(FL_DOWN_BOX);
        m_Bit18->labelfont(4);
        m_Bit18->callback((Fl_Callback*)cb_m_Bit18);
      } // Fl_Check_Button* m_Bit18
      { m_Bit19 = new Fl_Check_Button(370, 129, 177, 33, "(19): ");
        m_Bit19->down_box(FL_DOWN_BOX);
        m_Bit19->labelfont(4);
        m_Bit19->callback((Fl_Callback*)cb_m_Bit19);
      } // Fl_Check_Button* m_Bit19
      { m_Bit20 = new Fl_Check_Button(370, 161, 177, 33, "(20):");
        m_Bit20->down_box(FL_DOWN_BOX);
        m_Bit20->labelfont(4);
        m_Bit20->callback((Fl_Callback*)cb_m_Bit20);
      } // Fl_Check_Button* m_Bit20
      { m_Bit21 = new Fl_Check_Button(370, 193, 177, 33, "(21):");
        m_Bit21->down_box(FL_DOWN_BOX);
        m_Bit21->labelfont(4);
        m_Bit21->callback((Fl_Callback*)cb_m_Bit21);
      } // Fl_Check_Button* m_Bit21
      { m_Bit22 = new Fl_Check_Button(370, 225, 177, 33, "(22):");
        m_Bit22->down_box(FL_DOWN_BOX);
        m_Bit22->labelfont(4);
        m_Bit22->callback((Fl_Callback*)cb_m_Bit22);
      } // Fl_Check_Button* m_Bit22
      { m_Bit23 = new Fl_Check_Button(370, 257, 177, 33, "(23):");
        m_Bit23->down_box(FL_DOWN_BOX);
        m_Bit23->labelfont(4);
        m_Bit23->callback((Fl_Callback*)cb_m_Bit23);
      } // Fl_Check_Button* m_Bit23
      { m_Bit24 = new Fl_Check_Button(546, 33, 177, 33, "(24):");
        m_Bit24->down_box(FL_DOWN_BOX);
        m_Bit24->labelfont(4);
        m_Bit24->callback((Fl_Callback*)cb_m_Bit24);
      } // Fl_Check_Button* m_Bit24
      { m_Bit25 = new Fl_Check_Button(546, 65, 177, 33, "(25):");
        m_Bit25->down_box(FL_DOWN_BOX);
        m_Bit25->labelfont(4);
        m_Bit25->callback((Fl_Callback*)cb_m_Bit25);
      } // Fl_Check_Button* m_Bit25
      { m_Bit26 = new Fl_Check_Button(546, 97, 177, 33, "(26):");
        m_Bit26->down_box(FL_DOWN_BOX);
        m_Bit26->labelfont(4);
        m_Bit26->callback((Fl_Callback*)cb_m_Bit26);
      } // Fl_Check_Button* m_Bit26
      { m_Bit27 = new Fl_Check_Button(546, 129, 177, 33, "(27):");
        m_Bit27->down_box(FL_DOWN_BOX);
        m_Bit27->labelfont(4);
        m_Bit27->callback((Fl_Callback*)cb_m_Bit27);
      } // Fl_Check_Button* m_Bit27
      { m_Bit28 = new Fl_Check_Button(546, 161, 177, 33, "(28):");
        m_Bit28->down_box(FL_DOWN_BOX);
        m_Bit28->labelfont(4);
        m_Bit28->callback((Fl_Callback*)cb_m_Bit28);
      } // Fl_Check_Button* m_Bit28
      { m_Bit29 = new Fl_Check_Button(546, 193, 177, 33, "(29):");
        m_Bit29->down_box(FL_DOWN_BOX);
        m_Bit29->labelfont(4);
        m_Bit29->callback((Fl_Callback*)cb_m_Bit29);
      } // Fl_Check_Button* m_Bit29
      { m_Bit30 = new Fl_Check_Button(546, 225, 177, 33, "(30):");
        m_Bit30->down_box(FL_DOWN_BOX);
        m_Bit30->labelfont(4);
        m_Bit30->callback((Fl_Callback*)cb_m_Bit30);
      } // Fl_Check_Button* m_Bit30
      { m_Bit31 = new Fl_Check_Button(546, 257, 177, 33, "(31):");
        m_Bit31->down_box(FL_DOWN_BOX);
        m_Bit31->labelfont(4);
        m_Bit31->callback((Fl_Callback*)cb_m_Bit31);
      } // Fl_Check_Button* m_Bit31
      o->end();
    } // Fl_Group* o
    { Fl_Button* o = new Fl_Button(605, 330, 80, 30, "Reset");
      o->labelfont(4);
      o->callback((Fl_Callback*)cb_Reset);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(499, 330, 80, 30, "Forbidden");
      o->labelfont(4);
      o->callback((Fl_Callback*)cb_Forbidden);
    } // Fl_Button* o
    { Fl_Menu_Bar* o = new Fl_Menu_Bar(0, 0, 733, 25);
      o->labelfont(4);
      o->textfont(4);
      o->menu(menu_);
    } // Fl_Menu_Bar* o
    { Fl_Button* o = new Fl_Button(393, 330, 80, 30, "Flop");
      o->labelfont(4);
      o->callback((Fl_Callback*)cb_Flop);
    } // Fl_Button* o
    m_Window->end();
  } // Fl_Double_Window* m_Window
}

void GroundInfoWindow::ShowAll() {
  m_Window->show();
}

uint32_t GroundInfoWindow::Mask() {
  {
      uint32_t bRes = 0;
      if(m_Bit0 ->value()){ bRes += (1 << 0 ); }
      if(m_Bit1 ->value()){ bRes += (1 << 1 ); }
      if(m_Bit2 ->value()){ bRes += (1 << 2 ); }
      if(m_Bit3 ->value()){ bRes += (1 << 3 ); }
      if(m_Bit4 ->value()){ bRes += (1 << 4 ); }
      if(m_Bit5 ->value()){ bRes += (1 << 5 ); }
      if(m_Bit6 ->value()){ bRes += (1 << 6 ); }
      if(m_Bit7 ->value()){ bRes += (1 << 7 ); }
      if(m_Bit8 ->value()){ bRes += (1 << 8 ); }
      if(m_Bit9 ->value()){ bRes += (1 << 9 ); }
      if(m_Bit10->value()){ bRes += (1 << 10); }
      if(m_Bit11->value()){ bRes += (1 << 11); }
      if(m_Bit12->value()){ bRes += (1 << 12); }
      if(m_Bit13->value()){ bRes += (1 << 13); }
      if(m_Bit14->value()){ bRes += (1 << 14); }
      if(m_Bit15->value()){ bRes += (1 << 15); }
      if(m_Bit16->value()){ bRes += (1 << 16); }
      if(m_Bit17->value()){ bRes += (1 << 17); }
      if(m_Bit18->value()){ bRes += (1 << 18); }
      if(m_Bit19->value()){ bRes += (1 << 19); }
      if(m_Bit20->value()){ bRes += (1 << 20); }
      if(m_Bit21->value()){ bRes += (1 << 21); }
      if(m_Bit22->value()){ bRes += (1 << 22); }
      if(m_Bit23->value()){ bRes += (1 << 23); }
      if(m_Bit24->value()){ bRes += (1 << 24); }
      if(m_Bit25->value()){ bRes += (1 << 25); }
      if(m_Bit26->value()){ bRes += (1 << 26); }
      if(m_Bit27->value()){ bRes += (1 << 27); }
      if(m_Bit28->value()){ bRes += (1 << 28); }
      if(m_Bit29->value()){ bRes += (1 << 29); }
      if(m_Bit30->value()){ bRes += (1 << 30); }
      if(m_Bit31->value()){ bRes += (1 << 31); }
      return bRes;
  }
}

bool GroundInfoWindow::Test(uint32_t nInput) {
  // uint32_t nInput
  {
      if(m_Eq->value()){
          return nInput == Mask();
      }
  
      if(m_Neq->value()){
          return nInput != Mask();
      }
  
      if(m_Overlap->value()){
          return ((nInput & Mask()) != 0);
      }
  
      if(m_Exclude->value()){
          return ((nInput & Mask()) == 0);
      }
  
      if(m_Subset->value()){
          return false
              || (nInput == 0)
              || (((nInput & Mask()) != 0) && ((nInput & (~Mask())) == 0));
      }
  
      if(m_Superset->value()){
          return false
              || (Mask() == 0)
              || (((nInput & Mask()) != 0) && ((nInput & (~Mask())) != 0));
      }
  
      if(m_Complement->value()){
          return nInput == (~Mask());
      }
  
      return false;
  }
}
