// generated by Fast Light User Interface Designer (fluid) version 1.0303

#include "aboutwindow.hpp"

AboutWindow::AboutWindow() {
  { m_Window = new Fl_Double_Window(317, 197);
    m_Window->labelfont(5);
    m_Window->user_data((void*)(this));
    m_Window->align(Fl_Align(FL_ALIGN_CLIP|FL_ALIGN_INSIDE));
    { m_Output = new Fl_Output(0, 0, 325, 204);
      m_Output->type(12);
      m_Output->labelfont(4);
      m_Output->textfont(4);
      m_Output->value("Name : Anhong\nEmail: anhonghe@gmail.com");
      m_Output->cursor_color(FL_WHITE);
    } // Fl_Output* m_Output
    m_Window->end();
    m_Window->resizable(m_Window);
  } // Fl_Double_Window* m_Window
}

void AboutWindow::ShowAll() {
  m_Window->show();
}
