// generated by Fast Light User Interface Designer (fluid) version 1.0303

#pragma once
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Image.H>
#include <cstdint>

class PreviewWindow: public Fl_Double_Window
{
    public:
        PreviewWindow(int, int);
        ~PreviewWindow();

    public:
        void draw();

    private:
        void ExtendBuf(size_t);
        void LoadImage();
    private:
        bool          m_Inited;
        uint32_t      m_ImageIndex;
        uint32_t     *m_Data;
        size_t        m_DataLen;
        size_t        m_DataMaxLen;
        Fl_RGB_Image *m_Image;
};
