{},

// 光环
{   .name = u8"恢复光环使能",
    .type = u8"光环",
    .aura
    {
        .buff = u8"恢复光环",
        .self = 1,
    },
},

{   .name = u8"吸血光环使能",
    .type = u8"光环",
    .aura
    {
        .buff = u8"吸血光环",
        .self = 1,
    },
},

// 控制
{   .name = u8"眩晕",
    .type = u8"控制",
},

{   .name = u8"缠绕",
    .type = u8"控制",
    .controller
    {
        .can
        {
            .spell = 1,
        },
    },
},

{   .name = u8"束缚",
    .type = u8"控制",
},

{   .name = u8"妖术",
    .type = u8"控制",
},

{   .name = u8"龙卷风",
    .type = u8"控制",
},

{   .name = u8"隐藏",
    .type = u8"控制",
},

{   .name = u8"致盲",
    .type = u8"控制",
},

{   .name = u8"沉默",
    .type = u8"控制",
},

{   .name = u8"锁闭",
    .type = u8"控制",
},

{   .name = u8"破坏",
    .type = u8"控制",
},

{   .name = u8"缴械",
    .type = u8"控制",
},

{   .name = u8"减速",
    .type = u8"控制",
},

{   .name = u8"陷阱",
    .type = u8"控制",
},

{   .name = u8"嘲讽",
    .type = u8"控制",
},

{   .name = u8"恐惧",
    .type = u8"控制",
},

{   .name = u8"蛊惑",
    .type = u8"控制",
},

{   .name = u8"强制移动",
    .type = u8"控制",
},

// 触发
{   .name = u8"HP移动伤害",
    .type = u8"触发",
},

{   .name = u8"MP移动伤害",
    .type = u8"触发",
},

// 属性修改
{   .name = u8"HP",
    .type = u8"属性修改",
},

{   .name = u8"HP持续",
    .type = u8"属性修改",
},

{   .name = u8"HP上限",
    .type = u8"属性修改",
},

{   .name = u8"MP",
    .type = u8"属性修改",
},

{   .name = u8"MP持续",
    .type = u8"属性修改",
},

{   .name = u8"MP上限",
    .type = u8"属性修改",
},

{   .name = u8"DC下限",
    .type = u8"属性修改",
},

{   .name = u8"DC上限",
    .type = u8"属性修改",
},

{   .name = u8"AC下限",
    .type = u8"属性修改",
},

{   .name = u8"AC上限",
    .type = u8"属性修改",
},

{   .name = u8"MAC下限",
    .type = u8"属性修改",
},

{   .name = u8"MAC上限",
    .type = u8"属性修改",
},

{   .name = u8"隐身",
    .type = u8"属性修改",
},

{   .name = u8"相位",
    .type = u8"属性修改",
},

{   .name = u8"无敌",
    .type = u8"属性修改",
},

{   .name = u8"技能免疫",
    .type = u8"属性修改",
},

{   .name = u8"攻击免疫",
    .type = u8"属性修改",
},

{   .name = u8"虚无",
    .type = u8"属性修改",
},

// 攻击修改
{   .name = u8"重击",
    .type = u8"攻击修改",
    .attackModifier
    {
        .modifier = u8"重击",
    },
},

{   .name = u8"吸血",
    .type = u8"攻击修改",
    .attackModifier
    {
        .modifier = u8"吸血",
    },
},

{   .name = u8"淬毒",
    .type = u8"攻击修改",
    .attackModifier
    {
        .modifier = u8"淬毒",
    },
},

// 施法修改
{   .name = u8"魔法连击",
    .type = u8"施法修改",
    .attackModifier
    {
        .modifier = u8"魔法连击",
    },
},
