/*
 * =====================================================================================
 *
 *       Filename: itemrecord.inc
 *        Created: 05/12/2017 17:58:02
 *    Description:
 *                  check here: http://db.178.com/mir3/item-list
 *                  all gfx can match with current database used in mir2x
 *                  for weapons check Dropbox/vc_mir2/CsvDB/stditem.csv for all attributes
 *
 *        Version: 1.0
 *       Revision: none
 *       Compiler: gcc
 *
 *         Author: ANHONG
 *          Email: anhonghe@gmail.com
 *   Organization: USTC
 *
 * =====================================================================================
 */

{}, // place-holder

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0000,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0001,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0002,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0003,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0004,
},

{   .name = u8"金创药（小）",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0005,
},

{   .name = u8"金创药（中）",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0006,
},

{   .name = u8"金创药（大）",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0007,
},

{   .name = u8"金创药（特）",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0008,
},

{   .name = u8"金创药（超）",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0009,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X000A,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X000B,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X000C,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X000D,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X000E,
},

{   .name = u8"魔法药（小）",
    .type = u8"恢复药水",
    .pkgGfxID = 0X000F,
},

{   .name = u8"魔法药（中）",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0010,
},

{   .name = u8"魔法药（大）",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0011,
},

{   .name = u8"魔法药（特）",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0012,
},

{   .name = u8"魔法药（超）",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0013,
},

{   .name = u8"太阳水",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0014,
},

{   .name = u8"强效太阳水",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0015,
},

{   .name = u8"急救丸（小）",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0019,
},

{   .name = u8"急救丸（中）",
    .type = u8"恢复药水",
    .pkgGfxID = 0X001A,
},

{   .name = u8"急救丸（大）",
    .type = u8"恢复药水",
    .pkgGfxID = 0X001B,
},

{   .name = u8"急救丸（特）",
    .type = u8"恢复药水",
    .pkgGfxID = 0X001C,
},

{   .name = u8"急救丸（超）",
    .type = u8"恢复药水",
    .pkgGfxID = 0X001D,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X001E,
},

{   .name = u8"鸡血",
    .type = u8"恢复药水",
    .pkgGfxID = 0X001F,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0020,
},

{   .name = u8"清心丸（小）",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0023,
},

{   .name = u8"清心丸（中）",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0024,
},

{   .name = u8"清心丸（大）",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0025,
},

{   .name = u8"清心丸（特）",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0026,
},

{   .name = u8"清心丸（超）",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0027,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0028,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0029,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X002A,
},

{   .name = u8"润滑剂",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0032,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0033,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0034,
},

{   .name = u8"武器强化油",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0035,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0036,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X003C,
},

{   .name = u8"战神油",
    .type = u8"恢复药水",
    .pkgGfxID = 0X003D,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X003E,
},

{   .name = u8"祝福油",
    .type = u8"恢复药水",
    .pkgGfxID = 0X003F,
},

{   .name = u8"诅咒药水",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0040,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0041,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0042,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0043,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0044,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0045,
},

{   .name = u8"万年雪霜",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0046,
},

{   .name = u8"鹿茸",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0047,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0048,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0049,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X004A,
},

{   .name = u8"钱票",
    .type = u8"恢复药水",
    .pkgGfxID = 0X004B,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X004C,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X004D,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X004E,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X004F,
},

{   .name = u8"疾风神水",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0050,
},

{   .name = u8"灵魂神水",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0051,
},

{   .name = u8"自然神水",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0052,
},

{   .name = u8"魔力强效神水",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0053,
},

{   .name = u8"攻击神水",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0054,
},

{   .name = u8"体力强效神水",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0055,
},

{   .name = u8"苹果",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0056,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0057,
},

{   .name = u8"红玫瑰",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0058,
},

{   .name = u8"黄玫瑰",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0059,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X005A,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X005B,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X005C,
},

{   .name = u8"干肉",
    .type = u8"恢复药水",
    .pkgGfxID = 0X005D,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X005E,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X005F,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0060,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0061,
},

{   .name = u8"绿玫瑰",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0062,
},

{   .name = u8"蓝玫瑰",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0063,
},

{   .name = u8"沃玛号角",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0064,
},

{   .name = u8"沃玛号角",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0065,
},

{   .name = u8"蚂蚁卵",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0066,
},

{   .name = u8"骷髅骨",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0067,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0068,
},

{   .name = u8"蜘蛛线（大）",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0069,
},

{   .name = u8"蜘蛛线（小）",
    .type = u8"恢复药水",
    .pkgGfxID = 0X006A,
},

{   .name = u8"皮",
    .type = u8"恢复药水",
    .pkgGfxID = 0X006B,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X006C,
},

{   .name = u8"蛆卵",
    .type = u8"恢复药水",
    .pkgGfxID = 0X006E,
},

{   .name = u8"毒蜘蛛牙齿",
    .type = u8"恢复药水",
    .pkgGfxID = 0X006F,
},

{   .name = u8"蝎子尾巴",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0070,
},

{   .name = u8"食人树叶",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0071,
},

{   .name = u8"食人树果实",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0072,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0073,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0074,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0075,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0076,
},

{   .name = u8"金币（小）",
    .type = u8"金币",
    .weight = 0,
    .pkgGfxID = 0X0078,
},

{   .name = u8"金币（中）",
    .type = u8"金币",
    .weight = 0,
    .pkgGfxID = 0X0079,
},

{   .name = u8"金币（大）",
    .type = u8"金币",
    .weight = 0,
    .pkgGfxID = 0X007A,
},

{   .name = u8"金币（特）",
    .type = u8"金币",
    .weight = 0,
    .pkgGfxID = 0X007B,
},

{   .name = u8"金币（超）",
    .type = u8"金币",
    .weight = 0,
    .pkgGfxID = 0X007C,
},

{   .name = u8"金条",
    .type = u8"恢复药水",
    .pkgGfxID = 0X007D,
},

{   .name = u8"金砖",
    .type = u8"恢复药水",
    .pkgGfxID = 0X007E,
},

{   .name = u8"金箱",
    .type = u8"恢复药水",
    .pkgGfxID = 0X007F,
},

{   .name = u8"黄色药粉",
    .type = u8"药粉",
    .pkgGfxID = 0X0082,
},

{   .name = u8"灰色药粉",
    .type = u8"药粉",
    .pkgGfxID = 0X0083,
},

{   .name = u8"蓝色药粉",
    .type = u8"药粉",
    .pkgGfxID = 0X0084,
},

{   .name = u8"红色药粉",
    .type = u8"药粉",
    .pkgGfxID = 0X0085,
},

{   .name = u8"绿色药粉",
    .type = u8"药粉",
    .pkgGfxID = 0X0086,
},

{   .name = u8"骰子（1）",
    .type = u8"恢复药水",
    .pkgGfxID = 0X008C,
},

{   .name = u8"骰子（2）",
    .type = u8"恢复药水",
    .pkgGfxID = 0X008D,
},

{   .name = u8"骰子（3）",
    .type = u8"恢复药水",
    .pkgGfxID = 0X008E,
},

{   .name = u8"骰子（4）",
    .type = u8"恢复药水",
    .pkgGfxID = 0X008F,
},

{   .name = u8"骰子（5）",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0090,
},

{   .name = u8"骰子（6）",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0091,
},

{   .name = u8"转动的骰子（1）",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0096,
},

{   .name = u8"转动的骰子（2）",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0097,
},

{   .name = u8"转动的骰子（3）",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0098,
},

{   .name = u8"转动的骰子（4）",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0099,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X00A0,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X00A1,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X00A2,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X00A3,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X00A4,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X00A5,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X00A6,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X00A7,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X00AA,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X00AB,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X00AC,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X00AD,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X00AE,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X00AF,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X00B4,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X00B5,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X00B6,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X00B7,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X00BE,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X00BF,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X00C0,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X00C1,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X00C2,
},

{   .name = u8"行会回城卷",
    .type = u8"传送卷轴",
    .pkgGfxID = 0X00C8,
},

{   .name = u8"随机传送卷",
    .type = u8"传送卷轴",
    .pkgGfxID = 0X00C9,
},

{   .name = u8"地牢逃脱卷",
    .type = u8"传送卷轴",
    .pkgGfxID = 0X00CA,
},

{   .name = u8"回城卷",
    .type = u8"传送卷轴",
    .pkgGfxID = 0X00CB,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X00CC,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X00CD,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X00CE,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X00CF,
},

{   .name = u8"金矿",
    .type = u8"恢复药水",
    .pkgGfxID = 0X00D2,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X00D3,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X00D4,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X00D5,
},

{   .name = u8"黑铁",
    .type = u8"恢复药水",
    .pkgGfxID = 0X00D6,
},

{   .name = u8"铜矿",
    .type = u8"恢复药水",
    .pkgGfxID = 0X00D7,
},

{   .name = u8"铁矿",
    .type = u8"恢复药水",
    .pkgGfxID = 0X00D8,
},

{   .name = u8"紫水晶",
    .type = u8"恢复药水",
    .pkgGfxID = 0X00D9,
},

{   .name = u8"石榴石",
    .type = u8"恢复药水",
    .pkgGfxID = 0X00DA,
},

{   .name = u8"金刚石",
    .type = u8"恢复药水",
    .pkgGfxID = 0X00DB,
},

{   .name = u8"刚玉",
    .type = u8"恢复药水",
    .pkgGfxID = 0X00DC,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X00DD,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X00DE,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X00DF,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X00E0,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X00E1,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X00E2,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X00E3,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X00E4,
},

{   .name = u8"元宝",
    .type = u8"恢复药水",
    .pkgGfxID = 0X00E5,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X00E6,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X00E7,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X00E8,
},

{   .name = u8"钻石",
    .type = u8"恢复药水",
    .pkgGfxID = 0X00E9,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X00F0,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X00F1,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X00F2,
},

{   .name = u8"打捆金创药（小）",
    .type = u8"恢复药水",
    .pkgGfxID = 0X00F3,
},

{   .name = u8"打捆金创药（中）",
    .type = u8"恢复药水",
    .pkgGfxID = 0X00F4,
},

{   .name = u8"打捆金创药（大）",
    .type = u8"恢复药水",
    .pkgGfxID = 0X00F5,
},

{   .name = u8"打捆金创药（特）",
    .type = u8"恢复药水",
    .pkgGfxID = 0X00F6,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X00FA,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X00FB,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X00FC,
},

{   .name = u8"打捆魔法药（小）",
    .type = u8"恢复药水",
    .pkgGfxID = 0X00FD,
},

{   .name = u8"打捆魔法药（中）",
    .type = u8"恢复药水",
    .pkgGfxID = 0X00FE,
},

{   .name = u8"打捆魔法药（大）",
    .type = u8"恢复药水",
    .pkgGfxID = 0X00FF,
},

{   .name = u8"打捆魔法药（特）",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0100,
},

{   .name = u8"打捆行会回城卷",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0104,
},

{   .name = u8"打捆随机传送卷",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0105,
},

{   .name = u8"打捆地牢逃脱卷",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0106,
},

{   .name = u8"打捆回城卷",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0107,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0108,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0109,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X010A,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X010B,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X010E,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X010F,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0110,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0111,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0112,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0113,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0114,
},

{   .name = u8"烤鸡",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0118,
},

{   .name = u8"蜡烛",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0122,
},

{   .name = u8"火把",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0123,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0124,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0125,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0126,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0127,
},

{   .name = u8"鹿肉",
    .type = u8"恢复药水",
    .pkgGfxID = 0X012C,
},

{   .name = u8"鸡肉",
    .type = u8"恢复药水",
    .pkgGfxID = 0X012D,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X012E,
},

{   .name = u8"威魂深怨护身符",
    .type = u8"护身符",
    .pkgGfxID = 0X012F,
},

{   .name = u8"疾光电影",
    .type = u8"技能书",
    .pkgGfxID = 0X0130,
},

{   .name = u8"困魔咒",
    .type = u8"技能书",
    .pkgGfxID = 0X0130,
},

{   .name = u8"火墙",
    .type = u8"技能书",
    .pkgGfxID = 0X0130,
},

{   .name = u8"爆裂火焰",
    .type = u8"技能书",
    .pkgGfxID = 0X0130,
},

{   .name = u8"地狱雷光",
    .type = u8"技能书",
    .pkgGfxID = 0X0130,
},

{   .name = u8"烈火剑法",
    .type = u8"技能书",
    .pkgGfxID = 0X0130,
},

{   .name = u8"野蛮冲撞",
    .type = u8"技能书",
    .pkgGfxID = 0X0130,
},

{   .name = u8"群体治愈术",
    .type = u8"技能书",
    .pkgGfxID = 0X0130,
},

{   .name = u8"召唤神兽",
    .type = u8"技能书",
    .pkgGfxID = 0X0130,
},

{   .name = u8"魔法盾",
    .type = u8"技能书",
    .pkgGfxID = 0X0130,
},

{   .name = u8"圣言术",
    .type = u8"技能书",
    .pkgGfxID = 0X0130,
},

{   .name = u8"冰咆哮",
    .type = u8"技能书",
    .pkgGfxID = 0X0130,
},

{   .name = u8"翔空剑法",
    .type = u8"技能书",
    .pkgGfxID = 0X0130,
},

{   .name = u8"空拳刀法",
    .type = u8"技能书",
    .pkgGfxID = 0X0130,
},

{   .name = u8"月魂灵波",
    .type = u8"技能书",
    .pkgGfxID = 0X0130,
},

{   .name = u8"冰沙掌",
    .type = u8"技能书",
    .pkgGfxID = 0X0130,
},

{   .name = u8"龙卷风",
    .type = u8"技能书",
    .pkgGfxID = 0X0130,
},

{   .name = u8"风震天",
    .type = u8"技能书",
    .pkgGfxID = 0X0130,
},

{   .name = u8"回生术",
    .type = u8"技能书",
    .pkgGfxID = 0X0130,
},

{   .name = u8"强魔震法",
    .type = u8"技能书",
    .pkgGfxID = 0X0130,
},

{   .name = u8"猛虎强势",
    .type = u8"技能书",
    .pkgGfxID = 0X0130,
},

{   .name = u8"移形换位",
    .type = u8"技能书",
    .pkgGfxID = 0X0130,
},

{   .name = u8"魄冰刺",
    .type = u8"技能书",
    .pkgGfxID = 0X0130,
},

{   .name = u8"超强召唤骷髅",
    .type = u8"技能书",
    .pkgGfxID = 0X0130,
},

{   .name = u8"莲月剑法",
    .type = u8"技能书",
    .pkgGfxID = 0X0130,
},

{   .name = u8"云寂术",
    .type = u8"技能书",
    .pkgGfxID = 0X0130,
},

{   .name = u8"妙影无踪",
    .type = u8"技能书",
    .pkgGfxID = 0X0130,
},

{   .name = u8"阴阳法环",
    .type = u8"技能书",
    .pkgGfxID = 0X0130,
},

{   .name = u8"焰天火雨",
    .type = u8"技能书",
    .pkgGfxID = 0X0130,
},

{   .name = u8"灭魂火符",
    .type = u8"技能书",
    .pkgGfxID = 0X0130,
},

{   .name = u8"养生术",
    .type = u8"技能书",
    .pkgGfxID = 0X0130,
},

{   .name = u8"火球术",
    .type = u8"技能书",
    .pkgGfxID = 0X0130,
},

{   .name = u8"治愈术",
    .type = u8"技能书",
    .pkgGfxID = 0X0130,
},

{   .name = u8"基本剑术",
    .type = u8"技能书",
    .pkgGfxID = 0X0130,
},

{   .name = u8"精神力战法",
    .type = u8"技能书",
    .pkgGfxID = 0X0130,
},

{   .name = u8"大火球",
    .type = u8"技能书",
    .pkgGfxID = 0X0130,
},

{   .name = u8"攻杀剑术",
    .type = u8"技能书",
    .pkgGfxID = 0X0130,
},

{   .name = u8"施毒术",
    .type = u8"技能书",
    .pkgGfxID = 0X0130,
},

{   .name = u8"抗拒火环",
    .type = u8"技能书",
    .pkgGfxID = 0X0130,
},

{   .name = u8"地狱火",
    .type = u8"技能书",
    .pkgGfxID = 0X0130,
},

{   .name = u8"雷电术",
    .type = u8"技能书",
    .pkgGfxID = 0X0130,
},

{   .name = u8"灵魂火符",
    .type = u8"技能书",
    .pkgGfxID = 0X0130,
},

{   .name = u8"幽灵盾",
    .type = u8"技能书",
    .pkgGfxID = 0X0130,
},

{   .name = u8"神圣战甲术",
    .type = u8"技能书",
    .pkgGfxID = 0X0130,
},

{   .name = u8"刺杀剑术",
    .type = u8"技能书",
    .pkgGfxID = 0X0130,
},

{   .name = u8"召唤骷髅",
    .type = u8"技能书",
    .pkgGfxID = 0X0130,
},

{   .name = u8"隐身术",
    .type = u8"技能书",
    .pkgGfxID = 0X0130,
},

{   .name = u8"集体隐身术",
    .type = u8"技能书",
    .pkgGfxID = 0X0130,
},

{   .name = u8"诱惑之光",
    .type = u8"技能书",
    .pkgGfxID = 0X0130,
},

{   .name = u8"瞬息移动",
    .type = u8"技能书",
    .pkgGfxID = 0X0130,
},

{   .name = u8"半月弯刀",
    .type = u8"技能书",
    .pkgGfxID = 0X0130,
},

{   .name = u8"月魂断玉",
    .type = u8"技能书",
    .pkgGfxID = 0X0130,
},

{   .name = u8"冰月神掌",
    .type = u8"技能书",
    .pkgGfxID = 0X0130,
},

{   .name = u8"冰月震天",
    .type = u8"技能书",
    .pkgGfxID = 0X0130,
},

{   .name = u8"霹雳掌",
    .type = u8"技能书",
    .pkgGfxID = 0X0130,
},

{   .name = u8"风掌",
    .type = u8"技能书",
    .pkgGfxID = 0X0130,
},

{   .name = u8"击风",
    .type = u8"技能书",
    .pkgGfxID = 0X0130,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0131,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0132,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0133,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0134,
},

{   .name = u8"十方斩",
    .type = u8"技能书",
    .rarity = u8"高级",
    .pkgGfxID = 0X0135,
},

{   .name = u8"怒神霹雳",
    .type = u8"技能书",
    .rarity = u8"高级",
    .pkgGfxID = 0X0135,
},

{   .name = u8"移花接玉",
    .type = u8"技能书",
    .rarity = u8"高级",
    .pkgGfxID = 0X0135,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0136,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0137,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0138,
},

{   .name = u8"勋章",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0140,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0141,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0142,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0143,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0144,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0145,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0146,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0147,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0148,
},

{   .name = u8"护身符",
    .type = u8"护身符",
    .pkgGfxID = 0X014A,
},

{   .name = u8"神圣护身符",
    .type = u8"护身符",
    .pkgGfxID = 0X014B,
},

{   .name = u8"火焰护身符",
    .type = u8"护身符",
    .pkgGfxID = 0X014C,
},

{   .name = u8"寒气护身符",
    .type = u8"护身符",
    .pkgGfxID = 0X014D,
},

{   .name = u8"霹雷护身符",
    .type = u8"护身符",
    .pkgGfxID = 0X014E,
},

{   .name = u8"狂风护身符",
    .type = u8"护身符",
    .pkgGfxID = 0X014F,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0150,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0151,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0154,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0155,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0156,
},

{   .name = u8"未知",
    .type = u8"恢复药水",
    .pkgGfxID = 0X0157,
},

{   .name = u8"未知",
    .type = u8"头盔",
    .pkgGfxID = 0X015E,
},

{   .name = u8"未知",
    .type = u8"头盔",
    .pkgGfxID = 0X015F,
},

{   .name = u8"未知",
    .type = u8"头盔",
    .pkgGfxID = 0X0160,
},

{   .name = u8"未知",
    .type = u8"头盔",
    .pkgGfxID = 0X0161,
},

{   .name = u8"未知",
    .type = u8"头盔",
    .pkgGfxID = 0X0162,
},

{   .name = u8"天狼头盔",
    .type = u8"头盔",
    .pkgGfxID = 0X0163,
},

{   .name = u8"圣诞帽",
    .type = u8"头盔",
    .pkgGfxID = 0X0164,
},

{   .name = u8"未知",
    .type = u8"头盔",
    .pkgGfxID = 0X0165,
},

{   .name = u8"未知",
    .type = u8"头盔",
    .pkgGfxID = 0X0166,
},

{   .name = u8"未知",
    .type = u8"头盔",
    .pkgGfxID = 0X0167,
},

{   .name = u8"未知",
    .type = u8"头盔",
    .pkgGfxID = 0X0168,
},

{   .name = u8"未知",
    .type = u8"头盔",
    .pkgGfxID = 0X0169,
},

{   .name = u8"未知",
    .type = u8"头盔",
    .pkgGfxID = 0X016A,
},

{   .name = u8"未知",
    .type = u8"头盔",
    .pkgGfxID = 0X016B,
},

{   .name = u8"青铜头盔",
    .type = u8"头盔",
    .pkgGfxID = 0X0172,
    .shape = 1,
},

{   .name = u8"魔法头盔",
    .type = u8"头盔",
    .pkgGfxID = 0X0172,
    .shape = 1,
},

{   .name = u8"未知",
    .type = u8"头盔",
    .pkgGfxID = 0X0173,
},

{   .name = u8"道士头盔",
    .type = u8"头盔",
    .pkgGfxID = 0X0174,
    .shape = 2,
},

{   .name = u8"骷髅头盔",
    .type = u8"头盔",
    .pkgGfxID = 0X0175,
    .shape = 3,
},

{   .name = u8"黑铁头盔",
    .type = u8"头盔",
    .pkgGfxID = 0X0176,
    .shape = 6,
},

{   .name = u8"牛骨头盔",
    .type = u8"头盔",
    .pkgGfxID = 0X017A,
},

{   .name = u8"记忆头盔",
    .type = u8"头盔",
    .rarity = u8"高级",
    .pkgGfxID = 0X0186,
    .shape = 7,
},

{   .name = u8"祈祷头盔",
    .type = u8"头盔",
    .rarity = u8"高级",
    .pkgGfxID = 0X0187,
    .shape = 5,
},

{   .name = u8"天藤头盔",
    .type = u8"头盔",
    .pkgGfxID = 0X019A,
    .shape = 7,
},

{   .name = u8"斗笠",
    .type = u8"头盔",
    .pkgGfxID = 0X019B,
    .shape = 8,
},

{   .name = u8"霸龙头盔",
    .type = u8"头盔",
    .pkgGfxID = 0X019C,
    .shape = 9,
},

{   .name = u8"行者帽",
    .type = u8"头盔",
    .pkgGfxID = 0X019D,
    .shape = 10,
},

{   .name = u8"战神头盔",
    .type = u8"头盔",
    .rarity = u8"稀世",
    .pkgGfxID = 0X019E,
},

{   .name = u8"虎面头盔",
    .type = u8"头盔",
    .rarity = u8"稀世",
    .pkgGfxID = 0X019F,
    .shape = 12,
},

{   .name = u8"赤龙头盔",
    .type = u8"头盔",
    .rarity = u8"稀世",
    .pkgGfxID = 0X01A0,
},

{   .name = u8"血龙头盔",
    .type = u8"头盔",
    .rarity = u8"稀世",
    .pkgGfxID = 0X01A1,
},

{   .name = u8"未知",
    .type = u8"戒指",
    .pkgGfxID = 0X01B8,
},

{   .name = u8"未知",
    .type = u8"戒指",
    .pkgGfxID = 0X01B9,
},

{   .name = u8"未知",
    .type = u8"戒指",
    .pkgGfxID = 0X01BA,
},

{   .name = u8"未知",
    .type = u8"戒指",
    .pkgGfxID = 0X01BB,
},

{   .name = u8"未知",
    .type = u8"戒指",
    .pkgGfxID = 0X01BC,
},

{   .name = u8"未知",
    .type = u8"戒指",
    .pkgGfxID = 0X01BD,
},

{   .name = u8"未知",
    .type = u8"戒指",
    .pkgGfxID = 0X01BE,
},

{   .name = u8"未知",
    .type = u8"戒指",
    .pkgGfxID = 0X01BF,
},

{   .name = u8"未知",
    .type = u8"戒指",
    .pkgGfxID = 0X01C0,
},

{   .name = u8"未知",
    .type = u8"戒指",
    .pkgGfxID = 0X01C1,
},

{   .name = u8"未知",
    .type = u8"戒指",
    .pkgGfxID = 0X01C2,
},

{   .name = u8"牛角戒指",
    .type = u8"戒指",
    .pkgGfxID = 0X01D6,
},

{   .name = u8"玄铁戒指",
    .type = u8"戒指",
    .pkgGfxID = 0X01D7,
},

{   .name = u8"蓝色水晶戒指",
    .type = u8"戒指",
    .pkgGfxID = 0X01D8,
},

{   .name = u8"金戒指",
    .type = u8"戒指",
    .pkgGfxID = 0X01D9,
},

{   .name = u8"降妖除魔戒指",
    .type = u8"戒指",
    .pkgGfxID = 0X01DA,
},

{   .name = u8"润神戒指",
    .type = u8"戒指",
    .pkgGfxID = 0X01DB,
},

{   .name = u8"天际戒指",
    .type = u8"戒指",
    .pkgGfxID = 0X01DC,
},

{   .name = u8"新魔界之",
    .type = u8"戒指",
    .pkgGfxID = 0X01DD,
},

{   .name = u8"七彩金环",
    .type = u8"戒指",
    .pkgGfxID = 0X01DE,
},

{   .name = u8"虚空道环",
    .type = u8"戒指",
    .pkgGfxID = 0X01DF,
},

{   .name = u8"水晶魔戒",
    .type = u8"戒指",
    .pkgGfxID = 0X01EA,
},

{   .name = u8"珍珠戒指",
    .type = u8"戒指",
    .pkgGfxID = 0X01EB,
},

{   .name = u8"道德戒指",
    .type = u8"戒指",
    .pkgGfxID = 0X01EC,
},

{   .name = u8"铂金戒指",
    .type = u8"戒指",
    .pkgGfxID = 0X01ED,
},

{   .name = u8"泰坦戒指",
    .type = u8"戒指",
    .pkgGfxID = 0X01EE,
},

{   .name = u8"魔灵戒指",
    .type = u8"戒指",
    .pkgGfxID = 0X01EF,
},

{   .name = u8"武圣之戒",
    .type = u8"戒指",
    .pkgGfxID = 0X01F0,
},

{   .name = u8"紫金环",
    .type = u8"戒指",
    .pkgGfxID = 0X01F1,
},

{   .name = u8"六棱戒",
    .type = u8"戒指",
    .pkgGfxID = 0X01F2,
},

{   .name = u8"红叶血环",
    .type = u8"戒指",
    .pkgGfxID = 0X01F3,
},

{   .name = u8"永柳戒指",
    .type = u8"戒指",
    .pkgGfxID = 0X01F4,
},

{   .name = u8"夜叉戒指",
    .type = u8"戒指",
    .pkgGfxID = 0X01F5,
},

{   .name = u8"六绝星环",
    .type = u8"戒指",
    .pkgGfxID = 0X01FE,
},

{   .name = u8"蛇眼戒指",
    .type = u8"戒指",
    .pkgGfxID = 0X01FF,
},

{   .name = u8"魅力戒指",
    .type = u8"戒指",
    .pkgGfxID = 0X0200,
},

{   .name = u8"火玉戒指",
    .type = u8"戒指",
    .pkgGfxID = 0X0201,
},

{   .name = u8"紫碧螺",
    .type = u8"戒指",
    .pkgGfxID = 0X0202,
},

{   .name = u8"帝王戒指",
    .type = u8"戒指",
    .pkgGfxID = 0X0203,
},

{   .name = u8"石榴戒指",
    .type = u8"戒指",
    .pkgGfxID = 0X0204,
},

{   .name = u8"全能戒指",
    .type = u8"戒指",
    .pkgGfxID = 0X0205,
},

{   .name = u8"龙马戒指",
    .type = u8"戒指",
    .pkgGfxID = 0X0206,
},

{   .name = u8"九梦戒指",
    .type = u8"戒指",
    .pkgGfxID = 0X0207,
},

{   .name = u8"咒恶戒指",
    .type = u8"戒指",
    .pkgGfxID = 0X0208,
},

{   .name = u8"阿修罗戒指",
    .type = u8"戒指",
    .pkgGfxID = 0X0209,
},

{   .name = u8"古铜戒指",
    .type = u8"戒指",
    .pkgGfxID = 0X0212,
},

{   .name = u8"黑色水晶戒指",
    .type = u8"戒指",
    .pkgGfxID = 0X0213,
},

{   .name = u8"骷髅戒指",
    .type = u8"戒指",
    .pkgGfxID = 0X0214,
},

{   .name = u8"珊瑚戒指",
    .type = u8"戒指",
    .pkgGfxID = 0X0215,
},

{   .name = u8"龙之戒指",
    .type = u8"戒指",
    .pkgGfxID = 0X0216,
},

{   .name = u8"力量戒指",
    .type = u8"戒指",
    .pkgGfxID = 0X0217,
},

{   .name = u8"青摇戒指",
    .type = u8"戒指",
    .pkgGfxID = 0X0218,
},

{   .name = u8"莲丸戒指",
    .type = u8"戒指",
    .pkgGfxID = 0X0219,
},

{   .name = u8"师承戒指",
    .type = u8"戒指",
    .pkgGfxID = 0X021A,
},

{   .name = u8"未知",
    .type = u8"戒指",
    .pkgGfxID = 0X021B,
},

{   .name = u8"未知",
    .type = u8"戒指",
    .pkgGfxID = 0X021C,
},

{   .name = u8"未知",
    .type = u8"戒指",
    .pkgGfxID = 0X021D,
},

{   .name = u8"未知",
    .type = u8"戒指",
    .pkgGfxID = 0X021E,
},

{   .name = u8"未知",
    .type = u8"戒指",
    .pkgGfxID = 0X0226,
},

{   .name = u8"杀魔血刀戒指",
    .type = u8"戒指",
    .pkgGfxID = 0X0227,
},

{   .name = u8"未知",
    .type = u8"戒指",
    .pkgGfxID = 0X0228,
},

{   .name = u8"青云戒指",
    .type = u8"戒指",
    .pkgGfxID = 0X0229,
},

{   .name = u8"阐释戒指",
    .type = u8"戒指",
    .pkgGfxID = 0X022A,
},

{   .name = u8"继承戒指",
    .type = u8"戒指",
    .pkgGfxID = 0X022B,
},

{   .name = u8"三桓戒指",
    .type = u8"戒指",
    .pkgGfxID = 0X022C,
},

{   .name = u8"旭日戒指",
    .type = u8"戒指",
    .pkgGfxID = 0X022D,
},

{   .name = u8"师玉戒指",
    .type = u8"戒指",
    .pkgGfxID = 0X022E,
},

{   .name = u8"日月戒指",
    .type = u8"戒指",
    .pkgGfxID = 0X022F,
},

{   .name = u8"天辉戒指",
    .type = u8"戒指",
    .pkgGfxID = 0X0230,
},

{   .name = u8"销魂戒指",
    .type = u8"戒指",
    .pkgGfxID = 0X0231,
},

{   .name = u8"赤龙戒指",
    .type = u8"戒指",
    .pkgGfxID = 0X0232,
},

{   .name = u8"龙血戒指",
    .type = u8"戒指",
    .pkgGfxID = 0X0233,
},

{   .name = u8"玄灵天戒指",
    .type = u8"戒指",
    .pkgGfxID = 0X0234,
},

{   .name = u8"玄灵魔戒",
    .type = u8"戒指",
    .pkgGfxID = 0X0235,
},

{   .name = u8"玄灵之月龙戒指",
    .type = u8"戒指",
    .pkgGfxID = 0X0236,
},

{   .name = u8"未知",
    .type = u8"戒指",
    .pkgGfxID = 0X0237,
},

{   .name = u8"防御戒指",
    .type = u8"戒指",
    .pkgGfxID = 0X023A,
},

{   .name = u8"麻痹戒指",
    .type = u8"戒指",
    .pkgGfxID = 0X023B,
},

{   .name = u8"神力戒指",
    .type = u8"戒指",
    .pkgGfxID = 0X023C,
},

{   .name = u8"传送戒指",
    .type = u8"戒指",
    .pkgGfxID = 0X023D,
},

{   .name = u8"隐身戒指",
    .type = u8"戒指",
    .pkgGfxID = 0X023E,
},

{   .name = u8"复活戒指",
    .type = u8"戒指",
    .pkgGfxID = 0X023F,
},

{   .name = u8"护身戒指",
    .type = u8"戒指",
    .pkgGfxID = 0X0240,
},

{   .name = u8"火焰戒指",
    .type = u8"戒指",
    .pkgGfxID = 0X0241,
},

{   .name = u8"未知",
    .type = u8"戒指",
    .pkgGfxID = 0X0242,
},

{   .name = u8"记忆戒指",
    .type = u8"戒指",
    .pkgGfxID = 0X024E,
},

{   .name = u8"祈祷戒指",
    .type = u8"戒指",
    .pkgGfxID = 0X024F,
},

{   .name = u8"红魔戒指",
    .type = u8"戒指",
    .pkgGfxID = 0X0250,
},

{   .name = u8"魔血戒指",
    .type = u8"戒指",
    .pkgGfxID = 0X0251,
},

{   .name = u8"金刚魔法戒指",
    .type = u8"戒指",
    .pkgGfxID = 0X0252,
},

{   .name = u8"智慧之物",
    .type = u8"戒指",
    .pkgGfxID = 0X0253,
},

{   .name = u8"正义之物",
    .type = u8"戒指",
    .pkgGfxID = 0X0254,
},

{   .name = u8"三台戒指",
    .type = u8"戒指",
    .pkgGfxID = 0X0255,
},

{   .name = u8"天丛戒指",
    .type = u8"戒指",
    .pkgGfxID = 0X0256,
},

{   .name = u8"转轮戒指",
    .type = u8"戒指",
    .pkgGfxID = 0X0257,
},

{   .name = u8"未知",
    .type = u8"手镯",
    .pkgGfxID = 0X026C,
},

{   .name = u8"未知",
    .type = u8"手镯",
    .pkgGfxID = 0X026D,
},

{   .name = u8"未知",
    .type = u8"手镯",
    .pkgGfxID = 0X026E,
},

{   .name = u8"未知",
    .type = u8"手镯",
    .pkgGfxID = 0X026F,
},

{   .name = u8"未知",
    .type = u8"手镯",
    .pkgGfxID = 0X0270,
},

{   .name = u8"未知",
    .type = u8"手镯",
    .pkgGfxID = 0X0271,
},

{   .name = u8"未知",
    .type = u8"手镯",
    .pkgGfxID = 0X0272,
},

{   .name = u8"未知",
    .type = u8"手镯",
    .pkgGfxID = 0X0273,
},

{   .name = u8"未知",
    .type = u8"手镯",
    .pkgGfxID = 0X0274,
},

{   .name = u8"皮手套",
    .type = u8"手镯",
    .pkgGfxID = 0X0280,
},

{   .name = u8"幽灵手套",
    .type = u8"手镯",
    .pkgGfxID = 0X0281,
},

{   .name = u8"坚固手套",
    .type = u8"手镯",
    .pkgGfxID = 0X0282,
},

{   .name = u8"阎罗手套",
    .type = u8"手镯",
    .pkgGfxID = 0X0283,
},

{   .name = u8"大手镯",
    .type = u8"手镯",
    .pkgGfxID = 0X0284,
},

{   .name = u8"金手镯",
    .type = u8"手镯",
    .pkgGfxID = 0X0285,
},

{   .name = u8"钢手镯",
    .type = u8"手镯",
    .pkgGfxID = 0X0286,
},

{   .name = u8"魔法手镯",
    .type = u8"手镯",
    .pkgGfxID = 0X0287,
},

{   .name = u8"小手镯",
    .type = u8"手镯",
    .pkgGfxID = 0X0288,
},

{   .name = u8"魔令手镯",
    .type = u8"手镯",
    .pkgGfxID = 0X0289,
},

{   .name = u8"武士手镯",
    .type = u8"手镯",
    .pkgGfxID = 0X0294,
},

{   .name = u8"死神手套",
    .type = u8"手镯",
    .pkgGfxID = 0X0295,
},

{   .name = u8"骑士手镯",
    .type = u8"手镯",
    .pkgGfxID = 0X0296,
},

{   .name = u8"如来手镯",
    .type = u8"手镯",
    .pkgGfxID = 0X0297,
},

{   .name = u8"未知",
    .type = u8"手镯",
    .pkgGfxID = 0X0298,
},

{   .name = u8"未知",
    .type = u8"手镯",
    .pkgGfxID = 0X0299,
},

{   .name = u8"英雄手套",
    .type = u8"手镯",
    .pkgGfxID = 0X029A,
},

{   .name = u8"铁炼腕",
    .type = u8"手镯",
    .pkgGfxID = 0X029B,
},

{   .name = u8"未知",
    .type = u8"手镯",
    .pkgGfxID = 0X029C,
},

{   .name = u8"黑皮手套",
    .type = u8"手镯",
    .pkgGfxID = 0X029D,
},

{   .name = u8"未知",
    .type = u8"手镯",
    .pkgGfxID = 0X029E,
},

{   .name = u8"未知",
    .type = u8"手镯",
    .pkgGfxID = 0X029F,
},

{   .name = u8"未知",
    .type = u8"手镯",
    .pkgGfxID = 0X02A0,
},

{   .name = u8"未知",
    .type = u8"手镯",
    .pkgGfxID = 0X02A1,
},

{   .name = u8"未知",
    .type = u8"手镯",
    .pkgGfxID = 0X02A2,
},

{   .name = u8"未知",
    .type = u8"手镯",
    .pkgGfxID = 0X02A3,
},

{   .name = u8"夜叉手镯",
    .type = u8"手镯",
    .pkgGfxID = 0X02A4,
},

{   .name = u8"阿修罗手镯",
    .type = u8"手镯",
    .pkgGfxID = 0X02A5,
},

{   .name = u8"龙王手镯",
    .type = u8"手镯",
    .pkgGfxID = 0X02A6,
},

{   .name = u8"道士手镯",
    .type = u8"手镯",
    .pkgGfxID = 0X02A8,
},

{   .name = u8"三眼手镯",
    .type = u8"手镯",
    .pkgGfxID = 0X02A9,
},

{   .name = u8"心灵手镯",
    .type = u8"手镯",
    .pkgGfxID = 0X02AA,
},

{   .name = u8"毁灭手镯",
    .type = u8"手镯",
    .pkgGfxID = 0X02AB,
},

{   .name = u8"火玉手镯",
    .type = u8"手镯",
    .pkgGfxID = 0X02AC,
},

{   .name = u8"金棱手镯",
    .type = u8"手镯",
    .pkgGfxID = 0X02AD,
},

{   .name = u8"云龙手镯",
    .type = u8"手镯",
    .pkgGfxID = 0X02AE,
    .description = u8"李云龙的传家宝",
},

{   .name = u8"至善手镯",
    .type = u8"手镯",
    .pkgGfxID = 0X02AF,
},

{   .name = u8"登天手镯",
    .type = u8"手镯",
    .pkgGfxID = 0X02B0,
},

{   .name = u8"日月手镯",
    .type = u8"手镯",
    .pkgGfxID = 0X02B1,
},

{   .name = u8"天辉手镯",
    .type = u8"手镯",
    .pkgGfxID = 0X02B2,
},

{   .name = u8"销魂手镯",
    .type = u8"手镯",
    .pkgGfxID = 0X02B3,
},

{   .name = u8"赤龙手镯",
    .type = u8"手镯",
    .pkgGfxID = 0X02B4,
},

{   .name = u8"未知",
    .type = u8"手镯",
    .pkgGfxID = 0X02B5,
},

{   .name = u8"玄灵天手镯",
    .type = u8"手镯",
    .pkgGfxID = 0X02B6,
},

{   .name = u8"玄灵魔环",
    .type = u8"手镯",
    .pkgGfxID = 0X02B7,
},

{   .name = u8"玄灵之月龙手镯",
    .type = u8"手镯",
    .pkgGfxID = 0X02B8,
},

{   .name = u8"玄灵之紫月手镯",
    .type = u8"手镯",
    .pkgGfxID = 0X02B9,
},

{   .name = u8"黑檀手镯",
    .type = u8"手镯",
    .pkgGfxID = 0X02BC,
},

{   .name = u8"思贝儿手镯",
    .type = u8"手镯",
    .pkgGfxID = 0X02BD,
},

{   .name = u8"神秘腰带",
    .type = u8"手镯",
    .pkgGfxID = 0X02BE,
},

{   .name = u8"思过手镯",
    .type = u8"手镯",
    .pkgGfxID = 0X02BF,
},

{   .name = u8"九梦手镯",
    .type = u8"手镯",
    .pkgGfxID = 0X02C0,
},

{   .name = u8"师玉手镯",
    .type = u8"手镯",
    .pkgGfxID = 0X02C1,
},

{   .name = u8"杀魔血刀手镯",
    .type = u8"手镯",
    .pkgGfxID = 0X02C2,
},

{   .name = u8"未知",
    .type = u8"手镯",
    .pkgGfxID = 0X02D0,
},

{   .name = u8"夏普尔手镯",
    .type = u8"手镯",
    .pkgGfxID = 0X02D1,
},

{   .name = u8"银手镯",
    .type = u8"手镯",
    .pkgGfxID = 0X02D2,
},

{   .name = u8"避邪手镯",
    .type = u8"手镯",
    .pkgGfxID = 0X02D3,
},

{   .name = u8"未知",
    .type = u8"手镯",
    .pkgGfxID = 0X02D4,
},

{   .name = u8"世尊手镯",
    .type = u8"手镯",
    .pkgGfxID = 0X02D5,
},

{   .name = u8"未知",
    .type = u8"手镯",
    .pkgGfxID = 0X02E4,
},

{   .name = u8"心念手镯",
    .type = u8"手镯",
    .pkgGfxID = 0X02E5,
},

{   .name = u8"未知",
    .type = u8"手镯",
    .pkgGfxID = 0X02E6,
},

{   .name = u8"未知",
    .type = u8"手镯",
    .pkgGfxID = 0X02E7,
},

{   .name = u8"记忆手镯",
    .type = u8"手镯",
    .pkgGfxID = 0X02F8,
},

{   .name = u8"祈祷手镯",
    .type = u8"手镯",
    .pkgGfxID = 0X02F9,
},

{   .name = u8"虹魔手镯",
    .type = u8"手镯",
    .pkgGfxID = 0X02FA,
},

{   .name = u8"魔血手镯",
    .type = u8"手镯",
    .pkgGfxID = 0X02FB,
},

{   .name = u8"金刚手镯",
    .type = u8"手镯",
    .pkgGfxID = 0X02FC,
},

{   .name = u8"未知",
    .type = u8"手镯",
    .pkgGfxID = 0X02FD,
},

{   .name = u8"未知",
    .type = u8"手镯",
    .pkgGfxID = 0X02FE,
},

{   .name = u8"三台手镯",
    .type = u8"手镯",
    .pkgGfxID = 0X02FF,
},

{   .name = u8"天丛手镯",
    .type = u8"手镯",
    .pkgGfxID = 0X0300,
},

{   .name = u8"转轮手镯",
    .type = u8"手镯",
    .pkgGfxID = 0X0301,
},

{   .name = u8"造化宝轮",
    .type = u8"手镯",
    .pkgGfxID = 0X030C,
},

{   .name = u8"明刻经文手镯",
    .type = u8"手镯",
    .pkgGfxID = 0X030D,
},

{   .name = u8"悔悟手镯",
    .type = u8"手镯",
    .pkgGfxID = 0X030E,
},

{   .name = u8"金影甲",
    .type = u8"手镯",
    .pkgGfxID = 0X030F,
},

{   .name = u8"凡影手镯",
    .type = u8"手镯",
    .pkgGfxID = 0X0310,
},

{   .name = u8"未知",
    .type = u8"项链",
    .pkgGfxID = 0X0316,
},

{   .name = u8"未知",
    .type = u8"项链",
    .pkgGfxID = 0X0317,
},

{   .name = u8"未知",
    .type = u8"项链",
    .pkgGfxID = 0X0318,
},

{   .name = u8"未知",
    .type = u8"项链",
    .pkgGfxID = 0X0319,
},

{   .name = u8"未知",
    .type = u8"项链",
    .pkgGfxID = 0X031A,
},

{   .name = u8"未知",
    .type = u8"项链",
    .pkgGfxID = 0X031B,
},

{   .name = u8"未知",
    .type = u8"项链",
    .pkgGfxID = 0X031C,
},

{   .name = u8"未知",
    .type = u8"项链",
    .pkgGfxID = 0X031D,
},

{   .name = u8"未知",
    .type = u8"项链",
    .pkgGfxID = 0X031E,
},

{   .name = u8"未知",
    .type = u8"项链",
    .pkgGfxID = 0X031F,
},

{   .name = u8"黑色水晶项链",
    .type = u8"项链",
    .pkgGfxID = 0X032A,
},

{   .name = u8"魔鬼项链",
    .type = u8"项链",
    .pkgGfxID = 0X032B,
},

{   .name = u8"蓝翡翠项链",
    .type = u8"项链",
    .pkgGfxID = 0X032C,
},

{   .name = u8"幽灵项链",
    .type = u8"项链",
    .pkgGfxID = 0X032D,
},

{   .name = u8"绿色项链",
    .type = u8"项链",
    .pkgGfxID = 0X032E,
},

{   .name = u8"怨恨项链",
    .type = u8"项链",
    .pkgGfxID = 0X032F,
},

{   .name = u8"昏暗风印",
    .type = u8"项链",
    .pkgGfxID = 0X0330,
},

{   .name = u8"莲花宝镜",
    .type = u8"项链",
    .pkgGfxID = 0X0331,
},

{   .name = u8"复血",
    .type = u8"项链",
    .pkgGfxID = 0X0332,
},

{   .name = u8"破荒项链",
    .type = u8"项链",
    .pkgGfxID = 0X0333,
},

{   .name = u8"绿色水晶项链",
    .type = u8"项链",
    .pkgGfxID = 0X033E,
},

{   .name = u8"凤凰明珠",
    .type = u8"项链",
    .pkgGfxID = 0X033F,
},

{   .name = u8"竹笛",
    .type = u8"项链",
    .pkgGfxID = 0X0340,
},

{   .name = u8"天珠项链",
    .type = u8"项链",
    .pkgGfxID = 0X0341,
},

{   .name = u8"灵魂项链",
    .type = u8"项链",
    .pkgGfxID = 0X0342,
},

{   .name = u8"勇士项链",
    .type = u8"项链",
    .pkgGfxID = 0X0343,
},

{   .name = u8"破坏项链",
    .type = u8"项链",
    .pkgGfxID = 0X0344,
},

{   .name = u8"荣耀项链",
    .type = u8"项链",
    .pkgGfxID = 0X0345,
},

{   .name = u8"猫眼",
    .type = u8"项链",
    .pkgGfxID = 0X0346,
},

{   .name = u8"定心项链",
    .type = u8"项链",
    .pkgGfxID = 0X0347,
},

{   .name = u8"红色水晶项链",
    .type = u8"项链",
    .pkgGfxID = 0X0352,
},

{   .name = u8"白金项链",
    .type = u8"项链",
    .pkgGfxID = 0X0353,
},

{   .name = u8"琥珀项链",
    .type = u8"项链",
    .pkgGfxID = 0X0354,
},

{   .name = u8"放大镜",
    .type = u8"项链",
    .pkgGfxID = 0X0355,
},

{   .name = u8"五彩项链",
    .type = u8"项链",
    .pkgGfxID = 0X0356,
},

{   .name = u8"恶魔铃铛",
    .type = u8"项链",
    .pkgGfxID = 0X0357,
},

{   .name = u8"愤怒之钟",
    .type = u8"项链",
    .pkgGfxID = 0X0358,
},

{   .name = u8"未知",
    .type = u8"项链",
    .pkgGfxID = 0X0359,
},

{   .name = u8"神谕项链",
    .type = u8"项链",
    .pkgGfxID = 0X035A,
},

{   .name = u8"魔云项链",
    .type = u8"项链",
    .pkgGfxID = 0X035B,
},

{   .name = u8"新手项链",
    .type = u8"项链",
    .pkgGfxID = 0X0366,
},

{   .name = u8"白色虎齿项链",
    .type = u8"项链",
    .pkgGfxID = 0X0367,
},

{   .name = u8"灯笼项链",
    .type = u8"项链",
    .pkgGfxID = 0X0368,
},

{   .name = u8"传统项链",
    .type = u8"项链",
    .pkgGfxID = 0X0369,
},

{   .name = u8"躲避项链",
    .type = u8"项链",
    .pkgGfxID = 0X036A,
},

{   .name = u8"未知",
    .type = u8"项链",
    .pkgGfxID = 0X036B,
},

{   .name = u8"未知",
    .type = u8"项链",
    .pkgGfxID = 0X036C,
},

{   .name = u8"狂风项链",
    .type = u8"项链",
    .pkgGfxID = 0X036D,
},

{   .name = u8"铁系项链",
    .type = u8"项链",
    .pkgGfxID = 0X036E,
},

{   .name = u8"圣山项链",
    .type = u8"项链",
    .pkgGfxID = 0X036F,
},

{   .name = u8"探测项链",
    .type = u8"项链",
    .pkgGfxID = 0X037A,
},

{   .name = u8"技巧项链",
    .type = u8"项链",
    .pkgGfxID = 0X037B,
},

{   .name = u8"追魂项链",
    .type = u8"项链",
    .pkgGfxID = 0X037C,
},

{   .name = u8"追风项链",
    .type = u8"项链",
    .pkgGfxID = 0X037D,
},

{   .name = u8"魔令项链",
    .type = u8"项链",
    .pkgGfxID = 0X037E,
},

{   .name = u8"眼镜项链",
    .type = u8"项链",
    .pkgGfxID = 0X037F,
},

{   .name = u8"震天项链",
    .type = u8"项链",
    .pkgGfxID = 0X0380,
},

{   .name = u8"乾坤一气",
    .type = u8"项链",
    .pkgGfxID = 0X0381,
},

{   .name = u8"流星项链",
    .type = u8"项链",
    .pkgGfxID = 0X0382,
},

{   .name = u8"毁灭魔链",
    .type = u8"项链",
    .pkgGfxID = 0X0383,
},

{   .name = u8"记忆项链",
    .type = u8"项链",
    .pkgGfxID = 0X038E,
},

{   .name = u8"祈祷项链",
    .type = u8"项链",
    .pkgGfxID = 0X038F,
},

{   .name = u8"虹魔项链",
    .type = u8"项链",
    .pkgGfxID = 0X0390,
},

{   .name = u8"魔血项链",
    .type = u8"项链",
    .pkgGfxID = 0X0391,
},

{   .name = u8"金刚铃铛",
    .type = u8"项链",
    .pkgGfxID = 0X0392,
},

{   .name = u8"五行神镜",
    .type = u8"项链",
    .pkgGfxID = 0X0393,
},

{   .name = u8"气血项链",
    .type = u8"项链",
    .pkgGfxID = 0X0394,
},

{   .name = u8"神勇之物",
    .type = u8"项链",
    .pkgGfxID = 0X0395,
},

{   .name = u8"未知",
    .type = u8"项链",
    .pkgGfxID = 0X0396,
},

{   .name = u8"未知",
    .type = u8"项链",
    .pkgGfxID = 0X0397,
},

{   .name = u8"未知",
    .type = u8"项链",
    .pkgGfxID = 0X0398,
},

{   .name = u8"未知",
    .type = u8"项链",
    .pkgGfxID = 0X0399,
},

{   .name = u8"未知",
    .type = u8"项链",
    .pkgGfxID = 0X039A,
},

{   .name = u8"未知",
    .type = u8"项链",
    .pkgGfxID = 0X039B,
},

{   .name = u8"未知",
    .type = u8"项链",
    .pkgGfxID = 0X039C,
},

{   .name = u8"未知",
    .type = u8"项链",
    .pkgGfxID = 0X039D,
},

{   .name = u8"未知",
    .type = u8"项链",
    .pkgGfxID = 0X039E,
},

{   .name = u8"未知",
    .type = u8"项链",
    .pkgGfxID = 0X039F,
},

{   .name = u8"未知",
    .type = u8"项链",
    .pkgGfxID = 0X03A0,
},

{   .name = u8"未知",
    .type = u8"项链",
    .pkgGfxID = 0X03A1,
},

{   .name = u8"未知",
    .type = u8"项链",
    .pkgGfxID = 0X03A2,
},

{   .name = u8"未知",
    .type = u8"项链",
    .pkgGfxID = 0X03A3,
},

{   .name = u8"未知",
    .type = u8"项链",
    .pkgGfxID = 0X03A4,
},

{   .name = u8"未知",
    .type = u8"项链",
    .pkgGfxID = 0X03A5,
},

{   .name = u8"布衣（男）",
    .type = u8"衣服",
    .weight = 5,
    .pkgGfxID = 0X03AC,
    .shape = 1,
    .equip
    {
        .duration = 5,
        .ac = {2, 2},
        .mac = {0, 1},
        .req
        {
            .level = 1,
        },
    },
},

{   .name = u8"轻盔甲（男）",
    .type = u8"衣服",
    .pkgGfxID = 0X03AD,
    .shape = 2,
},

{   .name = u8"未知",
    .type = u8"衣服",
    .pkgGfxID = 0X03AE,
    .shape = 2,
},

{   .name = u8"未知",
    .type = u8"衣服",
    .pkgGfxID = 0X03AF,
},

{   .name = u8"未知",
    .type = u8"衣服",
    .pkgGfxID = 0X03B0,
},

{   .name = u8"韩服（男）",
    .type = u8"衣服",
    .pkgGfxID = 0X03B1,
},

{   .name = u8"唐装（男）",
    .type = u8"衣服",
    .pkgGfxID = 0X03B2,
},

{   .name = u8"布衣（女）",
    .type = u8"衣服",
    .pkgGfxID = 0X03B6,
    .shape = 1,
},

{   .name = u8"轻盔甲（女）",
    .type = u8"衣服",
    .pkgGfxID = 0X03B7,
    .shape = 2,
},

{   .name = u8"未知",
    .type = u8"衣服",
    .pkgGfxID = 0X03B8,
    .shape = 2,
},

{   .name = u8"未知",
    .type = u8"衣服",
    .pkgGfxID = 0X03B9,
},

{   .name = u8"未知",
    .type = u8"衣服",
    .pkgGfxID = 0X03BA,
},

{   .name = u8"韩服（女）",
    .type = u8"衣服",
    .pkgGfxID = 0X03BB,
},

{   .name = u8"旗袍（女）",
    .type = u8"衣服",
    .pkgGfxID = 0X03BC,
},

{   .name = u8"未知",
    .type = u8"衣服",
    .pkgGfxID = 0X03C0,
},

{   .name = u8"未知",
    .type = u8"衣服",
    .pkgGfxID = 0X03C1,
},

{   .name = u8"未知",
    .type = u8"衣服",
    .pkgGfxID = 0X03C2,
},

{   .name = u8"未知",
    .type = u8"衣服",
    .pkgGfxID = 0X03C3,
},

{   .name = u8"未知",
    .type = u8"衣服",
    .pkgGfxID = 0X03C4,
},

{   .name = u8"未知",
    .type = u8"衣服",
    .pkgGfxID = 0X03C5,
},

{   .name = u8"未知",
    .type = u8"衣服",
    .pkgGfxID = 0X03C6,
},

{   .name = u8"未知",
    .type = u8"衣服",
    .pkgGfxID = 0X03CA,
},

{   .name = u8"未知",
    .type = u8"衣服",
    .pkgGfxID = 0X03CB,
},

{   .name = u8"未知",
    .type = u8"衣服",
    .pkgGfxID = 0X03CC,
},

{   .name = u8"未知",
    .type = u8"衣服",
    .pkgGfxID = 0X03CD,
},

{   .name = u8"未知",
    .type = u8"衣服",
    .pkgGfxID = 0X03CE,
},

{   .name = u8"未知",
    .type = u8"衣服",
    .pkgGfxID = 0X03CF,
},

{   .name = u8"未知",
    .type = u8"衣服",
    .pkgGfxID = 0X03D0,
},

{   .name = u8"重盔甲（男）",
    .type = u8"衣服",
    .pkgGfxID = 0X03D4,
    .shape = 3,
},

{   .name = u8"战神盔甲（男）",
    .type = u8"衣服",
    .pkgGfxID = 0X03D5,
    .shape = 6,
},

{   .name = u8"未知",
    .type = u8"衣服",
    .pkgGfxID = 0X03D6,
    .shape = 6,
},

{   .name = u8"未知",
    .type = u8"衣服",
    .pkgGfxID = 0X03D7,
    .shape = 6,
},

{   .name = u8"未知",
    .type = u8"衣服",
    .pkgGfxID = 0X03D8,
},

{   .name = u8"未知",
    .type = u8"衣服",
    .pkgGfxID = 0X03D9,
},

{   .name = u8"未知",
    .type = u8"衣服",
    .pkgGfxID = 0X03DA,
},

{   .name = u8"重盔甲（女）",
    .type = u8"衣服",
    .pkgGfxID = 0X03DE,
    .shape = 3,
},

{   .name = u8"战神盔甲（女）",
    .type = u8"衣服",
    .pkgGfxID = 0X03DF,
    .shape = 6,
},

{   .name = u8"未知",
    .type = u8"衣服",
    .pkgGfxID = 0X03E0,
    .shape = 6,
},

{   .name = u8"未知",
    .type = u8"衣服",
    .pkgGfxID = 0X03E1,
    .shape = 6,
},

{   .name = u8"未知",
    .type = u8"衣服",
    .pkgGfxID = 0X03E2,
},

{   .name = u8"未知",
    .type = u8"衣服",
    .pkgGfxID = 0X03E3,
},

{   .name = u8"未知",
    .type = u8"衣服",
    .pkgGfxID = 0X03E4,
},

{   .name = u8"灵魂战衣（男）",
    .type = u8"衣服",
    .pkgGfxID = 0X03E8,
    .shape = 5,
},

{   .name = u8"幽灵战衣（男）",
    .type = u8"衣服",
    .pkgGfxID = 0X03E9,
    .shape = 8,
},

{   .name = u8"未知",
    .type = u8"衣服",
    .pkgGfxID = 0X03EA,
    .shape = 8,
},

{   .name = u8"未知",
    .type = u8"衣服",
    .pkgGfxID = 0X03EB,
    .shape = 8,
},

{   .name = u8"灵魂战衣（女）",
    .type = u8"衣服",
    .pkgGfxID = 0X03F2,
    .shape = 5,
},

{   .name = u8"幽灵战衣（女）",
    .type = u8"衣服",
    .pkgGfxID = 0X03F3,
    .shape = 8,
},

{   .name = u8"未知",
    .type = u8"衣服",
    .pkgGfxID = 0X03F4,
    .shape = 8,
},

{   .name = u8"未知",
    .type = u8"衣服",
    .pkgGfxID = 0X03F5,
    .shape = 8,
},

{   .name = u8"法师长袍（男）",
    .type = u8"衣服",
    .pkgGfxID = 0X03FC,
    .shape = 4,
},

{   .name = u8"恶魔长袍（男）",
    .type = u8"衣服",
    .pkgGfxID = 0X03FD,
    .shape = 7,
},

{   .name = u8"未知",
    .type = u8"衣服",
    .pkgGfxID = 0X03FE,
    .shape = 7,
},

{   .name = u8"未知",
    .type = u8"衣服",
    .pkgGfxID = 0X03FF,
    .shape = 7,
},

{   .name = u8"法师长袍（女）",
    .type = u8"衣服",
    .pkgGfxID = 0X0406,
    .shape = 4,
},

{   .name = u8"恶魔长袍（女）",
    .type = u8"衣服",
    .pkgGfxID = 0X0407,
    .shape = 7,
},

{   .name = u8"未知",
    .type = u8"衣服",
    .pkgGfxID = 0X0408,
    .shape = 7,
},

{   .name = u8"未知",
    .type = u8"衣服",
    .pkgGfxID = 0X0409,
    .shape = 7,
},

{   .name = u8"鹤嘴锄",
    .type = u8"武器",
    .pkgGfxID = 0X0410,
    .shape = 7,
},

{   .name = u8"破山剑",
    .type = u8"武器",
    .rarity = u8"稀世",
    .pkgGfxID = 0X0411,
    .shape = 8,
},

{   .name = u8"木剑",
    .type = u8"武器",
    .pkgGfxID = 0X0412,
    .shape = 9,
    .equip
    {
        .duration = 4,
        .dc = {2, 5},
        .req
        {
            .level = 1,
        },
    },
},

{   .name = u8"乌木剑",
    .type = u8"武器",
    .pkgGfxID = 0X0412,
    .shape = 9,
},

{   .name = u8"青铜剑",
    .type = u8"武器",
    .pkgGfxID = 0X0413,
    .shape = 23,
},

{   .name = u8"铁剑",
    .type = u8"武器",
    .pkgGfxID = 0X0414,
    .shape = 23,
},

{   .name = u8"匕首",
    .type = u8"武器",
    .pkgGfxID = 0X0415,
    .shape = 21,
},

{   .name = u8"封魔剑",
    .type = u8"武器",
    .rarity = u8"高级",
    .pkgGfxID = 0X0416,
    .shape = 1,
},

{   .name = u8"天神法杖",
    .type = u8"武器",
    .rarity = u8"稀世",
    .pkgGfxID = 0X0417,
    .shape = 24,
},

{   .name = u8"风之鹤嘴锄",
    .type = u8"武器",
    .rarity = u8"稀世",
    .pkgGfxID = 0X0418,
    .shape = 7,
},

{   .name = u8"旋风流星刀",
    .type = u8"武器",
    .rarity = u8"高级",
    .pkgGfxID = 0X0419,
    .shape = 22,
},

{   .name = u8"飞龙剑",
    .type = u8"武器",
    .rarity = u8"高级",
    .pkgGfxID = 0X041A,
    .shape = 14,
},

{   .name = u8"火银龙",
    .type = u8"武器",
    .rarity = u8"高级",
    .pkgGfxID = 0X041B,
},

{   .name = u8"破魂",
    .type = u8"武器",
    .pkgGfxID = 0X041C,
    .shape = 21,
},

{   .name = u8"八荒",
    .type = u8"武器",
    .pkgGfxID = 0X041D,
    .shape = 23,
},

{   .name = u8"单刀",
    .type = u8"武器",
    .pkgGfxID = 0X041E,
},

{   .name = u8"凌风",
    .type = u8"武器",
    .pkgGfxID = 0X041F,
    .shape = 11,
},

{   .name = u8"旗帜（龙）",
    .type = u8"武器",
    .pkgGfxID = 0X0420,
},

{   .name = u8"旗帜（虎）",
    .type = u8"武器",
    .pkgGfxID = 0X0421,
},

{   .name = u8"未知",
    .type = u8"武器",
    .pkgGfxID = 0X0422,
},

{   .name = u8"青铜斧",
    .type = u8"武器",
    .pkgGfxID = 0X0424,
    .shape = 10,
},

{   .name = u8"飞魂魔刃",
    .type = u8"武器",
    .rarity = u8"高级",
    .pkgGfxID = 0X0425,
    .shape = 25,
},

{   .name = u8"无名刀",
    .type = u8"武器",
    .weight = 25,
    .pkgGfxID = 0X0426,
    .shape = 33,
    .equip
    {
        .duration = 24,
        .dc = {7, 18},
        .sdc = {3, 6},
        .hit = 2,
        .req
        {
            .level = 33,
        }
    },
},

{   .name = u8"斩马刀",
    .type = u8"武器",
    .weight = 27,
    .pkgGfxID = 0X0427,
    .shape = 11,
    .equip
    {
        .duration = 18,
        .dc = {5, 16},
        .req
        {
            .level = 18,
        }
    },
},

{   .name = u8"阴阳刀",
    .type = u8"武器",
    .rarity = u8"高级",
    .pkgGfxID = 0X0428,
    .shape = 41,
},

{   .name = u8"修罗",
    .type = u8"武器",
    .weight = 30,
    .pkgGfxID = 0X0429,
    .shape = 12,
    .equip
    {
        .duration = 22,
        .dc = {0, 22},
        .req
        {
            .level = 20,
        }
    },
},

{   .name = u8"炼狱",
    .type = u8"武器",
    .weight = 70,
    .pkgGfxID = 0X042A,
    .shape = 5,
    .equip
    {
        .duration = 30,
        .dc = {1, 32},
        .req
        {
            .level = 33,
        }
    },
},

{   .name = u8"命运之刃",
    .type = u8"武器",
    .pkgGfxID = 0X042B,
    .shape = 13,
},

{   .name = u8"井中月",
    .type = u8"武器",
    .pkgGfxID = 0X042C,
    .shape = 14,
},

{   .name = u8"裁决之杖",
    .type = u8"武器",
    .rarity = u8"高级",
    .pkgGfxID = 0X042D,
    .shape = 15,
},

{   .name = u8"屠龙",
    .type = u8"武器",
    .rarity = u8"高级",
    .weight = 100,
    .pkgGfxID = 0X042E,
    .shape = 4,
    .equip
    {
        .duration = 36,
        .dc = {2, 40},
        .req
        {
            .level = 34,
        }
    },
    .description = u8"用天外玄铁打造，刀身刻有龙纹，潜藏着强大的气场，是荣耀和力量的象征。",
},

// above items includes all in itemDB with continuous index till 0X042E

{   .name = u8"草鞋",
    .type = u8"鞋",
    .pkgGfxID = 0X0550,
    .equip
    {
        .comfort = 1,
        .load
        {
            .hand = 1,
            .inventory = 1,
        },

        .req
        {
            .level = 6,
        }
    },
    .description = u8"用香蒲编成的凉鞋，价格低廉，是老百姓常穿的鞋子。",
},

{   .name = u8"皮靴",
    .type = u8"鞋",
    .pkgGfxID = 0X0551,
    .equip
    {
        .duration = 8,
        .comfort = 2,
        .load
        {
            .hand = 2,
            .inventory = 2,
        },

        .req
        {
            .level = 16,
        }
    },
    .description = u8"用皮革做成的鞋子，坚固耐用，是老百姓常穿的鞋子。",
},

{   .name = u8"五彩鞋",
    .type = u8"鞋",
    .pkgGfxID = 0X055E,
    .equip
    {
        .comfort = 3,
        .load
        {
            .hand = 2,
            .inventory = 2,
        },

        .req
        {
            .level = 26,
        }
    },
},

{   .name = u8"鹿皮靴",
    .type = u8"鞋",
    .pkgGfxID = 0X0561,
},

{   .name = u8"钢靴",
    .type = u8"鞋",
    .pkgGfxID = 0X055C,
},

{   .name = u8"天掌靴",
    .type = u8"鞋",
    .weight = 2,
    .pkgGfxID = 0X0552,
    .equip
    {
        .duration = 10,
        .comfort = 5,
        .load
        {
            .hand = 4,
            .inventory = 4,
        },

        .req
        {
            .level = 38,
        }
    },
},

{   .name = u8"赤飞靴",
    .type = u8"鞋",
    .weight = 2,
    .pkgGfxID = 0X0553,
    .equip
    {
        .duration = 10,
        .comfort = 4,
        .load
        {
            .hand = 3,
            .inventory = 3,
        },

        .req
        {
            .level = 33,
        }
    },
},

{   .name = u8"黑皮靴",
    .type = u8"鞋",
    .weight = 3,
    .pkgGfxID = 0X0554,
    .equip
    {
        .duration = 12,
        .comfort = 7,
        .load
        {
            .hand = 7,
            .inventory = 7,
        },
    },
},

{   .name = u8"长皮靴",
    .type = u8"鞋",
    .pkgGfxID = 0X055A,
},

{   .name = u8"月光鞋",
    .type = u8"鞋",
    .weight = 2,
    .pkgGfxID = 0X055B,
    .equip
    {
        .duration = 8,
        .comfort = 7,
        .load
        {
            .hand = 3,
            .inventory = 14,
        },
    },
},

{   .name = u8"无影靴",
    .type = u8"鞋",
    .pkgGfxID = 0X055D,
},

{   .name = u8"仙云靴",
    .type = u8"鞋",
    .pkgGfxID = 0X055F,
},

{   .name = u8"武神靴",
    .type = u8"鞋",
    .pkgGfxID = 0X0560,
},

{   .name = u8"踏浪靴",
    .type = u8"鞋",
    .pkgGfxID = 0X0562,
},

{   .name = u8"锦靴",
    .type = u8"鞋",
    .pkgGfxID = 0X0563,
},

{   .name = u8"黄金靴",
    .type = u8"鞋",
    .pkgGfxID = 0X0564,
},

{   .name = u8"紫金靴",
    .type = u8"鞋",
    .pkgGfxID = 0X0565,
},

{   .name = u8"布鞋",
    .type = u8"鞋",
    .pkgGfxID = 0X0566,
    .description = u8"由布做的鞋，是老百姓常穿的鞋子。"
},

{   .name = u8"乌金靴",
    .type = u8"鞋",
    .pkgGfxID = 0X0567,
},

// above items includes all in itemDB with continuous index till 0X0567
// items from 0X568 to 0X0572 are still shoes but they have only in-inventory-gfx, I suspect they are quest props

{   .name = u8"未知",
    .type = u8"道具",
    .pkgGfxID = 0X0578,
},

{   .name = u8"未知",
    .type = u8"道具",
    .pkgGfxID = 0X0579,
},

{   .name = u8"未知",
    .type = u8"道具",
    .pkgGfxID = 0X057A,
},

{   .name = u8"未知",
    .type = u8"道具",
    .pkgGfxID = 0X057B,
},

{   .name = u8"未知",
    .type = u8"道具",
    .pkgGfxID = 0X057C,
},

{   .name = u8"未知",
    .type = u8"道具",
    .pkgGfxID = 0X057D,
},

{   .name = u8"未知",
    .type = u8"道具",
    .pkgGfxID = 0X057E,
},

{   .name = u8"未知",
    .type = u8"道具",
    .pkgGfxID = 0X057F,
},

{   .name = u8"未知",
    .type = u8"道具",
    .pkgGfxID = 0X0580,
},

{   .name = u8"未知",
    .type = u8"道具",
    .pkgGfxID = 0X0581,
},

{   .name = u8"褐色栗子",
    .type = u8"道具",
    .pkgGfxID = 0X0582,
    .description = u8"营养丰富的褐色栗子，益气补脾，健胃厚肠。",
},

{   .name = u8"金色栗子",
    .type = u8"道具",
    .pkgGfxID = 0X0583,
    .description = u8"营养丰富的金色栗子，益气补脾，健胃厚肠，是栗子中的极品。",
},

{   .name = u8"银色栗子",
    .type = u8"道具",
    .pkgGfxID = 0X0584,
    .description = u8"营养丰富的银色栗子，益气补脾，健胃厚肠，是栗子中的珍品。",
},

{   .name = u8"铜色栗子",
    .type = u8"道具",
    .pkgGfxID = 0X0585,
    .description = u8"营养丰富的铜色栗子，益气补脾，健胃厚肠,是栗子中的上品。",
},
