{   .name = u8"",
},

{   .name = u8"比奇县_0",
    .miniMapID = 0X19001000,
    .mapSwitchList
    {
        {.x = 333, .y = 776, .endName = u8"边境城市_01", .endX = 564, .endY = 69},
        {.x = 334, .y = 775, .endName = u8"边境城市_01", .endX = 565, .endY = 68},
        {.x = 335, .y = 774, .endName = u8"边境城市_01", .endX = 566, .endY = 67},
        {.x = 779, .y = 698, .endName = u8"银杏山谷_02", .endX = 30, .endY = 452},
        {.x = 778, .y = 699, .endName = u8"银杏山谷_02", .endX = 29, .endY = 453},
        {.x = 777, .y = 700, .endName = u8"银杏山谷_02", .endX = 28, .endY = 454},
        {.x = 776, .y = 701, .endName = u8"银杏山谷_02", .endX = 27, .endY = 455},
        {.x = 643, .y = 15, .endName = u8"毒蛇山谷_2", .endX = 159, .endY = 369},
        {.x = 644, .y = 16, .endName = u8"毒蛇山谷_2", .endX = 160, .endY = 370},
        {.x = 645, .y = 17, .endName = u8"毒蛇山谷_2", .endX = 161, .endY = 371},
        {.x = 646, .y = 18, .endName = u8"毒蛇山谷_2", .endX = 162, .endY = 372},
        {.x = 209, .y = 49, .endName = u8"道馆_1", .endX = 515, .endY = 579},
        {.x = 208, .y = 50, .endName = u8"道馆_1", .endX = 514, .endY = 580},
        {.x = 207, .y = 51, .endName = u8"道馆_1", .endX = 513, .endY = 581},
        {.x = 206, .y = 52, .endName = u8"道馆_1", .endX = 512, .endY = 582},
        {.x = 65, .y = 174, .endName = u8"半兽洞穴1层_D001", .endX = 151, .endY = 362},
        {.x = 764, .y = 206, .endName = u8"废矿矿山入口_D401", .endX = 25, .endY = 181},
    }
},

{   .name = u8"边境城市_01",
    .miniMapID = 0X19001001,
    .mapSwitchList
    {
        {.x = 447, .y = 246, .endName = u8"志善屋_01_001", .endX = 20, .endY = 21},
        {.x = 563, .y = 68, .endName = u8"比奇县_0", .endX = 332, .endY = 775},
        {.x = 564, .y = 67, .endName = u8"比奇县_0", .endX = 333, .endY = 774},
        {.x = 565, .y = 66, .endName = u8"比奇县_0", .endX = 335, .endY = 773},
        {.x = 86, .y = 405, .endName = u8"沙漠_71", .endX = 379, .endY = 36},
        {.x = 87, .y = 406, .endName = u8"沙漠_71", .endX = 380, .endY = 37},
        {.x = 88, .y = 407, .endName = u8"沙漠_71", .endX = 381, .endY = 38},
        {.x = 89, .y = 408, .endName = u8"沙漠_71", .endX = 382, .endY = 39},
        {.x = 90, .y = 409, .endName = u8"沙漠_71", .endX = 383, .endY = 40},
        {.x = 91, .y = 410, .endName = u8"沙漠_71", .endX = 384, .endY = 41},
        {.x = 92, .y = 411, .endName = u8"沙漠_71", .endX = 385, .endY = 42},
        {.x = 355, .y = 65, .endName = u8"北部石矿1层_D1411", .endX = 92, .endY = 387},
        {.x = 497, .y = 86, .endName = u8"东部石矿_D1405", .endX = 86, .endY = 365},
        {.x = 294, .y = 153, .endName = u8"西部石矿1层_D1421", .endX = 92, .endY = 387},
    }
},

{   .name = u8"沙巴克城堡_0150",
    .mapSwitchList
    {
        {.x = 15, .y = 20, .endName = u8"沙巴克城_3", .endX = 194, .endY = 144},
        {.x = 16, .y = 19, .endName = u8"沙巴克城_3", .endX = 195, .endY = 143},
    }
},

{   .name = u8"沙巴克城楼_0157",
    .mapSwitchList
    {
        {.x = 8, .y = 26, .endName = u8"祖玛神殿_31", .endX = 173, .endY = 130},
        {.x = 9, .y = 27, .endName = u8"祖玛神殿_31", .endX = 173, .endY = 130},
        {.x = 20, .y = 15, .endName = u8"祖玛神殿1层_D501", .endX = 166, .endY = 216},
        {.x = 20, .y = 5, .endName = u8"祖玛神殿1层_D501", .endX = 166, .endY = 216},
    }
},

{   .name = u8"祖玛神殿大厅_0157",
    .mapSwitchList
    {
        {.x = 8, .y = 26, .endName = u8"祖玛神殿_31", .endX = 173, .endY = 130},
        {.x = 9, .y = 27, .endName = u8"祖玛神殿_31", .endX = 173, .endY = 130},
        {.x = 20, .y = 15, .endName = u8"祖玛神殿1层_D501", .endX = 166, .endY = 216},
        {.x = 20, .y = 5, .endName = u8"祖玛神殿1层_D501", .endX = 166, .endY = 216},
    }
},

{   .name = u8"志善屋_01_001",
    .mapSwitchList
    {
        {.x = 19, .y = 22, .endName = u8"边境城市_01", .endX = 446, .endY = 247},
    }
},

{   .name = u8"试练场_01_003",
},

{   .name = u8"银杏山谷_02",
    .miniMapID = 0X19001002,
    .mapSwitchList
    {
        {.x = 29, .y = 452, .endName = u8"比奇县_0", .endX = 778, .endY = 698},
        {.x = 28, .y = 453, .endName = u8"比奇县_0", .endX = 777, .endY = 699},
        {.x = 27, .y = 454, .endName = u8"比奇县_0", .endX = 776, .endY = 700},
        {.x = 26, .y = 455, .endName = u8"比奇县_0", .endX = 775, .endY = 701},
        {.x = 483, .y = 322, .endName = u8"天然洞穴1层_D011", .endX = 154, .endY = 367},
        {.x = 281, .y = 73, .endName = u8"北部银杏废矿1层_D1311", .endX = 358, .endY = 378},
        {.x = 346, .y = 120, .endName = u8"东部银杏废矿1层_D1301", .endX = 358, .endY = 378},
        {.x = 129, .y = 157, .endName = u8"西部银杏废矿1层_D1321", .endX = 358, .endY = 378},
    }
},

{   .name = u8"试练场_02_001",
},

{   .name = u8"试练场_02_002",
    .mapSwitchList
    {
        {.x = 90, .y = 15, .endName = u8"试练场_02_003", .endX = 22, .endY = 83},
        {.x = 90, .y = 16, .endName = u8"试练场_02_003", .endX = 22, .endY = 83},
        {.x = 91, .y = 14, .endName = u8"试练场_02_003", .endX = 22, .endY = 83},
        {.x = 91, .y = 15, .endName = u8"试练场_02_003", .endX = 22, .endY = 83},
        {.x = 91, .y = 16, .endName = u8"试练场_02_003", .endX = 22, .endY = 83},
        {.x = 92, .y = 13, .endName = u8"试练场_02_003", .endX = 22, .endY = 83},
        {.x = 92, .y = 14, .endName = u8"试练场_02_003", .endX = 22, .endY = 83},
        {.x = 92, .y = 15, .endName = u8"试练场_02_003", .endX = 22, .endY = 83},
    }
},

{   .name = u8"试练场_02_003",
},

{   .name = u8"试练场_02_004",
},

{   .name = u8"试练场_02_005",
},

{   .name = u8"试练场_02_006",
},

{   .name = u8"试练场_02_010",
},

{   .name = u8"试练场_02_011",
},

{   .name = u8"试练场_02_012",
},

{   .name = u8"试练场_02_013",
},

{   .name = u8"试练场_02_014",
},

{   .name = u8"比奇县_0_003",
    .mapSwitchList
    {
        {.x = 24, .y = 31, .endName = u8"比奇县_0", .endX = 514, .endY = 391},
        {.x = 25, .y = 31, .endName = u8"比奇县_0", .endX = 515, .endY = 391},
        {.x = 26, .y = 31, .endName = u8"比奇县_0", .endX = 516, .endY = 391},
        {.x = 27, .y = 31, .endName = u8"比奇县_0", .endX = 517, .endY = 391},
        {.x = 28, .y = 31, .endName = u8"比奇县_0", .endX = 518, .endY = 391},
        {.x = 29, .y = 31, .endName = u8"比奇县_0", .endX = 519, .endY = 391},
        {.x = 24, .y = 32, .endName = u8"比奇县_0", .endX = 514, .endY = 392},
        {.x = 24, .y = 33, .endName = u8"比奇县_0", .endX = 514, .endY = 393},
        {.x = 24, .y = 34, .endName = u8"比奇县_0", .endX = 514, .endY = 394},
        {.x = 24, .y = 35, .endName = u8"比奇县_0", .endX = 514, .endY = 395},
        {.x = 24, .y = 36, .endName = u8"比奇县_0", .endX = 514, .endY = 396},
        {.x = 24, .y = 37, .endName = u8"比奇县_0", .endX = 514, .endY = 397},
        {.x = 24, .y = 38, .endName = u8"比奇县_0", .endX = 514, .endY = 398},
        {.x = 24, .y = 39, .endName = u8"比奇县_0", .endX = 514, .endY = 399},
        {.x = 25, .y = 39, .endName = u8"比奇县_0", .endX = 515, .endY = 399},
        {.x = 26, .y = 39, .endName = u8"比奇县_0", .endX = 516, .endY = 399},
        {.x = 27, .y = 39, .endName = u8"比奇县_0", .endX = 517, .endY = 399},
        {.x = 28, .y = 39, .endName = u8"比奇县_0", .endX = 518, .endY = 399},
        {.x = 29, .y = 39, .endName = u8"比奇县_0", .endX = 519, .endY = 399},
        {.x = 30, .y = 39, .endName = u8"比奇县_0", .endX = 520, .endY = 399},
        {.x = 30, .y = 32, .endName = u8"比奇县_0", .endX = 520, .endY = 392},
        {.x = 30, .y = 33, .endName = u8"比奇县_0", .endX = 520, .endY = 393},
        {.x = 30, .y = 34, .endName = u8"比奇县_0", .endX = 520, .endY = 394},
        {.x = 30, .y = 35, .endName = u8"比奇县_0", .endX = 520, .endY = 395},
        {.x = 30, .y = 36, .endName = u8"比奇县_0", .endX = 520, .endY = 396},
        {.x = 30, .y = 37, .endName = u8"比奇县_0", .endX = 520, .endY = 397},
        {.x = 30, .y = 38, .endName = u8"比奇县_0", .endX = 520, .endY = 398},
        {.x = 30, .y = 31, .endName = u8"比奇县_0", .endX = 520, .endY = 391},
    }
},

{   .name = u8"道馆_1",
    .miniMapID = 0X19001003,
    .mapSwitchList
    {
        {.x = 429, .y = 96, .endName = u8"本馆_1_002", .endX = 10, .endY = 17},
        {.x = 394, .y = 169, .endName = u8"仓库_1_007", .endX = 6, .endY = 17},
        {.x = 388, .y = 113, .endName = u8"药剂师住居_1_006", .endX = 7, .endY = 15},
        {.x = 415, .y = 133, .endName = u8"洗衣住居_1_003", .endX = 8, .endY = 11},
        {.x = 429, .y = 120, .endName = u8"武器仓库_1_001", .endX = 6, .endY = 17},
        {.x = 367, .y = 134, .endName = u8"物品研究所_1_005", .endX = 11, .endY = 15},
        {.x = 415, .y = 96, .endName = u8"书房_1_004", .endX = 11, .endY = 15},
        {.x = 18, .y = 564, .endName = u8"失乐园_9", .endX = 746, .endY = 36},
        {.x = 19, .y = 565, .endName = u8"失乐园_9", .endX = 747, .endY = 37},
        {.x = 20, .y = 566, .endName = u8"失乐园_9", .endX = 748, .endY = 38},
        {.x = 21, .y = 567, .endName = u8"失乐园_9", .endX = 749, .endY = 39},
        {.x = 22, .y = 568, .endName = u8"失乐园_9", .endX = 750, .endY = 40},
        {.x = 516, .y = 580, .endName = u8"比奇县_0", .endX = 210, .endY = 50},
        {.x = 515, .y = 581, .endName = u8"比奇县_0", .endX = 209, .endY = 51},
        {.x = 514, .y = 582, .endName = u8"比奇县_0", .endX = 208, .endY = 52},
        {.x = 513, .y = 583, .endName = u8"比奇县_0", .endX = 207, .endY = 53},
        {.x = 405, .y = 30, .endName = u8"灌木林_12", .endX = 123, .endY = 467},
        {.x = 404, .y = 30, .endName = u8"灌木林_12", .endX = 122, .endY = 467},
        {.x = 403, .y = 30, .endName = u8"灌木林_12", .endX = 121, .endY = 467},
        {.x = 54, .y = 370, .endName = u8"沃玛神殿入口_D021", .endX = 76, .endY = 74},
        {.x = 54, .y = 369, .endName = u8"沃玛神殿入口_D021", .endX = 76, .endY = 75},
        {.x = 186, .y = 64, .endName = u8"无名老人隐居地_1_009", .endX = 39, .endY = 135},
        {.x = 185, .y = 65, .endName = u8"无名老人隐居地_1_009", .endX = 41, .endY = 137},
        {.x = 185, .y = 66, .endName = u8"无名老人隐居地_1_009", .endX = 40, .endY = 136},
    }
},

{   .name = u8"灌木林_12",
    .miniMapID = 0X19001004,
    .mapSwitchList
    {
        {.x = 206, .y = 48, .endName = u8"灌木林_125", .endX = 124, .endY = 366},
        {.x = 205, .y = 49, .endName = u8"灌木林_125", .endX = 123, .endY = 367},
        {.x = 204, .y = 50, .endName = u8"灌木林_125", .endX = 122, .endY = 368},
        {.x = 203, .y = 51, .endName = u8"灌木林_125", .endX = 121, .endY = 369},
        {.x = 202, .y = 52, .endName = u8"灌木林_125", .endX = 120, .endY = 370},
        {.x = 362, .y = 394, .endName = u8"灌木林_122", .endX = 24, .endY = 365},
        {.x = 363, .y = 393, .endName = u8"灌木林_122", .endX = 23, .endY = 364},
        {.x = 364, .y = 392, .endName = u8"灌木林_122", .endX = 22, .endY = 363},
        {.x = 365, .y = 391, .endName = u8"灌木林_122", .endX = 21, .endY = 362},
        {.x = 123, .y = 468, .endName = u8"道馆_1", .endX = 405, .endY = 31},
        {.x = 122, .y = 468, .endName = u8"道馆_1", .endX = 404, .endY = 31},
        {.x = 334, .y = 52, .endName = u8"赤月山谷1层_D1001", .endX = 269, .endY = 384},
        {.x = 110, .y = 31, .endName = u8"赤月山谷1层_D1011", .endX = 52, .endY = 286},
        {.x = 46, .y = 143, .endName = u8"赤月山谷1层_D1021", .endX = 288, .endY = 287},
    }
},

{   .name = u8"灌木林_122",
    .miniMapID = 0X19001025,
    .mapSwitchList
    {
        {.x = 255, .y = 53, .endName = u8"灌木林_125", .endX = 319, .endY = 74},
        {.x = 254, .y = 52, .endName = u8"灌木林_125", .endX = 320, .endY = 75},
        {.x = 253, .y = 51, .endName = u8"灌木林_125", .endX = 321, .endY = 76},
        {.x = 252, .y = 50, .endName = u8"灌木林_125", .endX = 322, .endY = 77},
        {.x = 251, .y = 49, .endName = u8"灌木林_125", .endX = 323, .endY = 78},
        {.x = 250, .y = 48, .endName = u8"灌木林_125", .endX = 324, .endY = 79},
        {.x = 24, .y = 367, .endName = u8"灌木林_12", .endX = 361, .endY = 393},
        {.x = 23, .y = 366, .endName = u8"灌木林_12", .endX = 362, .endY = 392},
        {.x = 22, .y = 365, .endName = u8"灌木林_12", .endX = 362, .endY = 391},
        {.x = 21, .y = 364, .endName = u8"灌木林_12", .endX = 363, .endY = 391},
        {.x = 20, .y = 363, .endName = u8"灌木林_12", .endX = 363, .endY = 390},
        {.x = 340, .y = 369, .endName = u8"沙巴克城_3", .endX = 32, .endY = 268},
        {.x = 341, .y = 368, .endName = u8"沙巴克城_3", .endX = 33, .endY = 267},
        {.x = 342, .y = 367, .endName = u8"沙巴克城_3", .endX = 34, .endY = 266},
        {.x = 343, .y = 366, .endName = u8"沙巴克城_3", .endX = 35, .endY = 265},
        {.x = 344, .y = 365, .endName = u8"沙巴克城_3", .endX = 36, .endY = 264},
    }
},

{   .name = u8"灌木林_125",
    .miniMapID = 0X19001028,
    .mapSwitchList
    {
        {.x = 125, .y = 367, .endName = u8"灌木林_12", .endX = 207, .endY = 49},
        {.x = 124, .y = 368, .endName = u8"灌木林_12", .endX = 206, .endY = 50},
        {.x = 123, .y = 369, .endName = u8"灌木林_12", .endX = 205, .endY = 51},
        {.x = 122, .y = 370, .endName = u8"灌木林_12", .endX = 204, .endY = 52},
        {.x = 121, .y = 371, .endName = u8"灌木林_12", .endX = 203, .endY = 53},
        {.x = 320, .y = 73, .endName = u8"灌木林_122", .endX = 254, .endY = 54},
        {.x = 321, .y = 74, .endName = u8"灌木林_122", .endX = 253, .endY = 53},
        {.x = 322, .y = 75, .endName = u8"灌木林_122", .endX = 252, .endY = 52},
        {.x = 323, .y = 76, .endName = u8"灌木林_122", .endX = 251, .endY = 51},
        {.x = 324, .y = 77, .endName = u8"灌木林_122", .endX = 250, .endY = 50},
        {.x = 325, .y = 78, .endName = u8"灌木林_122", .endX = 249, .endY = 49},
    }
},

{   .name = u8"武器仓库_1_001",
    .mapSwitchList
    {
        {.x = 5, .y = 18, .endName = u8"道馆_1", .endX = 428, .endY = 121},
    }
},

{   .name = u8"本馆_1_002",
    .mapSwitchList
    {
        {.x = 9, .y = 18, .endName = u8"道馆_1", .endX = 428, .endY = 97},
    }
},

{   .name = u8"洗衣住居_1_003",
    .mapSwitchList
    {
        {.x = 7, .y = 12, .endName = u8"道馆_1", .endX = 414, .endY = 134},
    }
},

{   .name = u8"书房_1_004",
    .mapSwitchList
    {
        {.x = 12, .y = 16, .endName = u8"道馆_1", .endX = 415, .endY = 97},
    }
},

{   .name = u8"物品研究所_1_005",
    .mapSwitchList
    {
        {.x = 12, .y = 16, .endName = u8"道馆_1", .endX = 368, .endY = 135},
    }
},

{   .name = u8"药剂师住居_1_006",
    .mapSwitchList
    {
        {.x = 8, .y = 16, .endName = u8"道馆_1", .endX = 389, .endY = 114},
    }
},

{   .name = u8"仓库_1_007",
    .mapSwitchList
    {
        {.x = 5, .y = 18, .endName = u8"道馆_1", .endX = 393, .endY = 170},
    }
},

{   .name = u8"试练场_1_008",
},

{   .name = u8"无名老人隐居地_1_009",
    .mapSwitchList
    {
        {.x = 43, .y = 138, .endName = u8"道馆_1", .endX = 186, .endY = 67},
        {.x = 43, .y = 139, .endName = u8"道馆_1", .endX = 188, .endY = 67},
        {.x = 44, .y = 139, .endName = u8"道馆_1", .endX = 188, .endY = 68},
    }
},

{   .name = u8"试练场_1_010",
    .mapSwitchList
    {
        {.x = 90, .y = 15, .endName = u8"试练场_1_011", .endX = 22, .endY = 83},
        {.x = 90, .y = 16, .endName = u8"试练场_1_011", .endX = 22, .endY = 83},
        {.x = 91, .y = 14, .endName = u8"试练场_1_011", .endX = 22, .endY = 83},
        {.x = 91, .y = 15, .endName = u8"试练场_1_011", .endX = 22, .endY = 83},
        {.x = 91, .y = 16, .endName = u8"试练场_1_011", .endX = 22, .endY = 83},
        {.x = 92, .y = 13, .endName = u8"试练场_1_011", .endX = 22, .endY = 83},
        {.x = 92, .y = 14, .endName = u8"试练场_1_011", .endX = 22, .endY = 83},
        {.x = 92, .y = 15, .endName = u8"试练场_1_011", .endX = 22, .endY = 83},
    }
},

{   .name = u8"试练场_1_011",
},

{   .name = u8"试练场_1_012",
},

{   .name = u8"试练场_1_013",
},

{   .name = u8"试练场_1_014",
},

{   .name = u8"困魔咒空间_1_015",
    .mapSwitchList
    {
        {.x = 9, .y = 15, .endName = u8"沃玛神殿2层_D023", .endX = 371, .endY = 364},
        {.x = 9, .y = 16, .endName = u8"沃玛神殿2层_D023", .endX = 371, .endY = 364},
        {.x = 28, .y = 33, .endName = u8"困魔咒空间_1_016", .endX = 10, .endY = 17},
        {.x = 29, .y = 33, .endName = u8"困魔咒空间_1_016", .endX = 10, .endY = 17},
        {.x = 29, .y = 32, .endName = u8"困魔咒空间_1_016", .endX = 10, .endY = 17},
        {.x = 30, .y = 32, .endName = u8"困魔咒空间_1_016", .endX = 10, .endY = 17},
    }
},

{   .name = u8"困魔咒空间_1_016",
    .mapSwitchList
    {
        {.x = 9, .y = 15, .endName = u8"困魔咒空间_1_015", .endX = 28, .endY = 31},
        {.x = 9, .y = 16, .endName = u8"困魔咒空间_1_015", .endX = 28, .endY = 31},
        {.x = 28, .y = 33, .endName = u8"困魔咒空间_1_017", .endX = 10, .endY = 17},
        {.x = 29, .y = 33, .endName = u8"困魔咒空间_1_017", .endX = 10, .endY = 17},
        {.x = 29, .y = 32, .endName = u8"困魔咒空间_1_017", .endX = 10, .endY = 17},
        {.x = 30, .y = 32, .endName = u8"困魔咒空间_1_017", .endX = 10, .endY = 17},
    }
},

{   .name = u8"困魔咒空间_1_017",
    .mapSwitchList
    {
        {.x = 9, .y = 15, .endName = u8"困魔咒空间_1_016", .endX = 28, .endY = 31},
        {.x = 9, .y = 16, .endName = u8"困魔咒空间_1_016", .endX = 28, .endY = 31},
        {.x = 28, .y = 33, .endName = u8"困魔咒空间_1_018", .endX = 10, .endY = 17},
        {.x = 29, .y = 33, .endName = u8"困魔咒空间_1_018", .endX = 10, .endY = 17},
        {.x = 29, .y = 32, .endName = u8"困魔咒空间_1_018", .endX = 10, .endY = 17},
        {.x = 30, .y = 32, .endName = u8"困魔咒空间_1_018", .endX = 10, .endY = 17},
    }
},

{   .name = u8"困魔咒空间_1_018",
    .mapSwitchList
    {
        {.x = 9, .y = 15, .endName = u8"困魔咒空间_1_017", .endX = 28, .endY = 31},
        {.x = 9, .y = 16, .endName = u8"困魔咒空间_1_017", .endX = 28, .endY = 31},
        {.x = 28, .y = 33, .endName = u8"困魔咒空间_1_019", .endX = 13, .endY = 17},
        {.x = 29, .y = 33, .endName = u8"困魔咒空间_1_019", .endX = 13, .endY = 17},
        {.x = 29, .y = 32, .endName = u8"困魔咒空间_1_019", .endX = 13, .endY = 17},
        {.x = 30, .y = 32, .endName = u8"困魔咒空间_1_019", .endX = 13, .endY = 17},
    }
},

{   .name = u8"困魔咒空间_1_019",
    .mapSwitchList
    {
        {.x = 12, .y = 15, .endName = u8"困魔咒空间_1_018", .endX = 28, .endY = 31},
        {.x = 13, .y = 16, .endName = u8"困魔咒空间_1_018", .endX = 28, .endY = 31},
        {.x = 39, .y = 40, .endName = u8"沃玛神殿2层_D023", .endX = 371, .endY = 364},
        {.x = 40, .y = 40, .endName = u8"沃玛神殿2层_D023", .endX = 371, .endY = 364},
        {.x = 38, .y = 41, .endName = u8"沃玛神殿2层_D023", .endX = 371, .endY = 364},
        {.x = 39, .y = 41, .endName = u8"沃玛神殿2层_D023", .endX = 371, .endY = 364},
        {.x = 39, .y = 40, .endName = u8"道馆_1", .endX = 350, .endY = 402},
        {.x = 40, .y = 40, .endName = u8"道馆_1", .endX = 350, .endY = 402},
        {.x = 38, .y = 41, .endName = u8"道馆_1", .endX = 350, .endY = 402},
        {.x = 39, .y = 41, .endName = u8"道馆_1", .endX = 350, .endY = 402},
    }
},

{   .name = u8"蜈蚣洞穴_1_020",
    .mapSwitchList
    {
        {.x = 186, .y = 17, .endName = u8"绝命谷3层_D6004", .endX = 41, .endY = 264},
        {.x = 187, .y = 17, .endName = u8"绝命谷3层_D6004", .endX = 41, .endY = 264},
        {.x = 187, .y = 18, .endName = u8"绝命谷3层_D6004", .endX = 41, .endY = 264},
        {.x = 172, .y = 173, .endName = u8"蜈蚣洞穴_1_021", .endX = 24, .endY = 40},
        {.x = 172, .y = 174, .endName = u8"蜈蚣洞穴_1_021", .endX = 24, .endY = 40},
        {.x = 172, .y = 175, .endName = u8"蜈蚣洞穴_1_021", .endX = 24, .endY = 40},
    }
},

{   .name = u8"蜈蚣洞穴_1_021",
    .mapSwitchList
    {
        {.x = 22, .y = 42, .endName = u8"蜈蚣洞穴_1_020", .endX = 169, .endY = 172},
        {.x = 22, .y = 43, .endName = u8"蜈蚣洞穴_1_020", .endX = 169, .endY = 172},
        {.x = 22, .y = 44, .endName = u8"蜈蚣洞穴_1_020", .endX = 169, .endY = 172},
        {.x = 23, .y = 44, .endName = u8"蜈蚣洞穴_1_020", .endX = 169, .endY = 172},
        {.x = 10, .y = 12, .endName = u8"蜈蚣洞穴_1_022", .endX = 163, .endY = 30},
        {.x = 10, .y = 13, .endName = u8"蜈蚣洞穴_1_022", .endX = 163, .endY = 30},
        {.x = 11, .y = 12, .endName = u8"蜈蚣洞穴_1_022", .endX = 163, .endY = 30},
    }
},

{   .name = u8"蜈蚣洞穴_1_022",
    .mapSwitchList
    {
        {.x = 166, .y = 33, .endName = u8"蜈蚣洞穴_1_021", .endX = 12, .endY = 14},
        {.x = 166, .y = 34, .endName = u8"蜈蚣洞穴_1_021", .endX = 12, .endY = 14},
        {.x = 166, .y = 35, .endName = u8"蜈蚣洞穴_1_021", .endX = 12, .endY = 14},
        {.x = 165, .y = 36, .endName = u8"蜈蚣洞穴_1_021", .endX = 12, .endY = 14},
        {.x = 11, .y = 12, .endName = u8"蜈蚣洞穴_1_023", .endX = 40, .endY = 36},
        {.x = 11, .y = 13, .endName = u8"蜈蚣洞穴_1_023", .endX = 40, .endY = 36},
        {.x = 11, .y = 14, .endName = u8"蜈蚣洞穴_1_023", .endX = 40, .endY = 36},
        {.x = 12, .y = 12, .endName = u8"蜈蚣洞穴_1_023", .endX = 40, .endY = 36},
    }
},

{   .name = u8"蜈蚣洞穴_1_023",
    .mapSwitchList
    {
        {.x = 42, .y = 38, .endName = u8"蜈蚣洞穴_1_022", .endX = 13, .endY = 13},
        {.x = 42, .y = 39, .endName = u8"蜈蚣洞穴_1_022", .endX = 13, .endY = 13},
        {.x = 42, .y = 40, .endName = u8"蜈蚣洞穴_1_022", .endX = 13, .endY = 13},
        {.x = 41, .y = 40, .endName = u8"蜈蚣洞穴_1_022", .endX = 13, .endY = 13},
    }
},

{   .name = u8"毒蛇山谷_2",
    .miniMapID = 0X19001005,
    .mapSwitchList
    {
        {.x = 158, .y = 370, .endName = u8"比奇县_0", .endX = 643, .endY = 16},
        {.x = 159, .y = 371, .endName = u8"比奇县_0", .endX = 643, .endY = 17},
        {.x = 160, .y = 372, .endName = u8"比奇县_0", .endX = 644, .endY = 18},
        {.x = 161, .y = 373, .endName = u8"比奇县_0", .endX = 645, .endY = 19},
        {.x = 118, .y = 55, .endName = u8"沙巴克城_3", .endX = 364, .endY = 571},
        {.x = 119, .y = 56, .endName = u8"沙巴克城_3", .endX = 365, .endY = 572},
        {.x = 120, .y = 57, .endName = u8"沙巴克城_3", .endX = 366, .endY = 573},
        {.x = 121, .y = 58, .endName = u8"沙巴克城_3", .endX = 367, .endY = 574},
        {.x = 354, .y = 33, .endName = u8"祖玛神殿_31", .endX = 120, .endY = 256},
        {.x = 355, .y = 34, .endName = u8"祖玛神殿_31", .endX = 121, .endY = 257},
        {.x = 256, .y = 35, .endName = u8"祖玛神殿_31", .endX = 122, .endY = 258},
        {.x = 355, .y = 33, .endName = u8"祖玛神殿_31", .endX = 120, .endY = 256},
        {.x = 356, .y = 34, .endName = u8"祖玛神殿_31", .endX = 121, .endY = 257},
        {.x = 357, .y = 35, .endName = u8"祖玛神殿_31", .endX = 122, .endY = 258},
        {.x = 366, .y = 200, .endName = u8"矿山1层_D421", .endX = 30, .endY = 374},
        {.x = 342, .y = 137, .endName = u8"南部矿山_D431", .endX = 25, .endY = 181},
        {.x = 350, .y = 261, .endName = u8"南部矿山1层_D451", .endX = 30, .endY = 374},
    }
},

{   .name = u8"沙巴克城_3",
    .miniMapID = 0X19001017,
    .mapSwitchList
    {
        {.x = 195, .y = 143, .endName = u8"沙巴克城堡_0150", .endX = 15, .endY = 18},
        {.x = 194, .y = 144, .endName = u8"沙巴克城堡_0150", .endX = 14, .endY = 19},
        {.x = 349, .y = 38, .endName = u8"祖玛神殿_31", .endX = 24, .endY = 50},
        {.x = 350, .y = 39, .endName = u8"祖玛神殿_31", .endX = 25, .endY = 51},
        {.x = 351, .y = 40, .endName = u8"祖玛神殿_31", .endX = 26, .endY = 52},
        {.x = 352, .y = 41, .endName = u8"祖玛神殿_31", .endX = 27, .endY = 53},
        {.x = 353, .y = 42, .endName = u8"祖玛神殿_31", .endX = 28, .endY = 54},
        {.x = 354, .y = 43, .endName = u8"祖玛神殿_31", .endX = 29, .endY = 55},
        {.x = 363, .y = 572, .endName = u8"毒蛇山谷_2", .endX = 118, .endY = 56},
        {.x = 364, .y = 573, .endName = u8"毒蛇山谷_2", .endX = 119, .endY = 57},
        {.x = 365, .y = 574, .endName = u8"毒蛇山谷_2", .endX = 120, .endY = 58},
        {.x = 366, .y = 575, .endName = u8"毒蛇山谷_2", .endX = 121, .endY = 59},
        {.x = 367, .y = 576, .endName = u8"毒蛇山谷_2", .endX = 122, .endY = 59},
        {.x = 349, .y = 38, .endName = u8"祖玛神殿_31", .endX = 24, .endY = 50},
        {.x = 350, .y = 39, .endName = u8"祖玛神殿_31", .endX = 25, .endY = 51},
        {.x = 351, .y = 40, .endName = u8"祖玛神殿_31", .endX = 26, .endY = 52},
        {.x = 352, .y = 41, .endName = u8"祖玛神殿_31", .endX = 27, .endY = 53},
        {.x = 353, .y = 42, .endName = u8"祖玛神殿_31", .endX = 28, .endY = 54},
        {.x = 354, .y = 43, .endName = u8"祖玛神殿_31", .endX = 29, .endY = 55},
        {.x = 35, .y = 264, .endName = u8"灌木林_122", .endX = 343, .endY = 364},
        {.x = 34, .y = 265, .endName = u8"灌木林_122", .endX = 342, .endY = 365},
        {.x = 33, .y = 266, .endName = u8"灌木林_122", .endX = 341, .endY = 366},
        {.x = 32, .y = 267, .endName = u8"灌木林_122", .endX = 340, .endY = 367},
        {.x = 31, .y = 268, .endName = u8"灌木林_122", .endX = 339, .endY = 368},
    }
},

{   .name = u8"祖玛神殿_31",
    .miniMapID = 0X19001030,
    .mapSwitchList
    {
        {.x = 119, .y = 256, .endName = u8"毒蛇山谷_2", .endX = 353, .endY = 34},
        {.x = 120, .y = 257, .endName = u8"毒蛇山谷_2", .endX = 354, .endY = 35},
        {.x = 121, .y = 258, .endName = u8"毒蛇山谷_2", .endX = 355, .endY = 36},
        {.x = 121, .y = 259, .endName = u8"毒蛇山谷_2", .endX = 357, .endY = 35},
        {.x = 23, .y = 51, .endName = u8"沙巴克城_3", .endX = 348, .endY = 39},
        {.x = 24, .y = 52, .endName = u8"沙巴克城_3", .endX = 349, .endY = 40},
        {.x = 25, .y = 53, .endName = u8"沙巴克城_3", .endX = 350, .endY = 41},
        {.x = 26, .y = 54, .endName = u8"沙巴克城_3", .endX = 351, .endY = 42},
        {.x = 27, .y = 55, .endName = u8"沙巴克城_3", .endX = 352, .endY = 43},
        {.x = 28, .y = 56, .endName = u8"沙巴克城_3", .endX = 353, .endY = 44},
        {.x = 119, .y = 256, .endName = u8"毒蛇山谷_2", .endX = 353, .endY = 34},
        {.x = 120, .y = 257, .endName = u8"毒蛇山谷_2", .endX = 354, .endY = 35},
        {.x = 121, .y = 258, .endName = u8"毒蛇山谷_2", .endX = 355, .endY = 36},
        {.x = 121, .y = 259, .endName = u8"毒蛇山谷_2", .endX = 355, .endY = 35},
        {.x = 23, .y = 51, .endName = u8"沙巴克城_3", .endX = 348, .endY = 39},
        {.x = 24, .y = 52, .endName = u8"沙巴克城_3", .endX = 349, .endY = 40},
        {.x = 25, .y = 53, .endName = u8"沙巴克城_3", .endX = 350, .endY = 41},
        {.x = 26, .y = 54, .endName = u8"沙巴克城_3", .endX = 351, .endY = 42},
        {.x = 27, .y = 55, .endName = u8"沙巴克城_3", .endX = 352, .endY = 43},
        {.x = 28, .y = 56, .endName = u8"沙巴克城_3", .endX = 353, .endY = 44},
        {.x = 175, .y = 128, .endName = u8"祖玛神殿大厅_0157", .endX = 9, .endY = 26},
        {.x = 174, .y = 128, .endName = u8"祖玛神殿大厅_0157", .endX = 9, .endY = 26},
    }
},

{   .name = u8"绿洲_4",
    .miniMapID = 0X19001006,
    .mapSwitchList
    {
        {.x = 476, .y = 57, .endName = u8"占卜屋_4_005", .endX = 11, .endY = 26},
        {.x = 449, .y = 73, .endName = u8"武器店_4_001", .endX = 13, .endY = 13},
        {.x = 448, .y = 93, .endName = u8"民家_4_002", .endX = 8, .endY = 15},
        {.x = 453, .y = 96, .endName = u8"民家_4_002", .endX = 14, .endY = 17},
        {.x = 433, .y = 72, .endName = u8"中药商_4_003", .endX = 13, .endY = 13},
        {.x = 462, .y = 89, .endName = u8"布匹店_4_004", .endX = 8, .endY = 13},
        {.x = 180, .y = 778, .endName = u8"沙漠_6", .endX = 178, .endY = 80},
        {.x = 181, .y = 779, .endName = u8"沙漠_6", .endX = 179, .endY = 81},
        {.x = 182, .y = 780, .endName = u8"沙漠_6", .endX = 180, .endY = 82},
        {.x = 283, .y = 778, .endName = u8"沙漠_6", .endX = 285, .endY = 80},
        {.x = 282, .y = 779, .endName = u8"沙漠_6", .endX = 284, .endY = 81},
        {.x = 281, .y = 780, .endName = u8"沙漠_6", .endX = 283, .endY = 82},
        {.x = 280, .y = 781, .endName = u8"沙漠_6", .endX = 282, .endY = 83},
        {.x = 384, .y = 768, .endName = u8"沙漠_6", .endX = 386, .endY = 70},
        {.x = 383, .y = 769, .endName = u8"沙漠_6", .endX = 385, .endY = 71},
        {.x = 382, .y = 770, .endName = u8"沙漠_6", .endX = 384, .endY = 72},
        {.x = 471, .y = 765, .endName = u8"沙漠_6", .endX = 473, .endY = 67},
        {.x = 470, .y = 766, .endName = u8"沙漠_6", .endX = 472, .endY = 68},
        {.x = 469, .y = 767, .endName = u8"沙漠_6", .endX = 471, .endY = 69},
        {.x = 27, .y = 231, .endName = u8"诺玛村庄_41", .endX = 380, .endY = 345},
        {.x = 28, .y = 232, .endName = u8"诺玛村庄_41", .endX = 381, .endY = 346},
        {.x = 29, .y = 233, .endName = u8"诺玛村庄_41", .endX = 382, .endY = 347},
        {.x = 30, .y = 234, .endName = u8"诺玛村庄_41", .endX = 383, .endY = 348},
        {.x = 73, .y = 461, .endName = u8"沙漠_44", .endX = 375, .endY = 112},
        {.x = 72, .y = 462, .endName = u8"沙漠_44", .endX = 374, .endY = 113},
        {.x = 71, .y = 463, .endName = u8"沙漠_44", .endX = 373, .endY = 114},
        {.x = 70, .y = 464, .endName = u8"沙漠_44", .endX = 372, .endY = 115},
        {.x = 69, .y = 465, .endName = u8"沙漠_44", .endX = 371, .endY = 116},
        {.x = 68, .y = 466, .endName = u8"沙漠_44", .endX = 370, .endY = 117},
        {.x = 515, .y = 639, .endName = u8"沙漠土城_5", .endX = 108, .endY = 386},
        {.x = 516, .y = 638, .endName = u8"沙漠土城_5", .endX = 109, .endY = 385},
        {.x = 517, .y = 637, .endName = u8"沙漠土城_5", .endX = 110, .endY = 384},
        {.x = 518, .y = 636, .endName = u8"沙漠土城_5", .endX = 111, .endY = 383},
        {.x = 458, .y = 648, .endName = u8"沙漠土城_5", .endX = 55, .endY = 365},
        {.x = 459, .y = 649, .endName = u8"沙漠土城_5", .endX = 56, .endY = 366},
        {.x = 460, .y = 650, .endName = u8"沙漠土城_5", .endX = 57, .endY = 367},
        {.x = 422, .y = 547, .endName = u8"沙漠土城_5", .endX = 18, .endY = 207},
        {.x = 423, .y = 548, .endName = u8"沙漠土城_5", .endX = 19, .endY = 208},
        {.x = 424, .y = 549, .endName = u8"沙漠土城_5", .endX = 20, .endY = 209},
        {.x = 447, .y = 480, .endName = u8"沙漠土城_5", .endX = 51, .endY = 119},
        {.x = 448, .y = 479, .endName = u8"沙漠土城_5", .endX = 52, .endY = 118},
        {.x = 449, .y = 478, .endName = u8"沙漠土城_5", .endX = 53, .endY = 117},
        {.x = 459, .y = 422, .endName = u8"沙漠土城_5", .endX = 76, .endY = 13},
        {.x = 460, .y = 423, .endName = u8"沙漠土城_5", .endX = 77, .endY = 14},
        {.x = 461, .y = 424, .endName = u8"沙漠土城_5", .endX = 78, .endY = 15},
        {.x = 462, .y = 425, .endName = u8"沙漠土城_5", .endX = 79, .endY = 16},
        {.x = 563, .y = 392, .endName = u8"沙漠土城_5", .endX = 174, .endY = 31},
        {.x = 562, .y = 393, .endName = u8"沙漠土城_5", .endX = 174, .endY = 32},
        {.x = 561, .y = 394, .endName = u8"沙漠土城_5", .endX = 173, .endY = 33},
        {.x = 375, .y = 119, .endName = u8"北部蚂蚁洞穴1层1_D8102", .endX = 179, .endY = 188},
        {.x = 476, .y = 152, .endName = u8"东部蚂蚁洞穴1层1_D8202", .endX = 179, .endY = 188},
    }
},

{   .name = u8"诺玛村庄_41",
    .miniMapID = 0X19001020,
    .mapSwitchList
    {
        {.x = 84, .y = 342, .endName = u8"西沙漠地洞_D2001", .endX = 282, .endY = 280},
        {.x = 381, .y = 345, .endName = u8"绿洲_4", .endX = 28, .endY = 231},
        {.x = 382, .y = 346, .endName = u8"绿洲_4", .endX = 29, .endY = 232},
        {.x = 383, .y = 347, .endName = u8"绿洲_4", .endX = 30, .endY = 233},
        {.x = 384, .y = 348, .endName = u8"绿洲_4", .endX = 31, .endY = 234},
        {.x = 385, .y = 349, .endName = u8"绿洲_4", .endX = 31, .endY = 234},
        {.x = 33, .y = 137, .endName = u8"沙漠_42", .endX = 375, .endY = 324},
        {.x = 32, .y = 138, .endName = u8"沙漠_42", .endX = 374, .endY = 325},
        {.x = 31, .y = 139, .endName = u8"沙漠_42", .endX = 373, .endY = 326},
        {.x = 30, .y = 140, .endName = u8"沙漠_42", .endX = 372, .endY = 327},
        {.x = 29, .y = 141, .endName = u8"沙漠_42", .endX = 371, .endY = 328},
        {.x = 169, .y = 56, .endName = u8"诺玛遗址1层_D1601", .endX = 313, .endY = 42},
        {.x = 169, .y = 57, .endName = u8"诺玛遗址1层_D1601", .endX = 313, .endY = 42},
        {.x = 189, .y = 112, .endName = u8"诺玛遗址1层_D1601", .endX = 353, .endY = 254},
        {.x = 190, .y = 111, .endName = u8"诺玛遗址1层_D1601", .endX = 353, .endY = 254},
        {.x = 116, .y = 71, .endName = u8"诺玛遗址1层_D1601", .endX = 38, .endY = 148},
        {.x = 115, .y = 72, .endName = u8"诺玛遗址1层_D1601", .endX = 38, .endY = 148},
        {.x = 139, .y = 138, .endName = u8"诺玛遗址1层_D1601", .endX = 90, .endY = 346},
        {.x = 140, .y = 139, .endName = u8"诺玛遗址1层_D1601", .endX = 90, .endY = 346},
    }
},

{   .name = u8"沙漠_42",
    .miniMapID = 0X19001021,
    .mapSwitchList
    {
        {.x = 376, .y = 324, .endName = u8"诺玛村庄_41", .endX = 34, .endY = 137},
        {.x = 375, .y = 325, .endName = u8"诺玛村庄_41", .endX = 33, .endY = 138},
        {.x = 374, .y = 326, .endName = u8"诺玛村庄_41", .endX = 32, .endY = 139},
        {.x = 373, .y = 327, .endName = u8"诺玛村庄_41", .endX = 31, .endY = 140},
        {.x = 372, .y = 328, .endName = u8"诺玛村庄_41", .endX = 30, .endY = 141},
        {.x = 34, .y = 189, .endName = u8"沙漠_43", .endX = 332, .endY = 65},
        {.x = 35, .y = 190, .endName = u8"沙漠_43", .endX = 333, .endY = 66},
        {.x = 36, .y = 191, .endName = u8"沙漠_43", .endX = 334, .endY = 67},
        {.x = 37, .y = 192, .endName = u8"沙漠_43", .endX = 335, .endY = 68},
        {.x = 38, .y = 193, .endName = u8"沙漠_43", .endX = 336, .endY = 69},
    }
},

{   .name = u8"沙漠_43",
    .miniMapID = 0X19001022,
    .mapSwitchList
    {
        {.x = 333, .y = 64, .endName = u8"沙漠_42", .endX = 35, .endY = 188},
        {.x = 334, .y = 65, .endName = u8"沙漠_42", .endX = 36, .endY = 189},
        {.x = 335, .y = 66, .endName = u8"沙漠_42", .endX = 37, .endY = 190},
        {.x = 336, .y = 67, .endName = u8"沙漠_42", .endX = 38, .endY = 191},
        {.x = 337, .y = 68, .endName = u8"沙漠_42", .endX = 39, .endY = 192},
        {.x = 41, .y = 204, .endName = u8"沙漠_44", .endX = 333, .endY = 333},
        {.x = 42, .y = 205, .endName = u8"沙漠_44", .endX = 334, .endY = 334},
        {.x = 43, .y = 206, .endName = u8"沙漠_44", .endX = 335, .endY = 335},
        {.x = 44, .y = 207, .endName = u8"沙漠_44", .endX = 336, .endY = 336},
        {.x = 45, .y = 208, .endName = u8"沙漠_44", .endX = 337, .endY = 337},
        {.x = 46, .y = 209, .endName = u8"沙漠_44", .endX = 337, .endY = 338},
    }
},

{   .name = u8"沙漠_44",
    .miniMapID = 0X19001023,
    .mapSwitchList
    {
        {.x = 334, .y = 333, .endName = u8"沙漠_43", .endX = 42, .endY = 204},
        {.x = 335, .y = 334, .endName = u8"沙漠_43", .endX = 42, .endY = 204},
        {.x = 336, .y = 335, .endName = u8"沙漠_43", .endX = 43, .endY = 205},
        {.x = 337, .y = 336, .endName = u8"沙漠_43", .endX = 44, .endY = 206},
        {.x = 338, .y = 337, .endName = u8"沙漠_43", .endX = 45, .endY = 207},
        {.x = 338, .y = 338, .endName = u8"沙漠_43", .endX = 46, .endY = 208},
        {.x = 376, .y = 112, .endName = u8"绿洲_4", .endX = 74, .endY = 461},
        {.x = 375, .y = 113, .endName = u8"绿洲_4", .endX = 73, .endY = 462},
        {.x = 374, .y = 114, .endName = u8"绿洲_4", .endX = 72, .endY = 463},
        {.x = 373, .y = 115, .endName = u8"绿洲_4", .endX = 71, .endY = 464},
        {.x = 372, .y = 116, .endName = u8"绿洲_4", .endX = 70, .endY = 465},
        {.x = 371, .y = 117, .endName = u8"绿洲_4", .endX = 69, .endY = 466},
    }
},

{   .name = u8"武器店_4_001",
    .mapSwitchList
    {
        {.x = 14, .y = 14, .endName = u8"绿洲_4", .endX = 450, .endY = 74},
    }
},

{   .name = u8"民家_4_002",
    .mapSwitchList
    {
        {.x = 7, .y = 16, .endName = u8"绿洲_4", .endX = 447, .endY = 94},
        {.x = 13, .y = 18, .endName = u8"绿洲_4", .endX = 452, .endY = 96},
    }
},

{   .name = u8"中药商_4_003",
    .mapSwitchList
    {
        {.x = 14, .y = 14, .endName = u8"绿洲_4", .endX = 434, .endY = 73},
    }
},

{   .name = u8"布匹店_4_004",
    .mapSwitchList
    {
        {.x = 7, .y = 14, .endName = u8"绿洲_4", .endX = 461, .endY = 90},
    }
},

{   .name = u8"占卜屋_4_005",
    .mapSwitchList
    {
        {.x = 10, .y = 27, .endName = u8"绿洲_4", .endX = 475, .endY = 58},
    }
},

{   .name = u8"沙漠土城_5",
    .miniMapID = 0X19001007,
    .mapSwitchList
    {
        {.x = 239, .y = 164, .endName = u8"贵族屋_5_0011", .endX = 28, .endY = 43},
        {.x = 243, .y = 167, .endName = u8"贵族屋_5_0011", .endX = 34, .endY = 47},
        {.x = 236, .y = 161, .endName = u8"贵族屋_5_0011", .endX = 24, .endY = 37},
        {.x = 240, .y = 194, .endName = u8"贵族屋_5_0012", .endX = 18, .endY = 23},
        {.x = 206, .y = 169, .endName = u8"贵族屋_5_0013", .endX = 17, .endY = 47},
        {.x = 190, .y = 249, .endName = u8"武器商_5_002", .endX = 13, .endY = 17},
        {.x = 193, .y = 231, .endName = u8"药房_5_003", .endX = 6, .endY = 21},
        {.x = 197, .y = 232, .endName = u8"药房_5_003", .endX = 16, .endY = 24},
        {.x = 179, .y = 278, .endName = u8"服饰店_5_004", .endX = 9, .endY = 21},
        {.x = 203, .y = 241, .endName = u8"饰品店_5_005", .endX = 6, .endY = 11},
        {.x = 159, .y = 267, .endName = u8"仓库_5_006", .endX = 8, .endY = 23},
        {.x = 170, .y = 266, .endName = u8"仓库_5_006", .endX = 19, .endY = 23},
        {.x = 112, .y = 384, .endName = u8"绿洲_4", .endX = 519, .endY = 637},
        {.x = 111, .y = 385, .endName = u8"绿洲_4", .endX = 518, .endY = 638},
        {.x = 110, .y = 386, .endName = u8"绿洲_4", .endX = 517, .endY = 639},
        {.x = 109, .y = 387, .endName = u8"绿洲_4", .endX = 516, .endY = 640},
        {.x = 54, .y = 366, .endName = u8"绿洲_4", .endX = 457, .endY = 649},
        {.x = 55, .y = 367, .endName = u8"绿洲_4", .endX = 458, .endY = 650},
        {.x = 56, .y = 368, .endName = u8"绿洲_4", .endX = 459, .endY = 651},
        {.x = 17, .y = 208, .endName = u8"绿洲_4", .endX = 421, .endY = 548},
        {.x = 18, .y = 209, .endName = u8"绿洲_4", .endX = 422, .endY = 549},
        {.x = 19, .y = 210, .endName = u8"绿洲_4", .endX = 423, .endY = 550},
        {.x = 50, .y = 118, .endName = u8"绿洲_4", .endX = 446, .endY = 479},
        {.x = 51, .y = 117, .endName = u8"绿洲_4", .endX = 447, .endY = 478},
        {.x = 52, .y = 116, .endName = u8"绿洲_4", .endX = 448, .endY = 477},
        {.x = 77, .y = 12, .endName = u8"绿洲_4", .endX = 460, .endY = 421},
        {.x = 78, .y = 13, .endName = u8"绿洲_4", .endX = 461, .endY = 422},
        {.x = 79, .y = 14, .endName = u8"绿洲_4", .endX = 462, .endY = 423},
        {.x = 80, .y = 15, .endName = u8"绿洲_4", .endX = 462, .endY = 424},
        {.x = 174, .y = 30, .endName = u8"绿洲_4", .endX = 562, .endY = 392},
        {.x = 173, .y = 31, .endName = u8"绿洲_4", .endX = 561, .endY = 392},
        {.x = 172, .y = 32, .endName = u8"绿洲_4", .endX = 560, .endY = 393},
    }
},

{   .name = u8"贵族屋_5_0011",
    .mapSwitchList
    {
        {.x = 27, .y = 44, .endName = u8"沙漠土城_5", .endX = 238, .endY = 165},
        {.x = 33, .y = 48, .endName = u8"沙漠土城_5", .endX = 242, .endY = 168},
        {.x = 23, .y = 38, .endName = u8"沙漠土城_5", .endX = 235, .endY = 161},
    }
},

{   .name = u8"贵族屋_5_0012",
    .mapSwitchList
    {
        {.x = 17, .y = 24, .endName = u8"沙漠土城_5", .endX = 239, .endY = 195},
    }
},

{   .name = u8"贵族屋_5_0013",
    .mapSwitchList
    {
        {.x = 18, .y = 48, .endName = u8"沙漠土城_5", .endX = 207, .endY = 170},
    }
},

{   .name = u8"武器商_5_002",
    .mapSwitchList
    {
        {.x = 14, .y = 18, .endName = u8"沙漠土城_5", .endX = 191, .endY = 250},
    }
},

{   .name = u8"药房_5_003",
    .mapSwitchList
    {
        {.x = 6, .y = 22, .endName = u8"沙漠土城_5", .endX = 194, .endY = 232},
        {.x = 15, .y = 24, .endName = u8"沙漠土城_5", .endX = 196, .endY = 232},
    }
},

{   .name = u8"服饰店_5_004",
    .mapSwitchList
    {
        {.x = 10, .y = 22, .endName = u8"沙漠土城_5", .endX = 179, .endY = 279},
    }
},

{   .name = u8"饰品店_5_005",
    .mapSwitchList
    {
        {.x = 5, .y = 12, .endName = u8"沙漠土城_5", .endX = 203, .endY = 242},
    }
},

{   .name = u8"仓库_5_006",
    .mapSwitchList
    {
        {.x = 7, .y = 24, .endName = u8"沙漠土城_5", .endX = 158, .endY = 267},
        {.x = 20, .y = 24, .endName = u8"沙漠土城_5", .endX = 171, .endY = 267},
    }
},

{   .name = u8"沙漠_6",
    .miniMapID = 0X19001008,
    .mapSwitchList
    {
        {.x = 771, .y = 555, .endName = u8"沙漠_78", .endX = 41, .endY = 106},
        {.x = 770, .y = 556, .endName = u8"沙漠_78", .endX = 40, .endY = 107},
        {.x = 769, .y = 557, .endName = u8"沙漠_78", .endX = 39, .endY = 108},
        {.x = 768, .y = 558, .endName = u8"沙漠_78", .endX = 38, .endY = 109},
        {.x = 767, .y = 559, .endName = u8"沙漠_78", .endX = 37, .endY = 110},
        {.x = 179, .y = 79, .endName = u8"绿洲_4", .endX = 181, .endY = 777},
        {.x = 180, .y = 80, .endName = u8"绿洲_4", .endX = 182, .endY = 778},
        {.x = 181, .y = 81, .endName = u8"绿洲_4", .endX = 183, .endY = 779},
        {.x = 284, .y = 79, .endName = u8"绿洲_4", .endX = 282, .endY = 777},
        {.x = 283, .y = 80, .endName = u8"绿洲_4", .endX = 281, .endY = 778},
        {.x = 282, .y = 81, .endName = u8"绿洲_4", .endX = 280, .endY = 779},
        {.x = 281, .y = 82, .endName = u8"绿洲_4", .endX = 279, .endY = 780},
        {.x = 385, .y = 69, .endName = u8"绿洲_4", .endX = 383, .endY = 767},
        {.x = 384, .y = 70, .endName = u8"绿洲_4", .endX = 382, .endY = 768},
        {.x = 383, .y = 71, .endName = u8"绿洲_4", .endX = 381, .endY = 769},
        {.x = 472, .y = 66, .endName = u8"绿洲_4", .endX = 470, .endY = 764},
        {.x = 471, .y = 67, .endName = u8"绿洲_4", .endX = 469, .endY = 765},
        {.x = 470, .y = 68, .endName = u8"绿洲_4", .endX = 468, .endY = 766},
        {.x = 291, .y = 719, .endName = u8"南部蚂蚁洞穴1层1_D8002", .endX = 179, .endY = 188},
    }
},

{   .name = u8"沙漠_71",
    .miniMapID = 0X19001009,
    .mapSwitchList
    {
        {.x = 380, .y = 36, .endName = u8"边境城市_01", .endX = 87, .endY = 405},
        {.x = 381, .y = 37, .endName = u8"边境城市_01", .endX = 88, .endY = 406},
        {.x = 382, .y = 38, .endName = u8"边境城市_01", .endX = 89, .endY = 407},
        {.x = 383, .y = 39, .endName = u8"边境城市_01", .endX = 90, .endY = 408},
        {.x = 384, .y = 40, .endName = u8"边境城市_01", .endX = 91, .endY = 409},
        {.x = 385, .y = 41, .endName = u8"边境城市_01", .endX = 92, .endY = 410},
        {.x = 386, .y = 42, .endName = u8"边境城市_01", .endX = 93, .endY = 411},
        {.x = 14, .y = 90, .endName = u8"沙漠_72", .endX = 384, .endY = 39},
        {.x = 13, .y = 91, .endName = u8"沙漠_72", .endX = 383, .endY = 40},
        {.x = 12, .y = 92, .endName = u8"沙漠_72", .endX = 382, .endY = 41},
        {.x = 11, .y = 93, .endName = u8"沙漠_72", .endX = 381, .endY = 42},
        {.x = 10, .y = 94, .endName = u8"沙漠_72", .endX = 380, .endY = 43},
        {.x = 9, .y = 95, .endName = u8"沙漠_72", .endX = 379, .endY = 44},
        {.x = 8, .y = 96, .endName = u8"沙漠_72", .endX = 378, .endY = 45},
    }
},

{   .name = u8"沙漠_72",
    .miniMapID = 0X19001010,
    .mapSwitchList
    {
        {.x = 385, .y = 39, .endName = u8"沙漠_71", .endX = 15, .endY = 90},
        {.x = 384, .y = 40, .endName = u8"沙漠_71", .endX = 14, .endY = 91},
        {.x = 383, .y = 41, .endName = u8"沙漠_71", .endX = 13, .endY = 92},
        {.x = 382, .y = 42, .endName = u8"沙漠_71", .endX = 12, .endY = 93},
        {.x = 381, .y = 43, .endName = u8"沙漠_71", .endX = 11, .endY = 94},
        {.x = 380, .y = 44, .endName = u8"沙漠_71", .endX = 10, .endY = 95},
        {.x = 379, .y = 45, .endName = u8"沙漠_71", .endX = 9, .endY = 96},
        {.x = 26, .y = 56, .endName = u8"沙漠_73", .endX = 356, .endY = 138},
        {.x = 25, .y = 57, .endName = u8"沙漠_73", .endX = 355, .endY = 139},
        {.x = 24, .y = 58, .endName = u8"沙漠_73", .endX = 354, .endY = 140},
        {.x = 23, .y = 59, .endName = u8"沙漠_73", .endX = 353, .endY = 141},
        {.x = 22, .y = 60, .endName = u8"沙漠_73", .endX = 352, .endY = 142},
        {.x = 21, .y = 61, .endName = u8"沙漠_73", .endX = 351, .endY = 143},
        {.x = 20, .y = 62, .endName = u8"沙漠_73", .endX = 350, .endY = 144},
    }
},

{   .name = u8"沙漠_73",
    .miniMapID = 0X19001011,
    .mapSwitchList
    {
        {.x = 357, .y = 138, .endName = u8"沙漠_72", .endX = 28, .endY = 56},
        {.x = 356, .y = 139, .endName = u8"沙漠_72", .endX = 27, .endY = 57},
        {.x = 355, .y = 140, .endName = u8"沙漠_72", .endX = 26, .endY = 58},
        {.x = 354, .y = 141, .endName = u8"沙漠_72", .endX = 25, .endY = 59},
        {.x = 353, .y = 142, .endName = u8"沙漠_72", .endX = 24, .endY = 60},
        {.x = 352, .y = 143, .endName = u8"沙漠_72", .endX = 23, .endY = 61},
        {.x = 351, .y = 144, .endName = u8"沙漠_72", .endX = 22, .endY = 62},
        {.x = 350, .y = 145, .endName = u8"沙漠_72", .endX = 21, .endY = 63},
        {.x = 40, .y = 106, .endName = u8"盟重县_74", .endX = 583, .endY = 291},
        {.x = 39, .y = 107, .endName = u8"盟重县_74", .endX = 582, .endY = 292},
        {.x = 38, .y = 108, .endName = u8"盟重县_74", .endX = 581, .endY = 293},
        {.x = 37, .y = 109, .endName = u8"盟重县_74", .endX = 580, .endY = 294},
        {.x = 36, .y = 110, .endName = u8"盟重县_74", .endX = 579, .endY = 295},
    }
},

{   .name = u8"盟重县_74",
    .miniMapID = 0X19001012,
    .mapSwitchList
    {
        {.x = 585, .y = 290, .endName = u8"沙漠_73", .endX = 41, .endY = 106},
        {.x = 584, .y = 291, .endName = u8"沙漠_73", .endX = 40, .endY = 107},
        {.x = 583, .y = 292, .endName = u8"沙漠_73", .endX = 39, .endY = 108},
        {.x = 582, .y = 293, .endName = u8"沙漠_73", .endX = 38, .endY = 109},
        {.x = 581, .y = 294, .endName = u8"沙漠_73", .endX = 37, .endY = 110},
        {.x = 580, .y = 295, .endName = u8"沙漠_73", .endX = 36, .endY = 111},
        {.x = 579, .y = 296, .endName = u8"沙漠_73", .endX = 37, .endY = 111},
        {.x = 578, .y = 297, .endName = u8"沙漠_73", .endX = 37, .endY = 112},
        {.x = 26, .y = 306, .endName = u8"石阁庙_75", .endX = 384, .endY = 214},
        {.x = 25, .y = 307, .endName = u8"石阁庙_75", .endX = 383, .endY = 215},
        {.x = 24, .y = 308, .endName = u8"石阁庙_75", .endX = 382, .endY = 216},
        {.x = 23, .y = 309, .endName = u8"石阁庙_75", .endX = 381, .endY = 217},
        {.x = 22, .y = 310, .endName = u8"石阁庙_75", .endX = 380, .endY = 218},
        {.x = 21, .y = 311, .endName = u8"石阁庙_75", .endX = 379, .endY = 219},
        {.x = 20, .y = 312, .endName = u8"石阁庙_75", .endX = 378, .endY = 220},
        {.x = 334, .y = 72, .endName = u8"绝命谷1层南部_D60011", .endX = 207, .endY = 237},
        {.x = 78, .y = 227, .endName = u8"万年谷_D6011", .endX = 159, .endY = 168},
        {.x = 132, .y = 503, .endName = u8"虫峡谷1层_D6021", .endX = 42, .endY = 167},
    }
},

{   .name = u8"石阁庙_75",
    .miniMapID = 0X19001013,
    .mapSwitchList
    {
        {.x = 385, .y = 214, .endName = u8"盟重县_74", .endX = 27, .endY = 306},
        {.x = 384, .y = 215, .endName = u8"盟重县_74", .endX = 26, .endY = 307},
        {.x = 383, .y = 216, .endName = u8"盟重县_74", .endX = 25, .endY = 308},
        {.x = 382, .y = 217, .endName = u8"盟重县_74", .endX = 24, .endY = 309},
        {.x = 381, .y = 218, .endName = u8"盟重县_74", .endX = 23, .endY = 310},
        {.x = 380, .y = 219, .endName = u8"盟重县_74", .endX = 22, .endY = 311},
        {.x = 379, .y = 220, .endName = u8"盟重县_74", .endX = 21, .endY = 312},
        {.x = 378, .y = 221, .endName = u8"盟重县_74", .endX = 21, .endY = 313},
        {.x = 26, .y = 206, .endName = u8"沙漠_76", .endX = 356, .endY = 138},
        {.x = 25, .y = 207, .endName = u8"沙漠_76", .endX = 355, .endY = 139},
        {.x = 24, .y = 208, .endName = u8"沙漠_76", .endX = 354, .endY = 140},
        {.x = 23, .y = 209, .endName = u8"沙漠_76", .endX = 353, .endY = 141},
        {.x = 22, .y = 210, .endName = u8"沙漠_76", .endX = 352, .endY = 142},
        {.x = 21, .y = 211, .endName = u8"沙漠_76", .endX = 351, .endY = 143},
        {.x = 20, .y = 212, .endName = u8"沙漠_76", .endX = 350, .endY = 144},
        {.x = 202, .y = 61, .endName = u8"石阁入口_D7101", .endX = 27, .endY = 22},
    }
},

{   .name = u8"沙漠_76",
    .miniMapID = 0X19001014,
    .mapSwitchList
    {
        {.x = 357, .y = 138, .endName = u8"石阁庙_75", .endX = 27, .endY = 206},
        {.x = 356, .y = 139, .endName = u8"石阁庙_75", .endX = 26, .endY = 207},
        {.x = 355, .y = 140, .endName = u8"石阁庙_75", .endX = 25, .endY = 208},
        {.x = 354, .y = 141, .endName = u8"石阁庙_75", .endX = 24, .endY = 209},
        {.x = 353, .y = 142, .endName = u8"石阁庙_75", .endX = 23, .endY = 210},
        {.x = 352, .y = 143, .endName = u8"石阁庙_75", .endX = 22, .endY = 211},
        {.x = 351, .y = 144, .endName = u8"石阁庙_75", .endX = 21, .endY = 212},
        {.x = 350, .y = 145, .endName = u8"石阁庙_75", .endX = 21, .endY = 213},
        {.x = 40, .y = 106, .endName = u8"沙漠_77", .endX = 355, .endY = 139},
        {.x = 39, .y = 107, .endName = u8"沙漠_77", .endX = 354, .endY = 140},
        {.x = 38, .y = 108, .endName = u8"沙漠_77", .endX = 353, .endY = 141},
        {.x = 37, .y = 109, .endName = u8"沙漠_77", .endX = 352, .endY = 142},
        {.x = 36, .y = 110, .endName = u8"沙漠_77", .endX = 351, .endY = 143},
    }
},

{   .name = u8"沙漠_77",
    .miniMapID = 0X19001015,
    .mapSwitchList
    {
        {.x = 357, .y = 138, .endName = u8"沙漠_76", .endX = 41, .endY = 106},
        {.x = 356, .y = 139, .endName = u8"沙漠_76", .endX = 40, .endY = 107},
        {.x = 355, .y = 140, .endName = u8"沙漠_76", .endX = 39, .endY = 108},
        {.x = 354, .y = 141, .endName = u8"沙漠_76", .endX = 38, .endY = 109},
        {.x = 353, .y = 142, .endName = u8"沙漠_76", .endX = 37, .endY = 110},
        {.x = 352, .y = 143, .endName = u8"沙漠_76", .endX = 36, .endY = 111},
        {.x = 351, .y = 144, .endName = u8"沙漠_76", .endX = 37, .endY = 111},
        {.x = 350, .y = 145, .endName = u8"沙漠_76", .endX = 36, .endY = 112},
        {.x = 40, .y = 106, .endName = u8"沙漠_78", .endX = 355, .endY = 139},
        {.x = 39, .y = 107, .endName = u8"沙漠_78", .endX = 354, .endY = 140},
        {.x = 38, .y = 108, .endName = u8"沙漠_78", .endX = 353, .endY = 141},
        {.x = 37, .y = 109, .endName = u8"沙漠_78", .endX = 352, .endY = 142},
        {.x = 36, .y = 110, .endName = u8"沙漠_78", .endX = 351, .endY = 143},
    }
},

{   .name = u8"沙漠_78",
    .miniMapID = 0X19001016,
    .mapSwitchList
    {
        {.x = 357, .y = 138, .endName = u8"沙漠_77", .endX = 41, .endY = 106},
        {.x = 356, .y = 139, .endName = u8"沙漠_77", .endX = 40, .endY = 107},
        {.x = 355, .y = 140, .endName = u8"沙漠_77", .endX = 39, .endY = 108},
        {.x = 354, .y = 141, .endName = u8"沙漠_77", .endX = 38, .endY = 109},
        {.x = 353, .y = 142, .endName = u8"沙漠_77", .endX = 37, .endY = 110},
        {.x = 352, .y = 143, .endName = u8"沙漠_77", .endX = 36, .endY = 111},
        {.x = 351, .y = 144, .endName = u8"沙漠_77", .endX = 37, .endY = 111},
        {.x = 350, .y = 145, .endName = u8"沙漠_77", .endX = 36, .endY = 112},
        {.x = 40, .y = 106, .endName = u8"沙漠_6", .endX = 770, .endY = 555},
        {.x = 39, .y = 107, .endName = u8"沙漠_6", .endX = 769, .endY = 556},
        {.x = 38, .y = 108, .endName = u8"沙漠_6", .endX = 768, .endY = 557},
        {.x = 37, .y = 109, .endName = u8"沙漠_6", .endX = 767, .endY = 558},
        {.x = 36, .y = 110, .endName = u8"沙漠_6", .endX = 766, .endY = 559},
    }
},

{   .name = u8"潘夜岛_8",
    .miniMapID = 0X19001018,
    .mapSwitchList
    {
        {.x = 692, .y = 358, .endName = u8"潘夜神殿1层_D1101", .endX = 135, .endY = 180},
        {.x = 416, .y = 553, .endName = u8"潘夜石窟1层_D1211", .endX = 128, .endY = 172},
    }
},

{   .name = u8"流放岛_81",
    .miniMapID = 0X19001019,
    .mapSwitchList
    {
        {.x = 156, .y = 135, .endName = u8"罪孽洞穴1层_D1201", .endX = 19, .endY = 147},
    }
},

{   .name = u8"失乐园_9",
    .miniMapID = 0X19001029,
    .mapSwitchList
    {
        {.x = 747, .y = 35, .endName = u8"道馆_1", .endX = 19, .endY = 563},
        {.x = 748, .y = 36, .endName = u8"道馆_1", .endX = 20, .endY = 564},
        {.x = 749, .y = 37, .endName = u8"道馆_1", .endX = 21, .endY = 565},
        {.x = 750, .y = 38, .endName = u8"道馆_1", .endX = 22, .endY = 566},
        {.x = 751, .y = 39, .endName = u8"道馆_1", .endX = 23, .endY = 567},
        {.x = 732, .y = 674, .endName = u8"南部蚂蚁洞穴1层1_D8002", .endX = 40, .endY = 175},
        {.x = 733, .y = 674, .endName = u8"南部蚂蚁洞穴1层1_D8002", .endX = 40, .endY = 175},
        {.x = 208, .y = 91, .endName = u8"黑度宫1层_D1510", .endX = 14, .endY = 45},
        {.x = 208, .y = 92, .endName = u8"黑度宫1层_D1510", .endX = 14, .endY = 45},
        {.x = 388, .y = 305, .endName = u8"真天宫地下1层_D1500", .endX = 172, .endY = 224},
        {.x = 388, .y = 306, .endName = u8"真天宫地下1层_D1500", .endX = 172, .endY = 224},
        {.x = 398, .y = 308, .endName = u8"真天宫地下1层_D1500", .endX = 195, .endY = 224},
        {.x = 399, .y = 308, .endName = u8"真天宫地下1层_D1500", .endX = 195, .endY = 224},
    }
},

{   .name = u8"NPC休息室_B103_001",
},

{   .name = u8"矿石空间_B115_001",
},

{   .name = u8"GM活动室_B132_001",
},

{   .name = u8"暗黑封印_B139_001",
},

{   .name = u8"半兽洞穴1层_D001",
    .miniMapID = 0X19000000,
    .mapSwitchList
    {
        {.x = 149, .y = 364, .endName = u8"比奇县_0", .endX = 64, .endY = 175},
        {.x = 150, .y = 364, .endName = u8"比奇县_0", .endX = 64, .endY = 175},
        {.x = 148, .y = 366, .endName = u8"比奇县_0", .endX = 64, .endY = 175},
        {.x = 30, .y = 328, .endName = u8"半兽洞穴2层_D002", .endX = 34, .endY = 323},
        {.x = 381, .y = 23, .endName = u8"半兽洞穴2层_D002", .endX = 324, .endY = 16},
        {.x = 350, .y = 356, .endName = u8"半兽洞穴2层_D002", .endX = 367, .endY = 351},
        {.x = 303, .y = 65, .endName = u8"半兽勇士洞_D001_001", .endX = 8, .endY = 10},
    }
},

{   .name = u8"半兽勇士洞_D001_001",
    .mapSwitchList
    {
        {.x = 7, .y = 9, .endName = u8"半兽洞穴1层_D001", .endX = 302, .endY = 66},
    }
},

{   .name = u8"半兽洞穴2层_D002",
    .miniMapID = 0X19000001,
    .mapSwitchList
    {
        {.x = 34, .y = 322, .endName = u8"半兽洞穴1层_D001", .endX = 30, .endY = 329},
        {.x = 324, .y = 15, .endName = u8"半兽洞穴1层_D001", .endX = 381, .endY = 24},
        {.x = 367, .y = 350, .endName = u8"半兽洞穴1层_D001", .endX = 350, .endY = 357},
        {.x = 191, .y = 231, .endName = u8"奸商_DM001", .endX = 5, .endY = 10},
        {.x = 225, .y = 175, .endName = u8"王陵_DM002", .endX = 8, .endY = 28},
        {.x = 117, .y = 95, .endName = u8"半兽洞穴3层_D003", .endX = 106, .endY = 83},
        {.x = 255, .y = 281, .endName = u8"骷髅精灵洞_D002_001", .endX = 8, .endY = 10},
    }
},

{   .name = u8"骷髅精灵洞_D002_001",
    .mapSwitchList
    {
        {.x = 7, .y = 9, .endName = u8"半兽洞穴2层_D002", .endX = 254, .endY = 282},
    }
},

{   .name = u8"半兽洞穴3层_D003",
    .miniMapID = 0X19000002,
    .mapSwitchList
    {
        {.x = 106, .y = 82, .endName = u8"半兽洞穴2层_D002", .endX = 117, .endY = 96},
        {.x = 78, .y = 229, .endName = u8"半兽天然洞穴_E001", .endX = 9, .endY = 14},
        {.x = 290, .y = 293, .endName = u8"连接通路_E402", .endX = 13, .endY = 73},
    }
},

{   .name = u8"天然洞穴1层_D011",
    .miniMapID = 0X19000003,
    .mapSwitchList
    {
        {.x = 155, .y = 368, .endName = u8"银杏山谷_02", .endX = 481, .endY = 324},
        {.x = 155, .y = 367, .endName = u8"银杏山谷_02", .endX = 481, .endY = 324},
        {.x = 330, .y = 115, .endName = u8"天然洞穴2层_D012", .endX = 337, .endY = 105},
        {.x = 127, .y = 201, .endName = u8"天然洞穴2层_D012", .endX = 77, .endY = 198},
    }
},

{   .name = u8"天然洞穴2层_D012",
    .miniMapID = 0X19000004,
    .mapSwitchList
    {
        {.x = 377, .y = 64, .endName = u8"半兽天然洞穴_E002", .endX = 35, .endY = 82},
        {.x = 337, .y = 104, .endName = u8"天然洞穴1层_D011", .endX = 330, .endY = 116},
        {.x = 77, .y = 197, .endName = u8"天然洞穴1层_D011", .endX = 127, .endY = 202},
        {.x = 189, .y = 144, .endName = u8"洞穴奸商_DM011", .endX = 5, .endY = 10},
        {.x = 229, .y = 355, .endName = u8"天然洞穴2层_D012_001", .endX = 9, .endY = 8},
    }
},

{   .name = u8"天然洞穴2层_D012_001",
    .mapSwitchList
    {
        {.x = 8, .y = 7, .endName = u8"天然洞穴2层_D012", .endX = 228, .endY = 356},
    }
},

{   .name = u8"沃玛神殿入口_D021",
    .miniMapID = 0X19000190,
    .mapSwitchList
    {
        {.x = 77, .y = 75, .endName = u8"道馆_1", .endX = 55, .endY = 371},
        {.x = 77, .y = 76, .endName = u8"道馆_1", .endX = 55, .endY = 370},
        {.x = 26, .y = 27, .endName = u8"沃玛神殿1层_D022", .endX = 338, .endY = 356},
        {.x = 26, .y = 26, .endName = u8"沃玛神殿1层_D022", .endX = 339, .endY = 355},
        {.x = 47, .y = 37, .endName = u8"沃玛神殿1层_D032", .endX = 338, .endY = 356},
        {.x = 34, .y = 50, .endName = u8"沃玛神殿1层_D042", .endX = 338, .endY = 356},
        {.x = 26, .y = 27, .endName = u8"沃玛神殿1层_D052", .endX = 338, .endY = 356},
        {.x = 26, .y = 26, .endName = u8"沃玛神殿1层_D052", .endX = 339, .endY = 355},
    }
},

{   .name = u8"沃玛神殿1层_D022",
    .miniMapID = 0X19000191,
    .mapSwitchList
    {
        {.x = 338, .y = 355, .endName = u8"沃玛神殿入口_D021", .endX = 25, .endY = 26},
        {.x = 338, .y = 354, .endName = u8"沃玛神殿入口_D021", .endX = 25, .endY = 25},
        {.x = 251, .y = 207, .endName = u8"沃玛神殿2层_D023", .endX = 198, .endY = 195},
        {.x = 251, .y = 206, .endName = u8"沃玛神殿2层_D023", .endX = 199, .endY = 194},
    }
},

{   .name = u8"沃玛神殿1层_D022_001",
    .mapSwitchList
    {
        {.x = 63, .y = 74, .endName = u8"沃玛神殿1层_D022", .endX = 145, .endY = 112},
        {.x = 64, .y = 74, .endName = u8"沃玛神殿1层_D022", .endX = 145, .endY = 112},
        {.x = 64, .y = 73, .endName = u8"沃玛神殿1层_D022", .endX = 145, .endY = 112},
        {.x = 65, .y = 73, .endName = u8"沃玛神殿1层_D022", .endX = 145, .endY = 112},
        {.x = 65, .y = 72, .endName = u8"沃玛神殿1层_D022", .endX = 145, .endY = 112},
        {.x = 66, .y = 72, .endName = u8"沃玛神殿1层_D022", .endX = 145, .endY = 112},
        {.x = 66, .y = 71, .endName = u8"沃玛神殿1层_D022", .endX = 145, .endY = 112},
    }
},

{   .name = u8"沃玛神殿2层_D023",
    .miniMapID = 0X19000195,
    .mapSwitchList
    {
        {.x = 198, .y = 194, .endName = u8"沃玛神殿1层_D022", .endX = 250, .endY = 206},
        {.x = 198, .y = 193, .endName = u8"沃玛神殿1层_D022", .endX = 250, .endY = 205},
        {.x = 52, .y = 366, .endName = u8"沃玛神殿_D024", .endX = 16, .endY = 19},
        {.x = 67, .y = 48, .endName = u8"沃玛神殿师徒关_D023_001", .endX = 13, .endY = 18},
        {.x = 67, .y = 47, .endName = u8"沃玛神殿师徒关_D023_001", .endX = 13, .endY = 18},
        {.x = 371, .y = 366, .endName = u8"困魔咒空间_1_015", .endX = 10, .endY = 17},
        {.x = 371, .y = 367, .endName = u8"困魔咒空间_1_015", .endX = 10, .endY = 17},
        {.x = 372, .y = 366, .endName = u8"困魔咒空间_1_015", .endX = 10, .endY = 17},
    }
},

{   .name = u8"沃玛神殿师徒关_D023_001",
    .mapSwitchList
    {
        {.x = 12, .y = 17, .endName = u8"沃玛神殿2层_D023", .endX = 65, .endY = 47},
    }
},

{   .name = u8"沃玛神殿师徒关_D023_002",
    .mapSwitchList
    {
        {.x = 12, .y = 17, .endName = u8"沃玛神殿2层_D023", .endX = 65, .endY = 47},
    }
},

{   .name = u8"沃玛神殿_D024",
    .miniMapID = 0X19000199,
    .mapSwitchList
    {
        {.x = 16, .y = 18, .endName = u8"沃玛神殿2层_D023", .endX = 51, .endY = 365},
        {.x = 46, .y = 28, .endName = u8"沃玛神殿2层_D033", .endX = 51, .endY = 365},
        {.x = 28, .y = 46, .endName = u8"沃玛神殿2层_D043", .endX = 51, .endY = 365},
        {.x = 16, .y = 18, .endName = u8"沃玛神殿2层_D053", .endX = 51, .endY = 365},
    }
},

{   .name = u8"沃玛神殿1层_D032",
    .miniMapID = 0X19000192,
    .mapSwitchList
    {
        {.x = 338, .y = 355, .endName = u8"沃玛神殿入口_D021", .endX = 46, .endY = 36},
        {.x = 338, .y = 354, .endName = u8"沃玛神殿入口_D021", .endX = 46, .endY = 36},
        {.x = 251, .y = 207, .endName = u8"沃玛神殿2层_D033", .endX = 198, .endY = 195},
        {.x = 251, .y = 206, .endName = u8"沃玛神殿2层_D033", .endX = 199, .endY = 194},
    }
},

{   .name = u8"沃玛神殿2层_D033",
    .miniMapID = 0X19000196,
    .mapSwitchList
    {
        {.x = 198, .y = 194, .endName = u8"沃玛神殿1层_D032", .endX = 250, .endY = 206},
        {.x = 198, .y = 193, .endName = u8"沃玛神殿1层_D032", .endX = 250, .endY = 205},
        {.x = 52, .y = 366, .endName = u8"沃玛神殿_D024", .endX = 47, .endY = 29},
    }
},

{   .name = u8"沃玛神殿1层_D042",
    .miniMapID = 0X19000193,
    .mapSwitchList
    {
        {.x = 338, .y = 355, .endName = u8"沃玛神殿入口_D021", .endX = 33, .endY = 49},
        {.x = 338, .y = 354, .endName = u8"沃玛神殿入口_D021", .endX = 33, .endY = 49},
        {.x = 251, .y = 207, .endName = u8"沃玛神殿2层_D043", .endX = 198, .endY = 195},
        {.x = 251, .y = 206, .endName = u8"沃玛神殿2层_D043", .endX = 199, .endY = 194},
    }
},

{   .name = u8"沃玛神殿2层_D043",
    .miniMapID = 0X19000197,
    .mapSwitchList
    {
        {.x = 198, .y = 194, .endName = u8"沃玛神殿1层_D042", .endX = 250, .endY = 206},
        {.x = 198, .y = 193, .endName = u8"沃玛神殿1层_D042", .endX = 250, .endY = 205},
        {.x = 52, .y = 366, .endName = u8"沃玛神殿_D024", .endX = 29, .endY = 47},
    }
},

{   .name = u8"沃玛神殿1层_D052",
    .miniMapID = 0X19000194,
    .mapSwitchList
    {
        {.x = 338, .y = 355, .endName = u8"沃玛神殿入口_D021", .endX = 25, .endY = 26},
        {.x = 338, .y = 354, .endName = u8"沃玛神殿入口_D021", .endX = 25, .endY = 25},
        {.x = 251, .y = 207, .endName = u8"沃玛神殿2层_D053", .endX = 198, .endY = 195},
        {.x = 251, .y = 206, .endName = u8"沃玛神殿2层_D053", .endX = 199, .endY = 194},
    }
},

{   .name = u8"沃玛神殿2层_D053",
    .miniMapID = 0X19000198,
    .mapSwitchList
    {
        {.x = 198, .y = 194, .endName = u8"沃玛神殿1层_D052", .endX = 250, .endY = 206},
        {.x = 198, .y = 193, .endName = u8"沃玛神殿1层_D052", .endX = 250, .endY = 205},
        {.x = 52, .y = 366, .endName = u8"沃玛神殿_D024", .endX = 16, .endY = 19},
    }
},

{   .name = u8"赤月山谷1层_D1001",
    .miniMapID = 0X19000100,
    .mapSwitchList
    {
        {.x = 270, .y = 385, .endName = u8"灌木林_12", .endX = 333, .endY = 53},
        {.x = 123, .y = 24, .endName = u8"赤月山谷2层_D1002", .endX = 62, .endY = 288},
    }
},

{   .name = u8"赤月山谷2层_D1002",
    .miniMapID = 0X19000101,
    .mapSwitchList
    {
        {.x = 61, .y = 289, .endName = u8"赤月山谷1层_D1001", .endX = 122, .endY = 25},
        {.x = 13, .y = 26, .endName = u8"赤月山谷3层_D10031", .endX = 289, .endY = 150},
        {.x = 289, .y = 138, .endName = u8"赤月山谷3层_D10032", .endX = 10, .endY = 155},
    }
},

{   .name = u8"赤月山谷3层_D10031",
    .miniMapID = 0X19000102,
    .mapSwitchList
    {
        {.x = 290, .y = 151, .endName = u8"赤月山谷2层_D1002", .endX = 14, .endY = 27},
    }
},

{   .name = u8"赤月山谷3层_D10032",
    .miniMapID = 0X19000103,
    .mapSwitchList
    {
        {.x = 9, .y = 156, .endName = u8"赤月山谷2层_D1002", .endX = 288, .endY = 139},
        {.x = 201, .y = 148, .endName = u8"赤月山谷4层_D1004", .endX = 171, .endY = 88},
    }
},

{   .name = u8"赤月山谷4层_D1004",
    .miniMapID = 0X19000104,
    .mapSwitchList
    {
        {.x = 170, .y = 89, .endName = u8"赤月山谷3层_D10032", .endX = 200, .endY = 149},
        {.x = 121, .y = 38, .endName = u8"赤月山谷3层_D10031", .endX = 150, .endY = 104},
        {.x = 217, .y = 133, .endName = u8"赤月山谷5层_D10052", .endX = 97, .endY = 184},
        {.x = 146, .y = 110, .endName = u8"赤月山谷5层_D10051", .endX = 48, .endY = 188},
    }
},

{   .name = u8"赤月山谷5层_D10051",
    .miniMapID = 0X19000105,
    .mapSwitchList
    {
        {.x = 47, .y = 189, .endName = u8"赤月山谷4层_D1004", .endX = 145, .endY = 111},
    }
},

{   .name = u8"赤月山谷5层_D10052",
    .miniMapID = 0X19000106,
    .mapSwitchList
    {
        {.x = 98, .y = 185, .endName = u8"赤月山谷4层_D1004", .endX = 216, .endY = 132},
    }
},

{   .name = u8"赤月山谷1层_D1011",
    .miniMapID = 0X19000110,
    .mapSwitchList
    {
        {.x = 53, .y = 287, .endName = u8"灌木林_12", .endX = 109, .endY = 32},
        {.x = 290, .y = 76, .endName = u8"赤月山谷2层_D1012", .endX = 14, .endY = 143},
    }
},

{   .name = u8"赤月山谷2层_D1012",
    .miniMapID = 0X19000111,
    .mapSwitchList
    {
        {.x = 13, .y = 144, .endName = u8"赤月山谷1层_D1011", .endX = 289, .endY = 77},
        {.x = 274, .y = 109, .endName = u8"赤月山谷3层_D10131", .endX = 286, .endY = 142},
        {.x = 134, .y = 15, .endName = u8"赤月山谷3层_D10132", .endX = 18, .endY = 82},
    }
},

{   .name = u8"赤月山谷3层_D10131",
    .miniMapID = 0X19000112,
    .mapSwitchList
    {
        {.x = 287, .y = 141, .endName = u8"赤月山谷2层_D1012", .endX = 275, .endY = 108},
        {.x = 11, .y = 99, .endName = u8"赤月山谷4层_D1014", .endX = 198, .endY = 290},
    }
},

{   .name = u8"赤月山谷3层_D10132",
    .miniMapID = 0X19000113,
    .mapSwitchList
    {
        {.x = 17, .y = 83, .endName = u8"赤月山谷2层_D1012", .endX = 133, .endY = 16},
        {.x = 234, .y = 25, .endName = u8"赤月山谷4层_D1014", .endX = 153, .endY = 254},
    }
},

{   .name = u8"赤月山谷4层_D1014",
    .miniMapID = 0X19000114,
    .mapSwitchList
    {
        {.x = 199, .y = 291, .endName = u8"赤月山谷3层_D10131", .endX = 12, .endY = 100},
        {.x = 152, .y = 255, .endName = u8"赤月山谷3层_D10132", .endX = 233, .endY = 26},
        {.x = 208, .y = 21, .endName = u8"赤月山谷5层_D10151", .endX = 89, .endY = 51},
        {.x = 91, .y = 12, .endName = u8"赤月山谷5层_D10152", .endX = 50, .endY = 190},
    }
},

{   .name = u8"赤月山谷5层_D10151",
    .miniMapID = 0X19000115,
    .mapSwitchList
    {
        {.x = 88, .y = 52, .endName = u8"赤月山谷4层_D1014", .endX = 207, .endY = 22},
        {.x = 152, .y = 16, .endName = u8"赤月恶魔洞穴_D10162", .endX = 12, .endY = 24},
    }
},

{   .name = u8"赤月山谷5层_D10152",
    .miniMapID = 0X19000116,
    .mapSwitchList
    {
        {.x = 51, .y = 191, .endName = u8"赤月山谷4层_D1014", .endX = 92, .endY = 13},
    }
},

{   .name = u8"赤月恶魔洞穴_D10162",
    .mapSwitchList
    {
        {.x = 11, .y = 25, .endName = u8"赤月山谷5层_D10151", .endX = 151, .endY = 17},
    }
},

{   .name = u8"赤月山谷1层_d1021",
    .miniMapID = 0X19000120,
    .mapSwitchList
    {
        {.x = 289, .y = 288, .endName = u8"灌木林_12", .endX = 45, .endY = 144},
        {.x = 148, .y = 12, .endName = u8"赤月山谷2层_D1022", .endX = 32, .endY = 244},
    }
},

{   .name = u8"赤月山谷2层_D1022",
    .miniMapID = 0X19000121,
    .mapSwitchList
    {
        {.x = 31, .y = 245, .endName = u8"赤月山谷1层_D1021", .endX = 147, .endY = 13},
        {.x = 46, .y = 32, .endName = u8"赤月山谷3层_D10231", .endX = 148, .endY = 152},
        {.x = 195, .y = 22, .endName = u8"赤月山谷3层_D10232", .endX = 52, .endY = 98},
    }
},

{   .name = u8"赤月山谷3层_d10231",
    .miniMapID = 0X19000122,
    .mapSwitchList
    {
        {.x = 149, .y = 153, .endName = u8"赤月山谷2层_D1022", .endX = 47, .endY = 33},
        {.x = 49, .y = 11, .endName = u8"赤月山谷4层_D1024", .endX = 194, .endY = 279},
    }
},

{   .name = u8"赤月山谷3层_D10232",
    .miniMapID = 0X19000123,
    .mapSwitchList
    {
        {.x = 51, .y = 99, .endName = u8"赤月山谷2层_D1022", .endX = 194, .endY = 23},
        {.x = 133, .y = 22, .endName = u8"赤月山谷4层_D1024", .endX = 282, .endY = 264},
    }
},

{   .name = u8"赤月山谷4层_D1024",
    .miniMapID = 0X19000124,
    .mapSwitchList
    {
        {.x = 195, .y = 280, .endName = u8"赤月山谷3层_D10231", .endX = 50, .endY = 12},
        {.x = 283, .y = 265, .endName = u8"赤月山谷3层_D10232", .endX = 134, .endY = 23},
        {.x = 284, .y = 51, .endName = u8"赤月山谷5层_D10251", .endX = 11, .endY = 58},
        {.x = 115, .y = 13, .endName = u8"赤月山谷5层_D10252", .endX = 182, .endY = 143},
    }
},

{   .name = u8"赤月山谷5层_D10251",
    .miniMapID = 0X19000125,
    .mapSwitchList
    {
        {.x = 10, .y = 59, .endName = u8"赤月山谷4层_D1024", .endX = 283, .endY = 52},
    }
},

{   .name = u8"赤月山谷5层_D10252",
    .miniMapID = 0X19000126,
    .mapSwitchList
    {
        {.x = 183, .y = 144, .endName = u8"赤月山谷4层_D1024", .endX = 116, .endY = 14},
    }
},

{   .name = u8"潘夜神殿1层_D1101",
    .miniMapID = 0X19000200,
    .mapSwitchList
    {
        {.x = 134, .y = 181, .endName = u8"潘夜岛_8", .endX = 691, .endY = 359},
        {.x = 222, .y = 228, .endName = u8"潘夜神殿2层_D1102", .endX = 141, .endY = 141},
    }
},

{   .name = u8"潘夜神殿2层_D1102",
    .miniMapID = 0X19000201,
    .mapSwitchList
    {
        {.x = 140, .y = 140, .endName = u8"潘夜神殿1层_D1101", .endX = 221, .endY = 227},
        {.x = 255, .y = 254, .endName = u8"潘夜神殿3层西部_D11031", .endX = 207, .endY = 333},
        {.x = 51, .y = 46, .endName = u8"潘夜神殿3层东部_D11032", .endX = 35, .endY = 64},
    }
},

{   .name = u8"潘夜神殿3层西部_D11031",
    .miniMapID = 0X19000202,
    .mapSwitchList
    {
        {.x = 206, .y = 332, .endName = u8"潘夜神殿2层_D1102", .endX = 254, .endY = 253},
    }
},

{   .name = u8"潘夜神殿3层东部_D11032",
    .miniMapID = 0X19000203,
    .mapSwitchList
    {
        {.x = 36, .y = 63, .endName = u8"潘夜神殿2层_D1102", .endX = 52, .endY = 45},
        {.x = 62, .y = 36, .endName = u8"潘夜神殿4层_D1104", .endX = 106, .endY = 94},
    }
},

{   .name = u8"潘夜神殿4层_D1104",
    .miniMapID = 0X19000204,
    .mapSwitchList
    {
        {.x = 107, .y = 93, .endName = u8"潘夜神殿3层东部_D11032", .endX = 63, .endY = 35},
        {.x = 157, .y = 152, .endName = u8"潘夜神殿5层_D1105", .endX = 105, .endY = 216},
    }
},

{   .name = u8"潘夜神殿5层_D1105",
    .miniMapID = 0X19000205,
    .mapSwitchList
    {
        {.x = 106, .y = 217, .endName = u8"潘夜神殿4层_D1104", .endX = 158, .endY = 153},
    }
},

{   .name = u8"潘夜神殿大厅_D1110",
    .mapSwitchList
    {
        {.x = 25, .y = 22, .endName = u8"潘夜神殿4层_D1111", .endX = 221, .endY = 224},
    }
},

{   .name = u8"潘夜神殿4层_D1111",
    .miniMapID = 0X19000210,
    .mapSwitchList
    {
        {.x = 220, .y = 225, .endName = u8"潘夜神殿大厅_D1110", .endX = 24, .endY = 23},
        {.x = 111, .y = 112, .endName = u8"潘夜神殿5层_D1112", .endX = 156, .endY = 157},
    }
},

{   .name = u8"潘夜神殿5层_D1112",
    .miniMapID = 0X19000211,
    .mapSwitchList
    {
        {.x = 155, .y = 156, .endName = u8"潘夜神殿4层_D1111", .endX = 110, .endY = 111},
        {.x = 373, .y = 378, .endName = u8"潘夜神殿6层_D1113", .endX = 35, .endY = 27},
    }
},

{   .name = u8"潘夜神殿6层_D1113",
    .miniMapID = 0X19000212,
    .mapSwitchList
    {
        {.x = 34, .y = 26, .endName = u8"潘夜神殿5层_D1112", .endX = 372, .endY = 377},
        {.x = 376, .y = 50, .endName = u8"潘夜神殿7层西部_D11141", .endX = 40, .endY = 108},
        {.x = 38, .y = 373, .endName = u8"潘夜神殿7层东部_D11142", .endX = 93, .endY = 127},
        {.x = 375, .y = 369, .endName = u8"潘夜神殿8层_D1115", .endX = 379, .endY = 382},
    }
},

{   .name = u8"潘夜神殿7层西部_D11141",
    .miniMapID = 0X19000213,
    .mapSwitchList
    {
        {.x = 39, .y = 109, .endName = u8"潘夜神殿6层_D1113", .endX = 375, .endY = 51},
        {.x = 125, .y = 63, .endName = u8"潘夜神殿8层_D1115", .endX = 384, .endY = 19},
    }
},

{   .name = u8"潘夜神殿7层东部_D11142",
    .miniMapID = 0X19000214,
    .mapSwitchList
    {
        {.x = 94, .y = 128, .endName = u8"潘夜神殿6层_D1113", .endX = 39, .endY = 374},
        {.x = 25, .y = 30, .endName = u8"潘夜神殿8层_D1115", .endX = 35, .endY = 382},
    }
},

{   .name = u8"潘夜神殿8层_D1115",
    .miniMapID = 0X19000215,
    .mapSwitchList
    {
        {.x = 380, .y = 383, .endName = u8"潘夜神殿6层_D1113", .endX = 376, .endY = 370},
        {.x = 385, .y = 18, .endName = u8"潘夜神殿7层西部_D11141", .endX = 126, .endY = 62},
        {.x = 36, .y = 383, .endName = u8"潘夜神殿7层东部_D11142", .endX = 26, .endY = 31},
        {.x = 200, .y = 199, .endName = u8"潘夜神殿_D1116", .endX = 90, .endY = 14},
    }
},

{   .name = u8"潘夜神殿_D1116",
    .miniMapID = 0X19000216,
    .mapSwitchList
    {
        {.x = 91, .y = 13, .endName = u8"潘夜神殿8层_D1115", .endX = 201, .endY = 198},
    }
},

{   .name = u8"罪孽洞穴1层_D1201",
    .miniMapID = 0X19000220,
    .mapSwitchList
    {
        {.x = 18, .y = 148, .endName = u8"流放岛_81", .endX = 155, .endY = 136},
        {.x = 17, .y = 23, .endName = u8"罪孽洞穴2层_D1202", .endX = 179, .endY = 182},
    }
},

{   .name = u8"罪孽洞穴2层_D1202",
    .miniMapID = 0X19000221,
    .mapSwitchList
    {
        {.x = 179, .y = 183, .endName = u8"罪孽洞穴1层_D1201", .endX = 18, .endY = 24},
        {.x = 120, .y = 87, .endName = u8"罪孽洞穴3层东部_D12032", .endX = 18, .endY = 186},
        {.x = 16, .y = 24, .endName = u8"罪孽洞穴3层西部_D12031", .endX = 50, .endY = 80},
    }
},

{   .name = u8"罪孽洞穴3层西部_D12031",
    .miniMapID = 0X19000222,
    .mapSwitchList
    {
        {.x = 51, .y = 81, .endName = u8"罪孽洞穴2层_D1202", .endX = 17, .endY = 25},
        {.x = 91, .y = 168, .endName = u8"罪孽洞穴4层_D1204", .endX = 172, .endY = 39},
    }
},

{   .name = u8"罪孽洞穴3层东部_D12032",
    .miniMapID = 0X19000223,
    .mapSwitchList
    {
        {.x = 17, .y = 187, .endName = u8"罪孽洞穴2层_D1202", .endX = 119, .endY = 88},
        {.x = 29, .y = 35, .endName = u8"罪孽洞穴4层_D1204", .endX = 24, .endY = 267},
    }
},

{   .name = u8"罪孽洞穴4层_D1204",
    .miniMapID = 0X19000224,
    .mapSwitchList
    {
        {.x = 23, .y = 268, .endName = u8"罪孽洞穴3层东部_D12032", .endX = 28, .endY = 36},
        {.x = 173, .y = 40, .endName = u8"罪孽洞穴3层西部_D12031", .endX = 92, .endY = 169},
        {.x = 265, .y = 253, .endName = u8"罪孽洞穴5层_D1205", .endX = 75, .endY = 201},
    }
},

{   .name = u8"罪孽洞穴5层_D1205",
    .miniMapID = 0X19000225,
    .mapSwitchList
    {
        {.x = 74, .y = 202, .endName = u8"罪孽洞穴4层_D1204", .endX = 264, .endY = 254},
    }
},

{   .name = u8"潘夜石窟1层_D1211",
    .miniMapID = 0X19000230,
    .mapSwitchList
    {
        {.x = 127, .y = 173, .endName = u8"潘夜岛_8", .endX = 415, .endY = 554},
        {.x = 10, .y = 96, .endName = u8"潘夜石窟2层西部_D12121", .endX = 281, .endY = 61},
    }
},

{   .name = u8"潘夜石窟2层西部_D12121",
    .miniMapID = 0X19000231,
    .mapSwitchList
    {
        {.x = 282, .y = 62, .endName = u8"潘夜石窟1层_D1211", .endX = 11, .endY = 97},
        {.x = 281, .y = 258, .endName = u8"潘夜石窟3层_D1213", .endX = 268, .endY = 275},
    }
},

{   .name = u8"潘夜石窟3层_D1213",
    .miniMapID = 0X19000233,
    .mapSwitchList
    {
        {.x = 267, .y = 276, .endName = u8"潘夜石窟2层西部_D12121", .endX = 280, .endY = 259},
        {.x = 107, .y = 130, .endName = u8"潘夜石窟4层_D1214", .endX = 59, .endY = 284},
    }
},

{   .name = u8"潘夜石窟4层_D1214",
    .miniMapID = 0X19000234,
    .mapSwitchList
    {
        {.x = 59, .y = 285, .endName = u8"潘夜石窟3层_D1213", .endX = 106, .endY = 131},
        {.x = 226, .y = 16, .endName = u8"潘夜石窟5层_D1215", .endX = 371, .endY = 47},
    }
},

{   .name = u8"潘夜石窟5层_D1215",
    .miniMapID = 0X19000235,
    .mapSwitchList
    {
        {.x = 371, .y = 48, .endName = u8"潘夜石窟4层_D1214", .endX = 227, .endY = 17},
    }
},

{   .name = u8"东部银杏废矿1层_D1301",
    .miniMapID = 0X19000240,
    .mapSwitchList
    {
        {.x = 357, .y = 379, .endName = u8"银杏山谷_02", .endX = 345, .endY = 121},
        {.x = 155, .y = 31, .endName = u8"东部银杏废矿2层_D1302", .endX = 367, .endY = 353},
    }
},

{   .name = u8"东部银杏废矿2层_D1302",
    .miniMapID = 0X19000241,
    .mapSwitchList
    {
        {.x = 368, .y = 354, .endName = u8"东部银杏废矿1层_D1301", .endX = 156, .endY = 32},
        {.x = 119, .y = 23, .endName = u8"东部银杏废矿3层_D1303", .endX = 49, .endY = 362},
    }
},

{   .name = u8"东部银杏废矿3层_D1303",
    .miniMapID = 0X19000242,
    .mapSwitchList
    {
        {.x = 48, .y = 363, .endName = u8"东部银杏废矿2层_D1302", .endX = 118, .endY = 24},
        {.x = 359, .y = 27, .endName = u8"东部银杏废矿4层_D1304", .endX = 69, .endY = 352},
    }
},

{   .name = u8"东部银杏废矿4层_D1304",
    .miniMapID = 0X19000243,
    .mapSwitchList
    {
        {.x = 68, .y = 353, .endName = u8"东部银杏废矿3层_D1303", .endX = 358, .endY = 28},
        {.x = 347, .y = 37, .endName = u8"东部银杏废矿5层_D1305", .endX = 360, .endY = 354},
    }
},

{   .name = u8"东部银杏废矿5层_D1305",
    .miniMapID = 0X19000244,
    .mapSwitchList
    {
        {.x = 361, .y = 355, .endName = u8"东部银杏废矿4层_D1304", .endX = 348, .endY = 38},
    }
},

{   .name = u8"北部银杏废矿1层_D1311",
    .miniMapID = 0X19000240,
    .mapSwitchList
    {
        {.x = 357, .y = 379, .endName = u8"银杏山谷_02", .endX = 280, .endY = 74},
        {.x = 155, .y = 31, .endName = u8"北部银杏废矿2层_D1312", .endX = 367, .endY = 353},
    }
},

{   .name = u8"北部银杏废矿2层_D1312",
    .miniMapID = 0X19000241,
    .mapSwitchList
    {
        {.x = 368, .y = 354, .endName = u8"北部银杏废矿1层_D1311", .endX = 156, .endY = 32},
        {.x = 119, .y = 23, .endName = u8"北部银杏废矿3层_D1313", .endX = 49, .endY = 362},
    }
},

{   .name = u8"北部银杏废矿3层_D1313",
    .miniMapID = 0X19000242,
    .mapSwitchList
    {
        {.x = 48, .y = 363, .endName = u8"北部银杏废矿2层_D1312", .endX = 118, .endY = 24},
        {.x = 359, .y = 27, .endName = u8"北部银杏废矿4层_D1314", .endX = 69, .endY = 352},
    }
},

{   .name = u8"北部银杏废矿4层_D1314",
    .miniMapID = 0X19000243,
    .mapSwitchList
    {
        {.x = 68, .y = 353, .endName = u8"北部银杏废矿3层_D1313", .endX = 358, .endY = 28},
        {.x = 347, .y = 37, .endName = u8"北部银杏废矿5层_D1315", .endX = 360, .endY = 354},
    }
},

{   .name = u8"北部银杏废矿5层_D1315",
    .miniMapID = 0X19000244,
    .mapSwitchList
    {
        {.x = 361, .y = 355, .endName = u8"北部银杏废矿4层_D1314", .endX = 348, .endY = 38},
    }
},

{   .name = u8"西部银杏废矿1层_D1321",
    .miniMapID = 0X19000240,
    .mapSwitchList
    {
        {.x = 357, .y = 379, .endName = u8"银杏山谷_02", .endX = 128, .endY = 158},
        {.x = 155, .y = 31, .endName = u8"西部银杏废矿2层_D1322", .endX = 367, .endY = 353},
    }
},

{   .name = u8"西部银杏废矿2层_D1322",
    .miniMapID = 0X19000241,
    .mapSwitchList
    {
        {.x = 368, .y = 354, .endName = u8"西部银杏废矿1层_D1321", .endX = 156, .endY = 32},
        {.x = 119, .y = 23, .endName = u8"西部银杏废矿3层_D1323", .endX = 49, .endY = 362},
    }
},

{   .name = u8"西部银杏废矿3层_D1323",
    .miniMapID = 0X19000242,
    .mapSwitchList
    {
        {.x = 48, .y = 363, .endName = u8"西部银杏废矿2层_D1322", .endX = 118, .endY = 24},
        {.x = 359, .y = 27, .endName = u8"西部银杏废矿4层_D1324", .endX = 69, .endY = 352},
    }
},

{   .name = u8"西部银杏废矿4层_D1324",
    .miniMapID = 0X19000243,
    .mapSwitchList
    {
        {.x = 68, .y = 353, .endName = u8"西部银杏废矿3层_D1323", .endX = 358, .endY = 28},
        {.x = 347, .y = 37, .endName = u8"西部银杏废矿5层_D1325", .endX = 360, .endY = 354},
    }
},

{   .name = u8"西部银杏废矿5层_D1325",
    .miniMapID = 0X19000244,
    .mapSwitchList
    {
        {.x = 361, .y = 355, .endName = u8"西部银杏废矿4层_D1324", .endX = 348, .endY = 38},
    }
},

{   .name = u8"东部石矿_D1405",
    .miniMapID = 0X19000254,
    .mapSwitchList
    {
        {.x = 85, .y = 366, .endName = u8"边境城市_01", .endX = 496, .endY = 87},
    }
},

{   .name = u8"北部石矿1层_D1411",
    .miniMapID = 0X19000250,
    .mapSwitchList
    {
        {.x = 91, .y = 388, .endName = u8"边境城市_01", .endX = 354, .endY = 66},
        {.x = 347, .y = 47, .endName = u8"北部石矿2层_D1412", .endX = 314, .endY = 373},
    }
},

{   .name = u8"北部石矿2层_d1412",
    .miniMapID = 0X19000251,
    .mapSwitchList
    {
        {.x = 313, .y = 374, .endName = u8"北部石矿1层_D1411", .endX = 346, .endY = 48},
        {.x = 35, .y = 354, .endName = u8"北部石矿3层_D1413", .endX = 315, .endY = 354},
    }
},

{   .name = u8"北部石矿3层_D1413",
    .miniMapID = 0X19000252,
    .mapSwitchList
    {
        {.x = 314, .y = 355, .endName = u8"北部石矿2层_D1412", .endX = 36, .endY = 355},
        {.x = 101, .y = 44, .endName = u8"北部石矿4层_D1414", .endX = 50, .endY = 355},
    }
},

{   .name = u8"北部石矿4层_D1414",
    .miniMapID = 0X19000253,
    .mapSwitchList
    {
        {.x = 49, .y = 356, .endName = u8"北部石矿3层_D1413", .endX = 100, .endY = 45},
        {.x = 376, .y = 61, .endName = u8"北部石矿5层_D1415", .endX = 86, .endY = 365},
    }
},

{   .name = u8"北部石矿5层_D1415",
    .miniMapID = 0X19000254,
    .mapSwitchList
    {
        {.x = 85, .y = 366, .endName = u8"北部石矿4层_D1414", .endX = 375, .endY = 62},
    }
},

{   .name = u8"西部石矿1层_D1421",
    .miniMapID = 0X19000250,
    .mapSwitchList
    {
        {.x = 91, .y = 388, .endName = u8"边境城市_01", .endX = 293, .endY = 154},
        {.x = 347, .y = 47, .endName = u8"西部石矿2层_D1422", .endX = 314, .endY = 373},
    }
},

{   .name = u8"西部石矿2层_D1422",
    .miniMapID = 0X19000251,
    .mapSwitchList
    {
        {.x = 313, .y = 374, .endName = u8"西部石矿1层_D1421", .endX = 346, .endY = 48},
        {.x = 35, .y = 354, .endName = u8"西部石矿3层_D1423", .endX = 315, .endY = 354},
    }
},

{   .name = u8"西部石矿3层_D1423",
    .miniMapID = 0X19000252,
    .mapSwitchList
    {
        {.x = 314, .y = 355, .endName = u8"西部石矿2层_D1422", .endX = 36, .endY = 355},
        {.x = 101, .y = 44, .endName = u8"西部石矿4层_D1424", .endX = 50, .endY = 355},
    }
},

{   .name = u8"西部石矿4层_D1424",
    .miniMapID = 0X19000253,
    .mapSwitchList
    {
        {.x = 49, .y = 356, .endName = u8"西部石矿3层_D1423", .endX = 100, .endY = 45},
        {.x = 376, .y = 61, .endName = u8"西部石矿5层_D1425", .endX = 86, .endY = 365},
    }
},

{   .name = u8"西部石矿5层_D1425",
    .miniMapID = 0X19000254,
    .mapSwitchList
    {
        {.x = 85, .y = 366, .endName = u8"西部石矿4层_D1424", .endX = 375, .endY = 62},
    }
},

{   .name = u8"真天宫地下1层_D1500",
    .miniMapID = 0X19000260,
    .mapSwitchList
    {
        {.x = 171, .y = 225, .endName = u8"失乐园_9", .endX = 387, .endY = 306},
        {.x = 172, .y = 226, .endName = u8"失乐园_9", .endX = 387, .endY = 306},
        {.x = 195, .y = 226, .endName = u8"失乐园_9", .endX = 399, .endY = 310},
        {.x = 195, .y = 225, .endName = u8"失乐园_9", .endX = 399, .endY = 310},
        {.x = 351, .y = 382, .endName = u8"真天宫东馆1层_D15013", .endX = 40, .endY = 38},
        {.x = 352, .y = 381, .endName = u8"真天宫东馆1层_D15013", .endX = 40, .endY = 38},
        {.x = 15, .y = 45, .endName = u8"真天宫西馆1层_D15011", .endX = 268, .endY = 90},
        {.x = 16, .y = 45, .endName = u8"真天宫西馆1层_D15011", .endX = 268, .endY = 90},
        {.x = 27, .y = 369, .endName = u8"真天宫南馆1层_D15012", .endX = 240, .endY = 27},
        {.x = 28, .y = 370, .endName = u8"真天宫南馆1层_D15012", .endX = 240, .endY = 27},
        {.x = 355, .y = 41, .endName = u8"真天宫北馆1层_D15014", .endX = 119, .endY = 198},
        {.x = 356, .y = 41, .endName = u8"真天宫北馆1层_D15014", .endX = 119, .endY = 198},
    }
},

{   .name = u8"真天宫西馆1层_D15011",
    .miniMapID = 0X19000261,
    .mapSwitchList
    {
        {.x = 268, .y = 92, .endName = u8"真天宫地下1层_D1500", .endX = 16, .endY = 46},
        {.x = 269, .y = 91, .endName = u8"真天宫地下1层_D1500", .endX = 16, .endY = 46},
        {.x = 16, .y = 276, .endName = u8"真天宫西馆2层_D15021", .endX = 242, .endY = 21},
        {.x = 17, .y = 277, .endName = u8"真天宫西馆2层_D15021", .endX = 242, .endY = 21},
    }
},

{   .name = u8"真天宫南馆1层_D15012",
    .miniMapID = 0X19000262,
    .mapSwitchList
    {
        {.x = 241, .y = 26, .endName = u8"真天宫地下1层_D1500", .endX = 28, .endY = 368},
        {.x = 242, .y = 26, .endName = u8"真天宫地下1层_D1500", .endX = 28, .endY = 368},
    }
},

{   .name = u8"真天宫东馆1层_D15013",
    .miniMapID = 0X19000263,
    .mapSwitchList
    {
        {.x = 39, .y = 37, .endName = u8"真天宫地下1层_D1500", .endX = 351, .endY = 380},
        {.x = 40, .y = 37, .endName = u8"真天宫地下1层_D1500", .endX = 351, .endY = 380},
        {.x = 149, .y = 152, .endName = u8"真天宫东馆2层_D15023", .endX = 160, .endY = 152},
        {.x = 150, .y = 152, .endName = u8"真天宫东馆2层_D15023", .endX = 160, .endY = 152},
    }
},

{   .name = u8"真天宫北馆1层_D15014",
    .miniMapID = 0X19000264,
    .mapSwitchList
    {
        {.x = 118, .y = 199, .endName = u8"真天宫地下1层_D1500", .endX = 354, .endY = 42},
        {.x = 119, .y = 200, .endName = u8"真天宫地下1层_D1500", .endX = 354, .endY = 42},
        {.x = 258, .y = 35, .endName = u8"真天宫北馆2层_D15024", .endX = 122, .endY = 132},
        {.x = 259, .y = 35, .endName = u8"真天宫北馆2层_D15024", .endX = 122, .endY = 132},
    }
},

{   .name = u8"真天宫西馆2层_D15021",
    .miniMapID = 0X19000265,
    .mapSwitchList
    {
        {.x = 243, .y = 20, .endName = u8"真天宫西馆1层_D15011", .endX = 17, .endY = 275},
        {.x = 244, .y = 20, .endName = u8"真天宫西馆1层_D15011", .endX = 17, .endY = 275},
        {.x = 119, .y = 262, .endName = u8"真天宫南馆2层_D15022", .endX = 18, .endY = 18},
        {.x = 120, .y = 261, .endName = u8"真天宫南馆2层_D15022", .endX = 18, .endY = 18},
    }
},

{   .name = u8"真天宫南馆2层_D15022",
    .miniMapID = 0X19000266,
    .mapSwitchList
    {
        {.x = 165, .y = 62, .endName = u8"黑度宫3层_D1512", .endX = 183, .endY = 168},
        {.x = 166, .y = 62, .endName = u8"黑度宫3层_D1512", .endX = 183, .endY = 168},
        {.x = 17, .y = 17, .endName = u8"真天宫西馆2层_D15021", .endX = 119, .endY = 260},
        {.x = 18, .y = 17, .endName = u8"真天宫西馆2层_D15021", .endX = 119, .endY = 260},
        {.x = 245, .y = 265, .endName = u8"真天宫南馆3层_D15032", .endX = 14, .endY = 19},
        {.x = 246, .y = 264, .endName = u8"真天宫南馆3层_D15032", .endX = 14, .endY = 19},
    }
},

{   .name = u8"真天宫东馆2层_D15023",
    .miniMapID = 0X19000267,
    .mapSwitchList
    {
        {.x = 161, .y = 153, .endName = u8"真天宫东馆1层_D15013", .endX = 150, .endY = 153},
        {.x = 160, .y = 154, .endName = u8"真天宫东馆1层_D15013", .endX = 150, .endY = 153},
        {.x = 259, .y = 275, .endName = u8"真天宫东馆3层_D15033", .endX = 30, .endY = 34},
        {.x = 258, .y = 276, .endName = u8"真天宫东馆3层_D15033", .endX = 30, .endY = 34},
    }
},

{   .name = u8"真天宫北馆2层_D15024",
    .miniMapID = 0X19000268,
    .mapSwitchList
    {
        {.x = 121, .y = 133, .endName = u8"真天宫北馆1层_D15014", .endX = 257, .endY = 36},
        {.x = 122, .y = 134, .endName = u8"真天宫北馆1层_D15014", .endX = 257, .endY = 36},
        {.x = 217, .y = 285, .endName = u8"真天宫北馆3层_D15034", .endX = 267, .endY = 36},
        {.x = 218, .y = 286, .endName = u8"真天宫北馆3层_D15034", .endX = 267, .endY = 36},
    }
},

{   .name = u8"真天宫南馆3层_D15032",
    .miniMapID = 0X19000269,
    .mapSwitchList
    {
        {.x = 13, .y = 18, .endName = u8"真天宫南馆2层_D15022", .endX = 245, .endY = 263},
        {.x = 14, .y = 18, .endName = u8"真天宫南馆2层_D15022", .endX = 245, .endY = 263},
        {.x = 269, .y = 238, .endName = u8"真天宫东馆3层_D15033", .endX = 66, .endY = 204},
        {.x = 270, .y = 238, .endName = u8"真天宫东馆3层_D15033", .endX = 66, .endY = 204},
    }
},

{   .name = u8"真天宫东馆3层_D15033",
    .miniMapID = 0X19000270,
    .mapSwitchList
    {
        {.x = 282, .y = 53, .endName = u8"黑度宫4层_D1513", .endX = 14, .endY = 123},
        {.x = 281, .y = 53, .endName = u8"黑度宫4层_D1513", .endX = 14, .endY = 123},
        {.x = 65, .y = 205, .endName = u8"真天宫南馆3层_D15032", .endX = 268, .endY = 239},
        {.x = 66, .y = 206, .endName = u8"真天宫南馆3层_D15032", .endX = 268, .endY = 239},
        {.x = 29, .y = 33, .endName = u8"真天宫东馆2层_D15023", .endX = 258, .endY = 274},
        {.x = 30, .y = 33, .endName = u8"真天宫东馆2层_D15023", .endX = 258, .endY = 274},
        {.x = 286, .y = 289, .endName = u8"真天宫北馆4层_D15043", .endX = 12, .endY = 20},
        {.x = 285, .y = 290, .endName = u8"真天宫北馆4层_D15043", .endX = 12, .endY = 20},
    }
},

{   .name = u8"真天宫北馆3层_D15034",
    .miniMapID = 0X19000271,
    .mapSwitchList
    {
        {.x = 268, .y = 35, .endName = u8"真天宫北馆2层_D15024", .endX = 218, .endY = 284},
        {.x = 269, .y = 35, .endName = u8"真天宫北馆2层_D15024", .endX = 218, .endY = 284},
    }
},

{   .name = u8"真天宫北馆4层_D15043",
    .miniMapID = 0X19000272,
    .mapSwitchList
    {
        {.x = 11, .y = 19, .endName = u8"真天宫东馆3层_D15033", .endX = 285, .endY = 288},
        {.x = 12, .y = 19, .endName = u8"真天宫东馆3层_D15033", .endX = 285, .endY = 288},
        {.x = 255, .y = 259, .endName = u8"真天宫北馆4层_D15044", .endX = 22, .endY = 267},
        {.x = 256, .y = 259, .endName = u8"真天宫北馆4层_D15044", .endX = 22, .endY = 267},
    }
},

{   .name = u8"真天宫北馆4层_D15044",
    .miniMapID = 0X19000273,
    .mapSwitchList
    {
        {.x = 21, .y = 268, .endName = u8"真天宫北馆4层_D15043", .endX = 254, .endY = 260},
        {.x = 22, .y = 269, .endName = u8"真天宫北馆4层_D15043", .endX = 254, .endY = 260},
        {.x = 245, .y = 20, .endName = u8"真天宫北馆5层_D15054", .endX = 181, .endY = 183},
        {.x = 246, .y = 20, .endName = u8"真天宫北馆5层_D15054", .endX = 181, .endY = 183},
    }
},

{   .name = u8"真天宫北馆5层_D15054",
    .miniMapID = 0X19000274,
    .mapSwitchList
    {
        {.x = 181, .y = 185, .endName = u8"真天宫北馆4层_D15044", .endX = 246, .endY = 21},
        {.x = 182, .y = 184, .endName = u8"真天宫北馆4层_D15044", .endX = 246, .endY = 21},
        {.x = 285, .y = 288, .endName = u8"真天宫_D1506", .endX = 44, .endY = 63},
        {.x = 286, .y = 288, .endName = u8"真天宫_D1506", .endX = 44, .endY = 63},
    }
},

{   .name = u8"真天宫_D1506",
    .mapSwitchList
    {
        {.x = 45, .y = 64, .endName = u8"真天宫北馆5层_D15054", .endX = 286, .endY = 289},
    }
},

{   .name = u8"黑度宫1层_D1510",
    .miniMapID = 0X19000280,
    .mapSwitchList
    {
        {.x = 13, .y = 46, .endName = u8"失乐园_9", .endX = 207, .endY = 92},
        {.x = 14, .y = 47, .endName = u8"失乐园_9", .endX = 207, .endY = 92},
        {.x = 9, .y = 172, .endName = u8"黑度宫2层_D15111", .endX = 178, .endY = 34},
        {.x = 10, .y = 173, .endName = u8"黑度宫2层_D15111", .endX = 178, .endY = 34},
        {.x = 189, .y = 188, .endName = u8"黑度宫2层_D15112", .endX = 95, .endY = 59},
        {.x = 190, .y = 181, .endName = u8"黑度宫2层_D15112", .endX = 95, .endY = 59},
    }
},

{   .name = u8"黑度宫2层_D15111",
    .miniMapID = 0X19000281,
    .mapSwitchList
    {
        {.x = 180, .y = 33, .endName = u8"黑度宫1层_D1510", .endX = 10, .endY = 171},
        {.x = 179, .y = 33, .endName = u8"黑度宫1层_D1510", .endX = 10, .endY = 171},
        {.x = 31, .y = 186, .endName = u8"黑度宫3层_D1512", .endX = 38, .endY = 23},
        {.x = 32, .y = 187, .endName = u8"黑度宫3层_D1512", .endX = 38, .endY = 23},
    }
},

{   .name = u8"黑度宫2层_D15112",
    .miniMapID = 0X19000282,
    .mapSwitchList
    {
        {.x = 94, .y = 58, .endName = u8"黑度宫1层_D1510", .endX = 189, .endY = 186},
        {.x = 95, .y = 58, .endName = u8"黑度宫1层_D1510", .endX = 189, .endY = 186},
        {.x = 30, .y = 181, .endName = u8"黑度宫3层_D1512", .endX = 186, .endY = 19},
        {.x = 31, .y = 182, .endName = u8"黑度宫3层_D1512", .endX = 186, .endY = 19},
    }
},

{   .name = u8"黑度宫3层_D1512",
    .miniMapID = 0X19000283,
    .mapSwitchList
    {
        {.x = 39, .y = 22, .endName = u8"黑度宫2层_D15111", .endX = 32, .endY = 185},
        {.x = 40, .y = 22, .endName = u8"黑度宫2层_D15111", .endX = 32, .endY = 185},
        {.x = 188, .y = 18, .endName = u8"黑度宫2层_D15112", .endX = 31, .endY = 180},
        {.x = 187, .y = 18, .endName = u8"黑度宫2层_D15112", .endX = 31, .endY = 180},
        {.x = 15, .y = 186, .endName = u8"黑度宫4层_D1513", .endX = 180, .endY = 28},
        {.x = 16, .y = 187, .endName = u8"黑度宫4层_D1513", .endX = 180, .endY = 28},
        {.x = 183, .y = 170, .endName = u8"真天宫南馆2层_D15022", .endX = 166, .endY = 63},
        {.x = 184, .y = 169, .endName = u8"真天宫南馆2层_D15022", .endX = 166, .endY = 63},
    }
},

{   .name = u8"黑度宫4层_D1513",
    .miniMapID = 0X19000284,
    .mapSwitchList
    {
        {.x = 182, .y = 27, .endName = u8"黑度宫3层_D1512", .endX = 16, .endY = 185},
        {.x = 181, .y = 27, .endName = u8"黑度宫3层_D1512", .endX = 16, .endY = 185},
        {.x = 13, .y = 124, .endName = u8"真天宫东馆3层_D15033", .endX = 280, .endY = 54},
        {.x = 14, .y = 125, .endName = u8"真天宫东馆3层_D15033", .endX = 280, .endY = 54},
    }
},

{   .name = u8"诺玛遗址1层_d1601",
    .miniMapID = 0X19000300,
    .mapSwitchList
    {
        {.x = 313, .y = 44, .endName = u8"诺玛村庄_41", .endX = 168, .endY = 57},
        {.x = 312, .y = 42, .endName = u8"诺玛村庄_41", .endX = 168, .endY = 57},
        {.x = 352, .y = 253, .endName = u8"诺玛村庄_41", .endX = 189, .endY = 111},
        {.x = 352, .y = 254, .endName = u8"诺玛村庄_41", .endX = 189, .endY = 111},
        {.x = 39, .y = 149, .endName = u8"诺玛村庄_41", .endX = 116, .endY = 72},
        {.x = 39, .y = 148, .endName = u8"诺玛村庄_41", .endX = 116, .endY = 72},
        {.x = 91, .y = 345, .endName = u8"诺玛村庄_41", .endX = 140, .endY = 138},
        {.x = 206, .y = 203, .endName = u8"诺玛遗址2层_D1602", .endX = 194, .endY = 200},
        {.x = 206, .y = 202, .endName = u8"诺玛遗址2层_D1602", .endX = 194, .endY = 200},
        {.x = 207, .y = 202, .endName = u8"诺玛遗址2层_D1602", .endX = 194, .endY = 200},
    }
},

{   .name = u8"诺玛遗址2层_d1602",
    .miniMapID = 0X19000301,
    .mapSwitchList
    {
        {.x = 195, .y = 198, .endName = u8"诺玛遗址1层_D1601", .endX = 208, .endY = 201},
        {.x = 195, .y = 199, .endName = u8"诺玛遗址1层_D1601", .endX = 208, .endY = 201},
        {.x = 383, .y = 205, .endName = u8"诺玛遗址3层_D16031", .endX = 357, .endY = 368},
        {.x = 383, .y = 204, .endName = u8"诺玛遗址3层_D16031", .endX = 357, .endY = 368},
        {.x = 199, .y = 14, .endName = u8"诺玛遗址3层_D16032", .endX = 341, .endY = 78},
        {.x = 199, .y = 15, .endName = u8"诺玛遗址3层_D16032", .endX = 341, .endY = 78},
        {.x = 12, .y = 194, .endName = u8"诺玛遗址3层_D16033", .endX = 42, .endY = 54},
        {.x = 12, .y = 195, .endName = u8"诺玛遗址3层_D16033", .endX = 42, .endY = 54},
        {.x = 188, .y = 385, .endName = u8"诺玛遗址3层_D16034", .endX = 62, .endY = 356},
        {.x = 188, .y = 384, .endName = u8"诺玛遗址3层_D16034", .endX = 62, .endY = 356},
    }
},

{   .name = u8"诺玛遗址3层_d16031",
    .miniMapID = 0X19000302,
    .mapSwitchList
    {
        {.x = 356, .y = 367, .endName = u8"诺玛遗址2层_D1602", .endX = 382, .endY = 204},
        {.x = 356, .y = 368, .endName = u8"诺玛遗址2层_D1602", .endX = 382, .endY = 204},
        {.x = 199, .y = 219, .endName = u8"诺玛遗址4层_D1604", .endX = 190, .endY = 177},
        {.x = 199, .y = 220, .endName = u8"诺玛遗址4层_D1604", .endX = 190, .endY = 177},
    }
},

{   .name = u8"诺玛遗址3层_d16032",
    .miniMapID = 0X19000303,
    .mapSwitchList
    {
        {.x = 340, .y = 79, .endName = u8"诺玛遗址2层_D1602", .endX = 198, .endY = 15},
        {.x = 340, .y = 78, .endName = u8"诺玛遗址2层_D1602", .endX = 198, .endY = 15},
        {.x = 200, .y = 217, .endName = u8"诺玛遗址4层_D1604", .endX = 191, .endY = 186},
        {.x = 200, .y = 216, .endName = u8"诺玛遗址4层_D1604", .endX = 191, .endY = 186},
    }
},

{   .name = u8"诺玛遗址3层_d16033",
    .miniMapID = 0X19000304,
    .mapSwitchList
    {
        {.x = 43, .y = 55, .endName = u8"诺玛遗址2层_D1602", .endX = 13, .endY = 195},
        {.x = 43, .y = 54, .endName = u8"诺玛遗址2层_D1602", .endX = 13, .endY = 195},
        {.x = 198, .y = 217, .endName = u8"诺玛遗址4层_D1604", .endX = 199, .endY = 185},
        {.x = 198, .y = 218, .endName = u8"诺玛遗址4层_D1604", .endX = 199, .endY = 185},
    }
},

{   .name = u8"诺玛遗址3层_d16034",
    .miniMapID = 0X19000305,
    .mapSwitchList
    {
        {.x = 63, .y = 355, .endName = u8"诺玛遗址2层_D1602", .endX = 189, .endY = 384},
        {.x = 63, .y = 356, .endName = u8"诺玛遗址2层_D1602", .endX = 189, .endY = 384},
        {.x = 199, .y = 217, .endName = u8"诺玛遗址4层_D1604", .endX = 200, .endY = 176},
        {.x = 199, .y = 218, .endName = u8"诺玛遗址4层_D1604", .endX = 200, .endY = 176},
    }
},

{   .name = u8"诺玛遗址4层_d1604",
    .miniMapID = 0X19000306,
    .mapSwitchList
    {
        {.x = 191, .y = 177, .endName = u8"诺玛遗址3层_D16031", .endX = 200, .endY = 220},
        {.x = 192, .y = 177, .endName = u8"诺玛遗址3层_D16031", .endX = 200, .endY = 220},
        {.x = 192, .y = 184, .endName = u8"诺玛遗址3层_D16032", .endX = 201, .endY = 216},
        {.x = 192, .y = 185, .endName = u8"诺玛遗址3层_D16032", .endX = 201, .endY = 216},
        {.x = 198, .y = 184, .endName = u8"诺玛遗址3层_D16033", .endX = 197, .endY = 217},
        {.x = 199, .y = 184, .endName = u8"诺玛遗址3层_D16033", .endX = 197, .endY = 217},
        {.x = 198, .y = 177, .endName = u8"诺玛遗址3层_D16034", .endX = 198, .endY = 218},
        {.x = 199, .y = 177, .endName = u8"诺玛遗址3层_D16034", .endX = 198, .endY = 218},
        {.x = 191, .y = 30, .endName = u8"诺玛遗址4层_D1604", .endX = 89, .endY = 153},
        {.x = 191, .y = 30, .endName = u8"诺玛遗址4层_D1604", .endX = 89, .endY = 153},
        {.x = 200, .y = 39, .endName = u8"诺玛遗址4层_D1604", .endX = 222, .endY = 61},
        {.x = 200, .y = 40, .endName = u8"诺玛遗址4层_D1604", .endX = 222, .endY = 61},
        {.x = 162, .y = 60, .endName = u8"诺玛遗址4层_D1604", .endX = 136, .endY = 246},
        {.x = 162, .y = 60, .endName = u8"诺玛遗址4层_D1604", .endX = 136, .endY = 246},
        {.x = 171, .y = 69, .endName = u8"诺玛遗址4层_D1604", .endX = 75, .endY = 181},
        {.x = 171, .y = 70, .endName = u8"诺玛遗址4层_D1604", .endX = 75, .endY = 181},
        {.x = 138, .y = 80, .endName = u8"诺玛遗址4层_D1604", .endX = 128, .endY = 224},
        {.x = 138, .y = 80, .endName = u8"诺玛遗址4层_D1604", .endX = 128, .endY = 224},
        {.x = 147, .y = 89, .endName = u8"诺玛遗址4层_D1604", .endX = 238, .endY = 108},
        {.x = 147, .y = 90, .endName = u8"诺玛遗址4层_D1604", .endX = 238, .endY = 108},
        {.x = 123, .y = 110, .endName = u8"诺玛遗址4层_D1604", .endX = 177, .endY = 213},
        {.x = 123, .y = 110, .endName = u8"诺玛遗址4层_D1604", .endX = 177, .endY = 213},
        {.x = 132, .y = 119, .endName = u8"诺玛遗址4层_D1604", .endX = 253, .endY = 172},
        {.x = 132, .y = 120, .endName = u8"诺玛遗址4层_D1604", .endX = 253, .endY = 172},
        {.x = 79, .y = 143, .endName = u8"诺玛遗址4层_D1604", .endX = 244, .endY = 94},
        {.x = 79, .y = 143, .endName = u8"诺玛遗址4层_D1604", .endX = 244, .endY = 94},
        {.x = 88, .y = 52, .endName = u8"诺玛遗址4层_D1604", .endX = 161, .endY = 59},
        {.x = 88, .y = 153, .endName = u8"诺玛遗址4层_D1604", .endX = 161, .endY = 59},
        {.x = 54, .y = 170, .endName = u8"诺玛遗址4层_D1604", .endX = 171, .endY = 149},
        {.x = 54, .y = 170, .endName = u8"诺玛遗址4层_D1604", .endX = 171, .endY = 149},
        {.x = 63, .y = 179, .endName = u8"诺玛遗址4层_D1604", .endX = 266, .endY = 98},
        {.x = 63, .y = 180, .endName = u8"诺玛遗址4层_D1604", .endX = 266, .endY = 98},
        {.x = 23, .y = 194, .endName = u8"诺玛遗址4层_D1604", .endX = 136, .endY = 246},
        {.x = 23, .y = 194, .endName = u8"诺玛遗址4层_D1604", .endX = 136, .endY = 246},
        {.x = 32, .y = 203, .endName = u8"诺玛遗址4层_D1604", .endX = 209, .endY = 117},
        {.x = 32, .y = 204, .endName = u8"诺玛遗址4层_D1604", .endX = 209, .endY = 117},
        {.x = 44, .y = 205, .endName = u8"诺玛遗址4层_D1604", .endX = 54, .endY = 215},
        {.x = 44, .y = 205, .endName = u8"诺玛遗址4层_D1604", .endX = 54, .endY = 215},
        {.x = 53, .y = 214, .endName = u8"诺玛遗址4层_D1604", .endX = 43, .endY = 204},
        {.x = 53, .y = 215, .endName = u8"诺玛遗址4层_D1604", .endX = 43, .endY = 204},
        {.x = 76, .y = 182, .endName = u8"诺玛遗址4层_D1604", .endX = 177, .endY = 213},
        {.x = 76, .y = 182, .endName = u8"诺玛遗址4层_D1604", .endX = 177, .endY = 213},
        {.x = 85, .y = 191, .endName = u8"诺玛遗址4层_D1604", .endX = 22, .endY = 193},
        {.x = 85, .y = 192, .endName = u8"诺玛遗址4层_D1604", .endX = 22, .endY = 193},
        {.x = 101, .y = 162, .endName = u8"诺玛遗址4层_D1604", .endX = 102, .endY = 255},
        {.x = 101, .y = 162, .endName = u8"诺玛遗址4层_D1604", .endX = 102, .endY = 255},
        {.x = 110, .y = 171, .endName = u8"诺玛遗址4层_D1604", .endX = 22, .endY = 193},
        {.x = 110, .y = 172, .endName = u8"诺玛遗址4层_D1604", .endX = 22, .endY = 193},
        {.x = 127, .y = 136, .endName = u8"诺玛遗址4层_D1604", .endX = 192, .endY = 127},
        {.x = 127, .y = 136, .endName = u8"诺玛遗址4层_D1604", .endX = 192, .endY = 127},
        {.x = 136, .y = 145, .endName = u8"诺玛遗址4层_D1604", .endX = 122, .endY = 109},
        {.x = 136, .y = 146, .endName = u8"诺玛遗址4层_D1604", .endX = 122, .endY = 109},
        {.x = 157, .y = 106, .endName = u8"诺玛遗址4层_D1604", .endX = 337, .endY = 171},
        {.x = 157, .y = 106, .endName = u8"诺玛遗址4层_D1604", .endX = 337, .endY = 171},
        {.x = 166, .y = 115, .endName = u8"诺玛遗址4层_D1604", .endX = 166, .endY = 202},
        {.x = 166, .y = 116, .endName = u8"诺玛遗址4层_D1604", .endX = 166, .endY = 202},
        {.x = 177, .y = 78, .endName = u8"诺玛遗址4层_D1604", .endX = 53, .endY = 169},
        {.x = 177, .y = 78, .endName = u8"诺玛遗址4层_D1604", .endX = 53, .endY = 169},
        {.x = 186, .y = 87, .endName = u8"诺玛遗址4层_D1604", .endX = 227, .endY = 137},
        {.x = 186, .y = 88, .endName = u8"诺玛遗址4层_D1604", .endX = 227, .endY = 137},
        {.x = 199, .y = 55, .endName = u8"诺玛遗址4层_D1604", .endX = 81, .endY = 249},
        {.x = 199, .y = 55, .endName = u8"诺玛遗址4层_D1604", .endX = 81, .endY = 249},
        {.x = 208, .y = 64, .endName = u8"诺玛遗址4层_D1604", .endX = 161, .endY = 59},
        {.x = 208, .y = 65, .endName = u8"诺玛遗址4层_D1604", .endX = 161, .endY = 59},
        {.x = 223, .y = 62, .endName = u8"诺玛遗址4层_D1604", .endX = 167, .endY = 116},
        {.x = 223, .y = 62, .endName = u8"诺玛遗址4层_D1604", .endX = 167, .endY = 116},
        {.x = 232, .y = 71, .endName = u8"诺玛遗址4层_D1604", .endX = 22, .endY = 193},
        {.x = 232, .y = 72, .endName = u8"诺玛遗址4层_D1604", .endX = 22, .endY = 193},
        {.x = 201, .y = 90, .endName = u8"诺玛遗址4层_D1604", .endX = 111, .endY = 274},
        {.x = 201, .y = 90, .endName = u8"诺玛遗址4层_D1604", .endX = 111, .endY = 274},
        {.x = 210, .y = 99, .endName = u8"诺玛遗址4层_D1604", .endX = 125, .endY = 235},
        {.x = 210, .y = 100, .endName = u8"诺玛遗址4层_D1604", .endX = 125, .endY = 235},
        {.x = 182, .y = 117, .endName = u8"诺玛遗址4层_D1604", .endX = 192, .endY = 127},
        {.x = 182, .y = 117, .endName = u8"诺玛遗址4层_D1604", .endX = 192, .endY = 127},
        {.x = 191, .y = 126, .endName = u8"诺玛遗址4层_D1604", .endX = 181, .endY = 116},
        {.x = 191, .y = 127, .endName = u8"诺玛遗址4层_D1604", .endX = 181, .endY = 116},
        {.x = 161, .y = 139, .endName = u8"诺玛遗址4层_D1604", .endX = 167, .endY = 116},
        {.x = 161, .y = 139, .endName = u8"诺玛遗址4层_D1604", .endX = 167, .endY = 116},
        {.x = 170, .y = 148, .endName = u8"诺玛遗址4层_D1604", .endX = 181, .endY = 145},
        {.x = 170, .y = 149, .endName = u8"诺玛遗址4层_D1604", .endX = 181, .endY = 145},
        {.x = 131, .y = 189, .endName = u8"诺玛遗址4层_D1604", .endX = 238, .endY = 108},
        {.x = 131, .y = 190, .endName = u8"诺玛遗址4层_D1604", .endX = 238, .endY = 108},
        {.x = 94, .y = 210, .endName = u8"诺玛遗址4层_D1604", .endX = 128, .endY = 224},
        {.x = 94, .y = 210, .endName = u8"诺玛遗址4层_D1604", .endX = 128, .endY = 224},
        {.x = 103, .y = 219, .endName = u8"诺玛遗址4层_D1604", .endX = 313, .endY = 249},
        {.x = 103, .y = 220, .endName = u8"诺玛遗址4层_D1604", .endX = 313, .endY = 249},
        {.x = 65, .y = 215, .endName = u8"诺玛遗址4层_D1604", .endX = 75, .endY = 225},
        {.x = 65, .y = 215, .endName = u8"诺玛遗址4层_D1604", .endX = 75, .endY = 225},
        {.x = 74, .y = 224, .endName = u8"诺玛遗址4层_D1604", .endX = 64, .endY = 214},
        {.x = 74, .y = 225, .endName = u8"诺玛遗址4层_D1604", .endX = 64, .endY = 214},
        {.x = 71, .y = 239, .endName = u8"诺玛遗址4层_D1604", .endX = 78, .endY = 142},
        {.x = 71, .y = 239, .endName = u8"诺玛遗址4层_D1604", .endX = 78, .endY = 142},
        {.x = 80, .y = 248, .endName = u8"诺玛遗址4层_D1604", .endX = 100, .endY = 161},
        {.x = 80, .y = 249, .endName = u8"诺玛遗址4层_D1604", .endX = 100, .endY = 161},
        {.x = 92, .y = 245, .endName = u8"诺玛遗址4层_D1604", .endX = 192, .endY = 127},
        {.x = 92, .y = 245, .endName = u8"诺玛遗址4层_D1604", .endX = 192, .endY = 127},
        {.x = 101, .y = 254, .endName = u8"诺玛遗址4层_D1604", .endX = 238, .endY = 108},
        {.x = 101, .y = 255, .endName = u8"诺玛遗址4层_D1604", .endX = 238, .endY = 108},
        {.x = 118, .y = 214, .endName = u8"诺玛遗址4层_D1604", .endX = 64, .endY = 180},
        {.x = 118, .y = 214, .endName = u8"诺玛遗址4层_D1604", .endX = 64, .endY = 180},
        {.x = 127, .y = 223, .endName = u8"诺玛遗址4层_D1604", .endX = 166, .endY = 202},
        {.x = 127, .y = 224, .endName = u8"诺玛遗址4层_D1604", .endX = 166, .endY = 202},
        {.x = 145, .y = 197, .endName = u8"诺玛遗址4层_D1604", .endX = 177, .endY = 213},
        {.x = 145, .y = 197, .endName = u8"诺玛遗址4层_D1604", .endX = 177, .endY = 213},
        {.x = 154, .y = 206, .endName = u8"诺玛遗址4层_D1604", .endX = 78, .endY = 142},
        {.x = 154, .y = 207, .endName = u8"诺玛遗址4层_D1604", .endX = 78, .endY = 142},
        {.x = 167, .y = 173, .endName = u8"诺玛遗址4层_D1604", .endX = 299, .endY = 220},
        {.x = 167, .y = 173, .endName = u8"诺玛遗址4层_D1604", .endX = 299, .endY = 220},
        {.x = 176, .y = 182, .endName = u8"诺玛遗址4层_D1604", .endX = 198, .endY = 54},
        {.x = 176, .y = 183, .endName = u8"诺玛遗址4层_D1604", .endX = 198, .endY = 54},
        {.x = 182, .y = 146, .endName = u8"诺玛遗址4层_D1604", .endX = 192, .endY = 156},
        {.x = 182, .y = 146, .endName = u8"诺玛遗址4层_D1604", .endX = 192, .endY = 156},
        {.x = 191, .y = 155, .endName = u8"诺玛遗址4层_D1604", .endX = 181, .endY = 145},
        {.x = 191, .y = 156, .endName = u8"诺玛遗址4层_D1604", .endX = 181, .endY = 145},
        {.x = 210, .y = 118, .endName = u8"诺玛遗址4层_D1604", .endX = 86, .endY = 192},
        {.x = 210, .y = 118, .endName = u8"诺玛遗址4层_D1604", .endX = 86, .endY = 192},
        {.x = 219, .y = 127, .endName = u8"诺玛遗址4层_D1604", .endX = 78, .endY = 142},
        {.x = 219, .y = 128, .endName = u8"诺玛遗址4层_D1604", .endX = 78, .endY = 142},
        {.x = 234, .y = 84, .endName = u8"诺玛遗址4层_D1604", .endX = 64, .endY = 180},
        {.x = 234, .y = 84, .endName = u8"诺玛遗址4层_D1604", .endX = 64, .endY = 180},
        {.x = 243, .y = 93, .endName = u8"诺玛遗址4层_D1604", .endX = 100, .endY = 161},
        {.x = 243, .y = 94, .endName = u8"诺玛遗址4层_D1604", .endX = 100, .endY = 161},
        {.x = 267, .y = 99, .endName = u8"诺玛遗址4层_D1604", .endX = 132, .endY = 190},
        {.x = 267, .y = 99, .endName = u8"诺玛遗址4层_D1604", .endX = 132, .endY = 190},
        {.x = 276, .y = 108, .endName = u8"诺玛遗址4层_D1604", .endX = 117, .endY = 213},
        {.x = 276, .y = 109, .endName = u8"诺玛遗址4层_D1604", .endX = 117, .endY = 213},
        {.x = 239, .y = 109, .endName = u8"诺玛遗址4层_D1604", .endX = 201, .endY = 40},
        {.x = 239, .y = 109, .endName = u8"诺玛遗址4层_D1604", .endX = 201, .endY = 40},
        {.x = 248, .y = 118, .endName = u8"诺玛遗址4层_D1604", .endX = 336, .endY = 230},
        {.x = 248, .y = 119, .endName = u8"诺玛遗址4层_D1604", .endX = 336, .endY = 230},
        {.x = 228, .y = 138, .endName = u8"诺玛遗址4层_D1604", .endX = 213, .endY = 163},
        {.x = 228, .y = 138, .endName = u8"诺玛遗址4层_D1604", .endX = 213, .endY = 163},
        {.x = 237, .y = 147, .endName = u8"诺玛遗址4层_D1604", .endX = 122, .endY = 109},
        {.x = 237, .y = 148, .endName = u8"诺玛遗址4层_D1604", .endX = 122, .endY = 109},
        {.x = 203, .y = 153, .endName = u8"诺玛遗址4层_D1604", .endX = 233, .endY = 72},
        {.x = 203, .y = 153, .endName = u8"诺玛遗址4层_D1604", .endX = 233, .endY = 72},
        {.x = 212, .y = 162, .endName = u8"诺玛遗址4层_D1604", .endX = 176, .endY = 77},
        {.x = 212, .y = 163, .endName = u8"诺玛遗址4层_D1604", .endX = 176, .endY = 77},
        {.x = 167, .y = 203, .endName = u8"诺玛遗址4层_D1604", .endX = 277, .endY = 109},
        {.x = 167, .y = 203, .endName = u8"诺玛遗址4层_D1604", .endX = 277, .endY = 109},
        {.x = 176, .y = 212, .endName = u8"诺玛遗址4层_D1604", .endX = 222, .endY = 61},
        {.x = 176, .y = 213, .endName = u8"诺玛遗址4层_D1604", .endX = 222, .endY = 61},
        {.x = 126, .y = 236, .endName = u8"诺玛遗址4层_D1604", .endX = 86, .endY = 192},
        {.x = 126, .y = 236, .endName = u8"诺玛遗址4层_D1604", .endX = 86, .endY = 192},
        {.x = 135, .y = 245, .endName = u8"诺玛遗址4层_D1604", .endX = 161, .endY = 59},
        {.x = 135, .y = 246, .endName = u8"诺玛遗址4层_D1604", .endX = 161, .endY = 59},
        {.x = 101, .y = 264, .endName = u8"诺玛遗址4层_D1604", .endX = 311, .endY = 170},
        {.x = 101, .y = 264, .endName = u8"诺玛遗址4层_D1604", .endX = 311, .endY = 170},
        {.x = 110, .y = 273, .endName = u8"诺玛遗址4层_D1604", .endX = 202, .endY = 152},
        {.x = 110, .y = 274, .endName = u8"诺玛遗址4层_D1604", .endX = 202, .endY = 152},
        {.x = 295, .y = 128, .endName = u8"诺玛遗址4层_D1604", .endX = 373, .endY = 209},
        {.x = 295, .y = 128, .endName = u8"诺玛遗址4层_D1604", .endX = 373, .endY = 209},
        {.x = 304, .y = 137, .endName = u8"诺玛遗址4层_D1604", .endX = 126, .endY = 135},
        {.x = 304, .y = 138, .endName = u8"诺玛遗址4层_D1604", .endX = 126, .endY = 135},
        {.x = 279, .y = 156, .endName = u8"诺玛遗址4层_D1604", .endX = 324, .endY = 260},
        {.x = 279, .y = 156, .endName = u8"诺玛遗址4层_D1604", .endX = 324, .endY = 260},
        {.x = 288, .y = 165, .endName = u8"诺玛遗址4层_D1604", .endX = 335, .endY = 198},
        {.x = 288, .y = 166, .endName = u8"诺玛遗址4层_D1604", .endX = 335, .endY = 198},
        {.x = 254, .y = 173, .endName = u8"诺玛遗址4层_D1604", .endX = 279, .endY = 241},
        {.x = 254, .y = 173, .endName = u8"诺玛遗址4层_D1604", .endX = 279, .endY = 241},
        {.x = 263, .y = 182, .endName = u8"诺玛遗址4层_D1604", .endX = 335, .endY = 198},
        {.x = 263, .y = 183, .endName = u8"诺玛遗址4层_D1604", .endX = 335, .endY = 198},
        {.x = 239, .y = 199, .endName = u8"诺玛遗址4层_D1604", .endX = 140, .endY = 308},
        {.x = 239, .y = 199, .endName = u8"诺玛遗址4层_D1604", .endX = 140, .endY = 308},
        {.x = 248, .y = 208, .endName = u8"诺玛遗址4层_D1604", .endX = 268, .endY = 231},
        {.x = 248, .y = 209, .endName = u8"诺玛遗址4层_D1604", .endX = 268, .endY = 231},
        {.x = 258, .y = 206, .endName = u8"诺玛遗址4层_D1604", .endX = 192, .endY = 127},
        {.x = 258, .y = 206, .endName = u8"诺玛遗址4层_D1604", .endX = 192, .endY = 127},
        {.x = 267, .y = 215, .endName = u8"诺玛遗址4层_D1604", .endX = 300, .endY = 159},
        {.x = 267, .y = 216, .endName = u8"诺玛遗址4层_D1604", .endX = 300, .endY = 159},
        {.x = 280, .y = 188, .endName = u8"诺玛遗址4层_D1604", .endX = 212, .endY = 297},
        {.x = 280, .y = 188, .endName = u8"诺玛遗址4层_D1604", .endX = 212, .endY = 297},
        {.x = 289, .y = 197, .endName = u8"诺玛遗址4层_D1604", .endX = 294, .endY = 127},
        {.x = 289, .y = 198, .endName = u8"诺玛遗址4层_D1604", .endX = 294, .endY = 127},
        {.x = 301, .y = 160, .endName = u8"诺玛遗址4层_D1604", .endX = 299, .endY = 258},
        {.x = 301, .y = 160, .endName = u8"诺玛遗址4层_D1604", .endX = 299, .endY = 258},
        {.x = 310, .y = 169, .endName = u8"诺玛遗址4层_D1604", .endX = 93, .endY = 209},
        {.x = 310, .y = 170, .endName = u8"诺玛遗址4层_D1604", .endX = 93, .endY = 209},
        {.x = 327, .y = 161, .endName = u8"诺玛遗址4层_D1604", .endX = 264, .endY = 183},
        {.x = 327, .y = 161, .endName = u8"诺玛遗址4层_D1604", .endX = 264, .endY = 183},
        {.x = 336, .y = 170, .endName = u8"诺玛遗址4层_D1604", .endX = 336, .endY = 230},
        {.x = 336, .y = 171, .endName = u8"诺玛遗址4层_D1604", .endX = 336, .endY = 230},
        {.x = 313, .y = 190, .endName = u8"诺玛遗址4层_D1604", .endX = 347, .endY = 241},
        {.x = 313, .y = 190, .endName = u8"诺玛遗址4层_D1604", .endX = 347, .endY = 241},
        {.x = 322, .y = 199, .endName = u8"诺玛遗址4层_D1604", .endX = 278, .endY = 155},
        {.x = 322, .y = 200, .endName = u8"诺玛遗址4层_D1604", .endX = 278, .endY = 155},
        {.x = 289, .y = 210, .endName = u8"诺玛遗址4层_D1604", .endX = 267, .endY = 320},
        {.x = 289, .y = 210, .endName = u8"诺玛遗址4层_D1604", .endX = 267, .endY = 320},
        {.x = 298, .y = 219, .endName = u8"诺玛遗址4层_D1604", .endX = 257, .endY = 205},
        {.x = 298, .y = 220, .endName = u8"诺玛遗址4层_D1604", .endX = 257, .endY = 205},
        {.x = 269, .y = 232, .endName = u8"诺玛遗址4层_D1604", .endX = 289, .endY = 166},
        {.x = 269, .y = 232, .endName = u8"诺玛遗址4层_D1604", .endX = 289, .endY = 166},
        {.x = 278, .y = 241, .endName = u8"诺玛遗址4层_D1604", .endX = 326, .endY = 160},
        {.x = 278, .y = 241, .endName = u8"诺玛遗址4层_D1604", .endX = 326, .endY = 160},
        {.x = 289, .y = 248, .endName = u8"诺玛遗址4层_D1604", .endX = 321, .endY = 233},
        {.x = 289, .y = 248, .endName = u8"诺玛遗址4层_D1604", .endX = 321, .endY = 233},
        {.x = 298, .y = 257, .endName = u8"诺玛遗址4层_D1604", .endX = 266, .endY = 98},
        {.x = 298, .y = 258, .endName = u8"诺玛遗址4层_D1604", .endX = 266, .endY = 98},
        {.x = 311, .y = 223, .endName = u8"诺玛遗址4层_D1604", .endX = 238, .endY = 198},
        {.x = 311, .y = 223, .endName = u8"诺玛遗址4层_D1604", .endX = 238, .endY = 198},
        {.x = 320, .y = 232, .endName = u8"诺玛遗址4层_D1604", .endX = 234, .endY = 328},
        {.x = 320, .y = 233, .endName = u8"诺玛遗址4层_D1604", .endX = 234, .endY = 328},
        {.x = 314, .y = 250, .endName = u8"诺玛遗址4层_D1604", .endX = 299, .endY = 258},
        {.x = 314, .y = 250, .endName = u8"诺玛遗址4层_D1604", .endX = 299, .endY = 258},
        {.x = 323, .y = 259, .endName = u8"诺玛遗址4层_D1604", .endX = 336, .endY = 230},
        {.x = 323, .y = 260, .endName = u8"诺玛遗址4层_D1604", .endX = 336, .endY = 230},
        {.x = 336, .y = 199, .endName = u8"诺玛遗址4层_D1604", .endX = 64, .endY = 180},
        {.x = 336, .y = 199, .endName = u8"诺玛遗址4层_D1604", .endX = 64, .endY = 180},
        {.x = 345, .y = 208, .endName = u8"诺玛遗址4层_D1604", .endX = 268, .endY = 231},
        {.x = 345, .y = 209, .endName = u8"诺玛遗址4层_D1604", .endX = 268, .endY = 231},
        {.x = 363, .y = 199, .endName = u8"诺玛遗址4层_D1604", .endX = 290, .endY = 198},
        {.x = 363, .y = 199, .endName = u8"诺玛遗址4层_D1604", .endX = 290, .endY = 198},
        {.x = 372, .y = 208, .endName = u8"诺玛遗址4层_D1604", .endX = 310, .endY = 222},
        {.x = 372, .y = 209, .endName = u8"诺玛遗址4层_D1604", .endX = 310, .endY = 222},
        {.x = 337, .y = 231, .endName = u8"诺玛遗址4层_D1604", .endX = 75, .endY = 225},
        {.x = 337, .y = 231, .endName = u8"诺玛遗址4层_D1604", .endX = 75, .endY = 225},
        {.x = 346, .y = 240, .endName = u8"诺玛遗址4层_D1604", .endX = 268, .endY = 231},
        {.x = 346, .y = 241, .endName = u8"诺玛遗址4层_D1604", .endX = 268, .endY = 231},
        {.x = 196, .y = 229, .endName = u8"诺玛遗址4层_D1604", .endX = 239, .endY = 294},
        {.x = 196, .y = 229, .endName = u8"诺玛遗址4层_D1604", .endX = 239, .endY = 294},
        {.x = 205, .y = 238, .endName = u8"诺玛遗址4层_D1604", .endX = 181, .endY = 349},
        {.x = 205, .y = 239, .endName = u8"诺玛遗址4层_D1604", .endX = 181, .endY = 349},
        {.x = 174, .y = 252, .endName = u8"诺玛遗址4层_D1604", .endX = 234, .endY = 324},
        {.x = 174, .y = 252, .endName = u8"诺玛遗址4层_D1604", .endX = 234, .endY = 324},
        {.x = 183, .y = 261, .endName = u8"诺玛遗址4层_D1604", .endX = 161, .endY = 59},
        {.x = 183, .y = 262, .endName = u8"诺玛遗址4层_D1604", .endX = 161, .endY = 59},
        {.x = 154, .y = 280, .endName = u8"诺玛遗址4层_D1604", .endX = 205, .endY = 330},
        {.x = 154, .y = 280, .endName = u8"诺玛遗址4层_D1604", .endX = 205, .endY = 330},
        {.x = 163, .y = 289, .endName = u8"诺玛遗址4层_D1604", .endX = 125, .endY = 235},
        {.x = 163, .y = 290, .endName = u8"诺玛遗址4层_D1604", .endX = 125, .endY = 235},
        {.x = 130, .y = 298, .endName = u8"诺玛遗址5层_D1605", .endX = 113, .endY = 96},
        {.x = 130, .y = 298, .endName = u8"诺玛遗址5层_D1605", .endX = 113, .endY = 96},
        {.x = 139, .y = 307, .endName = u8"诺玛遗址4层_D1604", .endX = 194, .endY = 258},
        {.x = 139, .y = 308, .endName = u8"诺玛遗址4层_D1604", .endX = 194, .endY = 258},
        {.x = 150, .y = 313, .endName = u8"诺玛遗址4层_D1604", .endX = 245, .endY = 339},
        {.x = 150, .y = 313, .endName = u8"诺玛遗址4层_D1604", .endX = 245, .endY = 339},
        {.x = 159, .y = 322, .endName = u8"诺玛遗址4层_D1604", .endX = 253, .endY = 172},
        {.x = 159, .y = 323, .endName = u8"诺玛遗址4层_D1604", .endX = 253, .endY = 172},
        {.x = 175, .y = 288, .endName = u8"诺玛遗址4层_D1604", .endX = 262, .endY = 298},
        {.x = 175, .y = 288, .endName = u8"诺玛遗址4层_D1604", .endX = 262, .endY = 298},
        {.x = 184, .y = 297, .endName = u8"诺玛遗址4层_D1604", .endX = 251, .endY = 287},
        {.x = 184, .y = 298, .endName = u8"诺玛遗址4层_D1604", .endX = 251, .endY = 287},
        {.x = 195, .y = 259, .endName = u8"诺玛遗址4层_D1604", .endX = 160, .endY = 323},
        {.x = 195, .y = 259, .endName = u8"诺玛遗址4层_D1604", .endX = 160, .endY = 323},
        {.x = 204, .y = 268, .endName = u8"诺玛遗址4层_D1604", .endX = 129, .endY = 297},
        {.x = 204, .y = 269, .endName = u8"诺玛遗址4层_D1604", .endX = 129, .endY = 297},
        {.x = 225, .y = 258, .endName = u8"诺玛遗址5层_D1605", .endX = 113, .endY = 96},
        {.x = 225, .y = 258, .endName = u8"诺玛遗址5层_D1605", .endX = 113, .endY = 96},
        {.x = 234, .y = 267, .endName = u8"诺玛遗址4层_D1604", .endX = 223, .endY = 313},
        {.x = 234, .y = 268, .endName = u8"诺玛遗址4层_D1604", .endX = 223, .endY = 313},
        {.x = 202, .y = 287, .endName = u8"诺玛遗址4层_D1604", .endX = 267, .endY = 320},
        {.x = 202, .y = 287, .endName = u8"诺玛遗址4层_D1604", .endX = 267, .endY = 320},
        {.x = 211, .y = 296, .endName = u8"诺玛遗址4层_D1604", .endX = 234, .endY = 328},
        {.x = 211, .y = 297, .endName = u8"诺玛遗址4层_D1604", .endX = 234, .endY = 328},
        {.x = 171, .y = 319, .endName = u8"诺玛遗址4层_D1604", .endX = 373, .endY = 209},
        {.x = 171, .y = 319, .endName = u8"诺玛遗址4层_D1604", .endX = 373, .endY = 209},
        {.x = 180, .y = 328, .endName = u8"诺玛遗址4层_D1604", .endX = 195, .endY = 228},
        {.x = 180, .y = 329, .endName = u8"诺玛遗址4层_D1604", .endX = 195, .endY = 228},
        {.x = 182, .y = 350, .endName = u8"诺玛遗址4层_D1604", .endX = 192, .endY = 360},
        {.x = 182, .y = 350, .endName = u8"诺玛遗址4层_D1604", .endX = 192, .endY = 360},
        {.x = 191, .y = 359, .endName = u8"诺玛遗址4层_D1604", .endX = 181, .endY = 349},
        {.x = 191, .y = 360, .endName = u8"诺玛遗址4层_D1604", .endX = 181, .endY = 349},
        {.x = 195, .y = 320, .endName = u8"诺玛遗址4层_D1604", .endX = 220, .endY = 355},
        {.x = 195, .y = 320, .endName = u8"诺玛遗址4层_D1604", .endX = 220, .endY = 355},
        {.x = 204, .y = 329, .endName = u8"诺玛遗址4层_D1604", .endX = 181, .endY = 145},
        {.x = 204, .y = 330, .endName = u8"诺玛遗址4层_D1604", .endX = 181, .endY = 145},
        {.x = 224, .y = 314, .endName = u8"诺玛遗址4层_D1604", .endX = 181, .endY = 329},
        {.x = 224, .y = 314, .endName = u8"诺玛遗址4层_D1604", .endX = 181, .endY = 329},
        {.x = 233, .y = 323, .endName = u8"诺玛遗址4层_D1604", .endX = 149, .endY = 312},
        {.x = 233, .y = 324, .endName = u8"诺玛遗址4层_D1604", .endX = 149, .endY = 312},
        {.x = 229, .y = 284, .endName = u8"诺玛遗址4层_D1604", .endX = 324, .endY = 260},
        {.x = 229, .y = 284, .endName = u8"诺玛遗址4层_D1604", .endX = 324, .endY = 260},
        {.x = 238, .y = 293, .endName = u8"诺玛遗址4层_D1604", .endX = 195, .endY = 228},
        {.x = 238, .y = 294, .endName = u8"诺玛遗址4层_D1604", .endX = 195, .endY = 228},
        {.x = 252, .y = 288, .endName = u8"诺玛遗址4层_D1604", .endX = 140, .endY = 308},
        {.x = 252, .y = 288, .endName = u8"诺玛遗址4层_D1604", .endX = 140, .endY = 308},
        {.x = 261, .y = 297, .endName = u8"诺玛遗址4层_D1604", .endX = 173, .endY = 251},
        {.x = 261, .y = 298, .endName = u8"诺玛遗址4层_D1604", .endX = 173, .endY = 251},
        {.x = 257, .y = 310, .endName = u8"诺玛遗址4层_D1604", .endX = 244, .endY = 94},
        {.x = 257, .y = 310, .endName = u8"诺玛遗址4层_D1604", .endX = 244, .endY = 94},
        {.x = 266, .y = 319, .endName = u8"诺玛遗址4层_D1604", .endX = 181, .endY = 349},
        {.x = 266, .y = 320, .endName = u8"诺玛遗址4层_D1604", .endX = 181, .endY = 349},
        {.x = 235, .y = 329, .endName = u8"诺玛遗址4层_D1604", .endX = 185, .endY = 298},
        {.x = 235, .y = 329, .endName = u8"诺玛遗址4层_D1604", .endX = 185, .endY = 298},
        {.x = 244, .y = 338, .endName = u8"诺玛遗址4层_D1604", .endX = 149, .endY = 312},
        {.x = 244, .y = 339, .endName = u8"诺玛遗址4层_D1604", .endX = 149, .endY = 312},
        {.x = 210, .y = 345, .endName = u8"诺玛遗址5层_D1605", .endX = 113, .endY = 96},
        {.x = 210, .y = 345, .endName = u8"诺玛遗址5层_D1605", .endX = 113, .endY = 96},
        {.x = 219, .y = 354, .endName = u8"诺玛遗址4层_D1604", .endX = 326, .endY = 160},
        {.x = 219, .y = 355, .endName = u8"诺玛遗址4层_D1604", .endX = 326, .endY = 160},
    }
},

{   .name = u8"诺玛遗址5层_d1605",
    .miniMapID = 0X19000307,
    .mapSwitchList
    {
        {.x = 112, .y = 95, .endName = u8"诺玛遗址4层_D1604", .endX = 190, .endY = 177},
        {.x = 112, .y = 96, .endName = u8"诺玛遗址4层_D1604", .endX = 190, .endY = 177},
        {.x = 184, .y = 23, .endName = u8"诺玛遗址5层_D1605", .endX = 190, .endY = 76},
        {.x = 184, .y = 24, .endName = u8"诺玛遗址5层_D1605", .endX = 190, .endY = 76},
        {.x = 172, .y = 35, .endName = u8"诺玛遗址5层_D1605", .endX = 126, .endY = 101},
        {.x = 172, .y = 36, .endName = u8"诺玛遗址5层_D1605", .endX = 126, .endY = 101},
        {.x = 160, .y = 47, .endName = u8"诺玛遗址5层_D1605", .endX = 62, .endY = 244},
        {.x = 160, .y = 48, .endName = u8"诺玛遗址5层_D1605", .endX = 62, .endY = 244},
        {.x = 148, .y = 59, .endName = u8"诺玛遗址4层_D1604", .endX = 181, .endY = 116},
        {.x = 148, .y = 60, .endName = u8"诺玛遗址4层_D1604", .endX = 181, .endY = 116},
        {.x = 136, .y = 71, .endName = u8"诺玛遗址5层_D1605", .endX = 146, .endY = 159},
        {.x = 136, .y = 72, .endName = u8"诺玛遗址5层_D1605", .endX = 146, .endY = 159},
        {.x = 124, .y = 83, .endName = u8"诺玛遗址5层_D1605", .endX = 194, .endY = 111},
        {.x = 124, .y = 84, .endName = u8"诺玛遗址5层_D1605", .endX = 194, .endY = 111},
        {.x = 100, .y = 107, .endName = u8"诺玛遗址5层_D1605", .endX = 106, .endY = 160},
        {.x = 100, .y = 108, .endName = u8"诺玛遗址5层_D1605", .endX = 106, .endY = 160},
        {.x = 88, .y = 119, .endName = u8"诺玛遗址5层_D1605", .endX = 62, .endY = 244},
        {.x = 88, .y = 120, .endName = u8"诺玛遗址5层_D1605", .endX = 62, .endY = 244},
        {.x = 76, .y = 131, .endName = u8"诺玛遗址5层_D1605", .endX = 174, .endY = 53},
        {.x = 76, .y = 132, .endName = u8"诺玛遗址5层_D1605", .endX = 174, .endY = 53},
        {.x = 64, .y = 143, .endName = u8"诺玛遗址5层_D1605", .endX = 42, .endY = 185},
        {.x = 64, .y = 144, .endName = u8"诺玛遗址5层_D1605", .endX = 42, .endY = 185},
        {.x = 52, .y = 155, .endName = u8"诺玛遗址5层_D1605", .endX = 298, .endY = 163},
        {.x = 52, .y = 156, .endName = u8"诺玛遗址5层_D1605", .endX = 298, .endY = 163},
        {.x = 40, .y = 167, .endName = u8"诺玛遗址5层_D1605", .endX = 174, .endY = 53},
        {.x = 40, .y = 168, .endName = u8"诺玛遗址5层_D1605", .endX = 174, .endY = 53},
        {.x = 28, .y = 179, .endName = u8"诺玛遗址5层_D1605", .endX = 138, .endY = 89},
        {.x = 28, .y = 180, .endName = u8"诺玛遗址5层_D1605", .endX = 138, .endY = 89},
        {.x = 16, .y = 191, .endName = u8"诺玛遗址5层_D1605", .endX = 86, .endY = 219},
        {.x = 16, .y = 192, .endName = u8"诺玛遗址5层_D1605", .endX = 86, .endY = 219},
        {.x = 208, .y = 38, .endName = u8"诺玛遗址5层_D1605", .endX = 206, .endY = 99},
        {.x = 208, .y = 39, .endName = u8"诺玛遗址5层_D1605", .endX = 206, .endY = 99},
        {.x = 196, .y = 50, .endName = u8"诺玛遗址5层_D1605", .endX = 86, .endY = 219},
        {.x = 196, .y = 51, .endName = u8"诺玛遗址5层_D1605", .endX = 86, .endY = 219},
        {.x = 184, .y = 62, .endName = u8"诺玛遗址5层_D1605", .endX = 138, .endY = 89},
        {.x = 184, .y = 63, .endName = u8"诺玛遗址5层_D1605", .endX = 138, .endY = 89},
        {.x = 172, .y = 74, .endName = u8"诺玛遗址5层_D1605", .endX = 186, .endY = 158},
        {.x = 172, .y = 75, .endName = u8"诺玛遗址5层_D1605", .endX = 186, .endY = 158},
        {.x = 160, .y = 86, .endName = u8"诺玛遗址5层_D1605", .endX = 218, .endY = 87},
        {.x = 160, .y = 87, .endName = u8"诺玛遗址5层_D1605", .endX = 218, .endY = 87},
        {.x = 148, .y = 98, .endName = u8"诺玛遗址5层_D1605", .endX = 194, .endY = 111},
        {.x = 148, .y = 99, .endName = u8"诺玛遗址5层_D1605", .endX = 194, .endY = 111},
        {.x = 136, .y = 110, .endName = u8"诺玛遗址5层_D1605", .endX = 102, .endY = 125},
        {.x = 136, .y = 111, .endName = u8"诺玛遗址5层_D1605", .endX = 102, .endY = 125},
        {.x = 124, .y = 122, .endName = u8"诺玛遗址5层_D1605", .endX = 134, .endY = 171},
        {.x = 124, .y = 123, .endName = u8"诺玛遗址5层_D1605", .endX = 134, .endY = 171},
        {.x = 112, .y = 134, .endName = u8"诺玛遗址5层_D1605", .endX = 202, .endY = 64},
        {.x = 112, .y = 135, .endName = u8"诺玛遗址5层_D1605", .endX = 202, .endY = 64},
        {.x = 100, .y = 146, .endName = u8"诺玛遗址5层_D1605", .endX = 54, .endY = 173},
        {.x = 100, .y = 147, .endName = u8"诺玛遗址5层_D1605", .endX = 54, .endY = 173},
        {.x = 88, .y = 158, .endName = u8"诺玛遗址4层_D1604", .endX = 335, .endY = 198},
        {.x = 88, .y = 159, .endName = u8"诺玛遗址4层_D1604", .endX = 335, .endY = 198},
        {.x = 76, .y = 170, .endName = u8"诺玛遗址5层_D1605", .endX = 30, .endY = 197},
        {.x = 76, .y = 171, .endName = u8"诺玛遗址5层_D1605", .endX = 30, .endY = 197},
        {.x = 64, .y = 182, .endName = u8"诺玛遗址5层_D1605", .endX = 178, .endY = 88},
        {.x = 64, .y = 183, .endName = u8"诺玛遗址5层_D1605", .endX = 178, .endY = 88},
        {.x = 52, .y = 194, .endName = u8"诺玛遗址5层_D1605", .endX = 190, .endY = 76},
        {.x = 52, .y = 195, .endName = u8"诺玛遗址5层_D1605", .endX = 190, .endY = 76},
        {.x = 40, .y = 206, .endName = u8"诺玛遗址5层_D1605", .endX = 174, .endY = 53},
        {.x = 40, .y = 207, .endName = u8"诺玛遗址5层_D1605", .endX = 174, .endY = 53},
        {.x = 28, .y = 218, .endName = u8"诺玛遗址5层_D1605", .endX = 78, .endY = 149},
        {.x = 28, .y = 219, .endName = u8"诺玛遗址5层_D1605", .endX = 78, .endY = 149},
        {.x = 228, .y = 57, .endName = u8"诺玛遗址5层_D1605", .endX = 34, .endY = 232},
        {.x = 228, .y = 58, .endName = u8"诺玛遗址5层_D1605", .endX = 34, .endY = 232},
        {.x = 216, .y = 69, .endName = u8"诺玛遗址5层_D1605", .endX = 298, .endY = 163},
        {.x = 216, .y = 70, .endName = u8"诺玛遗址5层_D1605", .endX = 298, .endY = 163},
        {.x = 204, .y = 81, .endName = u8"诺玛遗址5层_D1605", .endX = 54, .endY = 173},
        {.x = 204, .y = 82, .endName = u8"诺玛遗址5层_D1605", .endX = 54, .endY = 173},
        {.x = 192, .y = 93, .endName = u8"诺玛遗址5层_D1605", .endX = 30, .endY = 197},
        {.x = 192, .y = 94, .endName = u8"诺玛遗址5层_D1605", .endX = 30, .endY = 197},
        {.x = 180, .y = 105, .endName = u8"诺玛遗址5层_D1605", .endX = 142, .endY = 124},
        {.x = 180, .y = 106, .endName = u8"诺玛遗址5层_D1605", .endX = 142, .endY = 124},
        {.x = 168, .y = 117, .endName = u8"诺玛遗址5层_D1605", .endX = 106, .endY = 160},
        {.x = 168, .y = 118, .endName = u8"诺玛遗址5层_D1605", .endX = 106, .endY = 160},
        {.x = 156, .y = 129, .endName = u8"诺玛遗址4层_D1604", .endX = 75, .endY = 181},
        {.x = 156, .y = 130, .endName = u8"诺玛遗址4层_D1604", .endX = 75, .endY = 181},
        {.x = 144, .y = 141, .endName = u8"诺玛遗址5层_D1605", .endX = 158, .endY = 147},
        {.x = 144, .y = 142, .endName = u8"诺玛遗址5层_D1605", .endX = 158, .endY = 147},
        {.x = 132, .y = 153, .endName = u8"诺玛遗址5层_D1605", .endX = 154, .endY = 112},
        {.x = 132, .y = 154, .endName = u8"诺玛遗址5层_D1605", .endX = 154, .endY = 112},
        {.x = 120, .y = 165, .endName = u8"诺玛遗址5层_D1605", .endX = 230, .endY = 75},
        {.x = 120, .y = 166, .endName = u8"诺玛遗址5层_D1605", .endX = 230, .endY = 75},
        {.x = 108, .y = 177, .endName = u8"诺玛遗址5层_D1605", .endX = 146, .endY = 159},
        {.x = 108, .y = 178, .endName = u8"诺玛遗址5层_D1605", .endX = 146, .endY = 159},
        {.x = 96, .y = 189, .endName = u8"诺玛遗址5层_D1605", .endX = 46, .endY = 220},
        {.x = 96, .y = 190, .endName = u8"诺玛遗址5层_D1605", .endX = 46, .endY = 220},
        {.x = 84, .y = 201, .endName = u8"诺玛遗址5层_D1605", .endX = 118, .endY = 148},
        {.x = 84, .y = 202, .endName = u8"诺玛遗址5层_D1605", .endX = 118, .endY = 148},
        {.x = 72, .y = 213, .endName = u8"诺玛遗址5层_D1605", .endX = 154, .endY = 112},
        {.x = 72, .y = 214, .endName = u8"诺玛遗址5层_D1605", .endX = 154, .endY = 112},
        {.x = 60, .y = 225, .endName = u8"诺玛遗址5层_D1605", .endX = 230, .endY = 75},
        {.x = 60, .y = 226, .endName = u8"诺玛遗址5层_D1605", .endX = 230, .endY = 75},
        {.x = 48, .y = 237, .endName = u8"诺玛遗址5层_D1605", .endX = 178, .endY = 88},
        {.x = 48, .y = 238, .endName = u8"诺玛遗址5层_D1605", .endX = 178, .endY = 88},
        {.x = 248, .y = 76, .endName = u8"诺玛遗址5层_D1605", .endX = 90, .endY = 137},
        {.x = 248, .y = 77, .endName = u8"诺玛遗址5层_D1605", .endX = 90, .endY = 137},
        {.x = 236, .y = 88, .endName = u8"诺玛遗址5层_D1605", .endX = 170, .endY = 135},
        {.x = 236, .y = 89, .endName = u8"诺玛遗址5层_D1605", .endX = 170, .endY = 135},
        {.x = 224, .y = 100, .endName = u8"诺玛遗址5层_D1605", .endX = 258, .endY = 86},
        {.x = 224, .y = 101, .endName = u8"诺玛遗址5层_D1605", .endX = 258, .endY = 86},
        {.x = 212, .y = 112, .endName = u8"诺玛遗址5层_D1605", .endX = 66, .endY = 161},
        {.x = 212, .y = 113, .endName = u8"诺玛遗址5层_D1605", .endX = 66, .endY = 161},
        {.x = 200, .y = 124, .endName = u8"诺玛遗址5层_D1605", .endX = 114, .endY = 309},
        {.x = 200, .y = 125, .endName = u8"诺玛遗址5层_D1605", .endX = 114, .endY = 309},
        {.x = 188, .y = 136, .endName = u8"诺玛遗址5层_D1605", .endX = 290, .endY = 132},
        {.x = 188, .y = 137, .endName = u8"诺玛遗址5层_D1605", .endX = 290, .endY = 132},
        {.x = 176, .y = 148, .endName = u8"诺玛遗址5层_D1605", .endX = 185, .endY = 24},
        {.x = 176, .y = 149, .endName = u8"诺玛遗址5层_D1605", .endX = 185, .endY = 24},
        {.x = 164, .y = 160, .endName = u8"诺玛遗址5层_D1605", .endX = 78, .endY = 266},
        {.x = 164, .y = 161, .endName = u8"诺玛遗址5层_D1605", .endX = 78, .endY = 266},
        {.x = 152, .y = 172, .endName = u8"诺玛遗址5层_D1605", .endX = 150, .endY = 77},
        {.x = 152, .y = 173, .endName = u8"诺玛遗址5层_D1605", .endX = 150, .endY = 77},
        {.x = 140, .y = 184, .endName = u8"诺玛遗址5层_D1605", .endX = 166, .endY = 100},
        {.x = 140, .y = 185, .endName = u8"诺玛遗址5层_D1605", .endX = 166, .endY = 100},
        {.x = 128, .y = 196, .endName = u8"诺玛遗址4层_D1604", .endX = 194, .endY = 319},
        {.x = 128, .y = 197, .endName = u8"诺玛遗址4层_D1604", .endX = 194, .endY = 319},
        {.x = 116, .y = 208, .endName = u8"诺玛遗址5层_D1605", .endX = 94, .endY = 172},
        {.x = 116, .y = 209, .endName = u8"诺玛遗址5层_D1605", .endX = 94, .endY = 172},
        {.x = 104, .y = 220, .endName = u8"诺玛遗址5层_D1605", .endX = 214, .endY = 52},
        {.x = 104, .y = 221, .endName = u8"诺玛遗址5层_D1605", .endX = 214, .endY = 52},
        {.x = 92, .y = 232, .endName = u8"诺玛遗址5层_D1605", .endX = 157, .endY = 130},
        {.x = 92, .y = 233, .endName = u8"诺玛遗址5层_D1605", .endX = 157, .endY = 130},
        {.x = 80, .y = 244, .endName = u8"诺玛遗址5层_D1605", .endX = 122, .endY = 183},
        {.x = 80, .y = 245, .endName = u8"诺玛遗址5层_D1605", .endX = 122, .endY = 183},
        {.x = 68, .y = 256, .endName = u8"诺玛遗址5层_D1605", .endX = 70, .endY = 196},
        {.x = 68, .y = 257, .endName = u8"诺玛遗址5层_D1605", .endX = 70, .endY = 196},
        {.x = 268, .y = 95, .endName = u8"诺玛遗址5层_D1605", .endX = 98, .endY = 207},
        {.x = 268, .y = 96, .endName = u8"诺玛遗址5层_D1605", .endX = 98, .endY = 207},
        {.x = 256, .y = 107, .endName = u8"诺玛遗址5层_D1605", .endX = 126, .endY = 218},
        {.x = 256, .y = 108, .endName = u8"诺玛遗址5层_D1605", .endX = 126, .endY = 218},
        {.x = 244, .y = 119, .endName = u8"诺玛遗址5层_D1605", .endX = 174, .endY = 170},
        {.x = 244, .y = 120, .endName = u8"诺玛遗址5层_D1605", .endX = 174, .endY = 170},
        {.x = 232, .y = 131, .endName = u8"诺玛遗址5层_D1605", .endX = 186, .endY = 41},
        {.x = 232, .y = 132, .endName = u8"诺玛遗址5层_D1605", .endX = 186, .endY = 41},
        {.x = 288, .y = 114, .endName = u8"诺玛遗址5层_D1605", .endX = 130, .endY = 136},
        {.x = 288, .y = 115, .endName = u8"诺玛遗址5层_D1605", .endX = 130, .endY = 136},
        {.x = 276, .y = 126, .endName = u8"诺玛遗址5层_D1605", .endX = 306, .endY = 193},
        {.x = 276, .y = 127, .endName = u8"诺玛遗址5层_D1605", .endX = 306, .endY = 193},
        {.x = 264, .y = 138, .endName = u8"诺玛遗址5层_D1605", .endX = 310, .endY = 151},
        {.x = 264, .y = 139, .endName = u8"诺玛遗址5层_D1605", .endX = 310, .endY = 151},
        {.x = 252, .y = 150, .endName = u8"诺玛遗址5层_D1605", .endX = 242, .endY = 63},
        {.x = 252, .y = 151, .endName = u8"诺玛遗址5层_D1605", .endX = 242, .endY = 63},
        {.x = 308, .y = 133, .endName = u8"诺玛遗址5层_D1605", .endX = 114, .endY = 230},
        {.x = 308, .y = 134, .endName = u8"诺玛遗址5层_D1605", .endX = 114, .endY = 230},
        {.x = 296, .y = 145, .endName = u8"诺玛遗址5层_D1605", .endX = 74, .endY = 231},
        {.x = 296, .y = 146, .endName = u8"诺玛遗址5层_D1605", .endX = 74, .endY = 231},
        {.x = 284, .y = 157, .endName = u8"诺玛遗址5层_D1605", .endX = 198, .endY = 146},
        {.x = 284, .y = 158, .endName = u8"诺玛遗址5层_D1605", .endX = 198, .endY = 146},
        {.x = 272, .y = 169, .endName = u8"诺玛遗址5层_D1605", .endX = 198, .endY = 29},
        {.x = 272, .y = 170, .endName = u8"诺玛遗址5层_D1605", .endX = 198, .endY = 29},
        {.x = 328, .y = 151, .endName = u8"诺玛遗址5层_D1605", .endX = 210, .endY = 134},
        {.x = 328, .y = 152, .endName = u8"诺玛遗址5层_D1605", .endX = 210, .endY = 134},
        {.x = 316, .y = 163, .endName = u8"诺玛遗址5层_D1605", .endX = 270, .endY = 113},
        {.x = 316, .y = 164, .endName = u8"诺玛遗址5层_D1605", .endX = 270, .endY = 113},
        {.x = 304, .y = 175, .endName = u8"诺玛遗址5层_D1605", .endX = 266, .endY = 156},
        {.x = 304, .y = 176, .endName = u8"诺玛遗址5层_D1605", .endX = 266, .endY = 156},
        {.x = 292, .y = 187, .endName = u8"诺玛遗址5层_D1605", .endX = 82, .endY = 184},
        {.x = 292, .y = 188, .endName = u8"诺玛遗址5层_D1605", .endX = 82, .endY = 184},
        {.x = 348, .y = 170, .endName = u8"诺玛遗址5层_D1605", .endX = 322, .endY = 139},
        {.x = 348, .y = 171, .endName = u8"诺玛遗址5层_D1605", .endX = 322, .endY = 139},
        {.x = 336, .y = 182, .endName = u8"诺玛遗址5层_D1605", .endX = 258, .endY = 125},
        {.x = 336, .y = 183, .endName = u8"诺玛遗址5层_D1605", .endX = 258, .endY = 125},
        {.x = 324, .y = 194, .endName = u8"诺玛遗址5层_D1605", .endX = 350, .endY = 188},
        {.x = 324, .y = 195, .endName = u8"诺玛遗址5层_D1605", .endX = 350, .endY = 188},
        {.x = 312, .y = 206, .endName = u8"诺玛遗址5层_D1605", .endX = 90, .endY = 254},
        {.x = 312, .y = 217, .endName = u8"诺玛遗址5层_D1605", .endX = 90, .endY = 254},
        {.x = 112, .y = 251, .endName = u8"诺玛遗址5层_D1605", .endX = 350, .endY = 188},
        {.x = 112, .y = 252, .endName = u8"诺玛遗址5层_D1605", .endX = 350, .endY = 188},
        {.x = 100, .y = 263, .endName = u8"诺玛遗址5层_D1605", .endX = 156, .endY = 356},
        {.x = 100, .y = 264, .endName = u8"诺玛遗址5层_D1605", .endX = 156, .endY = 356},
        {.x = 88, .y = 275, .endName = u8"诺玛遗址5层_D1605", .endX = 138, .endY = 324},
        {.x = 88, .y = 276, .endName = u8"诺玛遗址5层_D1605", .endX = 138, .endY = 324},
        {.x = 76, .y = 287, .endName = u8"诺玛遗址5层_D1605", .endX = 102, .endY = 320},
        {.x = 76, .y = 288, .endName = u8"诺玛遗址5层_D1605", .endX = 102, .endY = 320},
        {.x = 132, .y = 270, .endName = u8"诺玛遗址5层_D1605", .endX = 342, .endY = 157},
        {.x = 132, .y = 271, .endName = u8"诺玛遗址5层_D1605", .endX = 342, .endY = 157},
        {.x = 120, .y = 282, .endName = u8"诺玛遗址5层_D1605", .endX = 151, .endY = 194},
        {.x = 120, .y = 283, .endName = u8"诺玛遗址5层_D1605", .endX = 151, .endY = 194},
        {.x = 108, .y = 294, .endName = u8"诺玛遗址5层_D1605", .endX = 58, .endY = 208},
        {.x = 108, .y = 295, .endName = u8"诺玛遗址5层_D1605", .endX = 58, .endY = 208},
        {.x = 96, .y = 306, .endName = u8"诺玛遗址5层_D1605", .endX = 330, .endY = 169},
        {.x = 96, .y = 307, .endName = u8"诺玛遗址5层_D1605", .endX = 330, .endY = 169},
        {.x = 156, .y = 286, .endName = u8"诺玛遗址5层_D1605", .endX = 278, .endY = 144},
        {.x = 156, .y = 287, .endName = u8"诺玛遗址5层_D1605", .endX = 278, .endY = 144},
        {.x = 144, .y = 298, .endName = u8"诺玛遗址5层_D1605", .endX = 110, .endY = 195},
        {.x = 144, .y = 299, .endName = u8"诺玛遗址5层_D1605", .endX = 110, .endY = 195},
        {.x = 132, .y = 310, .endName = u8"诺玛遗址5层_D1605", .endX = 102, .endY = 281},
        {.x = 132, .y = 311, .endName = u8"诺玛遗址5层_D1605", .endX = 102, .endY = 281},
        {.x = 120, .y = 322, .endName = u8"诺玛遗址5层_D1605", .endX = 138, .endY = 284},
        {.x = 120, .y = 323, .endName = u8"诺玛遗址5层_D1605", .endX = 138, .endY = 284},
        {.x = 176, .y = 306, .endName = u8"诺玛遗址5层_D1605", .endX = 126, .endY = 336},
        {.x = 176, .y = 307, .endName = u8"诺玛遗址5层_D1605", .endX = 126, .endY = 336},
        {.x = 164, .y = 318, .endName = u8"诺玛遗址5层_D1605", .endX = 302, .endY = 120},
        {.x = 164, .y = 319, .endName = u8"诺玛遗址5层_D1605", .endX = 302, .endY = 120},
        {.x = 152, .y = 330, .endName = u8"诺玛遗址5层_D1605", .endX = 150, .endY = 312},
        {.x = 152, .y = 331, .endName = u8"诺玛遗址5层_D1605", .endX = 150, .endY = 312},
        {.x = 140, .y = 342, .endName = u8"诺玛遗址5层_D1605", .endX = 162, .endY = 65},
        {.x = 140, .y = 343, .endName = u8"诺玛遗址5层_D1605", .endX = 162, .endY = 65},
        {.x = 196, .y = 326, .endName = u8"诺玛遗址5层_D1605", .endX = 126, .endY = 296},
        {.x = 196, .y = 327, .endName = u8"诺玛遗址5层_D1605", .endX = 126, .endY = 296},
        {.x = 184, .y = 338, .endName = u8"诺玛遗址5层_D1605", .endX = 170, .endY = 332},
        {.x = 184, .y = 339, .endName = u8"诺玛遗址5层_D1605", .endX = 170, .endY = 332},
        {.x = 172, .y = 350, .endName = u8"诺玛遗址5层_D1605", .endX = 286, .endY = 175},
        {.x = 172, .y = 351, .endName = u8"诺玛遗址5层_D1605", .endX = 286, .endY = 175},
        {.x = 160, .y = 362, .endName = u8"诺玛遗址5层_D1605", .endX = 162, .endY = 300},
        {.x = 160, .y = 363, .endName = u8"诺玛遗址5层_D1605", .endX = 162, .endY = 300},
        {.x = 199, .y = 29, .endName = u8"诺玛遗址5层_D1605", .endX = 132, .endY = 154},
        {.x = 199, .y = 30, .endName = u8"诺玛遗址5层_D1605", .endX = 132, .endY = 154},
        {.x = 187, .y = 41, .endName = u8"诺玛遗址5层_D1605", .endX = 149, .endY = 99},
        {.x = 187, .y = 42, .endName = u8"诺玛遗址5层_D1605", .endX = 149, .endY = 99},
        {.x = 175, .y = 53, .endName = u8"诺玛遗址5层_D1605", .endX = 49, .endY = 238},
        {.x = 175, .y = 54, .endName = u8"诺玛遗址5层_D1605", .endX = 49, .endY = 238},
        {.x = 163, .y = 65, .endName = u8"诺玛遗址5层_D1605", .endX = 61, .endY = 226},
        {.x = 163, .y = 66, .endName = u8"诺玛遗址5层_D1605", .endX = 61, .endY = 226},
        {.x = 151, .y = 77, .endName = u8"诺玛遗址5层_D1605", .endX = 61, .endY = 226},
        {.x = 151, .y = 78, .endName = u8"诺玛遗址5层_D1605", .endX = 61, .endY = 226},
        {.x = 139, .y = 89, .endName = u8"诺玛遗址5层_D1605", .endX = 149, .endY = 99},
        {.x = 139, .y = 90, .endName = u8"诺玛遗址5层_D1605", .endX = 149, .endY = 99},
        {.x = 127, .y = 101, .endName = u8"诺玛遗址5层_D1605", .endX = 121, .endY = 166},
        {.x = 127, .y = 102, .endName = u8"诺玛遗址5层_D1605", .endX = 121, .endY = 166},
        {.x = 103, .y = 125, .endName = u8"诺玛遗址5层_D1605", .endX = 161, .endY = 48},
        {.x = 103, .y = 126, .endName = u8"诺玛遗址5层_D1605", .endX = 161, .endY = 48},
        {.x = 91, .y = 137, .endName = u8"诺玛遗址5层_D1605", .endX = 121, .endY = 166},
        {.x = 91, .y = 138, .endName = u8"诺玛遗址5层_D1605", .endX = 121, .endY = 166},
        {.x = 79, .y = 149, .endName = u8"诺玛遗址5层_D1605", .endX = 193, .endY = 94},
        {.x = 79, .y = 150, .endName = u8"诺玛遗址5层_D1605", .endX = 193, .endY = 94},
        {.x = 67, .y = 161, .endName = u8"诺玛遗址5层_D1605", .endX = 97, .endY = 190},
        {.x = 67, .y = 162, .endName = u8"诺玛遗址5层_D1605", .endX = 97, .endY = 190},
        {.x = 55, .y = 173, .endName = u8"诺玛遗址5层_D1605", .endX = 65, .endY = 183},
        {.x = 55, .y = 174, .endName = u8"诺玛遗址5层_D1605", .endX = 65, .endY = 183},
        {.x = 43, .y = 185, .endName = u8"诺玛遗址5层_D1605", .endX = 77, .endY = 132},
        {.x = 43, .y = 186, .endName = u8"诺玛遗址5层_D1605", .endX = 77, .endY = 132},
        {.x = 31, .y = 197, .endName = u8"诺玛遗址5层_D1605", .endX = 101, .endY = 108},
        {.x = 31, .y = 198, .endName = u8"诺玛遗址5层_D1605", .endX = 101, .endY = 108},
        {.x = 215, .y = 52, .endName = u8"诺玛遗址5层_D1605", .endX = 149, .endY = 99},
        {.x = 215, .y = 53, .endName = u8"诺玛遗址5层_D1605", .endX = 149, .endY = 99},
        {.x = 203, .y = 64, .endName = u8"诺玛遗址5层_D1605", .endX = 197, .endY = 51},
        {.x = 203, .y = 65, .endName = u8"诺玛遗址5层_D1605", .endX = 197, .endY = 51},
        {.x = 191, .y = 76, .endName = u8"诺玛遗址5层_D1605", .endX = 149, .endY = 60},
        {.x = 191, .y = 77, .endName = u8"诺玛遗址5层_D1605", .endX = 149, .endY = 60},
        {.x = 179, .y = 88, .endName = u8"诺玛遗址5层_D1605", .endX = 132, .endY = 154},
        {.x = 179, .y = 89, .endName = u8"诺玛遗址5层_D1605", .endX = 132, .endY = 154},
        {.x = 167, .y = 100, .endName = u8"诺玛遗址5层_D1605", .endX = 161, .endY = 48},
        {.x = 167, .y = 101, .endName = u8"诺玛遗址5层_D1605", .endX = 161, .endY = 48},
        {.x = 155, .y = 112, .endName = u8"诺玛遗址4层_D1604", .endX = 192, .endY = 127},
        {.x = 155, .y = 113, .endName = u8"诺玛遗址4层_D1604", .endX = 192, .endY = 127},
        {.x = 143, .y = 124, .endName = u8"诺玛遗址5层_D1605", .endX = 101, .endY = 108},
        {.x = 143, .y = 125, .endName = u8"诺玛遗址5层_D1605", .endX = 101, .endY = 108},
        {.x = 131, .y = 136, .endName = u8"诺玛遗址5层_D1605", .endX = 41, .endY = 168},
        {.x = 131, .y = 137, .endName = u8"诺玛遗址5层_D1605", .endX = 41, .endY = 168},
        {.x = 119, .y = 148, .endName = u8"诺玛遗址5层_D1605", .endX = 197, .endY = 51},
        {.x = 119, .y = 149, .endName = u8"诺玛遗址5层_D1605", .endX = 197, .endY = 51},
        {.x = 107, .y = 160, .endName = u8"诺玛遗址5层_D1605", .endX = 65, .endY = 144},
        {.x = 107, .y = 161, .endName = u8"诺玛遗址5层_D1605", .endX = 65, .endY = 144},
        {.x = 95, .y = 172, .endName = u8"诺玛遗址5层_D1605", .endX = 17, .endY = 192},
        {.x = 95, .y = 173, .endName = u8"诺玛遗址5层_D1605", .endX = 17, .endY = 192},
        {.x = 83, .y = 184, .endName = u8"诺玛遗址5层_D1605", .endX = 93, .endY = 233},
        {.x = 83, .y = 185, .endName = u8"诺玛遗址5层_D1605", .endX = 93, .endY = 233},
        {.x = 71, .y = 196, .endName = u8"诺玛遗址5层_D1605", .endX = 161, .endY = 48},
        {.x = 71, .y = 197, .endName = u8"诺玛遗址5层_D1605", .endX = 161, .endY = 48},
        {.x = 59, .y = 208, .endName = u8"诺玛遗址5层_D1605", .endX = 193, .endY = 94},
        {.x = 59, .y = 209, .endName = u8"诺玛遗址5层_D1605", .endX = 193, .endY = 94},
        {.x = 47, .y = 220, .endName = u8"诺玛遗址5层_D1605", .endX = 77, .endY = 132},
        {.x = 47, .y = 221, .endName = u8"诺玛遗址5层_D1605", .endX = 77, .endY = 132},
        {.x = 35, .y = 232, .endName = u8"诺玛遗址5层_D1605", .endX = 85, .endY = 202},
        {.x = 35, .y = 233, .endName = u8"诺玛遗址5层_D1605", .endX = 85, .endY = 202},
        {.x = 243, .y = 63, .endName = u8"诺玛遗址5层_D1605", .endX = 125, .endY = 84},
        {.x = 243, .y = 64, .endName = u8"诺玛遗址5层_D1605", .endX = 125, .endY = 84},
        {.x = 231, .y = 75, .endName = u8"诺玛遗址5层_D1605", .endX = 161, .endY = 48},
        {.x = 231, .y = 76, .endName = u8"诺玛遗址5层_D1605", .endX = 161, .endY = 48},
        {.x = 219, .y = 87, .endName = u8"诺玛遗址5层_D1605", .endX = 161, .endY = 87},
        {.x = 219, .y = 88, .endName = u8"诺玛遗址5层_D1605", .endX = 161, .endY = 87},
        {.x = 207, .y = 99, .endName = u8"诺玛遗址5层_D1605", .endX = 29, .endY = 219},
        {.x = 207, .y = 100, .endName = u8"诺玛遗址5层_D1605", .endX = 29, .endY = 219},
        {.x = 195, .y = 111, .endName = u8"诺玛遗址5层_D1605", .endX = 77, .endY = 171},
        {.x = 195, .y = 112, .endName = u8"诺玛遗址5层_D1605", .endX = 77, .endY = 171},
        {.x = 183, .y = 123, .endName = u8"诺玛遗址5层_D1605", .endX = 17, .endY = 192},
        {.x = 183, .y = 124, .endName = u8"诺玛遗址5层_D1605", .endX = 17, .endY = 192},
        {.x = 171, .y = 135, .endName = u8"诺玛遗址5层_D1605", .endX = 265, .endY = 139},
        {.x = 171, .y = 136, .endName = u8"诺玛遗址5层_D1605", .endX = 265, .endY = 139},
        {.x = 159, .y = 147, .endName = u8"诺玛遗址5层_D1605", .endX = 101, .endY = 147},
        {.x = 159, .y = 148, .endName = u8"诺玛遗址5层_D1605", .endX = 101, .endY = 147},
        {.x = 147, .y = 159, .endName = u8"诺玛遗址5层_D1605", .endX = 41, .endY = 207},
        {.x = 147, .y = 160, .endName = u8"诺玛遗址5层_D1605", .endX = 41, .endY = 207},
        {.x = 135, .y = 171, .endName = u8"诺玛遗址5层_D1605", .endX = 77, .endY = 171},
        {.x = 135, .y = 172, .endName = u8"诺玛遗址5层_D1605", .endX = 77, .endY = 171},
        {.x = 123, .y = 183, .endName = u8"诺玛遗址5层_D1605", .endX = 101, .endY = 147},
        {.x = 123, .y = 184, .endName = u8"诺玛遗址5层_D1605", .endX = 101, .endY = 147},
        {.x = 111, .y = 195, .endName = u8"诺玛遗址5层_D1605", .endX = 41, .endY = 168},
        {.x = 111, .y = 196, .endName = u8"诺玛遗址5层_D1605", .endX = 41, .endY = 168},
        {.x = 99, .y = 207, .endName = u8"诺玛遗址5层_D1605", .endX = 197, .endY = 51},
        {.x = 99, .y = 208, .endName = u8"诺玛遗址5层_D1605", .endX = 197, .endY = 51},
        {.x = 87, .y = 219, .endName = u8"诺玛遗址5层_D1605", .endX = 29, .endY = 219},
        {.x = 87, .y = 220, .endName = u8"诺玛遗址5层_D1605", .endX = 29, .endY = 219},
        {.x = 75, .y = 231, .endName = u8"诺玛遗址5层_D1605", .endX = 125, .endY = 84},
        {.x = 75, .y = 232, .endName = u8"诺玛遗址5层_D1605", .endX = 125, .endY = 84},
        {.x = 63, .y = 243, .endName = u8"诺玛遗址5层_D1605", .endX = 145, .endY = 142},
        {.x = 63, .y = 244, .endName = u8"诺玛遗址5层_D1605", .endX = 145, .endY = 142},
        {.x = 259, .y = 86, .endName = u8"诺玛遗址5层_D1605", .endX = 169, .endY = 118},
        {.x = 259, .y = 87, .endName = u8"诺玛遗址5层_D1605", .endX = 169, .endY = 118},
        {.x = 247, .y = 98, .endName = u8"诺玛遗址5层_D1605", .endX = 137, .endY = 72},
        {.x = 247, .y = 99, .endName = u8"诺玛遗址5层_D1605", .endX = 137, .endY = 72},
        {.x = 235, .y = 110, .endName = u8"诺玛遗址5层_D1605", .endX = 53, .endY = 156},
        {.x = 235, .y = 111, .endName = u8"诺玛遗址5层_D1605", .endX = 53, .endY = 156},
        {.x = 223, .y = 122, .endName = u8"诺玛遗址5层_D1605", .endX = 69, .endY = 257},
        {.x = 223, .y = 123, .endName = u8"诺玛遗址5层_D1605", .endX = 69, .endY = 257},
        {.x = 211, .y = 134, .endName = u8"诺玛遗址5层_D1605", .endX = 185, .endY = 63},
        {.x = 211, .y = 135, .endName = u8"诺玛遗址5层_D1605", .endX = 185, .endY = 63},
        {.x = 199, .y = 146, .endName = u8"诺玛遗址5层_D1605", .endX = 113, .endY = 135},
        {.x = 199, .y = 147, .endName = u8"诺玛遗址5层_D1605", .endX = 113, .endY = 135},
        {.x = 187, .y = 158, .endName = u8"诺玛遗址5层_D1605", .endX = 205, .endY = 82},
        {.x = 187, .y = 159, .endName = u8"诺玛遗址5层_D1605", .endX = 205, .endY = 82},
        {.x = 175, .y = 170, .endName = u8"诺玛遗址5层_D1605", .endX = 257, .endY = 108},
        {.x = 175, .y = 171, .endName = u8"诺玛遗址5层_D1605", .endX = 257, .endY = 108},
        {.x = 163, .y = 182, .endName = u8"诺玛遗址5层_D1605", .endX = 89, .endY = 120},
        {.x = 163, .y = 183, .endName = u8"诺玛遗址5层_D1605", .endX = 89, .endY = 120},
        {.x = 151, .y = 194, .endName = u8"诺玛遗址5层_D1605", .endX = 29, .endY = 180},
        {.x = 151, .y = 195, .endName = u8"诺玛遗址5层_D1605", .endX = 29, .endY = 180},
        {.x = 139, .y = 206, .endName = u8"诺玛遗址5层_D1605", .endX = 209, .endY = 39},
        {.x = 139, .y = 207, .endName = u8"诺玛遗址5层_D1605", .endX = 209, .endY = 39},
        {.x = 127, .y = 218, .endName = u8"诺玛遗址5层_D1605", .endX = 185, .endY = 339},
        {.x = 127, .y = 219, .endName = u8"诺玛遗址5层_D1605", .endX = 185, .endY = 339},
        {.x = 115, .y = 230, .endName = u8"诺玛遗址5层_D1605", .endX = 53, .endY = 195},
        {.x = 115, .y = 231, .endName = u8"诺玛遗址5层_D1605", .endX = 53, .endY = 195},
        {.x = 103, .y = 242, .endName = u8"诺玛遗址5层_D1605", .endX = 109, .endY = 178},
        {.x = 103, .y = 243, .endName = u8"诺玛遗址5层_D1605", .endX = 109, .endY = 178},
        {.x = 91, .y = 254, .endName = u8"诺玛遗址5层_D1605", .endX = 173, .endY = 36},
        {.x = 91, .y = 255, .endName = u8"诺玛遗址5层_D1605", .endX = 173, .endY = 36},
        {.x = 79, .y = 266, .endName = u8"诺玛遗址5层_D1605", .endX = 225, .endY = 101},
        {.x = 79, .y = 267, .endName = u8"诺玛遗址5层_D1605", .endX = 225, .endY = 101},
        {.x = 283, .y = 101, .endName = u8"诺玛遗址5层_D1605", .endX = 137, .endY = 111},
        {.x = 283, .y = 102, .endName = u8"诺玛遗址5层_D1605", .endX = 137, .endY = 111},
        {.x = 271, .y = 113, .endName = u8"诺玛遗址5层_D1605", .endX = 153, .endY = 173},
        {.x = 271, .y = 114, .endName = u8"诺玛遗址5层_D1605", .endX = 153, .endY = 173},
        {.x = 259, .y = 125, .endName = u8"诺玛遗址5层_D1605", .endX = 153, .endY = 331},
        {.x = 259, .y = 126, .endName = u8"诺玛遗址5层_D1605", .endX = 153, .endY = 331},
        {.x = 247, .y = 137, .endName = u8"诺玛遗址5层_D1605", .endX = 173, .endY = 75},
        {.x = 247, .y = 138, .endName = u8"诺玛遗址5层_D1605", .endX = 173, .endY = 75},
        {.x = 303, .y = 120, .endName = u8"诺玛遗址5层_D1605", .endX = 229, .endY = 58},
        {.x = 303, .y = 121, .endName = u8"诺玛遗址5层_D1605", .endX = 229, .endY = 58},
        {.x = 291, .y = 132, .endName = u8"诺玛遗址5层_D1605", .endX = 217, .endY = 70},
        {.x = 291, .y = 133, .endName = u8"诺玛遗址5层_D1605", .endX = 217, .endY = 70},
        {.x = 279, .y = 144, .endName = u8"诺玛遗址5层_D1605", .endX = 249, .endY = 77},
        {.x = 279, .y = 145, .endName = u8"诺玛遗址5层_D1605", .endX = 249, .endY = 77},
        {.x = 267, .y = 156, .endName = u8"诺玛遗址5层_D1605", .endX = 285, .endY = 158},
        {.x = 267, .y = 157, .endName = u8"诺玛遗址5层_D1605", .endX = 285, .endY = 158},
        {.x = 323, .y = 139, .endName = u8"诺玛遗址5层_D1605", .endX = 133, .endY = 311},
        {.x = 323, .y = 140, .endName = u8"诺玛遗址5层_D1605", .endX = 133, .endY = 311},
        {.x = 311, .y = 151, .endName = u8"诺玛遗址5层_D1605", .endX = 73, .endY = 214},
        {.x = 311, .y = 152, .endName = u8"诺玛遗址5层_D1605", .endX = 73, .endY = 214},
        {.x = 299, .y = 163, .endName = u8"诺玛遗址5层_D1605", .endX = 89, .endY = 159},
        {.x = 299, .y = 164, .endName = u8"诺玛遗址5层_D1605", .endX = 89, .endY = 159},
        {.x = 287, .y = 175, .endName = u8"诺玛遗址5层_D1605", .endX = 213, .endY = 113},
        {.x = 287, .y = 176, .endName = u8"诺玛遗址5层_D1605", .endX = 213, .endY = 113},
        {.x = 343, .y = 157, .endName = u8"诺玛遗址5层_D1605", .endX = 77, .endY = 288},
        {.x = 343, .y = 158, .endName = u8"诺玛遗址5层_D1605", .endX = 77, .endY = 288},
        {.x = 331, .y = 169, .endName = u8"诺玛遗址5层_D1605", .endX = 125, .endY = 123},
        {.x = 331, .y = 170, .endName = u8"诺玛遗址5层_D1605", .endX = 125, .endY = 123},
        {.x = 319, .y = 181, .endName = u8"诺玛遗址5层_D1605", .endX = 117, .endY = 209},
        {.x = 319, .y = 182, .endName = u8"诺玛遗址5层_D1605", .endX = 117, .endY = 209},
        {.x = 307, .y = 193, .endName = u8"诺玛遗址5层_D1605", .endX = 189, .endY = 137},
        {.x = 307, .y = 194, .endName = u8"诺玛遗址5层_D1605", .endX = 189, .endY = 137},
        {.x = 363, .y = 176, .endName = u8"诺玛遗址5层_D1605", .endX = 293, .endY = 188},
        {.x = 363, .y = 177, .endName = u8"诺玛遗址5层_D1605", .endX = 293, .endY = 188},
        {.x = 351, .y = 188, .endName = u8"诺玛遗址5层_D1605", .endX = 325, .endY = 197},
        {.x = 351, .y = 189, .endName = u8"诺玛遗址5层_D1605", .endX = 325, .endY = 197},
        {.x = 339, .y = 200, .endName = u8"诺玛遗址5层_D1605", .endX = 233, .endY = 132},
        {.x = 339, .y = 201, .endName = u8"诺玛遗址5层_D1605", .endX = 233, .endY = 132},
        {.x = 127, .y = 257, .endName = u8"诺玛遗址5层_D1605", .endX = 109, .endY = 295},
        {.x = 127, .y = 258, .endName = u8"诺玛遗址5层_D1605", .endX = 109, .endY = 295},
        {.x = 115, .y = 269, .endName = u8"诺玛遗址5层_D1605", .endX = 245, .endY = 120},
        {.x = 115, .y = 270, .endName = u8"诺玛遗址5层_D1605", .endX = 245, .endY = 120},
        {.x = 103, .y = 281, .endName = u8"诺玛遗址5层_D1605", .endX = 161, .endY = 363},
        {.x = 103, .y = 282, .endName = u8"诺玛遗址5层_D1605", .endX = 161, .endY = 363},
        {.x = 91, .y = 293, .endName = u8"诺玛遗址5层_D1605", .endX = 329, .endY = 152},
        {.x = 91, .y = 294, .endName = u8"诺玛遗址5层_D1605", .endX = 329, .endY = 152},
        {.x = 139, .y = 284, .endName = u8"诺玛遗址5层_D1605", .endX = 309, .endY = 134},
        {.x = 139, .y = 285, .endName = u8"诺玛遗址5层_D1605", .endX = 309, .endY = 134},
        {.x = 127, .y = 296, .endName = u8"诺玛遗址5层_D1605", .endX = 141, .endY = 343},
        {.x = 127, .y = 297, .endName = u8"诺玛遗址5层_D1605", .endX = 141, .endY = 343},
        {.x = 115, .y = 308, .endName = u8"诺玛遗址5层_D1605", .endX = 201, .endY = 125},
        {.x = 115, .y = 309, .endName = u8"诺玛遗址5层_D1605", .endX = 201, .endY = 125},
        {.x = 103, .y = 320, .endName = u8"诺玛遗址5层_D1605", .endX = 289, .endY = 115},
        {.x = 103, .y = 321, .endName = u8"诺玛遗址5层_D1605", .endX = 289, .endY = 115},
        {.x = 163, .y = 300, .endName = u8"诺玛遗址5层_D1605", .endX = 297, .endY = 146},
        {.x = 163, .y = 301, .endName = u8"诺玛遗址5层_D1605", .endX = 297, .endY = 146},
        {.x = 151, .y = 312, .endName = u8"诺玛遗址5层_D1605", .endX = 133, .endY = 271},
        {.x = 151, .y = 313, .endName = u8"诺玛遗址5层_D1605", .endX = 133, .endY = 271},
        {.x = 139, .y = 324, .endName = u8"诺玛遗址5层_D1605", .endX = 317, .endY = 164},
        {.x = 139, .y = 325, .endName = u8"诺玛遗址5层_D1605", .endX = 317, .endY = 164},
        {.x = 127, .y = 336, .endName = u8"诺玛遗址5层_D1605", .endX = 177, .endY = 307},
        {.x = 127, .y = 337, .endName = u8"诺玛遗址5层_D1605", .endX = 177, .endY = 307},
        {.x = 183, .y = 320, .endName = u8"诺玛遗址5层_D1605", .endX = 277, .endY = 127},
        {.x = 183, .y = 321, .endName = u8"诺玛遗址5层_D1605", .endX = 277, .endY = 127},
        {.x = 171, .y = 332, .endName = u8"诺玛遗址5层_D1605", .endX = 269, .endY = 96},
        {.x = 171, .y = 333, .endName = u8"诺玛遗址5层_D1605", .endX = 269, .endY = 96},
        {.x = 159, .y = 344, .endName = u8"诺玛遗址5层_D1605", .endX = 157, .endY = 287},
        {.x = 159, .y = 345, .endName = u8"诺玛遗址5层_D1605", .endX = 157, .endY = 287},
        {.x = 147, .y = 356, .endName = u8"诺玛遗址5层_D1605", .endX = 273, .endY = 170},
        {.x = 147, .y = 357, .endName = u8"诺玛遗址5层_D1605", .endX = 273, .endY = 170},
        {.x = 203, .y = 340, .endName = u8"诺玛遗址5层_D1605", .endX = 145, .endY = 299},
        {.x = 203, .y = 341, .endName = u8"诺玛遗址5层_D1605", .endX = 145, .endY = 299},
        {.x = 191, .y = 352, .endName = u8"诺玛遗址5层_D1605", .endX = 165, .endY = 319},
        {.x = 191, .y = 353, .endName = u8"诺玛遗址5层_D1605", .endX = 165, .endY = 319},
        {.x = 179, .y = 364, .endName = u8"诺玛遗址5层_D1605", .endX = 325, .endY = 197},
        {.x = 179, .y = 365, .endName = u8"诺玛遗址5层_D1605", .endX = 325, .endY = 197},
        {.x = 167, .y = 376, .endName = u8"诺玛遗址5层_D1605", .endX = 165, .endY = 319},
        {.x = 167, .y = 377, .endName = u8"诺玛遗址5层_D1605", .endX = 165, .endY = 319},
        {.x = 327, .y = 213, .endName = u8"诺玛勇士墓穴_D1606", .endX = 38, .endY = 50},
    }
},

{   .name = u8"诺玛勇士墓穴_d1606",
    .mapSwitchList
    {
        {.x = 38, .y = 50, .endName = u8"诺玛遗址5层_D1605", .endX = 327, .endY = 213},
    }
},

{   .name = u8"怪人屋_D16063",
},

{   .name = u8"祭祀长领地_D16064",
},

{   .name = u8"神圣战甲术空间_D400_001",
},

{   .name = u8"废矿矿山入口_D401",
    .miniMapID = 0X19000010,
    .mapSwitchList
    {
        {.x = 24, .y = 182, .endName = u8"比奇县_0", .endX = 763, .endY = 207},
        {.x = 76, .y = 15, .endName = u8"地下1层第一间房_D411", .endX = 59, .endY = 8},
        {.x = 179, .y = 109, .endName = u8"地下1层第二间房_D413", .endX = 11, .endY = 8},
        {.x = 80, .y = 172, .endName = u8"尸王房_D401_001", .endX = 15, .endY = 15},
        {.x = 81, .y = 92, .endName = u8"尸王房_D401_001", .endX = 15, .endY = 15},
        {.x = 127, .y = 156, .endName = u8"尸王房_D401_001", .endX = 15, .endY = 15},
        {.x = 152, .y = 118, .endName = u8"尸王房_D401_001", .endX = 15, .endY = 15},
        {.x = 120, .y = 109, .endName = u8"尸王房_D401_001", .endX = 15, .endY = 15},
    }
},

{   .name = u8"尸王房_D401_001",
},

{   .name = u8"废矿东部洞穴_D402",
    .miniMapID = 0X19000011,
    .mapSwitchList
    {
        {.x = 8, .y = 147, .endName = u8"地下1层第二间房_D413", .endX = 85, .endY = 10},
        {.x = 195, .y = 81, .endName = u8"地下1层第三间房_D414", .endX = 15, .endY = 78},
        {.x = 27, .y = 116, .endName = u8"尸王房_D402_001", .endX = 15, .endY = 15},
        {.x = 89, .y = 62, .endName = u8"尸王房_D402_001", .endX = 15, .endY = 15},
        {.x = 22, .y = 105, .endName = u8"尸王房_D402_001", .endX = 15, .endY = 15},
        {.x = 151, .y = 16, .endName = u8"尸王房_D402_001", .endX = 15, .endY = 15},
        {.x = 143, .y = 75, .endName = u8"尸王房_D402_001", .endX = 15, .endY = 15},
    }
},

{   .name = u8"尸王房_D402_001",
},

{   .name = u8"地下1层采矿所_D403",
    .miniMapID = 0X19000012,
    .mapSwitchList
    {
        {.x = 10, .y = 106, .endName = u8"地下1层第三间房_D414", .endX = 70, .endY = 20},
        {.x = 121, .y = 191, .endName = u8"天桥2_D412", .endX = 55, .endY = 24},
        {.x = 28, .y = 144, .endName = u8"尸王房_D403_001", .endX = 15, .endY = 15},
        {.x = 86, .y = 118, .endName = u8"尸王房_D403_001", .endX = 15, .endY = 15},
        {.x = 88, .y = 116, .endName = u8"尸王房_D403_001", .endX = 15, .endY = 15},
        {.x = 160, .y = 70, .endName = u8"尸王房_D403_001", .endX = 15, .endY = 15},
        {.x = 146, .y = 152, .endName = u8"尸王房_D403_001", .endX = 15, .endY = 15},
    }
},

{   .name = u8"尸王房_D403_001",
},

{   .name = u8"地下2层采矿所_D404",
    .miniMapID = 0X19000013,
    .mapSwitchList
    {
        {.x = 152, .y = 19, .endName = u8"连接通路_E402", .endX = 70, .endY = 15},
        {.x = 129, .y = 42, .endName = u8"天桥2_D412", .endX = 52, .endY = 53},
        {.x = 9, .y = 152, .endName = u8"天桥3_D416", .endX = 89, .endY = 17},
        {.x = 78, .y = 80, .endName = u8"尸王房_D404_001", .endX = 15, .endY = 15},
        {.x = 82, .y = 69, .endName = u8"尸王房_D404_001", .endX = 15, .endY = 15},
        {.x = 150, .y = 186, .endName = u8"尸王房_D404_001", .endX = 15, .endY = 15},
        {.x = 78, .y = 152, .endName = u8"尸王房_D404_001", .endX = 15, .endY = 15},
        {.x = 104, .y = 99, .endName = u8"尸王房_D404_001", .endX = 15, .endY = 15},
        {.x = 55, .y = 127, .endName = u8"废矿矿山地下2层_D404_002", .endX = 4, .endY = 11},
    }
},

{   .name = u8"尸王房_D404_001",
},

{   .name = u8"废矿矿山地下2层_D404_002",
    .mapSwitchList
    {
        {.x = 3, .y = 12, .endName = u8"地下2层采矿所_D404", .endX = 54, .endY = 128},
    }
},

{   .name = u8"矿石储藏所_D405",
    .miniMapID = 0X19000014,
    .mapSwitchList
    {
        {.x = 166, .y = 138, .endName = u8"天桥3_D416", .endX = 7, .endY = 55},
        {.x = 11, .y = 148, .endName = u8"天桥1_D415", .endX = 83, .endY = 17},
        {.x = 82, .y = 154, .endName = u8"尸王房_D405_001", .endX = 15, .endY = 15},
        {.x = 176, .y = 61, .endName = u8"尸王房_D405_001", .endX = 15, .endY = 15},
        {.x = 80, .y = 153, .endName = u8"尸王房_D405_001", .endX = 15, .endY = 15},
        {.x = 69, .y = 95, .endName = u8"尸王房_D405_001", .endX = 15, .endY = 15},
        {.x = 128, .y = 100, .endName = u8"尸王房_D405_001", .endX = 15, .endY = 15},
    }
},

{   .name = u8"尸王房_D405_001",
},

{   .name = u8"废矿南部洞穴_D406",
    .miniMapID = 0X19000015,
    .mapSwitchList
    {
        {.x = 186, .y = 119, .endName = u8"天桥1_D415", .endX = 9, .endY = 85},
        {.x = 23, .y = 15, .endName = u8"地下1层第一间房_D411", .endX = 94, .endY = 48},
        {.x = 142, .y = 134, .endName = u8"尸王房_D406_001", .endX = 15, .endY = 15},
        {.x = 152, .y = 17, .endName = u8"尸王房_D406_001", .endX = 15, .endY = 15},
        {.x = 122, .y = 79, .endName = u8"尸王房_D406_001", .endX = 15, .endY = 15},
        {.x = 85, .y = 60, .endName = u8"尸王房_D406_001", .endX = 15, .endY = 15},
        {.x = 79, .y = 72, .endName = u8"尸王房_D406_001", .endX = 15, .endY = 15},
    }
},

{   .name = u8"尸王房_D406_001",
},

{   .name = u8"地下1层第一间房_D411",
    .miniMapID = 0X19000016,
    .mapSwitchList
    {
        {.x = 60, .y = 7, .endName = u8"废矿矿山入口_D401", .endX = 77, .endY = 14},
        {.x = 95, .y = 49, .endName = u8"废矿南部洞穴_D406", .endX = 24, .endY = 16},
    }
},

{   .name = u8"天桥2_D412",
    .miniMapID = 0X19000017,
    .mapSwitchList
    {
        {.x = 54, .y = 23, .endName = u8"地下1层采矿所_D403", .endX = 120, .endY = 190},
        {.x = 53, .y = 52, .endName = u8"地下2层采矿所_D404", .endX = 130, .endY = 42},
    }
},

{   .name = u8"地下1层第二间房_D413",
    .miniMapID = 0X19000018,
    .mapSwitchList
    {
        {.x = 10, .y = 7, .endName = u8"废矿矿山入口_D401", .endX = 179, .endY = 108},
        {.x = 86, .y = 9, .endName = u8"废矿东部洞穴_D402", .endX = 9, .endY = 146},
    }
},

{   .name = u8"地下1层第三间房_D414",
    .miniMapID = 0X19000019,
    .mapSwitchList
    {
        {.x = 14, .y = 79, .endName = u8"废矿东部洞穴_D402", .endX = 194, .endY = 82},
        {.x = 71, .y = 19, .endName = u8"地下1层采矿所_D403", .endX = 11, .endY = 105},
    }
},

{   .name = u8"天桥1_D415",
    .miniMapID = 0X19000020,
    .mapSwitchList
    {
        {.x = 84, .y = 16, .endName = u8"矿石储藏所_D405", .endX = 12, .endY = 147},
        {.x = 8, .y = 86, .endName = u8"废矿南部洞穴_D406", .endX = 185, .endY = 120},
    }
},

{   .name = u8"天桥3_D416",
    .miniMapID = 0X19000021,
    .mapSwitchList
    {
        {.x = 90, .y = 16, .endName = u8"地下2层采矿所_D404", .endX = 10, .endY = 151},
        {.x = 6, .y = 54, .endName = u8"矿石储藏所_D405", .endX = 165, .endY = 137},
    }
},

{   .name = u8"神圣战甲术空间_D420_001",
},

{   .name = u8"矿山1层_D421",
    .miniMapID = 0X19000022,
    .mapSwitchList
    {
        {.x = 30, .y = 375, .endName = u8"毒蛇山谷_2", .endX = 365, .endY = 201},
        {.x = 361, .y = 19, .endName = u8"矿山2层_D422", .endX = 22, .endY = 41},
    }
},

{   .name = u8"矿山2层_D422",
    .miniMapID = 0X19000023,
    .mapSwitchList
    {
        {.x = 22, .y = 42, .endName = u8"矿山1层_D421", .endX = 361, .endY = 20},
        {.x = 272, .y = 312, .endName = u8"竞技场_E601", .endX = 135, .endY = 19},
        {.x = 167, .y = 190, .endName = u8"矿山2层_D422_002", .endX = 30, .endY = 9},
    }
},

{   .name = u8"矿山2层_D422_002",
    .mapSwitchList
    {
        {.x = 31, .y = 8, .endName = u8"矿山2层_D422", .endX = 168, .endY = 189},
    }
},

{   .name = u8"南部矿山_D431",
    .miniMapID = 0X19000010,
    .mapSwitchList
    {
        {.x = 24, .y = 182, .endName = u8"毒蛇山谷_2", .endX = 341, .endY = 138},
        {.x = 76, .y = 15, .endName = u8"北部地下1层第一间房_D441", .endX = 59, .endY = 8},
        {.x = 179, .y = 109, .endName = u8"北部地下1层第二间房_D443", .endX = 11, .endY = 8},
        {.x = 80, .y = 172, .endName = u8"尸王房_D431_001", .endX = 15, .endY = 15},
        {.x = 81, .y = 92, .endName = u8"尸王房_D431_001", .endX = 15, .endY = 15},
        {.x = 127, .y = 156, .endName = u8"尸王房_D431_001", .endX = 15, .endY = 15},
        {.x = 152, .y = 118, .endName = u8"尸王房_D431_001", .endX = 15, .endY = 15},
        {.x = 120, .y = 109, .endName = u8"尸王房_D431_001", .endX = 15, .endY = 15},
    }
},

{   .name = u8"北部矿山入口_D431",
    .miniMapID = 0X19000010,
    .mapSwitchList
    {
        {.x = 24, .y = 182, .endName = u8"毒蛇山谷_2", .endX = 341, .endY = 138},
        {.x = 76, .y = 15, .endName = u8"北部地下1层第一间房_D441", .endX = 59, .endY = 8},
        {.x = 179, .y = 109, .endName = u8"北部地下1层第二间房_D443", .endX = 11, .endY = 8},
        {.x = 80, .y = 172, .endName = u8"尸王房_D431_001", .endX = 15, .endY = 15},
        {.x = 81, .y = 92, .endName = u8"尸王房_D431_001", .endX = 15, .endY = 15},
        {.x = 127, .y = 156, .endName = u8"尸王房_D431_001", .endX = 15, .endY = 15},
        {.x = 152, .y = 118, .endName = u8"尸王房_D431_001", .endX = 15, .endY = 15},
        {.x = 120, .y = 109, .endName = u8"尸王房_D431_001", .endX = 15, .endY = 15},
    }
},

{   .name = u8"尸王房_D431_001",
},

{   .name = u8"北部矿山_D432",
    .miniMapID = 0X19000011,
    .mapSwitchList
    {
        {.x = 8, .y = 147, .endName = u8"北部地下1层第二间房_D443", .endX = 85, .endY = 10},
        {.x = 195, .y = 81, .endName = u8"北部地下1层第三间房_D444", .endX = 15, .endY = 78},
        {.x = 27, .y = 116, .endName = u8"尸王房_D432_001", .endX = 15, .endY = 15},
        {.x = 89, .y = 62, .endName = u8"尸王房_D432_001", .endX = 15, .endY = 15},
        {.x = 22, .y = 105, .endName = u8"尸王房_D432_001", .endX = 15, .endY = 15},
        {.x = 151, .y = 16, .endName = u8"尸王房_D432_001", .endX = 15, .endY = 15},
        {.x = 143, .y = 75, .endName = u8"尸王房_D432_001", .endX = 15, .endY = 15},
    }
},

{   .name = u8"北部矿山东面洞穴_D432",
    .miniMapID = 0X19000011,
    .mapSwitchList
    {
        {.x = 8, .y = 147, .endName = u8"北部地下1层第二间房_D443", .endX = 85, .endY = 10},
        {.x = 195, .y = 81, .endName = u8"北部地下1层第三间房_D444", .endX = 15, .endY = 78},
        {.x = 27, .y = 116, .endName = u8"尸王房_D432_001", .endX = 15, .endY = 15},
        {.x = 89, .y = 62, .endName = u8"尸王房_D432_001", .endX = 15, .endY = 15},
        {.x = 22, .y = 105, .endName = u8"尸王房_D432_001", .endX = 15, .endY = 15},
        {.x = 151, .y = 16, .endName = u8"尸王房_D432_001", .endX = 15, .endY = 15},
        {.x = 143, .y = 75, .endName = u8"尸王房_D432_001", .endX = 15, .endY = 15},
    }
},

{   .name = u8"尸王房_D432_001",
},

{   .name = u8"北部地下1层采矿所_D433",
    .miniMapID = 0X19000012,
    .mapSwitchList
    {
        {.x = 10, .y = 106, .endName = u8"北部地下1层第三间房_D444", .endX = 70, .endY = 20},
        {.x = 121, .y = 191, .endName = u8"北部天桥2_D442", .endX = 55, .endY = 24},
        {.x = 28, .y = 144, .endName = u8"尸王房_D433_001", .endX = 15, .endY = 15},
        {.x = 86, .y = 118, .endName = u8"尸王房_D433_001", .endX = 15, .endY = 15},
        {.x = 88, .y = 116, .endName = u8"尸王房_D433_001", .endX = 15, .endY = 15},
        {.x = 160, .y = 70, .endName = u8"尸王房_D433_001", .endX = 15, .endY = 15},
        {.x = 146, .y = 152, .endName = u8"尸王房_D433_001", .endX = 15, .endY = 15},
    }
},

{   .name = u8"尸王房_D433_001",
},

{   .name = u8"北部地下2层采矿所_D434",
    .miniMapID = 0X19000013,
    .mapSwitchList
    {
        {.x = 129, .y = 42, .endName = u8"北部天桥2_D442", .endX = 52, .endY = 53},
        {.x = 9, .y = 152, .endName = u8"北部天桥3_D446", .endX = 89, .endY = 17},
        {.x = 78, .y = 80, .endName = u8"尸王房_D434_001", .endX = 15, .endY = 15},
        {.x = 82, .y = 69, .endName = u8"尸王房_D434_001", .endX = 15, .endY = 15},
        {.x = 150, .y = 186, .endName = u8"尸王房_D434_001", .endX = 15, .endY = 15},
        {.x = 78, .y = 152, .endName = u8"尸王房_D434_001", .endX = 15, .endY = 15},
        {.x = 104, .y = 99, .endName = u8"尸王房_D434_001", .endX = 15, .endY = 15},
    }
},

{   .name = u8"尸王房_D434_001",
},

{   .name = u8"北部矿石储藏所_D435",
    .miniMapID = 0X19000014,
    .mapSwitchList
    {
        {.x = 166, .y = 138, .endName = u8"北部天桥3_D446", .endX = 7, .endY = 55},
        {.x = 11, .y = 148, .endName = u8"北部天桥1_D445", .endX = 83, .endY = 17},
        {.x = 82, .y = 154, .endName = u8"尸王房_D435_001", .endX = 15, .endY = 15},
        {.x = 176, .y = 61, .endName = u8"尸王房_D435_001", .endX = 15, .endY = 15},
        {.x = 80, .y = 153, .endName = u8"尸王房_D435_001", .endX = 15, .endY = 15},
        {.x = 69, .y = 95, .endName = u8"尸王房_D435_001", .endX = 15, .endY = 15},
        {.x = 128, .y = 100, .endName = u8"尸王房_D435_001", .endX = 15, .endY = 15},
    }
},

{   .name = u8"尸王房_D435_001",
},

{   .name = u8"北部废矿南面洞穴_D436",
    .miniMapID = 0X19000015,
    .mapSwitchList
    {
        {.x = 186, .y = 119, .endName = u8"北部天桥1_D445", .endX = 9, .endY = 85},
        {.x = 23, .y = 15, .endName = u8"北部地下1层第一间房_D441", .endX = 94, .endY = 48},
        {.x = 142, .y = 134, .endName = u8"尸王房_D436_001", .endX = 15, .endY = 15},
        {.x = 152, .y = 17, .endName = u8"尸王房_D436_001", .endX = 15, .endY = 15},
        {.x = 122, .y = 79, .endName = u8"尸王房_D436_001", .endX = 15, .endY = 15},
        {.x = 85, .y = 60, .endName = u8"尸王房_D436_001", .endX = 15, .endY = 15},
        {.x = 79, .y = 72, .endName = u8"尸王房_D436_001", .endX = 15, .endY = 15},
    }
},

{   .name = u8"尸王房_D436_001",
},

{   .name = u8"北部地下1层第一间房_D441",
    .miniMapID = 0X19000016,
    .mapSwitchList
    {
        {.x = 60, .y = 7, .endName = u8"南部矿山_D431", .endX = 77, .endY = 14},
        {.x = 95, .y = 49, .endName = u8"北部废矿南面洞穴_D436", .endX = 24, .endY = 16},
    }
},

{   .name = u8"北部天桥2_D442",
    .miniMapID = 0X19000017,
    .mapSwitchList
    {
        {.x = 54, .y = 23, .endName = u8"北部地下1层采矿所_D433", .endX = 120, .endY = 190},
        {.x = 53, .y = 52, .endName = u8"北部地下2层采矿所_D434", .endX = 130, .endY = 42},
    }
},

{   .name = u8"北部地下1层第二间房_D443",
    .miniMapID = 0X19000018,
    .mapSwitchList
    {
        {.x = 10, .y = 7, .endName = u8"南部矿山_D431", .endX = 179, .endY = 108},
        {.x = 86, .y = 9, .endName = u8"北部矿山_D432", .endX = 9, .endY = 146},
    }
},

{   .name = u8"北部地下1层第三间房_D444",
    .miniMapID = 0X19000019,
    .mapSwitchList
    {
        {.x = 14, .y = 79, .endName = u8"北部矿山_D432", .endX = 194, .endY = 82},
        {.x = 71, .y = 19, .endName = u8"北部地下1层采矿所_D433", .endX = 11, .endY = 105},
    }
},

{   .name = u8"北部天桥1_D445",
    .miniMapID = 0X19000020,
    .mapSwitchList
    {
        {.x = 84, .y = 16, .endName = u8"北部矿石储藏所_D435", .endX = 12, .endY = 147},
        {.x = 8, .y = 86, .endName = u8"北部废矿南面洞穴_D436", .endX = 185, .endY = 120},
    }
},

{   .name = u8"北部天桥3_D446",
    .miniMapID = 0X19000021,
    .mapSwitchList
    {
        {.x = 90, .y = 16, .endName = u8"北部地下2层采矿所_D434", .endX = 10, .endY = 151},
        {.x = 6, .y = 54, .endName = u8"北部矿石储藏所_D435", .endX = 165, .endY = 137},
    }
},

{   .name = u8"南部矿山1层_D451",
    .miniMapID = 0X19000022,
    .mapSwitchList
    {
        {.x = 30, .y = 375, .endName = u8"毒蛇山谷_2", .endX = 349, .endY = 262},
        {.x = 361, .y = 19, .endName = u8"南部矿山2层_D452", .endX = 22, .endY = 41},
        {.x = 196, .y = 315, .endName = u8"尸王房_D451_001", .endX = 15, .endY = 15},
        {.x = 159, .y = 102, .endName = u8"尸王房_D451_001", .endX = 15, .endY = 15},
        {.x = 80, .y = 202, .endName = u8"尸王房_D451_001", .endX = 15, .endY = 15},
        {.x = 154, .y = 191, .endName = u8"尸王房_D451_001", .endX = 15, .endY = 15},
        {.x = 316, .y = 240, .endName = u8"尸王房_D451_001", .endX = 15, .endY = 15},
    }
},

{   .name = u8"尸王房_D451_001",
},

{   .name = u8"南部矿山2层_D452",
    .miniMapID = 0X19000024,
    .mapSwitchList
    {
        {.x = 22, .y = 42, .endName = u8"南部矿山1层_D451", .endX = 361, .endY = 20},
        {.x = 226, .y = 304, .endName = u8"尸王房_D452_001", .endX = 15, .endY = 15},
        {.x = 233, .y = 59, .endName = u8"尸王房_D452_001", .endX = 15, .endY = 15},
        {.x = 273, .y = 251, .endName = u8"尸王房_D452_001", .endX = 15, .endY = 15},
        {.x = 217, .y = 105, .endName = u8"尸王房_D452_001", .endX = 15, .endY = 15},
        {.x = 128, .y = 101, .endName = u8"尸王房_D452_001", .endX = 15, .endY = 15},
    }
},

{   .name = u8"尸王房_D452_001",
},

{   .name = u8"祖玛神殿1层_d501",
    .miniMapID = 0X19000030,
    .mapSwitchList
    {
        {.x = 165, .y = 217, .endName = u8"祖玛神殿大厅_0157", .endX = 19, .endY = 16},
        {.x = 326, .y = 97, .endName = u8"祖玛神殿_D512", .endX = 20, .endY = 11},
        {.x = 302, .y = 74, .endName = u8"祖玛神殿_D511", .endX = 29, .endY = 21},
        {.x = 165, .y = 217, .endName = u8"祖玛神殿大厅_0157", .endX = 19, .endY = 16},
        {.x = 350, .y = 170, .endName = u8"祖玛神殿2层_D502", .endX = 166, .endY = 216},
    }
},

{   .name = u8"祖玛神殿2层_d502",
    .miniMapID = 0X19000031,
    .mapSwitchList
    {
        {.x = 326, .y = 97, .endName = u8"祖玛神殿_D514", .endX = 20, .endY = 11},
        {.x = 302, .y = 74, .endName = u8"祖玛神殿_D513", .endX = 29, .endY = 21},
        {.x = 165, .y = 217, .endName = u8"祖玛神殿1层_D501", .endX = 350, .endY = 171},
        {.x = 112, .y = 231, .endName = u8"祖玛神殿3层_D503", .endX = 166, .endY = 216},
    }
},

{   .name = u8"祖玛神殿3层_d503",
    .miniMapID = 0X19000032,
    .mapSwitchList
    {
        {.x = 165, .y = 217, .endName = u8"祖玛神殿2层_D502", .endX = 112, .endY = 232},
        {.x = 295, .y = 146, .endName = u8"祖玛神殿4层_D504", .endX = 166, .endY = 216},
    }
},

{   .name = u8"祖玛神殿4层_d504",
    .miniMapID = 0X19000033,
    .mapSwitchList
    {
        {.x = 165, .y = 217, .endName = u8"祖玛神殿3层_D503", .endX = 295, .endY = 147},
        {.x = 51, .y = 173, .endName = u8"祖玛神殿5层_D505", .endX = 96, .endY = 101},
    }
},

{   .name = u8"祖玛神殿5层_D505",
    .miniMapID = 0X19000034,
    .mapSwitchList
    {
        {.x = 95, .y = 102, .endName = u8"祖玛神殿4层_D504", .endX = 52, .endY = 174},
        {.x = 123, .y = 10, .endName = u8"祖玛神殿6层大厅_D5071", .endX = 8, .endY = 10},
    }
},

{   .name = u8"祖玛神殿6层大厅_D5071",
    .miniMapID = 0X19000035,
    .mapSwitchList
    {
        {.x = 7, .y = 9, .endName = u8"祖玛神殿5层_D505", .endX = 122, .endY = 11},
        {.x = 39, .y = 43, .endName = u8"祖玛神殿6层_D5072", .endX = 7, .endY = 51},
    }
},

{   .name = u8"祖玛神殿6层_D5072",
    .miniMapID = 0X19000036,
    .mapSwitchList
    {
        {.x = 6, .y = 50, .endName = u8"祖玛神殿6层大厅_D5071", .endX = 38, .endY = 42},
        {.x = 90, .y = 20, .endName = u8"祖玛神殿6层_D5073", .endX = 10, .endY = 69},
    }
},

{   .name = u8"祖玛神殿6层_D5073",
    .miniMapID = 0X19000037,
    .mapSwitchList
    {
        {.x = 9, .y = 70, .endName = u8"祖玛神殿6层_D5072", .endX = 89, .endY = 21},
        {.x = 60, .y = 9, .endName = u8"祖玛神殿6层_D5074", .endX = 47, .endY = 90},
    }
},

{   .name = u8"祖玛神殿6层_D5074",
    .miniMapID = 0X19000038,
    .mapSwitchList
    {
        {.x = 77, .y = 15, .endName = u8"祖玛教主宫廷_D515", .endX = 14, .endY = 31},
        {.x = 48, .y = 91, .endName = u8"祖玛神殿6层_D5073", .endX = 59, .endY = 10},
    }
},

{   .name = u8"祖玛神殿_d511",
    .mapSwitchList
    {
        {.x = 29, .y = 22, .endName = u8"祖玛神殿1层_D501", .endX = 303, .endY = 75},
    }
},

{   .name = u8"祖玛神殿_d512",
    .mapSwitchList
    {
        {.x = 19, .y = 11, .endName = u8"祖玛神殿1层_D501", .endX = 325, .endY = 96},
    }
},

{   .name = u8"祖玛神殿_d513",
    .mapSwitchList
    {
        {.x = 29, .y = 22, .endName = u8"祖玛神殿2层_D502", .endX = 303, .endY = 75},
    }
},

{   .name = u8"祖玛神殿_d514",
    .mapSwitchList
    {
        {.x = 19, .y = 11, .endName = u8"祖玛神殿2层_D502", .endX = 325, .endY = 96},
    }
},

{   .name = u8"祖玛教主宫廷_d515",
    .mapSwitchList
    {
        {.x = 13, .y = 32, .endName = u8"祖玛神殿6层_D5074", .endX = 76, .endY = 16},
    }
},

{   .name = u8"绝命谷1层南部_d60011",
    .miniMapID = 0X19000040,
    .mapSwitchList
    {
        {.x = 208, .y = 238, .endName = u8"盟重县_74", .endX = 335, .endY = 73},
        {.x = 52, .y = 14, .endName = u8"石灯屋_D603", .endX = 17, .endY = 27},
        {.x = 149, .y = 55, .endName = u8"奇岩石屋_D606", .endX = 29, .endY = 28},
    }
},

{   .name = u8"绝命谷1层西部_d60012",
    .miniMapID = 0X19000041,
    .mapSwitchList
    {
        {.x = 177, .y = 33, .endName = u8"奇岩通路_D607", .endX = 33, .endY = 40},
        {.x = 110, .y = 86, .endName = u8"石灯屋_D603", .endX = 31, .endY = 9},
        {.x = 45, .y = 22, .endName = u8"绝命谷2层北部_D60022", .endX = 172, .endY = 61},
    }
},

{   .name = u8"绝命谷1层北部_d60013",
    .miniMapID = 0X19000042,
    .mapSwitchList
    {
        {.x = 41, .y = 194, .endName = u8"紫水晶洞_D604", .endX = 19, .endY = 23},
        {.x = 81, .y = 81, .endName = u8"奇岩石屋_D606", .endX = 29, .endY = 16},
        {.x = 185, .y = 82, .endName = u8"奇岩通路_D607", .endX = 55, .endY = 38},
    }
},

{   .name = u8"绝命谷2层西部_d60021",
    .miniMapID = 0X19000043,
    .mapSwitchList
    {
        {.x = 155, .y = 36, .endName = u8"奇岩通路_D607", .endX = 33, .endY = 70},
        {.x = 149, .y = 132, .endName = u8"紫水晶洞_D604", .endX = 18, .endY = 32},
    }
},

{   .name = u8"绝命谷2层北部_d60022",
    .miniMapID = 0X19000044,
    .mapSwitchList
    {
        {.x = 42, .y = 124, .endName = u8"暗阁泉_D605", .endX = 15, .endY = 33},
        {.x = 42, .y = 19, .endName = u8"紫水晶洞_D604", .endX = 31, .endY = 31},
        {.x = 173, .y = 60, .endName = u8"绝命谷1层西部_D60012", .endX = 46, .endY = 23},
    }
},

{   .name = u8"绝命谷3层_D6004",
    .miniMapID = 0X19000045,
    .mapSwitchList
    {
        {.x = 39, .y = 24, .endName = u8"奇岩通路_D607", .endX = 57, .endY = 69},
        {.x = 39, .y = 266, .endName = u8"蜈蚣洞穴_1_020", .endX = 184, .endY = 20},
        {.x = 39, .y = 267, .endName = u8"蜈蚣洞穴_1_020", .endX = 184, .endY = 20},
        {.x = 40, .y = 267, .endName = u8"蜈蚣洞穴_1_020", .endX = 184, .endY = 20},
    }
},

{   .name = u8"万年谷_d6011",
    .miniMapID = 0X19000050,
    .mapSwitchList
    {
        {.x = 160, .y = 169, .endName = u8"盟重县_74", .endX = 78, .endY = 229},
        {.x = 29, .y = 32, .endName = u8"万年原谷_D6012", .endX = 12, .endY = 16},
    }
},

{   .name = u8"万年原谷_D6012",
    .miniMapID = 0X19000051,
    .mapSwitchList
    {
        {.x = 199, .y = 51, .endName = u8"暗阁泉_D605", .endX = 22, .endY = 14},
        {.x = 11, .y = 15, .endName = u8"万年谷_D6011", .endX = 30, .endY = 33},
        {.x = 202, .y = 187, .endName = u8"万年谷中部_D60131", .endX = 9, .endY = 51},
        {.x = 9, .y = 182, .endName = u8"万年谷南部_D60132", .endX = 70, .endY = 66},
        {.x = 283, .y = 232, .endName = u8"万年谷北部_D60134", .endX = 25, .endY = 17},
    }
},

{   .name = u8"万年谷中部_D60131",
    .miniMapID = 0X19000052,
    .mapSwitchList
    {
        {.x = 8, .y = 50, .endName = u8"万年原谷_D6012", .endX = 203, .endY = 188},
        {.x = 12, .y = 13, .endName = u8"万年独孤关_D6014", .endX = 150, .endY = 66},
    }
},

{   .name = u8"万年谷南部_D60132",
    .miniMapID = 0X19000053,
    .mapSwitchList
    {
        {.x = 69, .y = 65, .endName = u8"万年原谷_D6012", .endX = 10, .endY = 183},
        {.x = 13, .y = 19, .endName = u8"万年谷西部_D60133", .endX = 63, .endY = 83},
    }
},

{   .name = u8"万年谷西部_D60133",
    .miniMapID = 0X19000054,
    .mapSwitchList
    {
        {.x = 64, .y = 82, .endName = u8"万年谷南部_D60132", .endX = 14, .endY = 20},
        {.x = 88, .y = 75, .endName = u8"万年独孤关_D6014", .endX = 14, .endY = 84},
    }
},

{   .name = u8"万年谷北部_D60134",
    .miniMapID = 0X19000055,
    .mapSwitchList
    {
        {.x = 26, .y = 16, .endName = u8"万年原谷_D6012", .endX = 284, .endY = 233},
        {.x = 86, .y = 17, .endName = u8"万年谷东部_D60135", .endX = 44, .endY = 43},
    }
},

{   .name = u8"万年谷东部_D60135",
    .miniMapID = 0X19000056,
    .mapSwitchList
    {
        {.x = 43, .y = 42, .endName = u8"万年谷北部_D60134", .endX = 85, .endY = 18},
        {.x = 90, .y = 11, .endName = u8"万年独孤关_D6014", .endX = 52, .endY = 22},
    }
},

{   .name = u8"万年独孤关_D6014",
    .miniMapID = 0X19000057,
    .mapSwitchList
    {
        {.x = 149, .y = 65, .endName = u8"万年谷中部_D60131", .endX = 13, .endY = 14},
        {.x = 13, .y = 83, .endName = u8"万年谷西部_D60133", .endX = 87, .endY = 76},
        {.x = 53, .y = 21, .endName = u8"万年谷东部_D60135", .endX = 89, .endY = 12},
        {.x = 160, .y = 170, .endName = u8"生死关_D6015", .endX = 10, .endY = 26},
    }
},

{   .name = u8"生死关_d6015",
    .miniMapID = 0X19000058,
    .mapSwitchList
    {
        {.x = 9, .y = 25, .endName = u8"万年独孤关_D6014", .endX = 159, .endY = 171},
    }
},

{   .name = u8"虫峡谷1层_d6021",
    .miniMapID = 0X19000060,
    .mapSwitchList
    {
        {.x = 41, .y = 168, .endName = u8"盟重县_74", .endX = 130, .endY = 505},
        {.x = 170, .y = 23, .endName = u8"虫峡谷2层_D6022", .endX = 40, .endY = 173},
    }
},

{   .name = u8"虫峡谷2层_d6022",
    .miniMapID = 0X19000061,
    .mapSwitchList
    {
        {.x = 39, .y = 174, .endName = u8"虫峡谷1层_D6021", .endX = 169, .endY = 24},
        {.x = 148, .y = 31, .endName = u8"虫峡谷3层_D6023", .endX = 80, .endY = 166},
    }
},

{   .name = u8"虫峡谷3层_D6023",
    .miniMapID = 0X19000062,
    .mapSwitchList
    {
        {.x = 81, .y = 167, .endName = u8"虫峡谷2层_D6022", .endX = 149, .endY = 32},
        {.x = 161, .y = 33, .endName = u8"虫峡谷4层_D6024", .endX = 15, .endY = 191},
    }
},

{   .name = u8"虫峡谷4层_d6024",
    .miniMapID = 0X19000063,
    .mapSwitchList
    {
        {.x = 14, .y = 192, .endName = u8"虫峡谷3层_D6023", .endX = 160, .endY = 34},
        {.x = 247, .y = 105, .endName = u8"虫峡谷5层_D6025", .endX = 218, .endY = 266},
    }
},

{   .name = u8"虫峡谷5层_D6025",
    .miniMapID = 0X19000064,
    .mapSwitchList
    {
        {.x = 219, .y = 267, .endName = u8"虫峡谷4层_D6024", .endX = 248, .endY = 106},
    }
},

{   .name = u8"石灯屋_d603",
    .mapSwitchList
    {
        {.x = 16, .y = 29, .endName = u8"绝命谷1层南部_D60011", .endX = 52, .endY = 15},
        {.x = 31, .y = 8, .endName = u8"绝命谷1层西部_D60012", .endX = 110, .endY = 87},
    }
},

{   .name = u8"紫水晶洞_d604",
    .mapSwitchList
    {
        {.x = 32, .y = 32, .endName = u8"绝命谷2层北部_D60022", .endX = 43, .endY = 20},
        {.x = 18, .y = 22, .endName = u8"绝命谷1层北部_D60013", .endX = 40, .endY = 195},
        {.x = 17, .y = 33, .endName = u8"绝命谷2层西部_D60021", .endX = 149, .endY = 133},
    }
},

{   .name = u8"暗阁泉_d605",
    .mapSwitchList
    {
        {.x = 14, .y = 34, .endName = u8"绝命谷2层北部_D60022", .endX = 43, .endY = 125},
        {.x = 22, .y = 13, .endName = u8"奇岩石屋_D606", .endX = 192, .endY = 123},
        {.x = 22, .y = 13, .endName = u8"万年原谷_D6012", .endX = 200, .endY = 52},
    }
},

{   .name = u8"奇岩石屋_d606",
    .mapSwitchList
    {
        {.x = 9, .y = 25, .endName = u8"奇岩通路_D607", .endX = 58, .endY = 69},
        {.x = 30, .y = 30, .endName = u8"绝命谷1层南部_D60011", .endX = 150, .endY = 56},
        {.x = 30, .y = 15, .endName = u8"绝命谷1层北部_D60013", .endX = 81, .endY = 82},
        {.x = 193, .y = 124, .endName = u8"暗阁泉_D605", .endX = 22, .endY = 14},
    }
},

{   .name = u8"奇岩通路_d607",
    .mapSwitchList
    {
        {.x = 32, .y = 40, .endName = u8"绝命谷1层西部_D60012", .endX = 177, .endY = 34},
        {.x = 32, .y = 71, .endName = u8"绝命谷2层西部_D60021", .endX = 155, .endY = 37},
        {.x = 59, .y = 70, .endName = u8"奇岩石屋_D606", .endX = 10, .endY = 26},
        {.x = 55, .y = 37, .endName = u8"绝命谷1层北部_D60013", .endX = 186, .endY = 81},
        {.x = 58, .y = 70, .endName = u8"绝命谷3层_D6004", .endX = 40, .endY = 25},
    }
},

{   .name = u8"石阁入口_d7101",
    .mapSwitchList
    {
        {.x = 26, .y = 23, .endName = u8"石阁庙_75", .endX = 207, .endY = 67},
        {.x = 25, .y = 21, .endName = u8"石阁1层_D711", .endX = 205, .endY = 198},
    }
},

{   .name = u8"石阁入口_d7102",
},

{   .name = u8"石阁1层_d711",
    .miniMapID = 0X19000090,
    .mapSwitchList
    {
        {.x = 205, .y = 197, .endName = u8"石阁入口_D7101", .endX = 26, .endY = 20},
        {.x = 364, .y = 229, .endName = u8"石阁2层_D712", .endX = 364, .endY = 226},
    }
},

{   .name = u8"石阁2层_d712",
    .miniMapID = 0X19000091,
    .mapSwitchList
    {
        {.x = 363, .y = 227, .endName = u8"石阁1层_D711", .endX = 363, .endY = 230},
        {.x = 31, .y = 193, .endName = u8"石阁3层_D713", .endX = 31, .endY = 191},
    }
},

{   .name = u8"石阁3层_d713",
    .miniMapID = 0X19000092,
    .mapSwitchList
    {
        {.x = 30, .y = 192, .endName = u8"石阁2层_D712", .endX = 30, .endY = 194},
        {.x = 350, .y = 244, .endName = u8"石阁4层_D714", .endX = 382, .endY = 190},
    }
},

{   .name = u8"石阁4层_d714",
    .miniMapID = 0X19000093,
    .mapSwitchList
    {
        {.x = 381, .y = 191, .endName = u8"石阁3层_D713", .endX = 349, .endY = 245},
        {.x = 16, .y = 200, .endName = u8"石阁5层_D715", .endX = 29, .endY = 344},
    }
},

{   .name = u8"石阁5层_D715",
    .miniMapID = 0X19000094,
    .mapSwitchList
    {
        {.x = 28, .y = 345, .endName = u8"石阁4层_D714", .endX = 16, .endY = 201},
        {.x = 83, .y = 81, .endName = u8"石阁6层_D716", .endX = 36, .endY = 17},
    }
},

{   .name = u8"石阁6层_D716",
    .miniMapID = 0X19000095,
    .mapSwitchList
    {
        {.x = 37, .y = 16, .endName = u8"石阁5层_D715", .endX = 84, .endY = 80},
        {.x = 25, .y = 26, .endName = u8"石阁7层_D717", .endX = 26, .endY = 74},
    }
},

{   .name = u8"石阁7层_D717",
    .miniMapID = 0X19000096,
    .mapSwitchList
    {
        {.x = 25, .y = 75, .endName = u8"石阁6层_D716", .endX = 24, .endY = 27},
    }
},

{   .name = u8"南部蚂蚁洞穴1层4_D8001",
    .miniMapID = 0X19000160,
    .mapSwitchList
    {
        {.x = 12, .y = 125, .endName = u8"南部蚂蚁洞穴1层3_D8004", .endX = 195, .endY = 143},
        {.x = 7, .y = 184, .endName = u8"南部蚂蚁洞穴1层3_D8004", .endX = 128, .endY = 179},
    }
},

{   .name = u8"南部蚂蚁洞穴1层1_D8002",
    .miniMapID = 0X19000161,
    .mapSwitchList
    {
        {.x = 178, .y = 189, .endName = u8"沙漠_6", .endX = 290, .endY = 720},
        {.x = 6, .y = 43, .endName = u8"南部蚂蚁洞穴1层2_D8003", .endX = 185, .endY = 57},
        {.x = 39, .y = 175, .endName = u8"失乐园_9", .endX = 732, .endY = 676},
        {.x = 40, .y = 176, .endName = u8"失乐园_9", .endX = 732, .endY = 676},
    }
},

{   .name = u8"南部蚂蚁洞穴1层2_D8003",
    .miniMapID = 0X19000162,
    .mapSwitchList
    {
        {.x = 186, .y = 58, .endName = u8"南部蚂蚁洞穴1层1_D8002", .endX = 7, .endY = 44},
        {.x = 119, .y = 185, .endName = u8"南部蚂蚁洞穴1层3_D8004", .endX = 177, .endY = 14},
        {.x = 29, .y = 185, .endName = u8"南部蚂蚁洞穴1层3_D8004", .endX = 33, .endY = 21},
    }
},

{   .name = u8"南部蚂蚁洞穴1层3_D8004",
    .miniMapID = 0X19000163,
    .mapSwitchList
    {
        {.x = 178, .y = 13, .endName = u8"南部蚂蚁洞穴1层2_D8003", .endX = 120, .endY = 184},
        {.x = 34, .y = 20, .endName = u8"南部蚂蚁洞穴1层2_D8003", .endX = 30, .endY = 184},
        {.x = 196, .y = 142, .endName = u8"南部蚂蚁洞穴1层4_D8001", .endX = 13, .endY = 124},
        {.x = 129, .y = 178, .endName = u8"南部蚂蚁洞穴1层4_D8001", .endX = 8, .endY = 183},
    }
},

{   .name = u8"北部蚂蚁洞穴1层4_D8101",
    .miniMapID = 0X19000160,
    .mapSwitchList
    {
        {.x = 12, .y = 125, .endName = u8"北部蚂蚁洞穴1层3_D8104", .endX = 195, .endY = 143},
        {.x = 7, .y = 184, .endName = u8"北部蚂蚁洞穴1层3_D8104", .endX = 128, .endY = 179},
    }
},

{   .name = u8"北部蚂蚁洞穴1层1_D8102",
    .miniMapID = 0X19000172,
    .mapSwitchList
    {
        {.x = 178, .y = 189, .endName = u8"绿洲_4", .endX = 374, .endY = 120},
        {.x = 6, .y = 43, .endName = u8"北部蚂蚁洞穴1层2_D8103", .endX = 185, .endY = 57},
    }
},

{   .name = u8"北部蚂蚁洞穴1层2_D8103",
    .miniMapID = 0X19000162,
    .mapSwitchList
    {
        {.x = 186, .y = 58, .endName = u8"北部蚂蚁洞穴1层1_D8102", .endX = 7, .endY = 44},
        {.x = 119, .y = 185, .endName = u8"北部蚂蚁洞穴1层3_D8104", .endX = 177, .endY = 14},
        {.x = 29, .y = 185, .endName = u8"北部蚂蚁洞穴1层3_D8104", .endX = 33, .endY = 21},
    }
},

{   .name = u8"北部蚂蚁洞穴1层3_D8104",
    .miniMapID = 0X19000163,
    .mapSwitchList
    {
        {.x = 178, .y = 13, .endName = u8"北部蚂蚁洞穴1层2_D8103", .endX = 120, .endY = 184},
        {.x = 34, .y = 20, .endName = u8"北部蚂蚁洞穴1层2_D8103", .endX = 30, .endY = 184},
        {.x = 196, .y = 142, .endName = u8"北部蚂蚁洞穴1层4_D8101", .endX = 13, .endY = 124},
        {.x = 129, .y = 178, .endName = u8"北部蚂蚁洞穴1层4_D8101", .endX = 8, .endY = 183},
    }
},

{   .name = u8"东部蚂蚁洞穴1层4_D8201",
    .miniMapID = 0X19000160,
    .mapSwitchList
    {
        {.x = 12, .y = 125, .endName = u8"东部蚂蚁洞穴1层3_D8204", .endX = 195, .endY = 143},
        {.x = 7, .y = 184, .endName = u8"东部蚂蚁洞穴1层3_D8204", .endX = 128, .endY = 179},
    }
},

{   .name = u8"东部蚂蚁洞穴1层1_D8202",
    .miniMapID = 0X19000172,
    .mapSwitchList
    {
        {.x = 178, .y = 189, .endName = u8"绿洲_4", .endX = 475, .endY = 153},
        {.x = 6, .y = 43, .endName = u8"东部蚂蚁洞穴1层2_D8203", .endX = 185, .endY = 57},
    }
},

{   .name = u8"东部蚂蚁洞穴1层2_D8203",
    .miniMapID = 0X19000162,
    .mapSwitchList
    {
        {.x = 186, .y = 58, .endName = u8"东部蚂蚁洞穴1层1_D8202", .endX = 7, .endY = 44},
        {.x = 119, .y = 185, .endName = u8"东部蚂蚁洞穴1层3_D8204", .endX = 177, .endY = 14},
        {.x = 29, .y = 185, .endName = u8"东部蚂蚁洞穴1层3_D8204", .endX = 33, .endY = 21},
    }
},

{   .name = u8"东部蚂蚁洞穴1层3_D8204",
    .miniMapID = 0X19000163,
    .mapSwitchList
    {
        {.x = 178, .y = 13, .endName = u8"东部蚂蚁洞穴1层2_D8203", .endX = 120, .endY = 184},
        {.x = 34, .y = 20, .endName = u8"东部蚂蚁洞穴1层2_D8203", .endX = 30, .endY = 184},
        {.x = 196, .y = 142, .endName = u8"东部蚂蚁洞穴1层4_D8201", .endX = 13, .endY = 124},
        {.x = 129, .y = 178, .endName = u8"东部蚂蚁洞穴1层4_D8201", .endX = 8, .endY = 183},
    }
},

{   .name = u8"神舰入口_d900",
    .mapSwitchList
    {
        {.x = 48, .y = 59, .endName = u8"神舰地下三层_D901", .endX = 22, .endY = 83},
    }
},

{   .name = u8"神舰地下三层_D901",
    .miniMapID = 0X19000145,
    .mapSwitchList
    {
        {.x = 21, .y = 85, .endName = u8"神舰入口_D900", .endX = 47, .endY = 60},
        {.x = 159, .y = 93, .endName = u8"神舰地下二层_D9021", .endX = 160, .endY = 94},
        {.x = 122, .y = 149, .endName = u8"木工室_D9011", .endX = 9, .endY = 18},
        {.x = 140, .y = 129, .endName = u8"木工仓库_D9012", .endX = 9, .endY = 18},
    }
},

{   .name = u8"木工室_D9011",
},

{   .name = u8"木工仓库_D9012",
    .mapSwitchList
    {
        {.x = 8, .y = 19, .endName = u8"神舰地下三层_D901", .endX = 139, .endY = 130},
    }
},

{   .name = u8"神舰地下二层_D9021",
    .miniMapID = 0X19000146,
    .mapSwitchList
    {
        {.x = 159, .y = 93, .endName = u8"神舰地下三层_D901", .endX = 160, .endY = 94},
        {.x = 57, .y = 21, .endName = u8"神舰地下二层_D9022", .endX = 34, .endY = 69},
        {.x = 100, .y = 52, .endName = u8"医务室_D90211", .endX = 28, .endY = 24},
        {.x = 38, .y = 61, .endName = u8"机械室_D90212", .endX = 14, .endY = 18},
        {.x = 52, .y = 110, .endName = u8"木工室_D9011", .endX = 18, .endY = 11},
        {.x = 157, .y = 134, .endName = u8"木工仓库_D9012", .endX = 11, .endY = 12},
        {.x = 95, .y = 155, .endName = u8"神舰地下三层_D901", .endX = 107, .endY = 161},
        {.x = 126, .y = 77, .endName = u8"神舰地下三层_D901", .endX = 120, .endY = 140},
        {.x = 117, .y = 173, .endName = u8"神舰地下三层_D901", .endX = 105, .endY = 131},
        {.x = 119, .y = 84, .endName = u8"神舰地下三层_D901", .endX = 149, .endY = 149},
        {.x = 116, .y = 87, .endName = u8"神舰地下三层_D901", .endX = 149, .endY = 149},
        {.x = 69, .y = 126, .endName = u8"神舰地下三层_D901", .endX = 88, .endY = 51},
        {.x = 75, .y = 71, .endName = u8"神舰地下三层_D901", .endX = 88, .endY = 51},
        {.x = 92, .y = 114, .endName = u8"神舰地下三层_D901", .endX = 169, .endY = 121},
        {.x = 67, .y = 21, .endName = u8"医务室_D90221", .endX = 12, .endY = 33},
        {.x = 30, .y = 75, .endName = u8"医务室_D90221", .endX = 12, .endY = 33},
        {.x = 90, .y = 145, .endName = u8"船长室_D9033", .endX = 19, .endY = 11},
        {.x = 126, .y = 77, .endName = u8"船长室_D9033", .endX = 19, .endY = 11},
    }
},

{   .name = u8"医务室_D90211",
    .mapSwitchList
    {
        {.x = 29, .y = 25, .endName = u8"神舰地下二层_D9021", .endX = 100, .endY = 53},
    }
},

{   .name = u8"机械室_D90212",
    .mapSwitchList
    {
        {.x = 15, .y = 19, .endName = u8"神舰地下二层_D9021", .endX = 39, .endY = 62},
    }
},

{   .name = u8"神舰地下二层_D9022",
    .miniMapID = 0X19000147,
    .mapSwitchList
    {
        {.x = 33, .y = 68, .endName = u8"神舰地下二层_D9021", .endX = 58, .endY = 22},
        {.x = 172, .y = 152, .endName = u8"神舰地下一层_D903", .endX = 187, .endY = 150},
        {.x = 111, .y = 146, .endName = u8"医务室_D90221", .endX = 28, .endY = 24},
        {.x = 157, .y = 95, .endName = u8"厨房_D90222", .endX = 22, .endY = 26},
        {.x = 74, .y = 26, .endName = u8"士兵食堂_D90223", .endX = 14, .endY = 18},
    }
},

{   .name = u8"医务室_D90221",
    .mapSwitchList
    {
        {.x = 29, .y = 25, .endName = u8"神舰地下二层_D9022", .endX = 112, .endY = 147},
    }
},

{   .name = u8"厨房_D90222",
},

{   .name = u8"士兵食堂_D90223",
    .mapSwitchList
    {
        {.x = 15, .y = 19, .endName = u8"神舰地下二层_D9022", .endX = 75, .endY = 27},
    }
},

{   .name = u8"神舰地下一层_D903",
    .miniMapID = 0X19000148,
    .mapSwitchList
    {
        {.x = 53, .y = 51, .endName = u8"调控室_D904", .endX = 54, .endY = 25},
        {.x = 144, .y = 179, .endName = u8"参谋室_D9031", .endX = 10, .endY = 22},
        {.x = 72, .y = 60, .endName = u8"长官食堂_D9032", .endX = 7, .endY = 16},
        {.x = 87, .y = 117, .endName = u8"船长室_D9033", .endX = 16, .endY = 18},
        {.x = 47, .y = 41, .endName = u8"慈善屋_Z013", .endX = 10, .endY = 10},
        {.x = 61, .y = 92, .endName = u8"医务室_D90221", .endX = 12, .endY = 33},
        {.x = 172, .y = 110, .endName = u8"医务室_D90221", .endX = 12, .endY = 33},
        {.x = 181, .y = 151, .endName = u8"船长室_D9033", .endX = 19, .endY = 11},
        {.x = 126, .y = 185, .endName = u8"神舰地下二层_D9022", .endX = 19, .endY = 11},
        {.x = 105, .y = 132, .endName = u8"神舰地下二层_D9022", .endX = 98, .endY = 151},
    }
},

{   .name = u8"参谋室_D9031",
    .mapSwitchList
    {
        {.x = 11, .y = 23, .endName = u8"神舰地下一层_D903", .endX = 144, .endY = 180},
    }
},

{   .name = u8"长官食堂_D9032",
    .mapSwitchList
    {
        {.x = 6, .y = 17, .endName = u8"神舰地下一层_D903", .endX = 72, .endY = 60},
    }
},

{   .name = u8"海图室_D90323",
},

{   .name = u8"船长室_D9033",
    .mapSwitchList
    {
        {.x = 17, .y = 19, .endName = u8"神舰地下一层_D903", .endX = 86, .endY = 118},
    }
},

{   .name = u8"调控室_D904",
    .miniMapID = 0X19000149,
    .mapSwitchList
    {
        {.x = 54, .y = 24, .endName = u8"神舰地下一层_D903", .endX = 53, .endY = 52},
    }
},

{   .name = u8"奸商_DM001",
    .mapSwitchList
    {
        {.x = 6, .y = 10, .endName = u8"半兽洞穴2层_D002", .endX = 191, .endY = 232},
    }
},

{   .name = u8"王陵_DM002",
    .mapSwitchList
    {
        {.x = 7, .y = 28, .endName = u8"半兽洞穴2层_D002", .endX = 225, .endY = 176},
    }
},

{   .name = u8"洞穴奸商_DM011",
    .mapSwitchList
    {
        {.x = 6, .y = 10, .endName = u8"天然洞穴2层_D012", .endX = 189, .endY = 145},
    }
},

{   .name = u8"行会大战_E001",
    .miniMapID = 0X19000070,
    .mapSwitchList
    {
        {.x = 8, .y = 13, .endName = u8"半兽洞穴3层_D003", .endX = 77, .endY = 230},
        {.x = 85, .y = 15, .endName = u8"行会大战_E002", .endX = 85, .endY = 10},
    }
},

{   .name = u8"半兽天然洞穴_E001",
    .miniMapID = 0X19000070,
    .mapSwitchList
    {
        {.x = 8, .y = 13, .endName = u8"半兽洞穴3层_D003", .endX = 77, .endY = 230},
        {.x = 85, .y = 15, .endName = u8"半兽天然洞穴_E002", .endX = 85, .endY = 10},
    }
},

{   .name = u8"行会大战_E002",
    .miniMapID = 0X19000071,
    .mapSwitchList
    {
        {.x = 84, .y = 9, .endName = u8"行会大战_E001", .endX = 84, .endY = 16},
        {.x = 36, .y = 81, .endName = u8"天然洞穴2层_D012", .endX = 378, .endY = 65},
        {.x = 63, .y = 12, .endName = u8"半兽天然洞穴_E002_001", .endX = 11, .endY = 10},
        {.x = 63, .y = 11, .endName = u8"半兽天然洞穴_E002_001", .endX = 11, .endY = 10},
    }
},

{   .name = u8"半兽天然洞穴_E002",
    .miniMapID = 0X19000071,
    .mapSwitchList
    {
        {.x = 84, .y = 9, .endName = u8"半兽天然洞穴_E001", .endX = 84, .endY = 16},
        {.x = 36, .y = 81, .endName = u8"天然洞穴2层_D012", .endX = 378, .endY = 65},
        {.x = 63, .y = 12, .endName = u8"半兽天然洞穴_E002_001", .endX = 11, .endY = 10},
        {.x = 63, .y = 11, .endName = u8"半兽天然洞穴_E002_001", .endX = 11, .endY = 10},
    }
},

{   .name = u8"半兽天然洞穴_E002_001",
    .mapSwitchList
    {
        {.x = 12, .y = 9, .endName = u8"半兽天然洞穴_E002", .endX = 64, .endY = 13},
    }
},

{   .name = u8"连接通路_E402",
    .miniMapID = 0X19000073,
    .mapSwitchList
    {
        {.x = 14, .y = 72, .endName = u8"半兽洞穴3层_D003", .endX = 291, .endY = 294},
        {.x = 69, .y = 14, .endName = u8"地下2层采矿所_D404", .endX = 151, .endY = 20},
        {.x = 62, .y = 71, .endName = u8"连接通路_E402_001", .endX = 25, .endY = 12},
    }
},

{   .name = u8"连接通路_E402_001",
    .mapSwitchList
    {
        {.x = 26, .y = 12, .endName = u8"连接通路_E402", .endX = 63, .endY = 72},
    }
},

{   .name = u8"竞技场_E601",
    .miniMapID = 0X19000076,
    .mapSwitchList
    {
        {.x = 134, .y = 20, .endName = u8"矿山2层_D422", .endX = 273, .endY = 311},
        {.x = 13, .y = 50, .endName = u8"竞技场_E602", .endX = 73, .endY = 66},
    }
},

{   .name = u8"竞技场_E602",
    .miniMapID = 0X19000077,
    .mapSwitchList
    {
        {.x = 72, .y = 65, .endName = u8"竞技场_E601", .endX = 12, .endY = 51},
        {.x = 10, .y = 9, .endName = u8"废矿秘密通路_E603", .endX = 25, .endY = 27},
    }
},

{   .name = u8"废矿秘密通路_E603",
    .miniMapID = 0X19000078,
    .mapSwitchList
    {
        {.x = 26, .y = 26, .endName = u8"竞技场_E602", .endX = 11, .endY = 10},
        {.x = 107, .y = 184, .endName = u8"废矿秘密通路_E603", .endX = 111, .endY = 181},
        {.x = 110, .y = 182, .endName = u8"废矿秘密通路_E603", .endX = 106, .endY = 185},
        {.x = 10, .y = 69, .endName = u8"废矿秘密通路_E604", .endX = 91, .endY = 45},
    }
},

{   .name = u8"废矿秘密通路_E604",
    .miniMapID = 0X19000079,
    .mapSwitchList
    {
        {.x = 90, .y = 44, .endName = u8"废矿秘密通路_E603", .endX = 9, .endY = 70},
        {.x = 10, .y = 9, .endName = u8"废矿秘密通路_E605", .endX = 12, .endY = 11},
    }
},

{   .name = u8"废矿秘密通路_E605",
    .miniMapID = 0X19000080,
    .mapSwitchList
    {
        {.x = 13, .y = 10, .endName = u8"废矿秘密通路_E604", .endX = 11, .endY = 10},
    }
},

{   .name = u8"生存游戏场_Island01",
    .miniMapID = 0X19000291,
},

{   .name = u8"生存游戏场_Island02",
    .miniMapID = 0X19000292,
},

{   .name = u8"NPC屋_npcroom1",
},

{   .name = u8"试练屋_RUSH1",
    .miniMapID = 0X19000290,
},

{   .name = u8"打雪仗地图_snow",
},

{   .name = u8"慈善屋_Z010",
},

{   .name = u8"慈善屋_Z011",
},

{   .name = u8"慈善屋_Z012",
},

{   .name = u8"慈善屋_Z013",
},

{   .name = u8"慈善屋_Z014",
},

