/*
 * =====================================================================================
 *
 *       Filename: maprecord.inc
 *        Created: 05/12/2017 17:58:02
 *  Last Modified: 08/31/2017 16:48:38
 *
 *    Description: 
 *
 *        Version: 1.0
 *       Revision: none
 *       Compiler: gcc
 *
 *         Author: ANHONG
 *          Email: anhonghe@gmail.com
 *   Organization: USTC
 *
 * =====================================================================================
 */

{
    u8"",
},

{
    u8"比奇省",

    LinkEntry { 10, 20, 10, 10, u8"盟重省"   },
    LinkEntry { 10, 20, 10, 10, u8"毒蛇山谷" },
},

{
    u8"盟重省",

    LinkEntry { 10, 20, 10, 10, u8"盟重省"   },
    LinkEntry { 10, 20, 10, 10, u8"毒蛇山谷" },
},

{
    u8"毒蛇山谷",

    LinkEntry { 10, 20, 10, 10, u8"盟重省"   },
    LinkEntry { 10, 20, 10, 10, u8"毒蛇山谷" },
},

{
    u8"银杏村",

    LinkEntry { 10, 20, 10, 10, u8"盟重省"   },
    LinkEntry { 10, 20, 10, 10, u8"毒蛇山谷" },
},
