/*
 * =====================================================================================
 *
 *       Filename: maprecord.inc
 *        Created: 05/12/2017 17:58:02
 *    Description: 
 *
 *        Version: 1.0
 *       Revision: none
 *       Compiler: gcc
 *
 *         Author: ANHONG
 *          Email: anhonghe@gmail.com
 *   Organization: USTC
 *
 * =====================================================================================
 */

{   .name = u8"",
},

{   .name = u8"比奇省",
    .miniMapID = 0X19001000,

    .mapSwitchList
    {
        {.x = 206, .y =  52, .endName = u8"道馆",       .endX = 506, .endY = 564},
        {.x = 774, .y = 700, .endName = u8"银杏山谷",   .endX =  28, .endY = 454},
        {.x = 331, .y = 772, .endName = u8"边境城市",   .endX = 564, .endY =  68},
        {.x = 476, .y = 357, .endName = u8"比奇省皇宫", .endX =  20, .endY =  53},
    }
},

{   .name = u8"比奇省皇宫",
    .mapSwitchList
    {
        {.x = 20, .y = 52, .endName = u8"比奇省", .endX = 477, .endY = 358},
    }
},

{   .name = u8"道馆",
    .miniMapID = 0X19001003,

    .mapSwitchList
    {
        {.x = 504, .y = 562, .endName = u8"比奇省", .endX = 208, .endY = 52},
    }
},

{   .name = u8"银杏山谷",
    .mapSwitchList
    {
        {.x = 28, .y = 453, .endName = u8"比奇省", .endX = 775, .endY = 702},
    }
},

{   .name = u8"边境城市",
    .mapSwitchList
    {
        {.x = 563, .y = 68, .endName = u8"比奇省", .endX = 333, .endY = 773},
    }
},

{   .name = u8"沙巴克",
},

{   .name = u8"盟重省",
},

{   .name = u8"毒蛇山谷",
},

{   .name = u8"比奇连接通道1",
},

{   .name = u8"比奇连接通道2",
},

{   .name = u8"比奇连接通道3",
},

{   .name = u8"比奇连接通道4",
},

{   .name = u8"比奇炼毒室",
},

{   .name = u8"比奇练武场",
},

{   .name = u8"比奇练武场",
},

{   .name = u8"比奇练武场",
},

{   .name = u8"比奇肉店",
},

{   .name = u8"比奇首饰店",
},

{   .name = u8"比奇书店",
},

{   .name = u8"比奇武器店",
},

{   .name = u8"比奇药店",
},

{   .name = u8"比奇衣服店",
},
