/*
 * =====================================================================================
 *
 *       Filename: npcrecord.inc
 *        Created: 11/23/2020 17:58:02
 *    Description: 
 *
 *        Version: 1.0
 *       Revision: none
 *       Compiler: gcc
 *
 *         Author: ANHONG
 *          Email: anhonghe@gmail.com
 *   Organization: USTC
 *
 * =====================================================================================
 */

// name-----------------+-lookID----------+-dirIndex-+
{  u8""                 , 0               , 0        },
{  u8"铁匠"             , 3               , 0        },
{  u8"裁缝"             , 1               , 0        },
